# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
A module that will disable java.net.URL internal cache of `jar` protocol URLs.
This will allow hot reload of webapps on systems that are sensitive
to file locks, like Microsoft Windows.

[tags]
classpath

[before]
server

[xml]
etc/disable-urlcache.xml