# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds Eclipse JDT ECJ libs

[ini]
eclipse.jdt.ecj.version?=@eclipse.jdt.ecj.version@

[files]
maven://org.eclipse.jdt/ecj/${eclipse.jdt.ecj.version}/jar|lib/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar

[lib]
lib/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
