# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables standard Servlet handling.

[environment]
ee11

[depends]
server
sessions

[ini]
jakarta.servlet-api.version?=@jakarta.servlet-api.version@

[files]
maven://jakarta.servlet/jakarta.servlet-api/${jakarta.servlet-api.version}/jar|lib/ee11/support/jakarta.servlet.jakarta.servlet-api-${jakarta.servlet-api.version}.jar
maven://org.eclipse.jetty.ee11/jetty-ee11-servlet/${project.version}/jar|lib/ee11/jetty-ee11-servlet-${project.version}.jar

[lib]
lib/ee11/jetty-ee11-servlet-${project.version}.jar
lib/ee11/support/jakarta.servlet.jakarta.servlet-api-${jakarta.servlet-api.version}.jar
