# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables standard Servlet handling.

[environment]
ee11

[depend]
ee/common-servlet
server
sessions

[lib]
lib/@jakarta.servlet:jakarta.servlet-api@
lib/jetty-ee11-servlet-${jetty.version}.jar
