# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables standard Servlet handling.

[environment]
ee11

[depend]
server
sessions

[lib]
lib/jakarta.servlet-api-@jakarta.servlet.api.version@.jar
lib/jetty-ee11-servlet-${jetty.version}.jar
