# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enable the Jetty WebSocket API support for deployed web applications.

[environment]
ee11

[tags]
websocket

[depends]
ee11-annotations
websocket-jetty

[files]
maven://org.eclipse.jetty.ee11.websocket/jetty-ee11-websocket-jetty-server/${jetty.version}/jar|lib/ee11/jetty-ee11-websocket-jetty-server-${jetty.version}.jar
maven://org.eclipse.jetty.ee11.websocket/jetty-ee11-websocket-servlet/${jetty.version}/jar|lib/ee11/jetty-ee11-websocket-servlet-${jetty.version}.jar

[lib]
lib/ee11/jetty-ee11-websocket-jetty-server-${jetty.version}.jar
lib/ee11/jetty-ee11-websocket-servlet-${jetty.version}.jar
