# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enable the Jetty WebSocket API support for deployed web applications.

[environment]
ee10

[tags]
websocket

[depends]
ee10-annotations
websocket-jetty

[files]
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-jetty-server/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-jetty-server-${jetty.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-servlet/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-servlet-${jetty.version}.jar

[lib]
lib/ee10/jetty-ee10-websocket-jetty-server-${jetty.version}.jar
lib/ee10/jetty-ee10-websocket-servlet-${jetty.version}.jar
