# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demo Javax WebSocket Webapp

[environment]
ee8

[tags]
demo
webapp

[depends]
ee8-deploy
ext
ee8-servlets
ee8-websocket-javax

[files]
basehome:modules/demo.d/ee8-demo-javax-websocket.xml|webapps/ee8-demo-javax-websocket.xml
basehome:modules/demo.d/ee8-demo-javax-websocket.properties|webapps/ee8-demo-javax-websocket.properties
maven://org.eclipse.jetty.demos/jetty-servlet4-demo-javax-websocket-webapp/${jetty.version}/war|webapps/ee8-demo-javax-websocket.war
