# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Demo Async Rest webapp

[tags]
demo
webapp

[depends]
deploy

[files]
maven://org.eclipse.jetty.demos/demo-async-rest-webapp/${jetty.version}/war|webapps/demo-async-rest.war

