# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Demo Async Rest webapp

[tags]
demo
webapp

[depends]
deploy

[files]
maven://org.eclipse.jetty.demos/demo-async-rest-webapp/${jetty.version}/war|webapps/demo-async-rest.war

