# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Enables an un-assembled Maven webapp to run in a Jetty distribution.

[depends]
server
webapp
annotations

[lib]
lib/maven/**.jar

[xml]
etc/jetty-maven.xml
