# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Enables an un-assembled Maven webapp to run in a Jetty distribution.

[depends]
server
webapp
annotations

[lib]
lib/maven/**.jar

[xml]
etc/jetty-maven.xml
