//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

package org.eclipse.jetty.quic.common.packets;

import java.util.EnumMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;

import org.eclipse.jetty.quic.api.frames.AckFrame;
import org.eclipse.jetty.quic.common.EncryptionLevel;
import org.eclipse.jetty.quic.common.PacketNumberSpace;
import org.eclipse.jetty.util.Atomics;

/// Generates, encodes, and decodes packet numbers.
///
/// Packet numbers are separated in [PacketNumberSpace]s.
///
/// Packet numbers are generated by [#nextPacketNumber(EncryptionLevel)],
/// that returns a progressively increasing packet number.
///
/// PacketNumbers are encoded and decoded when sent and received over the network.
/// The encoding and decoding depend on the largest acknowledged packet number
/// and the largest received packet number, respectively.
///
/// The packet number acknowledgements are received via [#onAckFrameReceived(EncryptionLevel, AckFrame)],
/// while the packet numbers are received via [#onPacketReceived(Packet)].
///
/// @see EncodedPacketNumber
public class PacketNumbers
{
    private final Map<PacketNumberSpace, Space> spaces = new EnumMap<>(PacketNumberSpace.class);

    public PacketNumbers()
    {
        spaces.put(PacketNumberSpace.INITIAL, new Space());
        spaces.put(PacketNumberSpace.HANDSHAKE, new Space());
        spaces.put(PacketNumberSpace.APPLICATION, new Space());
    }

    public void onPacketReceived(Packet packet)
    {
        if (packet instanceof Packet.WithFrames p)
            spaces.get(PacketNumberSpace.from(EncryptionLevel.from(p))).onPacketReceived(p);
    }

    /// Called to record the largest acked number for the given encryption level.
    ///
    /// @param encryptionLevel the encryption level
    /// @param frame the ack frame containing the acked packet numbers
    public void onAckFrameReceived(EncryptionLevel encryptionLevel, AckFrame frame)
    {
        spaces.get(PacketNumberSpace.from(encryptionLevel)).onAckFrameReceived(frame);
    }

    /// @param encryptionLevel the encryption level
    /// @return a new packet number for the given encryption level
    public long nextPacketNumber(EncryptionLevel encryptionLevel)
    {
        // TODO: skip packet numbers from time to time, to detect
        //  "optimistic ack" attacks.
        return spaces.get(PacketNumberSpace.from(encryptionLevel)).nextPacketNumber();
    }

    /// @param encryptionLevel the encryption level
    /// @param packetNumber the packet number
    /// @return an [EncodedPacketNumber] from the given encryption level and packet number
    public EncodedPacketNumber encode(EncryptionLevel encryptionLevel, long packetNumber)
    {
        return spaces.get(PacketNumberSpace.from(encryptionLevel)).encode(packetNumber);
    }

    public long decode(EncryptionLevel encryptionLevel, byte[] encoded)
    {
        int number = 0;
        for (byte b : encoded)
        {
            number = (number << 8) | (b & 0xFF);
        }
        return decode(encryptionLevel, new EncodedPacketNumber(number, encoded.length));
    }

    public long decode(EncryptionLevel encryptionLevel, EncodedPacketNumber encoded)
    {
        return spaces.get(PacketNumberSpace.from(encryptionLevel)).decode(encoded);
    }

    private static class Space
    {
        private final AtomicLong ids = new AtomicLong();
        private final AtomicLong largestReceived = new AtomicLong();
        private final AtomicLong largestAcknowledged = new AtomicLong();

        private void onPacketReceived(Packet.WithFrames packet)
        {
            Atomics.updateMax(largestReceived, packet.packetNumber());
        }

        private void onAckFrameReceived(AckFrame frame)
        {
            Atomics.updateMax(largestAcknowledged, frame.largestAcknowledged());
        }

        private long nextPacketNumber()
        {
            return ids.getAndIncrement();
        }

        private EncodedPacketNumber encode(long packetNumber)
        {
            // RFC9000[17.1, A.2].
            long acked = largestAcknowledged.get();
            long unacked = acked == 0 ? packetNumber + 1 : packetNumber - acked;
            // Must be able to represent twice the unacked range.
            int bits = 64 - Long.numberOfLeadingZeros(2 * unacked);
            int length = (bits + 7) / 8;
            if (length > 4)
                throw new IllegalStateException("could not encode packet number, bytes required " + length);
            // Convert the number of bytes to a mask of bits set to 1.
            long mask = (1L << (length * 8)) - 1;
            return new EncodedPacketNumber((int)(packetNumber & mask), length);
        }

        private long decode(EncodedPacketNumber encoded)
        {
            // RFC9000[17.1, A.3].
            long acked = largestReceived.get();
            long expected = acked + 1;
            long window = 1L << (encoded.length() * 8);
            long halfWindow = window / 2;
            long mask = window - 1;
            long candidate = (expected & ~mask) | encoded.number();
            if (candidate <= (expected - halfWindow) && candidate < (1L << 62) - window)
                return candidate + window;
            if (candidate > (expected + halfWindow) && candidate >= window)
                return candidate - window;
            return candidate;
        }
    }
}
