# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Expose the Jetty WebSocket Client classes to deployed web applications.

[environment]
ee

[tags]
websocket

[depend]
client
ee-annotations
websocket-jetty-client

[lib]
lib/ee-websocket/jetty-ee-websocket-jetty-client-webapp-${jetty.version}.jar

