# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Configures Jetty to use the "CdiSpiDecorator" as the default CDI mode.
This mode uses the CDI SPI to integrate an arbitrary CDI implementation.

[environment]
ee9

[tag]
cdi

[provides]
cdi-mode

[depend]
ee9-cdi

[ini]
jetty.cdi.mode=CdiSpiDecorator
