# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Adds servlet standard security handling to the classpath.

[depend]
server

[lib]
lib/jetty-security-${jetty.version}.jar
