# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JSP for all web applications deployed on the server.

[environment]
ee9

[depend]
ee9-servlet
ee9-annotations
ee9-apache-jsp
