# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Puts lib/ee9/ext jars on the ee9 classpath.

[tags]
classpath

[environment]
ee9

[lib]
lib/ee9/ext/**.jar

[files]
lib/
lib/ee9/
lib/ee9/ext/
