<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.ee</groupId>
    <artifactId>jetty-ee</artifactId>
    <version>13.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>jetty-ee-home</artifactId>
  <packaging>pom</packaging>
  <name>EE :: Home Assembly</name>

  <properties>
    <assembly-directory>${basedir}/target/jetty-ee-home</assembly-directory>
    <source-assembly-directory>${basedir}/target/jetty-ee-home-sources</source-assembly-directory>
    <spotbugs.skip>true</spotbugs.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-security</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-apache-jsp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-cdi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-fcgi-proxy</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-glassfish-jstl</artifactId>
      <exclusions>
        <exclusion>
          <groupId>jakarta.el</groupId>
          <artifactId>jakarta.el-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.el</groupId>
          <artifactId>el-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-jaspi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-jndi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-plus</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-proxy</artifactId>
    </dependency>

    <!-- ee specific dependencies -->
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-quickstart</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-servlets</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee.demos</groupId>
      <artifactId>jetty-ee-demo-jetty-websocket-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <!-- Demo EECommon Apps -->
    <dependency>
      <groupId>org.eclipse.jetty.ee.demos</groupId>
      <artifactId>jetty-ee-demo-proxy-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee.websocket</groupId>
      <artifactId>jetty-ee-websocket-jakarta-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee.websocket</groupId>
      <artifactId>jetty-ee-websocket-jetty-client-webapp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee.websocket</groupId>
      <artifactId>jetty-ee-websocket-jetty-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee.websocket</groupId>
      <artifactId>jetty-ee-websocket-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-analysis</artifactId>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-commons</artifactId>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-tree</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <tarLongFileMode>posix</tarLongFileMode>
          <appendAssemblyId>false</appendAssemblyId>
        </configuration>
        <executions>
          <execution>
            <id>binary</id>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <descriptors>
                <descriptor>src/main/assembly/jetty-assembly.xml</descriptor>
              </descriptors>
            </configuration>
          </execution>
          <execution>
            <id>sources</id>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <descriptors>
                <descriptor>src/main/assembly/jetty-source-assembly.xml</descriptor>
              </descriptors>
              <appendAssemblyId>true</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-ee-annotations-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.annotation</includeGroupIds>
              <includeArtifactIds>jakarta.annotation-api</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib/ee-annotations</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-annotations-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.annotation</includeGroupIds>
              <includeArtifactIds>jakarta.annotation-api</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee-annotations</outputDirectory>
            </configuration>
          </execution>

          <execution>
            <id>copy-ee-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.ee</includeGroupIds>
              <excludeArtifactIds>jetty-websocket-core-client,jetty-websocket-core-common,jetty-websocket-core-server,jetty-websocket-jetty-api,jetty-websocket-jetty-client,jetty-websocket-jetty-common,jetty-websocket-jetty-server</excludeArtifactIds>
              <excludeGroupIds>org.eclipse.jetty.ee.demos,org.eclipse.jetty.ee.websocket</excludeGroupIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-jaspi-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.authentication</includeGroupIds>
              <includeArtifactIds>jakarta.authentication-api</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib/ee-jaspi</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-jaspi-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.authentication</includeGroupIds>
              <includeArtifactIds>jakarta.authentication-api</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee-jaspi</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-jsp-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.servlet.jsp,jakarta.el,org.mortbay.jasper,org.eclipse.jdt</includeGroupIds>
              <includeArtifactIds>jakarta.servlet.jsp-api,jakarta.el-api,mortbay-apache-el,mortbay-apache-jsp,ecj</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib/ee-apache-jsp</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-jsp-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.servlet.jsp,jakart.el,org.mortbay.jasper,org.eclipse.jdt</includeGroupIds>
              <includeArtifactIds>jakart.servlet.jsp-api,jakarta.el-api,mortbay-apache-el,mortbay-apache-jsp,ecj</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee-apache-jsp</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-jstl-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.servlet.jsp.jstl,org.glassfish.wasp</includeGroupIds>
              <includeArtifactIds>jakarta.servlet.jsp.jstl-api,wasp</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib/ee-glassfish-jstl</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-jstl-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.servlet.jsp.jstl,org.glassfish.wasp</includeGroupIds>
              <includeArtifactIds>jakarta.servlet.jsp.jstl-api,wasp</includeArtifactIds>
              <includeTypes>jar</includeTypes>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee-glassfish-jstl</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-lib-jakarta-websocket-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.websocket</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib/ee-websocket</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-lib-jakarta-websocket-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.websocket</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee-websocket</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.ee</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <excludeGroupIds>org.eclipse.jetty.ee.demos,org.eclipse.jetty.ee.websocket</excludeGroupIds>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-lib-core-websocket-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.websocket</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-lib-core-websocket-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.websocket</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-lib-ee-websocket-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.ee.websocket</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <outputDirectory>${assembly-directory}/lib/ee-websocket</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-lib-ee-websocket-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.ee.websocket</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee-websocket</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-lib-servlet-api-deps</id>
            <goals>
              <goal>copy</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>jakarta.servlet</groupId>
                  <artifactId>jakarta.servlet-api</artifactId>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-lib-servlet-api-src-deps</id>
            <goals>
              <goal>copy</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>jakarta.servlet</groupId>
                  <artifactId>jakarta.servlet-api</artifactId>
                  <classifier>sources</classifier>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${source-assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-lib-transaction-api-deps</id>
            <goals>
              <goal>copy</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>jakarta.transaction</groupId>
                  <artifactId>jakarta.transaction-api</artifactId>
                </artifactItem>
                <artifactItem>
                  <groupId>jakarta.interceptor</groupId>
                  <artifactId>jakarta.interceptor-api</artifactId>
                </artifactItem>
                <artifactItem>
                  <groupId>jakarta.enterprise</groupId>
                  <artifactId>jakarta.enterprise.cdi-api</artifactId>
                </artifactItem>
                <artifactItem>
                  <groupId>jakarta.inject</groupId>
                  <artifactId>jakarta.inject-api</artifactId>
                </artifactItem>
                <artifactItem>
                  <groupId>jakarta.enterprise</groupId>
                  <artifactId>jakarta.enterprise.lang-model</artifactId>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>

          <execution>
            <id>copy-lib-transaction-api-src-deps</id>
            <goals>
              <goal>copy</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>jakarta.transaction</groupId>
                  <artifactId>jakarta.transaction-api</artifactId>
                  <classifier>sources</classifier>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${source-assembly-directory}/lib</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>unpack-config-deps</id>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.ee, org.eclipse.jetty.ee.demos</includeGroupIds>
              <excludeArtifactIds/>
              <classifier>config</classifier>
              <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
              <excludes>META-INF/**,webapps/**,start.d/**,start.ini</excludes>
              <outputDirectory>${assembly-directory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
