# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds the Jetty EE8 JNDI reference factories

[environment]
ee8

[depend]
jndi

[lib]
lib/jetty-ee8-jndi-${jetty.version}.jar
