# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the Jetty EE8 JNDI reference factories

[environment]
ee8

[depends]
jndi

[ini]
jetty.webapp.addHiddenClasses+=,-org.eclipse.jetty.ee8.jndi.factories.

[files]
maven://org.eclipse.jetty.ee8/jetty-ee8-jndi/${project.version}/jar|lib/ee8/jetty-ee8-jndi-${project.version}.jar

[lib]
lib/ee8/jetty-ee8-jndi-${project.version}.jar
