# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the Jetty EE8 JNDI reference factories

[environment]
ee8

[depend]
jndi

[lib]
lib/jetty-ee8-jndi-${jetty.version}.jar

[ini]
jetty.webapp.addHiddenClasses+=,-org.eclipse.jetty.ee8.jndi.factories.