# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Jetty Webapp

[environment]
ee10

[tags]
demo
webapp

[depends]
ee10-deploy
jdbc
ee10-jsp
ee10-jstl
ee10-annotations
ext
ee10-servlets
ee10-demo-rewrite
demo-realm

[files]
webapps/ee10-demo-jetty.d/
basehome:modules/demo.d/ee10-demo-jetty.xml|webapps/ee10-demo-jetty.xml
basehome:modules/demo.d/override-web.xml|webapps/ee10-demo-jetty.d/override-web.xml
basehome:modules/demo.d/ee10-demo-jetty.properties|webapps/ee10-demo-jetty.properties
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-jetty-webapp/${jetty.version}/war|webapps/ee10-demo-jetty.war
