# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Jetty Webapp

[environment]
ee9

[tags]
demo
webapp

[depends]
ee9-deploy
jdbc
ee9-jsp
ee9-jstl
ee9-annotations
ext
ee9-servlets
ee9-websocket-jakarta
ee9-websocket-jetty
ee9-demo-rewrite
demo-realm

[files]
webapps/ee9-demo-jetty.d/
basehome:modules/demo.d/ee9-demo-jetty.xml|webapps/ee9-demo-jetty.xml
basehome:modules/demo.d/override-web.xml|webapps/ee9-demo-jetty.d/override-web.xml
basehome:modules/demo.d/ee9-demo-jetty.properties|webapps/ee9-demo-jetty.properties
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-jetty-webapp/${jetty.version}/war|webapps/ee9-demo-jetty.war
