# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the Jetty EE9 JNDI reference factories

[environment]
ee9

[depend]
jndi

[lib]
lib/jetty-ee9-jndi-${jetty.version}.jar

[ini]
jetty.webapp.addHiddenClasses+=,-org.eclipse.jetty.ee9.jndi.factories.
