# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds the Jetty EE9 JNDI reference factories

[environment]
ee9

[depend]
jndi

[lib]
lib/jetty-ee9-jndi-${jetty.version}.jar
