//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

package org.eclipse.jetty.start;

import java.util.AbstractMap;
import java.util.Map;

public class AllOSSLicenses
{
    /**
     * Key is a license url without http|s part and value is a license name.
     * All licenses were taken from SPDX
     *
     * @see <a href="https://github.com/spdx/license-list-data/blob/main/json/licenses.json">licenses</a>
     */
    public static final Map<String, String> LICENSE_URL_TO_NAME;

    static
    {
        LICENSE_URL_TO_NAME = Map.ofEntries(
            new AbstractMap.SimpleEntry<>("landley.net/toybox/license.html", "BSD Zero Clause License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/attribution", "Attribution Assurance License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Abstyles", "Abstyles License"),
            new AbstractMap.SimpleEntry<>("github.com/AdaCore/xmlada/blob/master/docs/index.rst", "AdaCore Doc License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/AdobeLicense", "Adobe Systems Incorporated Source Code License Agreement"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/MIT#AdobeGlyph", "Adobe Glyph List License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense", "Amazon Digital Services License"),
            new AbstractMap.SimpleEntry<>("opensource.linux-mirror.org/licenses/afl-1.1.txt", "Academic Free License v1.1"),
            new AbstractMap.SimpleEntry<>("opensource.linux-mirror.org/licenses/afl-1.2.txt", "Academic Free License v1.2"),
            new AbstractMap.SimpleEntry<>("wayback.archive.org/web/20060924134533/www.opensource.org/licenses/afl-2.0.txt", "Academic Free License v2.0"),
            new AbstractMap.SimpleEntry<>("opensource.linux-mirror.org/licenses/afl-2.1.txt", "Academic Free License v2.1"),
            new AbstractMap.SimpleEntry<>("www.rosenlaw.com/AFL3.0.htm", "Academic Free License v3.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Afmparse", "Afmparse License"),
            new AbstractMap.SimpleEntry<>("www.affero.org/oagpl.html", "Affero General Public License v1.0"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/agpl.txt", "GNU Affero General Public License v3.0"),
            new AbstractMap.SimpleEntry<>("pages.cs.wisc.edu/~ghost/doc/AFPL/6.01/Public.htm", "Aladdin Free Public License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/AMD_plpa_map_License", "AMD's plpa_map.c License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Apple_MIT_License", "Apple MIT License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/BSD#AMPASBSD", "Academy of Motion Picture Arts and Sciences BSD"),
            new AbstractMap.SimpleEntry<>("www.antlr2.org/license.html", "ANTLR Software Rights Notice"),
            new AbstractMap.SimpleEntry<>("www.apache.org/licenses/LICENSE-1.0", "Apache License 1.0"),
            new AbstractMap.SimpleEntry<>("apache.org/licenses/LICENSE-1.1", "Apache License 1.1"),
            new AbstractMap.SimpleEntry<>("apache.org/licenses/LICENSE-1.1.txt", "Apache License 1.1"),
            new AbstractMap.SimpleEntry<>("www.apache.org/licenses/LICENSE-2.0", "Apache License 2.0"),
            new AbstractMap.SimpleEntry<>("www.apache.org/licenses/LICENSE-2.0.txt", "Apache License 2.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/AdobePostscriptAFM", "Adobe Postscript AFM License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/APL-1.0", "Adaptive Public License 1.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/App-s2p", "App::s2p License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0", "Apple Public Source License 1.0"),
            new AbstractMap.SimpleEntry<>("www.opensource.apple.com/source/IOSerialFamily/IOSerialFamily-7/APPLE_LICENSE", "Apple Public Source License 1.1"),
            new AbstractMap.SimpleEntry<>("www.samurajdata.se/opensource/mirror/licenses/apsl.php", "Apple Public Source License 1.2"),
            new AbstractMap.SimpleEntry<>("www.opensource.apple.com/license/apsl/", "Apple Public Source License 2.0"),
            new AbstractMap.SimpleEntry<>("ftp.gnu.org/gnu/non-gnu/chinese-fonts-truetype/LICENSE", "Arphic Public License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Artistic-1.0", "Artistic License 1.0"),
            new AbstractMap.SimpleEntry<>("dev.perl.org/licenses/artistic.html", "Artistic License 1.0 (Perl)"),
            new AbstractMap.SimpleEntry<>("www.perlfoundation.org/artistic_license_2_0", "Artistic License 2.0"),
            new AbstractMap.SimpleEntry<>("github.com/AcademySoftwareFoundation/foundation/blob/main/digital_assets/aswf_digital_assets_license_v1.0.txt", "ASWF Digital Assets License version 1.0"),
            new AbstractMap.SimpleEntry<>("github.com/AcademySoftwareFoundation/foundation/blob/main/digital_assets/aswf_digital_assets_license_v1.1.txt", "ASWF Digital Assets License 1.1"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:Baekmuk?rd=Licensing/Baekmuk", "Baekmuk License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Bahyph", "Bahyph License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Barr", "Barr License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Beerware", "Beerware License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Charter#License_Text", "Bitstream Charter Font License"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20080207013128/www.gnome.org/fonts/", "Bitstream Vera Font License"),
            new AbstractMap.SimpleEntry<>("sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/licenses/BitTorrent?r1=1.1&r2=1.1.1.1&diff_format=s", "BitTorrent Open Source License v1.0"),
            new AbstractMap.SimpleEntry<>("directory.fsf.org/wiki/License:BitTorrentOSL1.1", "BitTorrent Open Source License v1.1"),
            new AbstractMap.SimpleEntry<>("www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9", "SQLite Blessing"),
            new AbstractMap.SimpleEntry<>("blueoakcouncil.org/license/1.0.0", "Blue Oak Model License 1.0.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:MIT#Another_Minimal_variant_(found_in_libatomic_ops)", "Boehm-Demers-Weiser GC License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Borceux", "Borceux license"),
            new AbstractMap.SimpleEntry<>("github.com/SWI-Prolog/packages-clib/blob/master/sha1/brg_endian.h", "Brian Gladman 3-Clause License"),
            new AbstractMap.SimpleEntry<>("svnweb.freebsd.org/base/head/include/ifaddrs.h?revision=326823", "BSD 1-Clause License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/BSD-2-Clause", "BSD 2-Clause \"Simplified\" License"),
            new AbstractMap.SimpleEntry<>("www.freebsd.org/copyright/freebsd-license.html", "BSD 2-Clause FreeBSD License"),
            new AbstractMap.SimpleEntry<>("www.netbsd.org/about/redistribution.html#default", "BSD 2-Clause NetBSD License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/BSDplusPatent", "BSD-2-Clause Plus Patent License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/BSD-3-Clause", "BSD 3-Clause \"New\" or \"Revised\" License"),
            new AbstractMap.SimpleEntry<>("asm.ow2.io/LICENSE.txt", "BSD 3-Clause \"New\" or \"Revised\" License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/BSD_with_Attribution", "BSD with attribution"),
            new AbstractMap.SimpleEntry<>("labs.metacarta.com/license-explanation.html#license", "BSD 3-Clause Clear License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/LBNLBSD", "Lawrence Berkeley National Labs BSD variant license"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:BSD#Modification_Variant", "BSD 3-Clause Modification"),
            new AbstractMap.SimpleEntry<>("gitlab.syncad.com/hive/dhive/-/blob/master/LICENSE", "BSD 3-Clause No Military License"),
            new AbstractMap.SimpleEntry<>("download.oracle.com/otn-pub/java/licenses/bsd.txt?AuthParam=1467140197_43d516ce1776bd08a58235a7785be1cc", "BSD 3-Clause No Nuclear License"),
            new AbstractMap.SimpleEntry<>("java.net/projects/javaeetutorial/pages/BerkeleyLicense", "BSD 3-Clause No Nuclear License 2014"),
            new AbstractMap.SimpleEntry<>("jogamp.org/git/?p=gluegen.git;a=blob_plain;f=LICENSE.txt", "BSD 3-Clause No Nuclear Warranty"),
            new AbstractMap.SimpleEntry<>("www.open-mpi.org/community/license.php", "BSD 3-Clause Open MPI variant"),
            new AbstractMap.SimpleEntry<>("directory.fsf.org/wiki/License:BSD_4Clause", "BSD 4-Clause \"Original\" or \"Old\" License"),
            new AbstractMap.SimpleEntry<>("metadata.ftp-master.debian.org/changelogs//main/a/arpwatch/arpwatch_2.1a15-7_copyright", "BSD 4 Clause Shortened"),
            new AbstractMap.SimpleEntry<>("www.freebsd.org/copyright/license.html", "BSD-4-Clause (University of California-Specific)"),
            new AbstractMap.SimpleEntry<>("sourceware.org/git/?p=binutils-gdb.git;a=blob;f=libiberty/strcasecmp.c;h=131d81c2ce7881fa48c363dc5bf5fb302c61ce0b;hb=HEAD", "BSD 4.3 RENO License"),
            new AbstractMap.SimpleEntry<>("github.com/389ds/389-ds-base/blob/main/ldap/include/sysexits-compat.h#L15", "BSD 4.3 TAHOE License"),
            new AbstractMap.SimpleEntry<>("github.com/python-excel/xlrd/blob/master/LICENSE#L33", "BSD Advertising Acknowledgement License"),
            new AbstractMap.SimpleEntry<>("github.com/cyrusimap/cyrus-sasl/blob/master/COPYING", "BSD with Attribution and HPND disclaimer"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/BSD_Protection_License", "BSD Protection License"),
            new AbstractMap.SimpleEntry<>("github.com/robbiehanson/CocoaHTTPServer/blob/master/LICENSE.txt", "BSD Source Code Attribution"),
            new AbstractMap.SimpleEntry<>("www.boost.org/LICENSE_1_0.txt", "Boost Software License 1.0"),
            new AbstractMap.SimpleEntry<>("mariadb.com/bsl11/", "Business Source License 1.1"),
            new AbstractMap.SimpleEntry<>("sourceware.org/bzip2/1.0.5/bzip2-manual-1.0.5.html", "bzip2 and libbzip2 License v1.0.5"),
            new AbstractMap.SimpleEntry<>("sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.6", "bzip2 and libbzip2 License v1.0.6"),
            new AbstractMap.SimpleEntry<>("github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md", "Computational Use of Data Agreement v1.0"),
            new AbstractMap.SimpleEntry<>("cryptographicautonomylicense.com/license-text.html", "Cryptographic Autonomy License 1.0"),
            new AbstractMap.SimpleEntry<>("www.lemis.com/grog/UNIX/ancient-source-all.pdf", "Caldera License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/CATOSL-1.1", "Computer Associates Trusted Open Source License 1.1"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/1.0/legalcode", "Creative Commons Attribution 1.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/2.0/legalcode", "Creative Commons Attribution 2.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/2.5/legalcode", "Creative Commons Attribution 2.5 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/2.5/au/legalcode", "Creative Commons Attribution 2.5 Australia"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/3.0/legalcode", "Creative Commons Attribution 3.0 Unported"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/3.0/at/legalcode", "Creative Commons Attribution 3.0 Austria"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/3.0/de/legalcode", "Creative Commons Attribution 3.0 Germany"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/3.0/igo/legalcode", "Creative Commons Attribution 3.0 IGO"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/3.0/nl/legalcode", "Creative Commons Attribution 3.0 Netherlands"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/3.0/us/legalcode", "Creative Commons Attribution 3.0 United States"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by/4.0/legalcode", "Creative Commons Attribution 4.0 International"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc/1.0/legalcode", "Creative Commons Attribution Non Commercial 1.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc/2.0/legalcode", "Creative Commons Attribution Non Commercial 2.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc/2.5/legalcode", "Creative Commons Attribution Non Commercial 2.5 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc/3.0/legalcode", "Creative Commons Attribution Non Commercial 3.0 Unported"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc/3.0/de/legalcode", "Creative Commons Attribution Non Commercial 3.0 Germany"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc/4.0/legalcode", "Creative Commons Attribution Non Commercial 4.0 International"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nd-nc/1.0/legalcode", "Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-nd/2.0/legalcode", "Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-nd/2.5/legalcode", "Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-nd/3.0/legalcode", "Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-nd/3.0/de/legalcode", "Creative Commons Attribution Non Commercial No Derivatives 3.0 Germany"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-nd/3.0/igo/legalcode", "Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-nd/4.0/legalcode", "Creative Commons Attribution Non Commercial No Derivatives 4.0 International"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/1.0/legalcode", "Creative Commons Attribution Non Commercial Share Alike 1.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/2.0/legalcode", "Creative Commons Attribution Non Commercial Share Alike 2.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/2.0/de/legalcode", "Creative Commons Attribution Non Commercial Share Alike 2.0 Germany"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/2.0/fr/legalcode", "Creative Commons Attribution-NonCommercial-ShareAlike 2.0 France"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/2.0/uk/legalcode", "Creative Commons Attribution Non Commercial Share Alike 2.0 England and Wales"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/2.5/legalcode", "Creative Commons Attribution Non Commercial Share Alike 2.5 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/3.0/legalcode", "Creative Commons Attribution Non Commercial Share Alike 3.0 Unported"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/3.0/de/legalcode", "Creative Commons Attribution Non Commercial Share Alike 3.0 Germany"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/3.0/igo/legalcode", "Creative Commons Attribution Non Commercial Share Alike 3.0 IGO"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nc-sa/4.0/legalcode", "Creative Commons Attribution Non Commercial Share Alike 4.0 International"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nd/1.0/legalcode", "Creative Commons Attribution No Derivatives 1.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nd/2.0/legalcode", "Creative Commons Attribution No Derivatives 2.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nd/2.5/legalcode", "Creative Commons Attribution No Derivatives 2.5 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nd/3.0/legalcode", "Creative Commons Attribution No Derivatives 3.0 Unported"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nd/3.0/de/legalcode", "Creative Commons Attribution No Derivatives 3.0 Germany"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-nd/4.0/legalcode", "Creative Commons Attribution No Derivatives 4.0 International"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/1.0/legalcode", "Creative Commons Attribution Share Alike 1.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/2.0/legalcode", "Creative Commons Attribution Share Alike 2.0 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/2.0/uk/legalcode", "Creative Commons Attribution Share Alike 2.0 England and Wales"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/2.1/jp/legalcode", "Creative Commons Attribution Share Alike 2.1 Japan"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/2.5/legalcode", "Creative Commons Attribution Share Alike 2.5 Generic"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/3.0/legalcode", "Creative Commons Attribution Share Alike 3.0 Unported"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/3.0/at/legalcode", "Creative Commons Attribution Share Alike 3.0 Austria"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/3.0/de/legalcode", "Creative Commons Attribution Share Alike 3.0 Germany"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/3.0/igo/legalcode", "Creative Commons Attribution-ShareAlike 3.0 IGO"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/by-sa/4.0/legalcode", "Creative Commons Attribution Share Alike 4.0 International"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/licenses/publicdomain/", "Creative Commons Public Domain Dedication and Certification"),
            new AbstractMap.SimpleEntry<>("creativecommons.org/publicdomain/zero/1.0/legalcode", "Creative Commons Zero v1.0 Universal"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/cddl1", "Common Development and Distribution License 1.0"),
            new AbstractMap.SimpleEntry<>("glassfish.java.net/public/CDDL+GPL_1_1.html", "Common Development and Distribution License 1.1"),
            new AbstractMap.SimpleEntry<>("www.opensource.apple.com/cdl/", "Common Documentation License 1.0"),
            new AbstractMap.SimpleEntry<>("cdla.io/permissive-1-0", "Community Data License Agreement Permissive 1.0"),
            new AbstractMap.SimpleEntry<>("cdla.dev/permissive-2-0", "Community Data License Agreement Permissive 2.0"),
            new AbstractMap.SimpleEntry<>("cdla.io/sharing-1-0", "Community Data License Agreement Sharing 1.0"),
            new AbstractMap.SimpleEntry<>("www.cecill.info/licences/Licence_CeCILL_V1-fr.html", "CeCILL Free Software License Agreement v1.0"),
            new AbstractMap.SimpleEntry<>("www.cecill.info/licences/Licence_CeCILL_V1.1-US.html", "CeCILL Free Software License Agreement v1.1"),
            new AbstractMap.SimpleEntry<>("www.cecill.info/licences/Licence_CeCILL_V2-en.html", "CeCILL Free Software License Agreement v2.0"),
            new AbstractMap.SimpleEntry<>("www.cecill.info/licences/Licence_CeCILL_V2.1-en.html", "CeCILL Free Software License Agreement v2.1"),
            new AbstractMap.SimpleEntry<>("www.cecill.info/licences/Licence_CeCILL-B_V1-en.html", "CeCILL-B Free Software License Agreement"),
            new AbstractMap.SimpleEntry<>("www.cecill.info/licences/Licence_CeCILL-C_V1-en.html", "CeCILL-C Free Software License Agreement"),
            new AbstractMap.SimpleEntry<>("www.ohwr.org/project/licenses/wikis/cern-ohl-v1.1", "CERN Open Hardware Licence v1.1"),
            new AbstractMap.SimpleEntry<>("www.ohwr.org/project/licenses/wikis/cern-ohl-v1.2", "CERN Open Hardware Licence v1.2"),
            new AbstractMap.SimpleEntry<>("www.ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2", "CERN Open Hardware Licence Version 2 - Permissive"),
            new AbstractMap.SimpleEntry<>("heasarc.gsfc.nasa.gov/docs/software/fitsio/c/f_user/node9.html", "CFITSIO License"),
            new AbstractMap.SimpleEntry<>("github.com/libcheck/check/blob/master/checkmk/checkmk.in", "Checkmk License"),
            new AbstractMap.SimpleEntry<>("gianluca.dellavedova.org/2011/01/03/clarified-artistic-license/", "Clarified Artistic License"),
            new AbstractMap.SimpleEntry<>("github.com/DrItanium/maya/blob/master/LICENSE.CLIPS", "Clips License"),
            new AbstractMap.SimpleEntry<>("www.cs.cmu.edu/~410/licenses.html", "CMU Mach License"),
            new AbstractMap.SimpleEntry<>("www.jython.org/license.html", "CNRI Jython License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/CNRI-Python", "CNRI Python License"),
            new AbstractMap.SimpleEntry<>("www.python.org/download/releases/1.6.1/download_win/", "CNRI Python Open Source GPL Compatible License Agreement"),
            new AbstractMap.SimpleEntry<>("coil.apotheon.org/plaintext/01.0.txt", "Copyfree Open Innovation License"),
            new AbstractMap.SimpleEntry<>("github.com/CommunitySpecification/1.0/blob/master/1._Community_Specification_License-v1.md", "Community Specification License 1.0"),
            new AbstractMap.SimpleEntry<>("research.cs.wisc.edu/condor/license.html#condor", "Condor Public License v1.1"),
            new AbstractMap.SimpleEntry<>("github.com/copyleft-next/copyleft-next/blob/master/Releases/copyleft-next-0.3.0", "copyleft-next 0.3.0"),
            new AbstractMap.SimpleEntry<>("github.com/copyleft-next/copyleft-next/blob/master/Releases/copyleft-next-0.3.1", "copyleft-next 0.3.1"),
            new AbstractMap.SimpleEntry<>("android.googlesource.com/platform/external/dng_sdk/+/refs/heads/master/source/dng_lossless_jpeg.cpp#16", "Cornell Lossless JPEG License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/CPAL-1.0", "Common Public Attribution License 1.0"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/CPL-1.0", "Common Public License 1.0"),
            new AbstractMap.SimpleEntry<>("www.codeproject.com/info/cpol10.aspx", "Code Project Open License 1.02"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Crossword", "Crossword License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:CrystalStacker?rd=Licensing/CrystalStacker", "CrystalStacker License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/CUA-OPL-1.0", "CUA Office Public License v1.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Cube", "Cube License"),
            new AbstractMap.SimpleEntry<>("github.com/bagder/curl/blob/master/COPYING", "curl License"),
            new AbstractMap.SimpleEntry<>("www.dipp.nrw.de/d-fsl/lizenzen/", "Deutsche Freie Software Lizenz"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/diffmark", "diffmark license"),
            new AbstractMap.SimpleEntry<>("www.govdata.de/dl-de/by-2-0", "Data licence Germany – attribution – version 2.0"),
            new AbstractMap.SimpleEntry<>("www.cs.wustl.edu/~schmidt/ACE-copying.html", "DOC License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Dotseqn", "Dotseqn License"),
            new AbstractMap.SimpleEntry<>("github.com/Neo23x0/sigma/blob/master/LICENSE.Detection.Rules.md", "Detection Rule License 1.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/DSDP", "DSDP License"),
            new AbstractMap.SimpleEntry<>("github.com/SWI-Prolog/swipl-devel/blob/master/src/os/dtoa.c", "David M. Gay dtoa License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/dvipdfm", "dvipdfm License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/ECL-1.0", "Educational Community License v1.0"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/ECL-2.0", "Educational Community License v2.0"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/ecos-license.html", "eCos license version 2.0"),
            new AbstractMap.SimpleEntry<>("www.eiffel-nice.org/license/forum.txt", "Eiffel Forum License v1.0"),
            new AbstractMap.SimpleEntry<>("www.eiffel-nice.org/license/eiffel-forum-license-2.html", "Eiffel Forum License v2.0"),
            new AbstractMap.SimpleEntry<>("www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf", "eGenix.com Public License 1.1.0"),
            new AbstractMap.SimpleEntry<>("www.elastic.co/licensing/elastic-license", "Elastic License 2.0"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Entessa", "Entessa Public License v1.0"),
            new AbstractMap.SimpleEntry<>("epics.anl.gov/license/open.php", "EPICS Open License"),
            new AbstractMap.SimpleEntry<>("www.eclipse.org/legal/epl-v10.html", "Eclipse Public License 1.0"),
            new AbstractMap.SimpleEntry<>("www.eclipse.org/legal/epl-2.0", "Eclipse Public License 2.0"),
            new AbstractMap.SimpleEntry<>("www.erlang.org/EPLICENSE", "Erlang Public License v1.1"),
            new AbstractMap.SimpleEntry<>("github.com/DISIC/politique-de-contribution-open-source/blob/master/LICENSE.pdf", "Etalab Open License 2.0"),
            new AbstractMap.SimpleEntry<>("eu-datagrid.web.cern.ch/eu-datagrid/license.html", "EU DataGrid Software License"),
            new AbstractMap.SimpleEntry<>("ec.europa.eu/idabc/en/document/7330.html", "European Union Public License 1.0"),
            new AbstractMap.SimpleEntry<>("joinup.ec.europa.eu/software/page/eupl/licence-eupl", "European Union Public License 1.1"),
            new AbstractMap.SimpleEntry<>("joinup.ec.europa.eu/page/eupl-text-11-12", "European Union Public License 1.2"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Eurosym", "Eurosym License"),
            new AbstractMap.SimpleEntry<>("fairlicense.org/", "Fair License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/FDK-AAC", "Fraunhofer FDK AAC Codec Library"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Frameworx-1.0", "Frameworx Open License 1.0"),
            new AbstractMap.SimpleEntry<>("www.freebsd.org/copyright/freebsd-doc-license/", "FreeBSD Documentation License"),
            new AbstractMap.SimpleEntry<>("freeimage.sourceforge.net/freeimage-license.txt", "FreeImage Public License v1.0"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html", "FSF All Permissive License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/FSF_Unlimited_License", "FSF Unlimited License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant", "FSF Unlimited License (with License Retention)"),
            new AbstractMap.SimpleEntry<>("lists.gnu.org/archive/html/autoconf/2012-04/msg00061.html", "FSF Unlimited License (With License Retention and Warranty Disclaimer)"),
            new AbstractMap.SimpleEntry<>("freetype.fis.uniroma2.it/FTL.TXT", "Freetype Project License"),
            new AbstractMap.SimpleEntry<>("libgd.github.io/manuals/2.3.0/files/license-txt.html", "GD License"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/old-licenses/fdl-1.1.txt", "GNU Free Documentation License v1.1"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/old-licenses/fdl-1.2.txt", "GNU Free Documentation License v1.2"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/fdl-1.3.txt", "GNU Free Documentation License v1.3"),
            new AbstractMap.SimpleEntry<>("liballeg.org/license.html#allegro-4-the-giftware-license", "Giftware License"),
            new AbstractMap.SimpleEntry<>("www.geuz.org/gl2ps/COPYING.GL2PS", "GL2PS License"),
            new AbstractMap.SimpleEntry<>("www.users.on.net/~triforce/glidexp/COPYING.txt", "3dfx Glide License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Glulxe", "Glulxe License"),
            new AbstractMap.SimpleEntry<>("github.com/me-shaon/GLWTPL/commit/da5f6bc734095efbacb442c0b31e33a65b9d6e85", "Good Luck With That Public License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Gnuplot", "gnuplot License"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html", "GNU General Public License v1.0 only"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html", "GNU General Public License v2.0 only"),
            new AbstractMap.SimpleEntry<>("ac-archive.sourceforge.net/doc/copyright.html", "GNU General Public License v2.0 w/Autoconf exception"),
            new AbstractMap.SimpleEntry<>("git.savannah.gnu.org/cgit/bison.git/tree/data/yacc.c?id=193d7c7054ba7197b0789e14965b739162319b5e#n141", "GNU General Public License v2.0 w/Bison exception"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/software/classpath/license.html", "GNU General Public License v2.0 w/Classpath exception"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/gpl-faq.html#FontException", "GNU General Public License v2.0 w/Font exception"),
            new AbstractMap.SimpleEntry<>("gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/libgcc1.c;h=762f5143fc6eed57b6797c82710f3538aa52b40b;hb=cb143a3ce4fb417c68f5fa2691a1b1b1053dfba9#l10", "GNU General Public License v2.0 w/GCC Runtime Library exception"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/gpl-3.0-standalone.html", "GNU General Public License v3.0 only"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/autoconf-exception-3.0.html", "GNU General Public License v3.0 w/Autoconf exception"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/gcc-exception-3.1.html", "GNU General Public License v3.0 w/GCC Runtime Library exception"),
            new AbstractMap.SimpleEntry<>("github.com/erich666/GraphicsGems/blob/master/LICENSE.md", "Graphics Gems License"),
            new AbstractMap.SimpleEntry<>("www.cs.fsu.edu/~engelen/license.html", "gSOAP Public License v1.3b"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License", "Haskell Language Report License"),
            new AbstractMap.SimpleEntry<>("firstdonoharm.dev/version/2/1/license.html", "Hippocratic License 2.1"),
            new AbstractMap.SimpleEntry<>("sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/machine/hppa/memchr.S;h=1cca3e5e8867aa4bffef1f75a5c1bba25c0c441e;hb=HEAD#l2", "Hewlett-Packard 1986 License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/HPND", "Historical Permission Notice and Disclaimer"),
            new AbstractMap.SimpleEntry<>("www.kermitproject.org/ck90.html#source", "HPND with US Government export control warning"),
            new AbstractMap.SimpleEntry<>("www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c", "Historical Permission Notice and Disclaimer - Markus Kuhn variant"),
            new AbstractMap.SimpleEntry<>("git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/sunrpc/auth_gss/gss_generic_token.c?h=v4.19", "Historical Permission Notice and Disclaimer - sell variant"),
            new AbstractMap.SimpleEntry<>("github.com/sigmavirus24/x11-ssh-askpass/blob/master/README", "HPND sell variant with MIT disclaimer"),
            new AbstractMap.SimpleEntry<>("github.com/htacg/tidy-html5/blob/next/README/LICENSE.md", "HTML Tidy License"),
            new AbstractMap.SimpleEntry<>("git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d", "IBM PowerPC Initialization and Boot Software"),
            new AbstractMap.SimpleEntry<>("source.icu-project.org/repos/icu/icu/trunk/license.html", "ICU License"),
            new AbstractMap.SimpleEntry<>("www.iec.ch/webstore/custserv/pdf/CC-EULA.pdf", "IEC    Code Components End-user licence agreement"),
            new AbstractMap.SimpleEntry<>("dev.w3.org/cvsweb/Amaya/libjpeg/Attic/README?rev=1.2", "Independent JPEG Group License"),
            new AbstractMap.SimpleEntry<>("sourceforge.net/p/xmedcon/code/ci/master/tree/libs/ljpg/", "Independent JPEG Group License - short"),
            new AbstractMap.SimpleEntry<>("www.imagemagick.org/script/license.php", "ImageMagick License"),
            new AbstractMap.SimpleEntry<>("legacy.imatix.com/html/sfl/sfl4.htm#license", "iMatix Standard Function Library Agreement"),
            new AbstractMap.SimpleEntry<>("trac.enlightenment.org/e/browser/trunk/imlib2/COPYING", "Imlib2 License"),
            new AbstractMap.SimpleEntry<>("www.info-zip.org/license.html", "Info-ZIP License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Inner_Net_License", "Inner Net License v2.0"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Intel", "Intel Open Source License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Intel_ACPI_Software_License_Agreement", "Intel ACPI Software License Agreement"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20060319014854/info.borland.com/devsupport/interbase/opensource/IPL.html", "Interbase Public License v1.0"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/IPA", "IPA Font License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/IPL-1.0", "IBM Public License v1.0"),
            new AbstractMap.SimpleEntry<>("www.isc.org/licenses/", "ISC License"),
            new AbstractMap.SimpleEntry<>("www.boost.org/doc/libs/1_35_0/doc/html/jam.html", "Jam License"),
            new AbstractMap.SimpleEntry<>("www.ece.uvic.ca/~mdadams/jasper/LICENSE", "JasPer License"),
            new AbstractMap.SimpleEntry<>("www.jpl.nasa.gov/jpl-image-use-policy", "JPL Image Use Policy"),
            new AbstractMap.SimpleEntry<>("gitlab.isc.org/isc-projects/bind9/blob/master/COPYRIGHT#L366", "Japan Network Information Center License"),
            new AbstractMap.SimpleEntry<>("www.json.org/license.html", "JSON License"),
            new AbstractMap.SimpleEntry<>("git.savannah.gnu.org/cgit/kazlib.git/tree/except.c?id=0062df360c2d17d57f6af19b0e444c51feb99036", "Kazlib License"),
            new AbstractMap.SimpleEntry<>("ctan.org/license/knuth", "Knuth CTAN License"),
            new AbstractMap.SimpleEntry<>("artlibre.org/licence/lal/licence-art-libre-12/", "Licence Art Libre 1.2"),
            new AbstractMap.SimpleEntry<>("artlibre.org/", "Licence Art Libre 1.3"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Latex2e", "Latex2e License"),
            new AbstractMap.SimpleEntry<>("git.savannah.gnu.org/cgit/indent.git/tree/doc/indent.texi?id=a74c6b4ee49397cf330b333da1042bffa60ed14f#n74", "Latex2e with translated notice permission"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Leptonica", "Leptonica License"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/old-licenses/lgpl-2.0-standalone.html", "GNU Library General Public License v2 only"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html", "GNU Lesser General Public License v2.1 only"),
            new AbstractMap.SimpleEntry<>("www.gnu.org/licenses/lgpl-3.0-standalone.html", "GNU Lesser General Public License v3.0 only"),
            new AbstractMap.SimpleEntry<>("www-igm.univ-mlv.fr/~unitex/lgpllr.html", "Lesser General Public License For Linguistic Resources"),
            new AbstractMap.SimpleEntry<>("www.libpng.org/pub/png/src/libpng-LICENSE.txt", "libpng License"),
            new AbstractMap.SimpleEntry<>("github.com/SELinuxProject/selinux/blob/master/libselinux/LICENSE", "libselinux public domain notice"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/libtiff", "libtiff License"),
            new AbstractMap.SimpleEntry<>("web.mit.edu/freebsd/head/lib/libutil/login_ok.3", "libutil David Nugent License"),
            new AbstractMap.SimpleEntry<>("forge.gouv.qc.ca/licence/fr/liliq-v1-1/", "Licence Libre du Québec – Permissive version 1.1"),
            new AbstractMap.SimpleEntry<>("www.forge.gouv.qc.ca/participez/licence-logicielle/licence-libre-du-quebec-liliq-en-francais/licence-libre-du-quebec-reciprocite-liliq-r-v1-1/", "Licence Libre du Québec – Réciprocité version 1.1"),
            new AbstractMap.SimpleEntry<>("www.forge.gouv.qc.ca/participez/licence-logicielle/licence-libre-du-quebec-liliq-en-francais/licence-libre-du-quebec-reciprocite-forte-liliq-r-v1-1/", "Licence Libre du Québec – Réciprocité forte version 1.1"),
            new AbstractMap.SimpleEntry<>("git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/getcpu.2#n4", "Linux man-pages - 1 paragraph"),
            new AbstractMap.SimpleEntry<>("www.kernel.org/doc/man-pages/licenses.html", "Linux man-pages Copyleft"),
            new AbstractMap.SimpleEntry<>("git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/move_pages.2#n5", "Linux man-pages Copyleft - 2 paragraphs"),
            new AbstractMap.SimpleEntry<>("git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/set_mempolicy.2#n5", "Linux man-pages Copyleft Variant"),
            new AbstractMap.SimpleEntry<>("git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h", "Linux Kernel Variant of OpenIB.org license"),
            new AbstractMap.SimpleEntry<>("gitlab.com/embeddable-common-lisp/ecl/-/blob/develop/src/lsp/loop.lsp", "Common Lisp LOOP License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/LPL-1.0", "Lucent Public License Version 1.0"),
            new AbstractMap.SimpleEntry<>("plan9.bell-labs.com/plan9/license.html", "Lucent Public License v1.02"),
            new AbstractMap.SimpleEntry<>("www.latex-project.org/lppl/lppl-1-0.txt", "LaTeX Project Public License v1.0"),
            new AbstractMap.SimpleEntry<>("www.latex-project.org/lppl/lppl-1-1.txt", "LaTeX Project Public License v1.1"),
            new AbstractMap.SimpleEntry<>("www.latex-project.org/lppl/lppl-1-2.txt", "LaTeX Project Public License v1.2"),
            new AbstractMap.SimpleEntry<>("www.latex-project.org/lppl/lppl-1-3a.txt", "LaTeX Project Public License v1.3a"),
            new AbstractMap.SimpleEntry<>("www.latex-project.org/lppl/lppl-1-3c.txt", "LaTeX Project Public License v1.3c"),
            new AbstractMap.SimpleEntry<>("www.7-zip.org/sdk.html", "LZMA SDK License (versions 9.11 to 9.20)"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/MakeIndex", "MakeIndex License"),
            new AbstractMap.SimpleEntry<>("github.com/Perl/perl5/blob/blead/util.c#L6136", "Martin Birgmeier License"),
            new AbstractMap.SimpleEntry<>("github.com/Dual-Life/mime-base64/blob/master/Base64.xs#L12", "metamail License"),
            new AbstractMap.SimpleEntry<>("www.netlib.org/minpack/disclaimer", "Minpack License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/MirOS", "The MirOS Licence"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/MIT", "MIT License"),
            new AbstractMap.SimpleEntry<>("github.com/aws/mit-0", "MIT No Attribution"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/MIT_With_Advertising", "Enlightenment License (e16)"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#CMU_Style", "CMU License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/MIT#enna", "enna License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/MIT#feh", "feh License"),
            new AbstractMap.SimpleEntry<>("github.com/festvox/flite/blob/master/COPYING", "MIT Festival Variant"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:MIT#Modern_Variants", "MIT License Modern Variant"),
            new AbstractMap.SimpleEntry<>("gitlab.freedesktop.org/xorg/app/iceauth/-/blob/master/COPYING", "MIT Open Group variant"),
            new AbstractMap.SimpleEntry<>("github.com/chromium/octane/blob/master/crypto.js", "MIT Tom Wu Variant"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/MITNFA", "MIT +no-false-attribs license"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Motosoto", "Motosoto License"),
            new AbstractMap.SimpleEntry<>("sources.debian.org/src/openmpi/4.1.0-10/ompi/debuggers/msgq_interface.h/?hl=19#L19", "mpi Permissive License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/MIT", "mpich2 License"),
            new AbstractMap.SimpleEntry<>("www.mozilla.org/MPL/MPL-1.0.html", "Mozilla Public License 1.0"),
            new AbstractMap.SimpleEntry<>("www.mozilla.org/MPL/MPL-1.1.html", "Mozilla Public License 1.1"),
            new AbstractMap.SimpleEntry<>("www.mozilla.org/MPL/2.0/", "Mozilla Public License 2.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:Mplus?rd=Licensing/mplus", "mplus Font License"),
            new AbstractMap.SimpleEntry<>("www.openhub.net/licenses/mslpl", "Microsoft Limited Public License"),
            new AbstractMap.SimpleEntry<>("www.microsoft.com/opensource/licenses.mspx", "Microsoft Public License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License", "Matrix Template Library License"),
            new AbstractMap.SimpleEntry<>("license.coscl.org.cn/MulanPSL/", "Mulan Permissive Software License, Version 1"),
            new AbstractMap.SimpleEntry<>("license.coscl.org.cn/MulanPSL2/", "Mulan Permissive Software License, Version 2"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Multics", "Multics License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Mup", "Mup License"),
            new AbstractMap.SimpleEntry<>("enterprise.dejacode.com/licenses/public/naist-2003/#license-text", "Nara Institute of Science and Technology License (2003)"),
            new AbstractMap.SimpleEntry<>("ti.arc.nasa.gov/opensource/nosa/", "NASA Open Source Agreement 1.3"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Naumen", "Naumen Public License"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=37b4b3f6cc4bf34e1d3dec61e69914b9819d8894", "Net Boolean Public License v1"),
            new AbstractMap.SimpleEntry<>("www.nationalarchives.gov.uk/doc/non-commercial-government-licence/version/2/", "Non-Commercial Government Licence"),
            new AbstractMap.SimpleEntry<>("otm.illinois.edu/uiuc_openSource", "University of Illinois/NCSA Open Source License"),
            new AbstractMap.SimpleEntry<>("net-snmp.sourceforge.net/about/license.html", "Net-SNMP License"),
            new AbstractMap.SimpleEntry<>("www.unidata.ucar.edu/software/netcdf/copyright.html", "NetCDF license"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Newsletr", "Newsletr License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/NGPL", "Nethack General Public License"),
            new AbstractMap.SimpleEntry<>("opensource.apple.com/source/mDNSResponder/mDNSResponder-320.10/mDNSPosix/nss_ReadMe.txt", "NICTA Public Software License, Version 1.0"),
            new AbstractMap.SimpleEntry<>("github.com/tcheneau/simpleRPL/blob/e645e69e38dd4e3ccfeceb2db8cba05b7c2e0cd3/LICENSE.txt", "NIST Public Domain Notice"),
            new AbstractMap.SimpleEntry<>("github.com/usnistgov/jsip/blob/59700e6926cbe96c5cdae897d9a7d2656b42abe3/LICENSE", "NIST Public Domain Notice with license fallback"),
            new AbstractMap.SimpleEntry<>("github.com/open-quantum-safe/liboqs/blob/40b01fdbb270f8614fde30e65d30e9da18c02393/src/common/rand/rand_nist.c#L1-L15", "NIST Software License"),
            new AbstractMap.SimpleEntry<>("data.norge.no/nlod/en/1.0", "Norwegian Licence for Open Government Data (NLOD) 1.0"),
            new AbstractMap.SimpleEntry<>("data.norge.no/nlod/en/2.0", "Norwegian Licence for Open Government Data (NLOD) 2.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/NLPL", "No Limit Public License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/nokia", "Nokia Open Source License"),
            new AbstractMap.SimpleEntry<>("bits.netizen.com.au/licenses/NOSL/nosl.txt", "Netizen Open Source License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Noweb", "Noweb License"),
            new AbstractMap.SimpleEntry<>("www.mozilla.org/MPL/NPL/1.0/", "Netscape Public License v1.0"),
            new AbstractMap.SimpleEntry<>("www.mozilla.org/MPL/NPL/1.1/", "Netscape Public License v1.1"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/NOSL3.0", "Non-Profit Open Software License 3.0"),
            new AbstractMap.SimpleEntry<>("web.mit.edu/network/isakmp/nrllicense.html", "NRL License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/NTP", "NTP License"),
            new AbstractMap.SimpleEntry<>("github.com/tytso/e2fsprogs/blob/master/lib/et/et_name.c", "NTP No Attribution"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Nunit", "Nunit License"),
            new AbstractMap.SimpleEntry<>("github.com/microsoft/Open-Use-of-Data-Agreement/blob/v1.0/O-UDA-1.0.md", "Open Use of Data Agreement v1.0"),
            new AbstractMap.SimpleEntry<>("www.opencascade.com/content/occt-public-license", "Open CASCADE Technology Public License"),
            new AbstractMap.SimpleEntry<>("www.oclc.org/research/activities/software/license/v2final.htm", "OCLC Research Public License 2.0"),
            new AbstractMap.SimpleEntry<>("www.opendatacommons.org/licenses/odbl/1.0/", "Open Data Commons Open Database License v1.0"),
            new AbstractMap.SimpleEntry<>("opendatacommons.org/licenses/by/1.0/", "Open Data Commons Attribution License v1.0"),
            new AbstractMap.SimpleEntry<>("sourceforge.net/p/xmedcon/code/ci/master/tree/libs/dicom/README", "OFFIS License"),
            new AbstractMap.SimpleEntry<>("scripts.sil.org/cms/scripts/page.php?item_id=OFL10_web", "SIL Open Font License 1.0"),
            new AbstractMap.SimpleEntry<>("scripts.sil.org/cms/scripts/page.php?item_id=OFL_web", "SIL Open Font License 1.1"),
            new AbstractMap.SimpleEntry<>("www.ogc.org/ogc/software/1.0", "OGC Software License, Version 1.0"),
            new AbstractMap.SimpleEntry<>("data.gov.tw/license", "Taiwan Open Government Data License, version 1.0"),
            new AbstractMap.SimpleEntry<>("open.canada.ca/en/open-government-licence-canada", "Open Government Licence - Canada"),
            new AbstractMap.SimpleEntry<>("www.nationalarchives.gov.uk/doc/open-government-licence/version/1/", "Open Government Licence v1.0"),
            new AbstractMap.SimpleEntry<>("www.nationalarchives.gov.uk/doc/open-government-licence/version/2/", "Open Government Licence v2.0"),
            new AbstractMap.SimpleEntry<>("www.nationalarchives.gov.uk/doc/open-government-licence/version/3/", "Open Government Licence v3.0"),
            new AbstractMap.SimpleEntry<>("www.opengroup.org/testing/downloads/The_Open_Group_TSL.txt", "Open Group Test Suite License"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=806557a5ad59804ef3a44d5abfbe91d706b0791f", "Open LDAP Public License v1.1"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=42b0383c50c299977b5893ee695cf4e486fb0dc7", "Open LDAP Public License v1.2"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=e5f8117f0ce088d0bd7a8e18ddf37eaa40eb09b1", "Open LDAP Public License v1.3"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=c9f95c2f3f2ffb5e0ae55fe7388af75547660941", "Open LDAP Public License v1.4"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=cbf50f4e1185a21abd4c0a54d3f4341fe28f36ea", "Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e", "Open LDAP Public License v2.0.1"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715", "Open LDAP Public License v2.1"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=470b0c18ec67621c85881b2733057fecf4a1acc3", "Open LDAP Public License v2.2"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=4bc786f34b50aa301be6f5600f58a980070f481e", "Open LDAP Public License v2.2.1"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=df2cc1e21eb7c160695f5b7cffd6296c151ba188", "Open LDAP Public License 2.2.2"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=d32cf54a32d581ab475d23c810b0a7fbaf8d63c3", "Open LDAP Public License v2.3"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=cd1284c4a91a8a380d904eee68d1583f989ed386", "Open LDAP Public License v2.4"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=6852b9d90022e8593c98205413380536b1b5a7cf", "Open LDAP Public License v2.5"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=1cae062821881f41b73012ba816434897abf4205", "Open LDAP Public License v2.6"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=47c2415c1df81556eeb39be6cad458ef87c534a2", "Open LDAP Public License v2.7"),
            new AbstractMap.SimpleEntry<>("www.openldap.org/software/release/license.html", "Open LDAP Public License v2.8"),
            new AbstractMap.SimpleEntry<>("openlogisticsfoundation.org/licenses/", "Open Logistics Foundation License Version 1.3"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Open_Market_License", "Open Market License"),
            new AbstractMap.SimpleEntry<>("github.com/adaptivecomputing/torque/blob/master/PBS_License.txt", "OpenPBS v2.3 Software License"),
            new AbstractMap.SimpleEntry<>("www.openssl.org/source/license.html", "OpenSSL License"),
            new AbstractMap.SimpleEntry<>("old.koalateam.com/jackaroo/OPL_1_0.TXT", "Open Public License v1.0"),
            new AbstractMap.SimpleEntry<>("www.parliament.uk/site-information/copyright-parliament/open-parliament-licence/", "United    Kingdom Open Parliament Licence v3.0"),
            new AbstractMap.SimpleEntry<>("opencontent.org/openpub/", "Open Publication License v1.0"),
            new AbstractMap.SimpleEntry<>("www.osetfoundation.org/public-license", "OSET Public License version 2.1"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/OSL-1.0", "Open Software License 1.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/OSL1.1", "Open Software License 1.1"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20041020171434/www.rosenlaw.com/osl2.0.html", "Open Software License 2.0"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20050212003940/www.rosenlaw.com/osl21.htm", "Open Software License 2.1"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20120101081418/rosenlaw.com:80/OSL3.0.htm", "Open Software License 3.0"),
            new AbstractMap.SimpleEntry<>("paritylicense.com/versions/6.0.0.html", "The Parity Public License 6.0.0"),
            new AbstractMap.SimpleEntry<>("paritylicense.com/versions/7.0.0.html", "The Parity Public License 7.0.0"),
            new AbstractMap.SimpleEntry<>("opendatacommons.org/licenses/pddl/1.0/", "Open Data Commons Public Domain Dedication & License 1.0"),
            new AbstractMap.SimpleEntry<>("www.php.net/license/3_0.txt", "PHP License v3.0"),
            new AbstractMap.SimpleEntry<>("www.php.net/license/3_01.txt", "PHP License v3.01"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License", "Plexus Classworlds License"),
            new AbstractMap.SimpleEntry<>("polyformproject.org/licenses/noncommercial/1.0.0", "PolyForm Noncommercial License 1.0.0"),
            new AbstractMap.SimpleEntry<>("polyformproject.org/licenses/small-business/1.0.0", "PolyForm Small Business License 1.0.0"),
            new AbstractMap.SimpleEntry<>("www.postgresql.org/about/licence", "PostgreSQL License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Python-2.0", "Python Software Foundation License 2.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/psfrag", "psfrag License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/psutils", "psutils License"),
            new AbstractMap.SimpleEntry<>("www.python.org/download/releases/2.0.1/license/", "Python License 2.0.1"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Qhull", "Qhull License"),
            new AbstractMap.SimpleEntry<>("doc.qt.nokia.com/3.3/license.html", "Q Public License 1.0"),
            new AbstractMap.SimpleEntry<>("github.com/maranget/hevea/blob/master/LICENSE", "Q Public License 1.0 - INRIA 2004 variant"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Rdisc_License", "Rdisc License"),
            new AbstractMap.SimpleEntry<>("ecos.sourceware.org/old-license.html", "Red Hat eCos Public License v1.1"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/RPL-1.1", "Reciprocal Public License 1.1"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/RPL-1.5", "Reciprocal Public License 1.5"),
            new AbstractMap.SimpleEntry<>("helixcommunity.org/content/rpsl", "RealNetworks Public Source License v1.0"),
            new AbstractMap.SimpleEntry<>("www.faqs.org/rfcs/rfc1321.html", "RSA Message-Digest License"),
            new AbstractMap.SimpleEntry<>("wayback.archive.org/web/20060715140826/www.risource.org/RPL/RPL-1.0A.shtml", "Ricoh Source Code Public License"),
            new AbstractMap.SimpleEntry<>("www.ruby-lang.org/en/LICENSE.txt", "Ruby License"),
            new AbstractMap.SimpleEntry<>("www.saxproject.org/copying.html", "Sax Public Domain Notice"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Saxpath_License", "Saxpath License"),
            new AbstractMap.SimpleEntry<>("research.scea.com/scea_shared_source_license.html", "SCEA Shared Source License"),
            new AbstractMap.SimpleEntry<>("www.sendmail.com/pdfs/open_source/sendmail_license.pdf", "Sendmail License"),
            new AbstractMap.SimpleEntry<>("www.proofpoint.com/sites/default/files/sendmail-license.pdf", "Sendmail License 8.23"),
            new AbstractMap.SimpleEntry<>("oss.sgi.com/projects/FreeB/SGIFreeSWLicB.1.0.html", "SGI Free Software License B v1.0"),
            new AbstractMap.SimpleEntry<>("oss.sgi.com/projects/FreeB/", "SGI Free Software License B v1.1"),
            new AbstractMap.SimpleEntry<>("oss.sgi.com/projects/FreeB/SGIFreeSWLicB.2.0.pdf", "SGI Free Software License B v2.0"),
            new AbstractMap.SimpleEntry<>("celestrak.org/publications/AIAA/2006-6753/faq.php", "SGP4 Permission Notice"),
            new AbstractMap.SimpleEntry<>("solderpad.org/licenses/SHL-0.5/", "Solderpad Hardware License v0.5"),
            new AbstractMap.SimpleEntry<>("solderpad.org/licenses/SHL-0.51/", "Solderpad Hardware License, Version 0.51"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/SimPL-2.0", "Simple Public License 2.0"),
            new AbstractMap.SimpleEntry<>("www.openoffice.org/licenses/sissl_license.html", "Sun Industry Standards Source License v1.1"),
            new AbstractMap.SimpleEntry<>("gridscheduler.sourceforge.net/Gridengine_SISSL_license.html", "Sun Industry Standards Source License v1.2"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Sleepycat", "Sleepycat License"),
            new AbstractMap.SimpleEntry<>("www.smlnj.org/license.html", "Standard ML of New Jersey License"),
            new AbstractMap.SimpleEntry<>("github.com/dcblake/SMP/blob/master/Documentation/License.txt", "Secure Messaging Protocol Public License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/SNIA_Public_License", "SNIA Public License 1.1"),
            new AbstractMap.SimpleEntry<>("github.com/openssh/openssh-portable/blob/master/openbsd-compat/bsd-snprintf.c#L2", "snprintf License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License", "Spencer License 86"),
            new AbstractMap.SimpleEntry<>("www.opensource.apple.com/source/tcl/tcl-5/tcl/generic/regfronts.c", "Spencer License 99"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/SPL-1.0", "Sun Public License v1.0"),
            new AbstractMap.SimpleEntry<>("github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/LICENCE#L10", "SSH OpenSSH license"),
            new AbstractMap.SimpleEntry<>("github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/pathnames.h", "SSH short notice"),
            new AbstractMap.SimpleEntry<>("www.mongodb.com/licensing/server-side-public-license", "Server Side Public License, v 1"),
            new AbstractMap.SimpleEntry<>("www.sugarcrm.com/crm/SPL", "SugarCRM Public License v1.1.3"),
            new AbstractMap.SimpleEntry<>("github.com/freebsd/freebsd-src/blob/main/lib/msun/src/e_acosh.c", "SunPro License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/SWL", "Scheme Widget Library (SWL) Software License Agreement"),
            new AbstractMap.SimpleEntry<>("www.mail-archive.com/debian-bugs-rc@lists.debian.org/msg11494.html", "Symlinks License"),
            new AbstractMap.SimpleEntry<>("www.tapr.org/OHL", "TAPR Open Hardware License v1.0"),
            new AbstractMap.SimpleEntry<>("www.tcl.tk/software/tcltk/license.html", "TCL/TK License"),
            new AbstractMap.SimpleEntry<>("rc.quest.com/topics/openssh/license.php#tcpwrappers", "TCP Wrappers License"),
            new AbstractMap.SimpleEntry<>("github.com/jonathanstowe/TermReadKey/blob/master/README#L9-L10", "TermReadKey License"),
            new AbstractMap.SimpleEntry<>("svnkit.com/license.html", "TMate Open Source License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/TORQUEv1.1", "TORQUE v2.5+ Software License v1.1"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/TOSL", "Trusster Open Source License"),
            new AbstractMap.SimpleEntry<>("metacpan.org/pod/Time::ParseDate#LICENSE", "Time::ParseDate License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing:ThorPublicLicense", "THOR Public License 1.0"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/TTWL", "Text-Tabs+Wrap License"),
            new AbstractMap.SimpleEntry<>("github.com/swh/ladspa/blob/7bf6f3799fdba70fda297c2d8fd9f526803d9680/gsm/COPYRIGHT", "Technische Universitaet Berlin License 1.0"),
            new AbstractMap.SimpleEntry<>("github.com/CorsixTH/deps/blob/fd339a9f526d1d9c9f01ccf39e438a015da50035/licences/libgsm.txt", "Technische Universitaet Berlin License 2.0"),
            new AbstractMap.SimpleEntry<>("github.com/Unidata/UDUNITS-2/blob/master/COPYRIGHT", "UCAR License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/UCL-1.0", "Upstream Compatibility License v1.0"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20151224134844/unicode.org/copyright.html", "Unicode License Agreement - Data Files and Software (2015)"),
            new AbstractMap.SimpleEntry<>("www.unicode.org/license.txt", "Unicode License Agreement - Data Files and Software (2016)"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20140704074106/www.unicode.org/copyright.html", "Unicode Terms of Use"),
            new AbstractMap.SimpleEntry<>("foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/LICENSE#L70", "UnixCrypt License"),
            new AbstractMap.SimpleEntry<>("unlicense.org/", "The Unlicense"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/UPL", "Universal Permissive License v1.0"),
            new AbstractMap.SimpleEntry<>("vimdoc.sourceforge.net/htmldoc/uganda.html", "Vim License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/VOSTROM", "VOSTROM Public License for Open Source"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/VSL-1.0", "Vovida Software License v1.0"),
            new AbstractMap.SimpleEntry<>("www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html", "W3C Software Notice and License (2002-12-31)"),
            new AbstractMap.SimpleEntry<>("www.w3.org/Consortium/Legal/copyright-software-19980720.html", "W3C Software Notice and License (1998-07-20)"),
            new AbstractMap.SimpleEntry<>("www.w3.org/Consortium/Legal/2015/copyright-software-and-document", "W3C Software Notice and Document License (2015-05-13)"),
            new AbstractMap.SimpleEntry<>("github.com/tats/w3m/blob/master/COPYING", "w3m License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Watcom-1.0", "Sybase Open Watcom Public License 1.0"),
            new AbstractMap.SimpleEntry<>("github.com/novnc/noVNC/blob/master/core/crypto/des.js#L24", "Widget Workshop License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Wsuipa", "Wsuipa License"),
            new AbstractMap.SimpleEntry<>("www.wtfpl.net/about/", "Do What The F*ck You Want To Public License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/WXwindows", "wxWindows Library License"),
            new AbstractMap.SimpleEntry<>("www.xfree86.org/3.3.6/COPYRIGHT2.html#3", "X11 License"),
            new AbstractMap.SimpleEntry<>("github.com/mirror/ncurses/blob/master/COPYING", "X11 License Distribution Modification Variant"),
            new AbstractMap.SimpleEntry<>("github.com/xdebug/xdebug/blob/master/LICENSE", "Xdebug License v 1.03"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Xerox", "Xerox License"),
            new AbstractMap.SimpleEntry<>("github.com/Distrotech/transfig/blob/master/transfig/transfig.c", "Xfig License"),
            new AbstractMap.SimpleEntry<>("www.xfree86.org/current/LICENSE4.html", "XFree86 License 1.1"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Xinetd_License", "xinetd License"),
            new AbstractMap.SimpleEntry<>("fossies.org/linux/tiff/contrib/ras/ras2tif.c", "xlock License"),
            new AbstractMap.SimpleEntry<>("opensource.org/licenses/Xnet", "X.Net License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/xpp", "XPP License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/XSkat_License", "XSkat License"),
            new AbstractMap.SimpleEntry<>("www.zimbra.com/license/yahoo_public_license_1.0.html", "Yahoo! Public License v1.0"),
            new AbstractMap.SimpleEntry<>("www.zimbra.com/license/yahoo_public_license_1.1.html", "Yahoo! Public License v1.1"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/Zed", "Zed License"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20130517195954/www.zend.com/license/2_00.txt", "Zend License v2.0"),
            new AbstractMap.SimpleEntry<>("web.archive.org/web/20100302225219/www.zimbra.com/license/zimbra-public-license-1-3.html", "Zimbra Public License v1.3"),
            new AbstractMap.SimpleEntry<>("www.zimbra.com/legal/zimbra-public-license-1-4", "Zimbra Public License v1.4"),
            new AbstractMap.SimpleEntry<>("www.zlib.net/zlib_license.html", "zlib License"),
            new AbstractMap.SimpleEntry<>("fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement", "zlib/libpng License with Acknowledgement"),
            new AbstractMap.SimpleEntry<>("old.zope.org/Resources/License/ZPL-1.1", "Zope Public License 1.1"),
            new AbstractMap.SimpleEntry<>("old.zope.org/Resources/License/ZPL-2.0", "Zope Public License 2.0"),
            new AbstractMap.SimpleEntry<>("old.zope.org/Resources/ZPL/", "Zope Public License 2.1")
        );
    }
}
