version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-9.4.x"
    schedule:
      interval: "weekly"
    ignore:
      # Restrict updates in this branch to jetty in the 9.4.x space
      - dependency-name: "javax.servlet:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "javax.activation:*"
        versions: [ ">=1.3.0" ]
      - dependency-name: "javax.annotation:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "javax.el:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "javax.inject:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "javax.websocket:*"
        versions: [ ">=1.1.0" ]

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-10.0.x"
    schedule:
      interval: "weekly"
    ignore:
      # Restrict updates in this branch to jetty in the 10.x.x space
      - dependency-name: "jakarta.servlet:*"
        versions: [ ">=5.0.0" ]
      - dependency-name: "jakarta.activation:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.annotation:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.el:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "jakarta.inject:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.websocket:*"
        versions: [ ">=2.0.0" ]

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-11.0.x"
    schedule:
      interval: "weekly"
    ignore:
      # Restrict updates in this branch to jetty in the 11.x.x space
      - dependency-name: "jakarta.servlet:*"
        versions: [ ">=6.0.0" ]
      - dependency-name: "jakarta.activation:*"
        versions: [ ">=2.1.0" ]
      - dependency-name: "jakarta.annotation:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.el:*"
        versions: [ ">=5.0.0" ]
      - dependency-name: "jakarta.inject:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.websocket:*"
        versions: [ ">=3.0.0" ]
