version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "jetty-10.0.x"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "10:00"
      timezone: "Australia/Brisbane"
    # Associate with milestone 10.0.x
    milestone: 6
    commit-message:
      prefix: "[10.0.x] "
    groups:
      build-deps:
        patterns:
          - "org.apache.maven:*"
          - "org.apache.maven.plugins:*"
          - "org.apache.maven.plugin-tools:*"
          - "org.apache.felix:*-plugin"
          - "org.apache.servicemix.tooling:*"
          - "org.asciidoctor:*"
          - "org.codehaus.mojo:*"
          - "org.eclipse.jetty.toolchain:*-maven-plugin"
          - "org.jacoco:*"
          - "org.mortbay:*-maven-plugin"
          - "org.testcontainers:*"
          - "com.diffplug.spotless:*"
          - "com.github.spotbugs:*"
          - "com.mycila:*"
      integration-deps:
        patterns:
          - "org.infinispan*"
          - "org.mongodb*"
          - "org.wildfly*"
          - "org.eclipse.platform*"
          - "com.google.cloud:*"
          - "org.hawtio:*"
      spec-deps:
        patterns:
          - "jakarta.*"
          - "org.jboss.weld.*"
          - "com.sun.xml*"
          - "org.glassfish.jaxb*"
          - "org.mortbay.jasper:*"
      dev-dependencies:
        patterns:
          - "*"
    ignore:
      # Do not upgrade major versions of dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      # Restrict updates in this branch to jetty in the 10.x.x space
      - dependency-name: "jakarta.servlet:*"
        versions: [ ">=5.0.0" ]
      - dependency-name: "jakarta.activation:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.annotation:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.el:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "jakarta.inject:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.interceptor:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.websocket:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.servlet.jsp:*"
        versions: [ ">=2.4.0" ]
      - dependency-name: "jakarta.servlet.jsp.jstl:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "org.jboss.weld.servlet:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "jakarta.enterprise:jakarta.enterprise.cdi-api:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "com.sun.xml.ws:jaxws-rt"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.transaction:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "org.infinispan:*"
        versions: [ ">=12" ]
      - dependency-name: "jakarta.xml.bind:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "org.glassfish.jaxb:*"
        versions: [ ">=3.0.0"]
      - dependency-name: "ch.qos.logback:*"
        versions: [ ">=1.4.0"]
      - dependency-name: "org.mortbay.jasper:*"
        versions: [ ">=10.0.0"]

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 30
    target-branch: "jetty-11.0.x"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "10:00"
      timezone: "Australia/Brisbane"
    # Associate with milestone 11.0.x
    milestone: 7
    commit-message:
      prefix: "[11.0.x] "
    groups:
      build-deps:
        patterns:
          - "org.apache.maven:*"
          - "org.apache.maven.plugins:*"
          - "org.apache.maven.plugin-tools:*"
          - "org.apache.felix:*-plugin"
          - "org.apache.servicemix.tooling:*"
          - "org.asciidoctor:*"
          - "org.codehaus.mojo:*"
          - "org.eclipse.jetty.toolchain:*-maven-plugin"
          - "org.jacoco:*"
          - "org.mortbay:*-maven-plugin"
          - "org.testcontainers:*"
          - "com.diffplug.spotless:*"
          - "com.github.spotbugs:*"
          - "com.mycila:*"
      integration-deps:
        patterns:
          - "org.infinispan*"
          - "org.mongodb*"
          - "org.wildfly*"
          - "org.eclipse.platform*"
          - "com.google.cloud:*"
          - "org.hawtio:*"
      spec-deps:
        patterns:
          - "jakarta.*"
          - "org.jboss.weld.*"
          - "com.sun.xml*"
          - "org.glassfish.jaxb*"
          - "org.mortbay.jasper:*"
      dev-dependencies:
        patterns:
          - "*"
    ignore:
      # Do not upgrade major versions of dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      # Restrict updates in this branch to jetty in the 11.x.x space
      - dependency-name: "jakarta.activation:*"
        versions: [ ">=2.1.0" ]
      - dependency-name: "jakarta.annotation:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.authentication:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.el:*"
        versions: [ ">=5.0.0" ]
      - dependency-name: "jakarta.enterprise:jakarta.enterprise.cdi-api:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.inject:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.interceptor:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.mail:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.servlet:*"
        versions: [ ">=6.0.0" ]
      - dependency-name: "jakarta.servlet.jsp:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "jakarta.servlet.jsp.jstl:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.transaction:*"
        versions: [ ">=2.0.0" ]
      - dependency-name: "jakarta.websocket:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "jakarta.ws.rs:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "jakarta.xml.bind:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "org.glassfish.jaxb:*"
        versions: [ ">=4.0.0"]
      - dependency-name: "jakarta.xml.ws:*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "com.sun.xml.ws:jaxws*"
        versions: [ ">=4.0.0" ]
      - dependency-name: "org.jboss.weld.servlet:*"
        versions: [ ">=5.0.0" ]
      - dependency-name: "org.infinispan:*"
        versions: [ ">=12" ]
      - dependency-name: "org.mortbay.jasper:*"
        versions: [ ">=10.1.0"]

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 30
    target-branch: "jetty-9.4.x"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "10:00"
      timezone: "Australia/Brisbane"
    # Associate with milestone 9.4.x
    milestone: 3
    commit-message:
      prefix: "[9.4.x] "
    groups:
      dev-dependencies:
        patterns:
          - "*"
    ignore:
      # Do not upgrade major versions of dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      # Restrict updates in this branch to jetty in the 9.4.x space
      - dependency-name: "org.infinispan:*"
        versions: [ ">=12" ]
      - dependency-name: "com.hazelcast:*"
      - dependency-name: "org.apache.directory*"
      - dependency-name: "org.apache.felix:*"
        versions: [ ">=4" ]
      - dependency-name: "org.jboss.weld.servlet:*"
        versions: [ ">=4" ]
      - dependency-name: "org.jboss.threads:jboss-threads"
        versions: [ ">=3.6" ]
      - dependency-name: "ch.qos.logback:*"
        versions: [ ">=1.3" ]
      - dependency-name: "org.asciidoctor:asciidoctor-maven-plugin"
        versions: [ ">=3" ]
      - dependency-name: "org.wildfly.common:*"
        versions: [ ">=1.6" ]
      - dependency-name: "org.wildfly.security:*"
        versions: [ ">=2.3" ]
      - dependency-name: "org.eclipse.platform:org.eclipse.osgi.services"
        versions: [ ">=3.12" ]

