# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Adds the Jetty JNDI implementation to the classpath.

[depend]
server

[lib]
lib/jetty-jndi-${jetty.version}.jar
