# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo JNDI Resources Webapp

[environment]
ee9

[tags]
demo
webapp

[depends]
ee9-deploy
ext
jdbc
ee9-jndi
ee9-plus
ee9-demo-mock-resources

[files]
basehome:modules/demo.d/ee9-demo-jndi.xml|webapps/ee9-demo-jndi.xml
basehome:modules/demo.d/ee9-demo-jndi.properties|webapps/ee9-demo-jndi.properties
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-jndi-webapp/${jetty.version}/war|webapps/ee9-demo-jndi.war
maven://com.sun.mail/jakarta.mail/2.0.1/jar|lib/ee9/jakarta.mail-2.0.1.jar
maven://com.sun.activation/jakarta.activation/2.0.1/jar|lib/ee9/jakarta.activation-2.0.1.jar

[lib]
lib/ee9/jakarta.mail-2.0.1.jar
lib/ee9/jakarta.activation-2.0.1.jar