# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the RewriteHandler to the Handler chain.
Specific rewrite rules must be added to $JETTY_BASE/etc/jetty-rewrite-rules.xml.

[tags]
server

[provides]
rewrite|default

[depend]
server

[lib]
lib/jetty-rewrite-${jetty.version}.jar

[files]
basehome:modules/rewrite/jetty-rewrite-rules.xml|etc/jetty-rewrite-rules.xml

[xml]
etc/jetty-rewrite.xml
etc/jetty-rewrite-rules.xml

[ini-template]
# tag::documentation[]
## Request attribute name used to store the original request path.
# jetty.rewrite.originalPathAttribute=jetty.rewrite.originalRequestPath
# end::documentation[]
