# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Add a rule to the rewrite module to compact paths.
Double slashes in the path are treated as a single slash.

[depends]
rewrite

[xml]
etc/jetty-rewrite-compactpath.xml
