# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JASPI authentication for deployed web applications.

[environment]
ee9

[tags]
security

[depend]
ee9-security
ee9-auth-config-factory

[lib]
lib/jetty-ee9-jaspi-${jetty.version}.jar
lib/ee9-jaspi/@jakarta.authentication:jakarta.authentication-api@

[xml]
etc/jaspi/jetty-ee9-jaspi-authmoduleconfig.xml

[files]
basehome:etc/jaspi/jetty-ee9-jaspi-authmoduleconfig.xml|etc/jaspi/jetty-ee9-jaspi-authmoduleconfig.xml

