# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JASPI authentication for deployed web applications.

[environment]
ee9

[tags]
security

[depends]
ee9-security
ee9-auth-config-factory

[xml]
etc/jaspi/jetty-ee9-jaspi-authmoduleconfig.xml

[ini]
jakarta.authentication-api.version?=@jakarta.authentication-api.version@

[files]
basehome:etc/jaspi/jetty-ee9-jaspi-authmoduleconfig.xml|etc/jaspi/jetty-ee9-jaspi-authmoduleconfig.xml
maven://jakarta.authentication/jakarta.authentication-api/${jakarta.authentication-api.version}/jar|lib/ee9/support/jakarta.authentication.jakarta.authentication-api-${jakarta.authentication-api.version}.jar
maven://org.eclipse.jetty.ee9/jetty-ee9-jaspi/${jetty.version}/jar|lib/ee9/jetty-ee9-jaspi-${jetty.version}.jar

[lib]
lib/ee9/jetty-ee9-jaspi-${jetty.version}.jar
lib/ee9/support/jakarta.authentication.jakarta.authentication-api-${jakarta.authentication-api.version}.jar
