# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Provides a DefaultAuthConfigFactory for jaspi

[tags]
security

[environment]
ee9

[depend]
ee9-security

[provide]
ee9-auth-config-factory

[xml]
etc/jaspi/jetty-ee9-jaspi-default.xml
