//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-protocols]]
=== Jetty Connectors and Protocols

Connectors are the network components through which Jetty accepts incoming network connections.

Each connector listens on a network port and can be configured with `ConnectionFactory` components that _understand_ one or more network protocols.

Understanding a protocol means that the connector is able to interpret incoming network bytes (for example, the bytes that represent an HTTP/1.1 request) and convert them into more abstract objects (for example an `HttpServletRequest` object) that are then processed by applications.
Conversely, an abstract object (for example an `HttpServletResponse`) is converted into the correspondent outgoing network bytes (the bytes that represent an HTTP/1.1 response).

Like other Jetty components, connectors are enabled and configured by enabling and configuring the correspondent Jetty module.

IMPORTANT: Recall that you must always issue the commands to enable Jetty modules from within the `$JETTY_BASE` directory, and that the Jetty module configuration files are in the `$JETTY_BASE/start.d/` directory.

You can obtain the list of connector-related modules in this way:

----
$ java -jar $JETTY_HOME/start.jar --list-modules=connector
----

include::protocols-http.adoc[]
include::protocols-https.adoc[]
include::protocols-http2.adoc[]
include::protocols-http2s.adoc[]
include::protocols-http2c.adoc[]
include::protocols-http3.adoc[]
include::protocols-ssl.adoc[]
include::protocols-proxy.adoc[]
include::protocols-websocket.adoc[]

// TODO: old_docs/connectors/*.adoc

// TODO: add documentation for how to add an additional connector e.g. with a name
//  we have 2 connectors out of the box, but a third would need an additional XML.
