//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-protocols-fcgi]]
==== FastCGI

FastCGI is a network protocol primarily used by a _web server_ to communicate to a __FastCGI server__.

FastCGI servers are typically used to serve web content generated by dynamic web languages, primarily http://www.php.net/[PHP], but also Python, Ruby, Perl and others.

Web servers that supports FastCGI are, among others, http://httpd.apache.org/[Apache], http://nginx.org/[Nginx], and Jetty.
Web servers typically act as reverse proxies, converting HTTP requests that they receive from clients (browsers) to FastCGI requests that are forwarded to the FastCGI server.
The FastCGI server spawns the dynamic web language interpreter, passing it the information contained in the FastCGI request and a dynamic web language script is executed, producing web content, typically HTML.
The web content is then formatted into a FastCGI response that is returned to the web server, which converts it to an HTTP response that is then returned to the client.

The most well known FastCGI server is the http://php-fpm.org/[PHP FastCGI Process Manager], or `php-fpm`.
In the following we will assume that `php-fpm` is used as FastCGI server.

This is a diagram of what described above:

[plantuml]
----
skinparam backgroundColor transparent
skinparam monochrome true
skinparam shadowing false

Browser -> Jetty : GET /path (HTTP)
Jetty -> "php-fpm" : GET /path (FastCGI)
"php-fpm" -> PHP : spawn PHP interpreter
PHP -> "index.php" : execute PHP script
"index.php" -> "php-fpm" : HTML
"php-fpm" -> Jetty : 200 OK + HTML (FastCGI)
Jetty -> Browser : 200 OK + HTML (HTTP)

----

Jetty can be configured to act as a web server that supports FastCGI, replacing the functionality that is normally provided by Apache or Nginx.
This allows users to leverage Jetty features such as the support for HTTP/1.1, HTTP/2 and HTTP/3, Jetty's scalability, and of course Jetty's native support for Java Web Standards such as Servlets, JSPs, etc.

With such configuration, users can not only deploy their Java Web Applications in Jetty, but also serve their http://wordpress.com/[WordPress] site or blog or their https://drupal.org/[Drupal] site without having to install and manage multiple web servers.

[[og-protocols-fcgi-configure]]
===== Configuring WordPress

This section explains how to configure Jetty to serve your link:https://wordpress.com/[WordPress] site.

The prerequisites are:

* Have `php-fpm` installed on your server host, and configured to listen either on a Unix-Domain socket (such as `/run/php/php-fpm.sock`), or on a TCP socket (such as `localhost:9000`).
* Have WordPress installed on your server host, for example under `/var/www/wordpress`.
For more information about how to install WordPress and the necessary PHP modules, please refer to the link:https://wordpress.org/support/article/how-to-install-wordpress/[WordPress Installation Guide].

Then, the xref:og-protocols-https[secure HTTP] and/or the xref:og-protocols-http2[secure HTTP/2] Jetty modules should be enabled to allow browsers to connect to Jetty.

Lastly, enable the `fcgi-proxy` module to provide FastCGI support (to convert HTTP requests from browsers to FastCGI for `php-fpm` and vice versa), and the `core-deploy` module to deploy your WordPress web application as a xref:og-deploy-jetty[Jetty context XML file].

For example:

----
$ java -jar $JETTY_HOME/start.jar --add-modules=ssl,https,fcgi-proxy,core-deploy
----

TIP: The `https` Jetty module requires a KeyStore. If you do not already have one configured, you can add the `test-keystore` Jetty module to the command line above to create a KeyStore on-the-fly.

Now you can deploy a Jetty context XML file that represents your WordPress web application.

Use the following file as example, copy it as `$JETTY_BASE/webapps/wordpress.xml` and customize it as necessary:

[source,xml,options=nowrap]
----
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN" "http://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.server.handler.ContextHandler">

  <New id="root" class="java.lang.String">
    <Arg>/var/www/wordpress</Arg> <!--1-->
  </New>

  <Set name="contextPath">/</Set> <!--2-->
  <Set name="baseResourceAsString"><Ref refid="root" /></Set>

  <Set name="handler">
    <New class="org.eclipse.jetty.server.handler.TryPathsHandler">
      <Set name="originalPathAttribute">wordpress.originalPath</Set>
      <Set name="originalQueryAttribute">wordpress.originalQuery</Set>
      <Set name="paths">
        <Call class="java.util.List" name="of">
          <Arg>$path</Arg>
          <Arg>/index.php</Arg>
        </Call>
      </Set>

      <Set name="handler">
        <New class="org.eclipse.jetty.server.handler.PathMappingsHandler">
          <Call name="addMapping">
            <Arg>
              <New class="org.eclipse.jetty.http.pathmap.ServletPathSpec"><Arg>*.php</Arg></New>
            </Arg>
            <Arg>
              <New class="org.eclipse.jetty.fcgi.proxy.FastCGIProxyHandler"> <!--3-->
                <Arg>(https?)://([^/]+)(.*)</Arg> <!--4-->
                <Arg>http://localhost:9000$3</Arg> <!--5-->
                <Arg><Ref refid="root" /></Arg>

                <Set name="originalPathAttribute">wordpress.originalPath</Set>
                <Set name="originalQueryAttribute">wordpress.originalQuery</Set>
                <Set name="scriptPattern"><Call class="java.util.regex.Pattern" name="compile"><Arg>(.+?\\.php)</Arg></Call></Set>
                <Set name="fastCGISecure">true</Set>
                <Set name="unixDomainPath"><Call class="java.nio.file.Path" name="of"><Arg>/run/php/php-fpm.sock</Arg></Call></Set> <!--6-->
              </New>
            </Arg>
          </Call>
          <Call name="addMapping">
            <Arg>
              <New class="org.eclipse.jetty.http.pathmap.ServletPathSpec"><Arg>/</Arg></New>
            </Arg>
            <Arg>
              <New class="org.eclipse.jetty.server.handler.ResourceHandler"> <!--7-->
                <Set name="welcomeFiles"><Call class="java.util.List" name="of"><Arg>/index.php</Arg></Call></Set>
                <Set name="welcomeMode"><Call class="org.eclipse.jetty.server.ResourceService$WelcomeMode" name="valueOf"><Arg>REHANDLE</Arg></Call></Set>
                <Set name="dirAllowed">false</Set>
              </New>
            </Arg>
          </Call>
        </New>
      </Set>
    </New>
  </Set>

</Configure>
----
<1> Specify the WordPress installation path.
<2> Specify the context path of your web application.
<3> The `FastCGIProxyHandler` forwards requests whose URI path matches `+*.php+` to `php-fpm`.
<4> The client URI regex pattern to match.
<5> The URI used to forward the request to `php-fpm`, where `+$3+` is the 3rd matching group of the client URI regex pattern (int this example, the client URI path).
If `php-fpm` is configured to listen on a TCP socket, the host and port must match the listening TCP socket.
If `php-fpm` is configured to listen on a Unix-Domain socket, the host and port values are ignored but must be present.
<6> If `php-fpm` is configured to listen on a Unix-Domain socket, specify the Unix-Domain socket path, otherwise omit this line.
<7> The `ResourceHandler` serves static files from WordPress, such as `+*.css+`, `+*.js+` and image files.

Now you can start Jetty and navigate to `+http://localhost:8080+` with your browser to enjoy WordPress:

----
$ java -jar $JETTY_HOME/start.jar
----
