<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.demos</groupId>
    <artifactId>jetty-servlet6-demos</artifactId>
    <version>12.1.13</version>
  </parent>
  <artifactId>jetty-servlet6-demo-jspc-6-1-webapp</artifactId>
  <packaging>war</packaging>
  <name>Servlet 6 :: Demo Servlet 6.1 :: Precompiled JSP WebApp</name>

  <properties>
    <bundle-symbolic-name>${project.groupId}.servlet6.jspc61</bundle-symbolic-name>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-apache-jsp</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-glassfish-jstl</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <supportedProjectTypes>
            <supportedProjectType>war</supportedProjectType>
          </supportedProjectTypes>
          <instructions>
            <Import-Package>jakarta.servlet;version="6.1", jakarta.servlet.http;version="6.1", jakarta.servlet.jsp.*;version="3",*</Import-Package>
            <Export-Package>!org.example.*</Export-Package>
            <Web-ContextPath>/servlet6-demo-jspc-61</Web-ContextPath>
            <Bundle-ClassPath>.,WEB-INF/classes</Bundle-ClassPath>
          </instructions>
        </configuration>
        <executions>
          <execution>
            <id>ee11</id>
            <goals>
              <goal>manifest</goal>
            </goals>
            <configuration>
              <instructions>
                <Jetty-Environment>ee11</Jetty-Environment>
              </instructions>
              <manifestLocation>${project.build.outputDirectory}/META-INF-ee11</manifestLocation>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>ee11-web-bundle-assembly</id>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <descriptors>
                <descriptor>src/main/assembly/ee11-web-bundle.xml</descriptor>
              </descriptors>
              <archive>
                <manifestFile>${project.build.outputDirectory}/META-INF-ee11/MANIFEST.MF</manifestFile>
              </archive>
              <mergeManifestMode>merge</mergeManifestMode>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <configuration>
          <packagingExcludes>**/*.jsp</packagingExcludes>
          <archive>
            <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>precompile-jsp</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-war-plugin</artifactId>
            <configuration>
              <webXml>${basedir}/target/web.xml</webXml>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.eclipse.jetty.ee11</groupId>
            <artifactId>jetty-ee11-jspc-maven-plugin</artifactId>
            <version>${project.version}</version>
            <executions>
              <execution>
                <id>jspc</id>
                <goals>
                  <goal>jspc</goal>
                </goals>
                <configuration>
                  <keepSources>true</keepSources>
                  <!-- example configuration
                   <includes>**/*.foo</includes>
                   <excludes>**/*.fff</excludes>
                   <sourceVersion>1.8</sourceVersion>
                   <targetVersion>1.8</targetVersion>
                 -->
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
