//  ========================================================================
//  Copyright (c) 1995-2016 Mort Bay Consulting Pty. Ltd.
//  ========================================================================
//  All rights reserved. This program and the accompanying materials
//  are made available under the terms of the Eclipse Public License v1.0
//  and Apache License v2.0 which accompanies this distribution.
//
//      The Eclipse Public License is available at
//      http://www.eclipse.org/legal/epl-v10.html
//
//      The Apache License v2.0 is available at
//      http://www.opensource.org/licenses/apache2.0.php
//
//  You may elect to redistribute this code under either of these licenses.
//  ========================================================================

[[contributing-patches]]
=== Contributing Patches

How to contribute a patch to the jetty project.
You should first familiarize yourself with the Eclipse wiki page on http://wiki.eclipse.org/Development_Resources/Contributing_via_Git[contributing
via Git].
Not everything is specifically relevant since we are at GitHub but the crux of things are detailed there.  The CLA is critically important to the process.

[[contributing-cla]]
==== Sign a CLA

The Eclipse Foundation has a strong Intellectual Property policy which tracks contributions in detail to ensure that:

1.  Did the contributor author 100% of the content?
2.  Does the contributor have the rights to contribute this content to Eclipse?
3.  Is the contribution under the project’s license(s) (e.g. EPL)

Thus a contributor needs to e-sign a Contributor Licence Agreement (for more explanation see the http://www.eclipse.org/legal/clafaq.php[Eclipse CLA FAQ] ) regardless of how their contribution patch is provided.

____
[TIP]
Log into the https://projects.eclipse.org/user/login/sso[Eclipse projects forge] (you will need to create an account with the Eclipse Foundation if you have not already done so); click on "Contributor License Agreement"; and Complete the form.
Be sure to use the _same email address_ when you create any Git commit records.
____

==== GitHub Contribution

Jetty is hosted at GitHub and accepts pull requests now.
However you must have a CLA on file as mentioned above, with the email address you will be using at github for your signed commit.
Make sure your commit is using the email that you registered in your CLA or no amount of pushing
the in world from us will get past the eclipse git commit hooks.
When you do your commit that you use for the pull request it is also _vital_ that you "sign-off" on the commit using "git commit -s". Without the sign-off, your patch cannot be applied to the jetty repo because it will be rejected.

One way to think of this is that when you sign the CLA you are indicating that you are free to contribute to eclipse, but that doesn't mean everything you ever do can be contributed.
Using the commit signing mechanism indicates that your commit is under the auspices of your agreement.
