# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds the Jetty JNDI implementation to the classpath.

[depend]
server

[lib]
lib/jetty-jndi-${jetty.version}.jar
