# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Installs OpenTelemetryHandler at the root of the Handler tree,
to support exporting OpenTelemetry spans and metrics for requests and responses.
Requires separate installation of an OpenTelemetry agent in the JVM, configured to export OTel to desired backends.

[tags]
server
handler
opentelemetry

[depend]
server

[lib]
lib/opentelemetry/jetty-opentelemetry-server-${jetty.version}.jar

[xml]
etc/jetty-opentelemetry.xml
