# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the Jetty Proxy Servlet.

[environment]
<inherit>

[depend]
client
ee/common-servlet

[lib]
lib/jetty-ee-proxy-${jetty.version}.jar

[xml]
etc/jetty-ee-proxy.xml
