# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables support for EE9 FastCGI proxying.

[environment]
ee9

[tags]
fcgi
proxy

[depends]
fcgi

[files]
maven://org.eclipse.jetty.ee9/jetty-ee9-fcgi-proxy/${jetty.version}/jar|lib/ee9/jetty-ee9-fcgi-proxy-${jetty.version}.jar
maven://org.eclipse.jetty.ee9/jetty-ee9-proxy/${jetty.version}/jar|lib/ee9/jetty-ee9-proxy-${jetty.version}.jar

[lib]
lib/ee9/jetty-ee9-fcgi-proxy-${jetty.version}.jar
lib/ee9/jetty-ee9-proxy-${jetty.version}.jar
