# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee12

[depend]
ee/common-annotations
ee12-plus
annotations

[lib]
lib/jetty-ee12-annotations-${jetty.version}.jar
lib/ee12-annotations/@jakarta.annotation:jakarta.annotation-api@
