# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Enables standard Servlet handling.

[depend]
server

[lib]
lib/jetty-servlet-${jetty.version}.jar
