# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enable jakarta.websocket APIs for deployed web applications.

[environment]
ee10

[tags]
websocket

[depends]
websocket-core-client
websocket-core-server
ee10-annotations

[files]
maven://jakarta.websocket/jakarta.websocket-api/2.1.1/jar|lib/ee10/support/jakarta.websocket.jakarta.websocket-api-2.1.1.jar
maven://jakarta.websocket/jakarta.websocket-client-api/2.1.1/jar|lib/ee10/support/jakarta.websocket.jakarta.websocket-client-api-2.1.1.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-jakarta-client/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-jakarta-client-${jetty.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-jakarta-common/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-jakarta-common-${jetty.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-jakarta-server/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-jakarta-server-${jetty.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-servlet/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-servlet-${jetty.version}.jar

[lib]
lib/ee10/jetty-ee10-websocket-jakarta-client-${jetty.version}.jar
lib/ee10/jetty-ee10-websocket-jakarta-common-${jetty.version}.jar
lib/ee10/jetty-ee10-websocket-jakarta-server-${jetty.version}.jar
lib/ee10/jetty-ee10-websocket-servlet-${jetty.version}.jar
lib/ee10/support/jakarta.websocket.jakarta.websocket-api-2.1.1.jar
lib/ee10/support/jakarta.websocket.jakarta.websocket-client-api-2.1.1.jar
