# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enable jakarta.websocket APIs for deployed web applications.

[environment]
ee10

[tags]
websocket

[depends]
websocket-core-client
websocket-core-server
ee10-annotations

[ini]
ee10.jakarta.websocket.api.version?=@ee10.jakarta.websocket.api.version@

[files]
maven://jakarta.websocket/jakarta.websocket-api/${ee10.jakarta.websocket.api.version}/jar|lib/ee10/support/jakarta.websocket.jakarta.websocket-api-${ee10.jakarta.websocket.api.version}.jar
maven://jakarta.websocket/jakarta.websocket-client-api/${ee10.jakarta.websocket.api.version}/jar|lib/ee10/support/jakarta.websocket.jakarta.websocket-client-api-${ee10.jakarta.websocket.api.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-jakarta-client/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-jakarta-client-${jetty.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-jakarta-common/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-jakarta-common-${jetty.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-jakarta-server/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-jakarta-server-${jetty.version}.jar
maven://org.eclipse.jetty.ee10.websocket/jetty-ee10-websocket-servlet/${jetty.version}/jar|lib/ee10/jetty-ee10-websocket-servlet-${jetty.version}.jar

[lib]
lib/ee10/jetty-ee10-websocket-jakarta-client-${jetty.version}.jar
lib/ee10/jetty-ee10-websocket-jakarta-common-${jetty.version}.jar
lib/ee10/jetty-ee10-websocket-jakarta-server-${jetty.version}.jar
lib/ee10/jetty-ee10-websocket-servlet-${jetty.version}.jar
lib/ee10/support/jakarta.websocket.jakarta.websocket-api-${ee10.jakarta.websocket.api.version}.jar
lib/ee10/support/jakarta.websocket.jakarta.websocket-client-api-${ee10.jakarta.websocket.api.version}.jar
