# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables a server-wide limit on TCP connections.

[tags]
connector

[depend]
server

[xml]
etc/jetty-connection-limit.xml

[ini-template]
#tag::documentation[]
## The maximum number of TCP connections allowed across all connectors.
#jetty.connectionlimit.maxConnections=1000

## The idle timeout to apply (in milliseconds) to existing connections when the connection limit is reached.
#jetty.connectionlimit.idleTimeout=1000
#end::documentation[]
