# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Template environments configuration files for the core environment.

[tags]
deployment

[depend]
deployment-scanner

[files]
basehome:modules/deployment.d/core-environment.properties|environments/core-environment.properties
basehome:modules/deployment.d/core-environment.xml|environments/core-environment.xml

