# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Debug Log using DebugHandle.

[tags]
server
debug
internal

[depend]
server

[files]
logs/

[xml]
etc/jetty-debuglog.xml

[ini-template]
#tag::documentation[]
## Logging directory (relative to $JETTY_BASE)
# jetty.debuglog.dir=logs

## Whether to append to existing file
# jetty.debuglog.append=false

## How many days to retain old log files
# jetty.debuglog.retainDays=90

## Timezone of the log entries
# jetty.debuglog.timezone=GMT

## Show Request/Response headers
# jetty.debug.showHeaders=true
#end::documentation[]
