# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables the DebugListener.
Generates additional logging regarding detailed request handling events.
Renames threads to include request URI.

[tags]
server
debug

[depend]
deploy

[files]
logs/

[xml]
etc/jetty-debug.xml

[ini-template]

## How many days to retain old log files
# jetty.debug.retainDays=14

## Should existing log be appended to
# jetty.debug.append=true

## Log directory for jetty debug logs
# jetty.debug.logs=./logs

## Timezone of the log entries
# jetty.debug.timezone=GMT

## Show Request/Response headers
# jetty.debug.showHeaders=true

## Rename threads while in context scope
# jetty.debug.renameThread=false

## Dump context as deployed
# jetty.debug.dumpContext=true
