# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables the DosHandler for the server.

[tags]
connector

[depend]
server

[xml]
etc/jetty-dos.xml

[ini-template]

## Is the remote address used to track the clients
#jetty.dos.useAddress=true

## Is the remote port used to track the clients
#jetty.dos.usePort=true

## The maximum requests per second per client
#jetty.dos.maxRequestsPerSecond=100

## The maximum number of clients to track or -1 for a default value
#jetty.dos.maxTrackers=10000

## The sample period(ms) to determine the request rate, or -1 for a default value
#jetty.dos.samplePeriodMs=100

## The Exponential factor for the moving average rate
#jetty.dos.alpha=0.2

## The maximum number of requests to be held in the delay queue
#jetty.dos.maxDelayQueueSize=1000

## List of InetAddress patterns to include
#jetty.dos.include.inet=10.10.10-14.0-128

## List of InetAddressPatterns to exclude
#jetty.dos.exclude.inet=10.10.10-14.0-128

## List of path patterns to include
#jetty.dos.include.path=/context/*

## List of path to exclude
#jetty.dos.exclude.path=/context/*

