# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Graceful processing of requests

[tags]
server

[depend]
server

[xml]
etc/jetty-graceful.xml

[ini-template]
# tag::documentation[]
## The timeout, in milliseconds, to apply when stopping the server gracefully.
# jetty.server.stopTimeout=5000

## The idleTimeout, in milliseconds, to apply to active connections during a graceful shutdown, or to -1 to disable this mechanism.
# jetty.server.shutdownIdleTimeout=1000
# end::documentation[]

