# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds HTTPS protocol support to the TLS(SSL) Connector.

[tags]
connector
https
http
ssl

[depend]
ssl

[after]
alpn
http2

[xml]
etc/jetty-https.xml

