# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds a HashLoginService to the server, for reading users, passwords and roles from a properties file.

[tags]
security

[depend]
security

[xml]
etc/jetty-loginservice-hash.xml

[files]
basehome:modules/loginservice-hash.d/realm.properties|etc/realm.properties

[ini-template]
# tag::documentation[]
## The name of the realm. It must match the realm name expected by the
## Authenticator. Web applications that declare a <login-config> without a
## <realm-name> use the realm name "default", which is why that is the
## default value here.
# jetty.hashLoginService.name=default

## The properties file that holds the users, passwords and roles.
## Format of each line: <username>: <password>[,<rolename>...]
# jetty.hashLoginService.config=etc/realm.properties

## The interval, in seconds, at which the properties file is scanned for
## changes and reloaded. A value of 0 (the default) disables reloading.
# jetty.hashLoginService.reloadInterval=0

## Whether to fully validate an already authenticated user on each request
## by re-loading and re-checking their credentials against the user store,
## rather than trusting the existing authenticated identity.
# jetty.hashLoginService.fullValidate=false
# end::documentation[]
