# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Logs requests using CustomRequestLog and Slf4jRequestLogWriter.
Request logs are written to the SLF4J logging framework at INFO level,
allowing integration with Logback, Log4j2, or any SLF4J-compatible logging system.

[tags]
requestlog
logging

[depend]
server

[xml]
etc/jetty-requestlog-slf4j.xml

[ini-template]
# tag::documentation[]
## SLF4J Logger name for request log
# jetty.requestlog.slf4j.loggerName=org.eclipse.jetty.server.RequestLog

## Format string
# jetty.requestlog.formatString=%{client}a - %u %{dd/MMM/yyyy:HH:mm:ss ZZZ|GMT}t "%r" %s %O "%{Referer}i" "%{User-Agent}i"
# end::documentation[]
