# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
# tag::description[]
This module adds the `$JETTY_BASE/resources` directory to the server's classpath.
# end::description[]

[tags]
classpath

[lib]
resources/

[files]
resources/

