# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Allows Jetty to be shutdown from a configured host/port/password

[tags]
shutdown

[depend]
server

[xml]
etc/jetty-server-shutdown.xml

[ini-template]
# tag::documentation[]
## ServerShutdown Listening Host
# jetty.shutdown.host=127.0.0.1

## ServerShutdown Listening Port
# Port 0 will use a port number that is automatically allocated
# If automatically allocated, the port chosen is reported to STDOUT.
# jetty.shutdown.port=-1

## ServerShutdown Key
# If key is blank, then an auto generated key is used, and reported to STDOUT.
# jetty.shutdown.key=

## ServerShutdown will exit JVM with call to System.exit(0)
# jetty.shutdown.exit=true
# end::documentation[]
