# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Creates and updates state file used by jetty.sh

[tags]
start

[depends]
server

[before]
deploy

[xml]
etc/jetty-state.xml

[ini-template]
## State file path
# jetty.state=${jetty.base}/jetty.state