# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Serve static files from a directory for the "/.well-known" context path.

[tags]
handler

[depend]
server

[xml]
etc/well-known.xml

[files]
.well-known/

[ini-template]
# tag::documentation[]
## Well Known Directory (absolute path, or relative to $JETTY_BASE).
# jetty.wellknown.dir=.well-known

## Allow contents of the well-known directory to be listed.
# jetty.wellknown.listDirectories=false
# end::documentation[]
