//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

= Web Application Deployment

The Jetty server deploys each web application to a specific _environment_.

The available environments are:

* The Jetty Static Environment -- Supports web applications made of static files only.
* The Jetty Core Environment -- Supports web applications written against the Jetty `Handler` APIs, without any Servlet dependencies.
* The Java EE 8 Environment -- Supports Servlet 4.0 (and associated specifications) in the `+javax.*+` packages.
* Any version from the Jakarta EE 9 Environment up to the Jakarta {ee-current-caps} Environment -- Supports corresponding Servlet (and associated specifications) in the `+jakarta.*+` packages.

You can simultaneously deploy an old Java EE 8 web application, say `old-ee8.war`, alongside a new Jakarta {ee-current-caps} web application, say `new-{ee-current}.war`, alongside a web application that only uses the core Jetty `Handler` APIs, all in the same Jetty server.

For each specific environment there is a specific deploy module that must be enabled:

* For Jetty Static, the xref:modules/standard.adoc#static-deploy[`static-deploy`] module
* For Jetty Core, the xref:modules/standard.adoc#core-deploy[`core-deploy`] module
* For Java EE 8, the xref:modules/standard.adoc#eeN-deploy[`ee8-deploy`] module
* For Jakarta EE 9 up to Jakarta {ee-current-caps}, the corresponding xref:modules/standard.adoc#eeN-deploy[`ee<N>-deploy`] module

Each of these modules provides environment specific features, such as library dependencies and default configuration.
The Jakarta EE deploy modules provide the corresponding Jakarta EE APIs and the Jetty implementation of the Jakarta EE APIs.

For example, you can enable the `{ee-current}-deploy` module in the following way:

[source,bash,subs=attributes+]
----
$ java -jar $JETTY_HOME/start.jar --add-modules={ee-current}-deploy
----

All the deploy modules depend on the xref:modules/standard.adoc#deployment-scanner[`deployment-scanner`] module, that scans <<monitored-directories,monitored directories>> for <<web-application-files,web applications>> to deploy, and for <<environment-configuration,environment configuration>> files to process.

NOTE: While you can have many deploy modules enabled, one for each environment, there is only one `deployment-scanner` module that scans the monitored directories.

By default, for security reasons, web applications are only deployed at server startup from the `$JETTY_BASE/webapps` directory.

However, you can configure the `deployment-scanner` module to deploy web applications from a <<monitored-directories,different deploy directory>>, and/or to deploy/undeploy web applications as they are moved to/removed from the deploy directory (<<hot-cold,hot deployment>>).

[[monitored-directories]]
== Monitored Directories

The `deployment-scanner` module scans the web applications deploy directory specified by the `jetty.deploy.webappsDir` property, by default `$JETTY_BASE/webapps`, for web applications to deploy.

The directory specified by the `jetty.deploy.environmentsDir` property, by default `$JETTY_BASE/environments`, is also scanned for configuration files that apply to each environment, and therefore to all web applications deployed to that environment.

[[web-application-files]]
== Web Application Files

A web application _basefile_ can be:

* A <<context-xml, Jetty context XML file>>, for Jetty Static, Jetty Core and Jakarta EE web applications.
* A `+*.war+` file, for Jakarta EE web applications.
* A directory, for Jetty Static, Jetty Core and Jakarta EE web applications.

A web application has a _basename_ derived either from the _basefile_ described above, that is either from the Jetty context XML file name, from the `+*.war+` file name, or from the directory name.

For example, for the Jetty context XML file `old-site.xml`, the web application _basename_ is `old-site`.
For the file `myapp.war`, the _basename_ is `myapp`.
For the directory `shop-app/` the _basename_ is `shop-app`.

Web applications may have an associated `<basename>.properties` configuration file, for example `old-site.properties` or `shop-app.properties`.

This `<basename>.properties` file contains properties that influence the deployment of the web application, for example by declaring its environment, as described <<rules-environment,in this section>>.

A web application `<basename>.properties` configuration file can specify the following properties:

* `environment=<environment>`, to specify the web application environment.
* `jetty.deploy.contextPath=<contextPath>`, to specify the web application `contextPath` (see also <<rules-context-path,this section>>).
* `jetty.deploy.baseResource=<pathToBaseResource>`, to specify the web application base resource directory.
The web application base resource directory can be outside of `$JETTY_BASE/webapps`.
* `jetty.deploy.baseResource.dirAllowed=<true|false>`, to specify whether directory listing for the base resource directory is allowed (by default `true`).

[[web-application-format]]
== Web Application Format

[[web-application-format-static]]
=== Jetty Static Format

For Jetty Static web applications, the web application format is just a directory, and any file in that directory and any subdirectory is served when requested with the proper request URI -- no files are hidden.

For example, with the following directory structure:

----
$JETTY_BASE/webapps
└── static-app
    ├── css/
    │   └── styles.css
    └── index.html
----

Requests to `+http://localhost:8080/static-app/index.html+` and `+http://localhost:8080/static-app/css/style.css+` will serve the correspondent files.

A request to `+http://localhost:8080/static-app/css/+` will list the content of the directory.

To disable directory listing, create a web application <<web-application-files,properties file>> with the following content:

.static-app.properties
[,properties]
----
# Specifies the environment.
environment=static

# Disables directory listing.
jetty.deploy.baseResource.dirAllowed=false
----

[[web-application-format-core]]
=== Jetty Core Format

For Jetty Core web applications, the web application format is a directory with the following structure:

[,bash]
----
core-app
├── static         # Static files are served from this directory.
│   ├── css
│   │   └── styles.css
│   └── index.html
├── classes        # Where web application Java classes reside.
│   └── com
│       └── acme
│           └── AcmeHandler.class
├── lib            # Where web application Java libraries reside.
│   └── acme-util.jar
└── jetty-web.xml  # Web application specific configuration.
----

The structure is similar to that of a `+*.war+` file.

A notable difference with `+*.war+` files is that static files are only served from the `static/` directory (with the `static/` prefix removed).
This means that files in the directory root, or under any other directory that is not `static/`, are hidden and if requested they will result in a `404 Not Found` response.
If the `static/` directory is missing, then no static files can be served, and therefore all requests are processed dynamically by the ``Handler``s configured in the web application.

Since static files can only be served from the `static/` directory, the `classes/` and `lib/` directories are implicitly hidden, as well as any other directory such as `includes/` or `fragments/`.

The `classes/` directory stores the web application's `+*.class+` files, while the `lib/` directory stores the web application's libraries, typically `+*.jar+` files.
Both these directories are optional.

The `jetty-web.xml` file is an optional in-application <<jetty-web-xml,Jetty Context XML file,>> that allows you to configure the web application deployment.

[[web-application-format-jakarta]]
=== Jakarta EE Format

For Jakarta EE web applications, the deployment unit is the usual `+*.war+` file or a directory with a `+*.war+` structure.

Like for the <<web-application-format-core,Jetty Core Format>>, the `+*.war+` file or a directory can contain an optional in-application <<jetty-web-xml,Jetty Context XML file>> under the `WEB-INF` directory, that allows you to configure the web application deployment.

[[hot-cold]]
== Hot vs Cold Deployment

You can configure the `deployment-scanner` module to scan the <<monitored-directories, monitored directories>> every `N` seconds, where `N` is configured via the `jetty.deploy.scanInterval` property.

By default, the scan interval is `0` seconds, which means _cold_ deployment, where the scanning is only performed once, at server startup.
This means that to deploy a new web application, or redeploy/undeploy an existing web application, you will need to stop and restart the Jetty server.

Setting the scan interval to a value greater than zero means that _hot_ deployment is enabled.
The <<monitored-directories, monitored directories>> are scanned periodically for file changes.

When a file is added/changed/removed from the web applications deploy directory (by default `$JETTY_BASE/webapps`), then the correspondent web application is processed for deploy/redeploy/undeploy with the <<rules,deployment rules>> detailed below.

When a file is added/changed/removed from the environments directory (by default `$JETTY_BASE/environments`), the file is processed and all web applications deployed to that specific environment are redeployed.

The following command line enables _hot_ deployment by specifying the `jetty.deploy.scanInterval` property on the command line, and therefore only for this particular run:

----
$ java -jar $JETTY_HOME/start.jar jetty.deploy.scanInterval=5
----

To make _hot_ deployment configuration persistent, you need to edit the `$JETTY_BASE/start.d/deployment-scanner.ini` module configuration file, and uncomment the property `jetty.deploy.scanInterval` and change the value to `5` seconds:

.deployment-scanner.ini
[source,subs=+quotes]
----
--module=deployment-scanner

#jetty.deploy.scanInterval=5#
...
----

When _hot_ deployment is enabled, the scanner may detect changes to multiple files, and will process the changes in the following way:

* Undeploy the web applications that have been removed, if any, in _basename_ [.underline]#reverse# alphabetical order.
* Redeploy the web applications that have been modified, if any, in _basename_ alphabetical order.
* Deploy the web applications that have been added, if any, in _basename_ alphabetical order.

[[rules]]
== Deployment Rules

For <<hot-cold,_cold_ deployment>>, the presence of a web application <<web-application-files,_basefile_>> causes its deployment at server startup.

For <<hot-cold,_hot_ deployment>> the following rules apply:

* Adding a new web application _basefile_ that refers to a new _basename_ to the web applications deploy directory (by default `$JETTY_BASE/webapps`) causes the deployment of the new web application.
For example, adding `mywebapp.war` to an empty `$JETTY_BASE/webapps`.
* Adding a new web application _basefile_ (such as `mywebapp.xml`), or a web application properties file (such as `mywebapp.properties`) to the web applications deploy directory that refers to an existing _basename_ causes the redeployment of the web application.
For example, adding `mywebapp.xml` or `mywebapp.properties` when `mywebapp.war` already exists.
* Changing a file that refers to a _basename_ causes the redeployment of the web application.
For example, editing or changing `mywebapp.xml`, `mywebapp.war` or `mywebapp.properties`.
* Removing some, but not all, of the files that refer to the same _basename_ causes the redeployment of the web application.
For example, removing `mywebapp.xml` or `mywebapp.properties`, but leaving `mywebapp.war`.
* Removing all the files that refer to the same _basename_ causes the undeployment of the web application.
For example, removing `mywebapp.xml`, `mywebapp.war` and `mywebapp.properties`.

NOTE: When a web application is deployed as a directory (not as a file), it is not possible to change the directory (for example using the `touch` command) to cause the redeployment of the web application.
Modification of the files inside the web application directory is not detected as a change.
You must add at least a `<basename>.properties` file (even empty), and `touch` it to cause redeployment.

In the presence of multiple web application __basefile__s that refers to the same _basename_, for example when both `mywebapp.xml` and `mywebapp.war` exist, or when both `mywebapp.war` and `mywebapp/` exist, then the following rules apply:

* If `<basename>.xml` exists, it has precedence over `<basename>.war` and `<basename>/`, so only `<basename>.xml` will be considered for deployment.
This allows the XML file to reference the `+*.war+` file or directory and avoid that the web application is deployed twice.
* Otherwise, if `<basename>.war` exists, it has precedence over `<basename>/`, so only the `+*.war+` file will be considered for deployment.
This allows the directory with the same _basename_ to be the `+*.war+` file unpack location and avoid that the web application is deployed twice.
* Otherwise, `<basename>/` exists and will be considered for deployment.

[[rules-context-path]]
=== Context Path Resolution

When a web application is deployed (or redeployed), the web application `contextPath` is derived from the web application <<web-application-files,_basename_>>, with the following rules:

* If `<basename>.xml` exists, it is processed and the directives contained in the XML file can set the `contextPath` to any value (including one that is different from the _basename_).
* If `<basename>.properties` exists, then the `contextPath` is set to the value of the `jetty.deploy.contextPath` property, if it is present in `<basename>.properties`.
* If the _basename_ is `ROOT`, case-insensitive, the `contextPath` is `/`, and the web application is reachable at `+http://localhost:8080/+`.
* Otherwise, the `contextPath` is the _basename_, and the web application is reachable at `+http://localhost:8080/<basename>+`.

[[rules-environment]]
=== Environment Resolution

A web application is always deployed to a specific environment, which is either configured explicitly for the web application or set to the default environment.

You must always enable at least one deploy module, otherwise no web application can be deployed.

[[rules-environment-single-deployer]]
==== Single Deployer Environment Resolution

If only a single specific deploy module is enabled, for example `{ee-current}-deploy`, then its environment is the default environment and applications will be deployed to that environment without any additional configuration.

If a web application <<web-application-files,properties file>> exists, and it specifies the `environment` property, then its value must specify the same environment as the deploy module, otherwise the deployment will fail.

[CAUTION]
====
Make sure that you do not inadvertently mix a deploy module for one environment with a web application of a different environment.

For example, if you have a Jetty `core` web application in directory `core-app/`, and you enable the `static-deploy` module, then the `core-app/` directory will be interpreted as a `static` web application, and files from the `core-app/classes/` directory (that are normally hidden and not served) will be served as static files.
====

TIP: It is good practice to always specify the web application <<web-application-files,properties file>> and specify the `environment` property, to avoid deployment of your web applications to an unexpected environment.

[[rules-environment-multiple-deployers]]
==== Multiple Deployers Environment Resolution

If multiple deployer modules are enabled, then the default environment is (in order):

* The most recent Jakarta EE environment of the `{ee-all}-deploy` modules that are enabled, if any.
* Otherwise, the `core` environment, if the `core-deploy` module is enabled.
* Otherwise, the `static` environment, if the `static-deploy` module is enabled.

For example, if `core-deploy`, `ee9-deploy` and the `{ee-current}-deploy` modules are enabled, then `{ee-current}` is the default environment, to which applications will be deployed unless otherwise configured (see below).

To configure a specific environment for an application, you add a web application <<web-application-files,properties file>> and specify the `environment` property.

For example, an application deployed to `$JETTY_BASE/webapps/my-ee9-app.war` is configured with the file `$JETTY_BASE/webapps/my-ee9-app.properties`, with the following content:

.my-ee9-app.properties
[,properties]
----
environment=ee9
----

TIP: In case of multiple deploy environments, it is good practice to always specify the web application <<web-application-files,properties file>> for your web applications, and specify the `environment` property, to avoid deployment of your web applications to an unexpected environment.

[CAUTION]
====
If you do *not* specify the `environment` property in the web application <<web-application-files,properties file>> for your web applications, then the deployer for the default environment will be used.

For example, if the `{ee-current}-deploy` and the `ee9-deploy` module are enabled, and you deploy an EE 9 web application _without_ the `+*.properties+` file, then it will be deployed to the (default) `{ee-current}` environment, with unspecified results.

This unspecified deployment may not work as the EE 9 web application may use APIs that have been removed in {ee-current-caps}, causing an error at runtime.
====

Also in case of multiple deployers, if a web application <<web-application-files,properties file>> specifies an `environment` property, and the corresponding deploy module is not enabled, the deployment will fail.

[[context-xml]]
== Deploying Jetty Context XML Files

A Jetty context XML file is a xref:xml/index.adoc[Jetty XML file] that allows you to customize the deployment of web applications.

NOTE: Recall that the <<rules,deployment rules>> give priority to Jetty context XML files over `+*.war+` files or directories.

To deploy a web application using a Jetty context XML file, simply place the Jetty context XML file in the `$JETTY_BASE/webapps` directory.

For example, to deploy a Jakarta {ee-current-caps} web application, enable the `{ee-current}-deploy` module, and add the following Jetty context XML file, named `wiki.xml`:

.wiki.xml
[,xml,subs=attributes+]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext"> <!--1-->
  <Set name="contextPath">/wiki</Set> <!--2-->
  <Set name="war">/opt/myapps/myapp.war</Set> <!--3-->
</Configure>
----
<1> Configures a link:{javadoc-url}/org/eclipse/jetty/{ee-current}/webapp/WebAppContext.html[`WebAppContext`], which is the Jetty component that represents a standard Servlet web application for Jakarta {ee-current-caps}.
<2> Specifies the web application `contextPath`, which may be different from the _basename_ derived from `wiki.xml`.
<3> Specifies the file system path of the `+*.war+` file (which may be external to `$JETTY_BASE`).

The Jetty context XML file may be accompanied by a web application <<web-application-files,properties file>> that specifies the xref:deploy/index.adoc[environment] to use for the deployment:

.wiki.properties
[,properties,subs=attributes+]
----
environment={ee-current}
----

Refer to <<rules-environment,this section>> for more information about specifying the environment.

The `$JETTY_BASE` directory would look like this:

[,subs=+attributes]
----
$JETTY_BASE
├── resources
│   └── jetty-logging.properties
├── start.d
│   ├── ...
│   ├── {ee-current}-deploy.ini
│   └── http.ini
└── webapps
    ├── wiki.properties
    └── wiki.xml
----

TIP: The `+*.war+` file may be placed anywhere in the file system and does not need to be placed in the `$JETTY_BASE/webapps` directory, as long as you have a Jetty context XML file referencing it.

IMPORTANT: If you place both the Jetty context XML file _and_ the `+*.war+` file in the `$JETTY_BASE/webapps` directory, remember that they must produce the same _basename_, for example `wiki.xml` and `wiki.war`, so that the deployment is performed only once using the Jetty context XML file (and not the `+*.war+` file).

You can use the features of xref:xml/index.adoc[Jetty XML files] to avoid to hard-code file system paths or other configurations in your Jetty context XML files, for example by using properties declared in `wiki.properties` or JVM system properties:

.wiki.xml
[,xml,subs=attributes+]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath"><Property name="wiki.contextPath"/></Set>
  <Set name="war"><SystemProperty name="webapps.dir"/>/myapp.war</Set>
</Configure>
----

Note how the `contextPath` is obtained from the `wiki.contextPath` configuration property (as an alternative to the `jetty.deploy.contextPath` property specified in <<web-application-files,this section>>), while `+*.war+` file path is obtained by resolving the system property `webapps.dir` that you can specify on the command line when you start Jetty:

.wiki.properties
[,properties,subs=+attributes]
----
environment={ee-current}
wiki.contextPath=/wiki
----

[,bash]
----
$ java -jar $JETTY_HOME/start.jar -Dwebapps.dir=/opt/myapps
----

Properties specified in environment properties file (described in <<environment-configuration,this section>>) and in the web application properties file (described in <<web-application-files,this section>>) are available when processing the Jetty context XML file.

Remember that Jetty Context XML files in the `$JETTY_BASE/webapps` directory can only refer to classes present in the environment class-path or module-path, and in the server class-path or module-path.

If you need to configure the deployment of your web application referring to web application specific classes, use the in-application Jetty Context XML file, as described in <<jetty-web-xml,this section>>.

[[environment-configuration]]
== Environment Configuration

Environments can be configured via xref:xml/index.adoc[Jetty XML files] or `+*.properties+` files placed in the `$JETTY_HOME/environments` directory.

Each environment configuration is applied to _all_ web applications deployed/redeployed to that `environment`.

The environment configuration files must start with the environment name, and are processed in alphabetical order, for example `{ee-current}.xml`, `{ee-current}-extra.xml` and `{ee-current}-other.xml` are processed in this order, and they all affect the `{ee-current}` environment.
The same holds for `+*.properties+` files.

The environment-specific Jetty XML files will be applied to the web application _before_ any Jetty context XML file associated with the web application, present in the `$JETTY_HOME/webapps` directory.

IMPORTANT: The contents of the environment specific Jetty context XML file may only contain references to classes appropriate for that environment.

For example, you can have a `$JETTY_HOME/environments/{ee-current}.xml` file with the following content:

.{ee-current}.xml
[,xml,subs=+attributes]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Call name="setAttribute">
    <Arg>com.acme.{ee-current}.feature</Arg>
    <Arg>value</Arg>
  </Call>
</Configure>
----

The `$JETTY_HOME/environments/{ee-current}-extra.xml` file may contain:

.{ee-current}-extra.xml
[,xml,subs=+attributes]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Call name="addEventListener">
    <Arg>
      <New class="com.acme.MyListenerFeature"/>
    </Arg>
  </Call>
</Configure>
----

Custom classes like `com.acme.MyListenerFeature` must be present in the environment class loader, so that the XML file can reference them.
You can extend the environment class loader by enabling the xref:modules/standard.adoc#eeN-ext[`{ee-current}-ext.mod`].

The directory structure would look like this:

[,subs=+attributes]
----
$JETTY_BASE
├── environments
│   ├── {ee-current}.xml
│   └── {ee-current}-extra.xml
├── start.d
│   ├── ...
│   └── {ee-current}-ext.xml
└── webapps
    ├── wiki.properties
    └── wiki.xml
----

[[jetty-web-xml]]
== In-Application Jetty Context XML File

As discussed in <<context-xml,this section>>, the deployment of a web application can be specified with a Jetty Context XML file placed in the `$JETTY_HOME/webapps` directory.

However, the deployment of a web application can also be configured using a Jetty Context XML file placed _inside_ the web application, both for <<web-application-format-core,core deployments>> and <<web-application-format-jakarta,Jakarta deployments>>.

This file can be useful:

* To place all configuration inside your web application archive.
* To perform configuration of the web application that can only occur _after_ the web application's class-path has been created, for example because it references classes present in web application itself.

[[jetty-web-xml-core]]
=== In-Application Jetty Context XML File for Core Deployments

The file must be in the root of the web application and named `jetty-web.xml`, see <<web-application-format-core,this section>> for an example.

[[jetty-web-xml-jakarta]]
=== In-Application Jetty Context XML Files for Jakarta Deployments

For Jakarta deployments, there may be multiple in-application Jetty Context XML files, typically one for each `{ee-all}` environment.

The files must be named either `WEB-INF/jetty-{ee-all}-web.xml` or `WEB-INF/jetty-web.xml`; the latter is only processed if the former(s) are missing.

[TIP]
====
It is good practice to name the file according to the environment into which the web application will be deployed.

If your web application can be deployed to multiple environments, then you should include a `WEB-INF/jetty-{ee-all}-web.xml` file for each environment.

If you only deploy to a single environment, then you can omit it from the filename and use `WEB-INF/jetty-web.xml`, but be aware that likely you will not be able to deploy the web application to a different environment without updating the contents of the file.
====

[[jndi]]
== Configuring JNDI Entries

Web applications may _reference_ JNDI entries, such as a JDBC `DataSource` or a Jakarta Mail `Session`.

The JNDI entries must be _defined_ in a Jetty Context XML file, as detailed in xref:jndi/index.adoc[this section].

[[virtual-hosts]]
== Configuring Virtual Hosts

A _virtual host_ is an internet domain name, registered in the Domain Name Server (DNS), for an IP address such that multiple virtual hosts will resolve to the same IP address of a single server instance.

If you have multiple web applications deployed on the same Jetty server, by using virtual hosts you will be able to target a specific web application.

For example, you may have a web application for your business and a web application for your hobbies , both deployed in the same Jetty server.
By using virtual hosts, you will be able to have the first web application available at `+http://domain.biz/+`, and the second web application available at `+http://hobby.net/+`.

Another typical case is when you want to use different subdomains for different web application, for example a project website is at `+http://project.org/+` and the project documentation is at `+http://docs.project.org+`.

Virtual hosts can be used with any context that is a subclass of link:{javadoc-url}/org/eclipse/jetty/server/handler/ContextHandler.html[ContextHandler], and therefore for <<web-application-format-static, Static web applications>>, <<web-application-format-core,Core web applications>> and <<web-application-format-jakarta,Jakarta web applications>>.

[[virtual-hosts-names]]
=== Virtual Host Names

Jetty supports the following variants to be specified as virtual host names:

`www.hostname.com`::
A fully qualified domain name. It is important to list all variants as a site may receive traffic for both `www.hostname.com` and `hostname.com`.

`+*.hostname.com+`::
A wildcard domain name which will match only one level of arbitrary subdomains.
The wildcard domain `+*.foo.com+` will match `www.foo.com` and `m.foo.com`, but not `www.other.foo.com`.

`10.0.0.2`::
An IP address may be set as a virtual host to indicate that a web application should handle requests received on the network interface with that IP address.
This is typically only used for protocols that do not indicate a host name such as HTTP/0.9 or HTTP/1.0.

`@<ConnectorName>`::
A Jetty server `Connector` name to indicate that a web application should handle requests received on the server `Connector` with that name, and therefore received on a specific socket address, either an IP port for `ServerConnector`, or a Unix-Domain path for `UnixDomainServerConnector` (see also xref:virtual-hosts-port[this section]).

`www.√integral.com`::
Non-ASCII and https://en.wikipedia.org/wiki/Internationalized_domain_name[IDN] domain names can be set as virtual hosts using https://en.wikipedia.org/wiki/Punycode[Puny Code] equivalents that may be obtained from a https://www.punycoder.com/[Punycode/IDN converters].
For example if the non-ASCII domain name `www.√integral.com` is given to a browser, then the browser will make a request that uses the domain name `www.xn--integral-7g7d.com`, which is the name that should be added as the virtual host name.

[[virtual-hosts-config]]
=== Virtual Hosts Configuration

If you have a web application `mywebapp.war` you can configure its virtual hosts in this way:

[,xml,subs=attributes+]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath">/mywebapp</Set>
  <Set name="war">/opt/webapps/mywebapp.war</Set>
  <Set name="virtualHosts">
    <Array type="java.lang.String">
      <Item>mywebapp.com</Item>
      <Item>www.mywebapp.com</Item>
      <Item>mywebapp.net</Item>
      <Item>www.mywebapp.net</Item>
    </Array>
  </Set>
</Configure>
----

Your web application will be available at:

* `+http://mywebapp.com/mywebapp+`
* `+http://www.mywebapp.com/mywebapp+`
* `+http://mywebapp.net/mywebapp+`
* `+http://www.mywebapp.net/mywebapp+`

[NOTE]
====
In the example above, the web application `contextPath` is configured to `/mywebapp`.

As such, a request to `+http://mywebapp.com/other+` will not match your web application because the `contextPath` does not match.

Likewise, a request to `+http://other.com/mywebapp+` will not match your web application because the virtual host does not match.
====

[[virtual-hosts-same-context]]
=== Same Context Path, Different Virtual Hosts

If you want to deploy different web applications to the same context path, typically the root context path `/`, you must use virtual hosts to differentiate among web applications.

You have `domain.war` that you want to deploy at `+http://domain.biz/+` and `hobby.war` that you want to deploy at `+http://hobby.net+`.

To achieve this, you simply use the same context path of `/` for each of your webapps, while specifying different virtual hosts for each of your webapps:

.domain.xml
[,xml,subs=attributes+]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war">/opt/webapps/domain.war</Set>
  <Set name="virtualHosts">
    <Array type="java.lang.String">
      <Item>domain.biz</Item>
    </Array>
  </Set>
</Configure>
----

.hobby.xml
[,xml,subs=attributes+]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war">/opt/webapps/hobby.war</Set>
  <Set name="virtualHosts">
    <Array type="java.lang.String">
      <Item>hobby.net</Item>
    </Array>
  </Set>
</Configure>
----

[[virtual-hosts-port]]
=== Different Port, Different Web Application

Sometimes it is required to serve different web applications from different socket addresses (either different IP ports, or different Unix-Domain paths), and therefore from different server ``Connector``s.

For example, you want requests to `+http://localhost:8080/+` to be served by one web application, but requests to `+http://localhost:9090/+` to be served by another web application.

This configuration may be useful when Jetty sits behind a load balancer.

In this case, you want to xref:protocols/index.adoc[configure multiple connectors], each with a different name specified with link:{javadoc-url}/org/eclipse/jetty/server/AbstractConnector.html#setName(java.lang.String)[], and then reference the connector name in the web application virtual host configuration:

.domain.xml
[,xml,subs="attributes+,+quotes"]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war">/opt/webapps/domain.war</Set>
  <Set name="virtualHosts">
    <Array type="java.lang.String">
      #<Item>@port8080</Item>#
    </Array>
  </Set>
</Configure>
----

.hobby.xml
[,xml,subs="attributes+,+quotes"]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war">/opt/webapps/hobby.war</Set>
  <Set name="virtualHosts">
    <Array type="java.lang.String">
      #<Item>@port9090</Item>#
    </Array>
  </Set>
</Configure>
----

[NOTE]
====
Web application `domain.war` has a virtual host of `@port8080`, where `port8080` is the name of a Jetty connector.

Likewise, web application `hobby.war` has a virtual host of `@port9090`, where `port9090` is the name of another Jetty connector.

See xref:protocols/index.adoc[this section] for further information about how to configure connectors.
====

[[extract-war]]
== Configuring `+*.war+` File Extraction

By default, `+*.war+` files are uncompressed and its content extracted in a temporary directory.
// TODO: reference the `work` module and how it works, perhaps in a section about the `deploy` module?
The web application resources are served by Jetty from the files extracted in the temporary directory, not from the files within the `+*.war+` file, for performance reasons.

If you do not want Jetty to extract the `+*.war+` files, you can disable this feature, for example:

.mywebapp.xml
[,xml,subs="attributes+,+quotes"]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath">/mywebapp</Set>
  <Set name="war">/opt/webapps/mywebapp.war</Set>
  #<Set name="extractWAR">false</Set>#
</Configure>
----

[[jetty-override-web-xml]]
== Overriding `web.xml`

You can configure an additional `web.xml` that complements the `web.xml` file that is present in the web application `+*.war+` file.
This additional `web.xml` is processed _after_ the `+*.war+` file `web.xml`.
This allows you to add host specific configuration or server specific configuration without having to extract the web application `web.xml`, modify it, and repackage it in the `+*.war+` file.

.mywebapp.xml
[,xml,subs="attributes+,+quotes"]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext">
  <Set name="contextPath">/mywebapp</Set>
  <Set name="war">/opt/webapps/mywebapp.war</Set>
  #<Set name="overrideDescriptor">/opt/webapps/mywebapp-web.xml</Set>#
</Configure>
----

The format of the additional `web.xml` is exactly the same as a standard `web.xml` file, for example:

.mywebapp-web.xml
[,xml,linenums,highlight=10-11]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd"
         version="6.0">
  <servlet>
    <servlet-name>my-servlet</servlet-name>
    <init-param>
      <param-name>host</param-name>
      <param-value>192.168.0.13</param-value>
    </init-param>
  </servlet>
</web-app>
----

In the example above, you configured the `my-servlet` Servlet (defined in the web application `web.xml`), adding a host-specific `init-param` with the IP address of the host.
