//
// ========================================================================
// Copyright (c) 1995-2020 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under
// the terms of the Eclipse Public License 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0
//
// This Source Code may also be made available under the following
// Secondary Licenses when the conditions for such availability set
// forth in the Eclipse Public License, v. 2.0 are satisfied:
// the Apache License v2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[ops-session-overview]]

=== Session Overview

==== Terminology 

Before diving into the specifics of how to plug-in and configure various alternative http session management modules, let's review some useful terminology:

Session::
is a means of retaining information across requests for a particular user.
The Servlet Specification defines the semantics of sessions.
Some of the most important characteristics of sessions is that they have a unique id, and that their contents cannot be shared between different contexts (although the id can be).
SessionIdManager:: 
is responsible for allocating session ids.
Any Jetty server can have at most 1 SessionIdManager.
HouseKeeper:: 
is responsible for periodically orchestrating the removal of expired sessions.
This process is referred to as "scavenging".
SessionHandler:: 
is responsible for managing the lifecycle of sessions.
A context can have at most 1 `SessionHandler`.
SessionCache::
is an L1 cache of in-use session objects.
The `SessionCache` is used by the `SessionHandler`.
SessionDataStore::
is responsible for all clustering/persistence operations on sessions.
A `SessionCache` uses a `SessionDataStore` as a backing store.
CachingSessionDataStore:: 
is an L2 cache of session data.
A `SessionCache` can use a `CachingSessionDataStore` as its backing store.

More details on these concepts can be found in the link:${PROGGUIDE}/server/sessions/sessions[Programming Guide].

[NOTE]
====
`SessionDataStores` interface with other, usually third party, systems responsible for storing and/or distributing session information.
Sessions can be distributed without being persisted.
They can also be persisted without being persisted.
Because persisting session information to a shared store is one very common way of distributing or "clustering" sessions, in the documentation we will often refer to just "persisting".
====

==== Jetty Session Modules

There are a number of modules that offer pluggable alternatives for http session management.
You can design how you want to cache and store http sessions by selecting alternative combinations of session modules.

For example, jetty ships with two alternative implementations of the `SessionCache`: one that caches sessions in memory (`session-cache-hash`) and a trivial implementation that does not actually cache (`session-cache-null`).

There are at least 6 alternative implementations of the `SessionDataStore` that you can use to persist your http sessions.
The list currently includes support for:

* file system storage (`session-store-file`)
* relational database storage (`session-store-jdbc`)
* NoSQL database storage (`session-store-mongo`)
* Google Cloud datastore storage (`session-store-gcloud`)
* Hazelcast storage (`session-store-hazelcast-remote` or `session-store-hazelcast-embedded`)
* Infinispan storage (`session-store-infinispan-remote` or `session-store-infinispan-embedded`)

You might like to consult the xref:ops-session-usecases[use cases] to help you decide which combinations best suit your needs.

TIP: It is worth noting that if you do not configure _any_ session modules, jetty will still provide http sessions that are cached in memory but are never persisted.
