# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Experimental Brotli algorithm for CompressionHandler server wide compression.

[tags]
server
handler
compression
experimental

[depend]
server
compression-api
compression

[files]
maven://com.aayushatharva.brotli4j/brotli4j/${brotli4j.version}|lib/compression/brotli4j-${brotli4j.version}.jar

[lib]
lib/compression/brotli4j-${brotli4j.version}.jar

[xml]
etc/jetty-compression-brotli.xml

[ini]
brotli4j.version?=@brotli4j.version@

[ini-template]
## Minimum content length after which brotli is enabled
# jetty.brotli.minCompressSize=32

## Buffer Size for Decoder
# jetty.brotli.decoder.bufferSize=16384

## Buffer Size for Encoder
# jetty.brotli.encoder.bufferSize=4096

## Compression Level for Encoder
# valid values from 0 to 11
# jetty.brotli.encoder.compressionLevel=11

## Strategy for Encoder
# 0 = Generic
# 1 = Text
# 2 = Font
# jetty.brotli.encoder.strategy=0

## Brotli log2(LZ window size) for Encoder
# valid values from 10 to 24
# jetty.brotli.encoder.lgWindow=22

[license]
Brotli4j is distributed under Apache License 2.0
Copyright 2021, Aayush Atharva
https://github.com/hyperxpro/Brotli4j/blob/main/LICENSE

