//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[cgi-servlet]]
=== CGI Servlet

[[cgi-servlet-metadata]]
==== Info

* Classname: `org.eclipse.jetty.ee9.servlets.CGI`
* Maven Artifact: org.eclipse.jetty:jetty-servlets
* Javadoc: {JDURL}/org/eclipse/jetty/servlets/CGI.html

[[cgi-servlet-usage]]
==== Usage

The CGI servlet class extends the abstract HttpServlet class.
When the init parameter is called, the cgi bin directory is set with the `cgibinResourceBase`.
Otherwise, it defaults to the resource base of the context.

The cgi bin uses three parameters:

commandPrefix::
The init parameter obtained when there is a prefix set to all commands directed to the method exec.
Path::
An init parameter passed to the exec environment as a PATH.
This must be run unpacked somewhere in the filesystem.
ENV_::
An init parameter that points to an environment variable with the name stripped of the leading ENV_ and using the init parameter value.
