# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Server/port connections for Mongo session storage.

[xml]
etc/sessions/mongo/session-store-by-address.xml

