# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables standard Servlet handling.

[environment]
ee10

[depends]
server
sessions

[ini]
jakarta.servlet-api.version?=@jakarta.servlet-api.version@

[files]
maven://jakarta.servlet/jakarta.servlet-api/${jakarta.servlet-api.version}/jar|lib/ee10/support/jakarta.servlet.jakarta.servlet-api-${jakarta.servlet-api.version}.jar
maven://org.eclipse.jetty.ee10/jetty-ee10-servlet/${jetty.version}/jar|lib/ee10/jetty-ee10-servlet-${jetty.version}.jar

[lib]
lib/ee10/jetty-ee10-servlet-${jetty.version}.jar
lib/ee10/support/jakarta.servlet.jakarta.servlet-api-${jakarta.servlet-api.version}.jar
