# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables standard Servlet handling.

[environment]
ee10

[depend]
ee-servlet
server
sessions

[lib]
lib/@jakarta.servlet:jakarta.servlet-api@
lib/jetty-ee10-servlet-${jetty.version}.jar
