# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds servlet standard security handling to the classpath.

[environment]
ee10

[depend]
server
security
ee10-servlet

