# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee10

[depends]
ee10-apache-jsp

[lib]
lib/ee10-glassfish-jstl/@jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api@
lib/ee10-glassfish-jstl/@org.glassfish.web:jakarta.servlet.jsp.jstl@
