# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee10

[depends]
ee10-apache-jsp

[lib]
lib/ee10-glassfish-jstl/*.jar
