# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables standard Servlet handling.

[environment]
ee8

[depend]
server
sessions

[lib]
lib/@org.eclipse.jetty.toolchain:jetty-servlet-api@
lib/jetty-ee8-nested-${jetty.version}.jar
lib/jetty-ee8-servlet-${jetty.version}.jar
