# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Puts lib/ee8/ext jars on the ee8 classpath.

[tags]
classpath

[environment]
ee8

[lib]
lib/ee8/ext/**.jar

[files]
lib/
lib/ee8/
lib/ee8/ext/
