# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JSP for all web applications deployed on the server.

[environment]
ee8

[depend]
ee8-servlet
ee8-annotations
ee8-apache-jsp
