//
//  ========================================================================
//  Copyright (c) 1995-2018 Mort Bay Consulting Pty. Ltd.
//  ========================================================================
//  All rights reserved. This program and the accompanying materials
//  are made available under the terms of the Eclipse Public License v1.0
//  and Apache License v2.0 which accompanies this distribution.
//
//      The Eclipse Public License is available at
//      http://www.eclipse.org/legal/epl-v10.html
//
//      The Apache License v2.0 is available at
//      http://www.opensource.org/licenses/apache2.0.php
//
//  You may elect to redistribute this code under either of these licenses.
//  ========================================================================
//

[[t-contributing-mailing-lists]]
=== Mailing Lists

Mailing lists are a wonderful way to interact with the community at large and for a certain class of issue have the best chances of achieving resolution.  There are a number of mailing lists available within the Jetty project and a good rule of thumb to choose between the developer and user lists is to ask yourself if your question is broadly interesting to the community, use the users list and if narrowly focused on Jetty internals or minutiae, then the dev list might be a better option.

* Jetty Developers List
** Join - https://dev.eclipse.org/mailman/listinfo/jetty-dev
** Archives - http://dev.eclipse.org/mhonarc/lists/jetty-dev/
* Jetty Users List
** Join - https://dev.eclipse.org/mailman/listinfo/jetty-users
** Archives - http://dev.eclipse.org/mhonarc/lists/jetty-users/
* Jetty Announcements List
** Join - https://dev.eclipse.org/mailman/listinfo/jetty-announce
** Archives - http://dev.eclipse.org/mhonarc/lists/jetty-announce/

[[t-contributing-irc]]
=== Internet Relay Chat - IRC

IRC has been around for decades and it is hard to beat a communication platform that has such support.  Users are always welcome to come join our IRC channels and talk with us, other users, or just lurk.  Please note that IRC is not necessarily an active support channel, if you have a question by all means ask it but there should be no expectation that you will immediately get a response.  Your best bet is to ask and then lurk.

irc.freenode.org - #jetty::
  Our primary location, we recommend that if your looking to find folks on IRC you try here.

[[t-contributing-stackoverflow]]
=== Stack Overflow

From a simple support perspective it is hard to beat http://stackoverflow.com[StackOverflow] for interacting with a Jetty community.  Numerous users have asked and had answered their questions on the platform by other users and developers alike.

* Check out the general https://stackoverflow.com/questions/tagged/jetty[Jetty] tag!
* The https://stackoverflow.com/questions/tagged/embedded-jetty[Embedded-Jetty] tag has a fair amount of traffic as well.
