# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds Jetty EE11 utility servlets and filters available to a webapp.
Puts org.eclipse.jetty.ee11.servlets on the server classpath
(CrossOriginFilter, DosFilter, MultiPartFilter, QoSFilter, etc.)
for use by all web applications.

[environment]
ee11

[depend]
ee11-servlet

[lib]
lib/jetty-ee11-servlets-${jetty.version}.jar

