# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds Jetty EE11 utility servlets and filters available to a webapp.
Puts org.eclipse.jetty.ee11.servlets on the server classpath
(CrossOriginFilter, DosFilter, MultiPartFilter, QoSFilter, etc.)
for use by all web applications.

[environment]
ee11

[depends]
ee11-servlet

[files]
maven://org.eclipse.jetty.ee11/jetty-ee11-servlets/${project.version}/jar|lib/ee11/jetty-ee11-servlets-${project.version}.jar

[lib]
lib/ee11/jetty-ee11-servlets-${project.version}.jar
