# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds Jetty EE9 utility servlets and filters available to a webapp.
Puts org.eclipse.jetty.ee9.servlets on the server classpath
(CrossOriginFilter, DosFilter, MultiPartFilter, QoSFilter, etc.)
for use by all web applications.

[environment]
ee9

[depends]
ee9-servlet

[files]
maven://org.eclipse.jetty.ee9/jetty-ee9-servlets/${project.version}/jar|lib/ee9/jetty-ee9-servlets-${project.version}.jar

[lib]
lib/ee9/jetty-ee9-servlets-${project.version}.jar
