# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds Jetty EE9 utility servlets and filters available to a webapp.
Puts org.eclipse.jetty.ee9.servlets on the server classpath
(CrossOriginFilter, DosFilter, MultiPartFilter, QoSFilter, etc.)
for use by all web applications.

[environment]
ee9

[depend]
ee9-servlet

[lib]
lib/jetty-ee9-servlets-${jetty.version}.jar

