# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee8

[depend]
plus
ee8-plus
annotations

[ini]
ee8.jakarta.annotation.api.version?=@jakarta.annotation.api.version@

[lib]
lib/jetty-ee8-annotations-${jetty.version}.jar
lib/ee8-annotations/@jakarta.annotation:jakarta.annotation-api@
