# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee8

[depends]
plus
ee8-plus
annotations

[ini]
ee8.jakarta.annotation.api.version?=@jakarta.annotation.api.version@

[files]
maven://jakarta.annotation/jakarta.annotation-api/${ee8.jakarta.annotation.api.version}/jar|lib/ee8/support/jakarta.annotation.jakarta.annotation-api-${ee8.jakarta.annotation.api.version}.jar
maven://org.eclipse.jetty.ee8/jetty-ee8-annotations/${project.version}/jar|lib/ee8/jetty-ee8-annotations-${project.version}.jar

[lib]
lib/ee8/jetty-ee8-annotations-${project.version}.jar
lib/ee8/support/jakarta.annotation.jakarta.annotation-api-${ee8.jakarta.annotation.api.version}.jar
