<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-project</artifactId>
    <version>12.1.12-SNAPSHOT</version>
  </parent>
  <groupId>org.eclipse.jetty.ee11</groupId>
  <artifactId>jetty-ee11</artifactId>
  <packaging>pom</packaging>
  <name>EE11</name>

  <modules>
    <module>jetty-ee11-annotations</module>
    <module>jetty-ee11-apache-jsp</module>
    <module>jetty-ee11-bom</module>
    <module>jetty-ee11-cdi</module>
    <module>jetty-ee11-demos</module>
    <module>jetty-ee11-fcgi-proxy</module>
    <module>jetty-ee11-glassfish-jstl</module>
    <module>jetty-ee11-home</module>
    <module>jetty-ee11-jaspi</module>
    <module>jetty-ee11-jndi</module>
    <module>jetty-ee11-jspc-maven-plugin</module>
    <module>jetty-ee11-maven-plugin</module>
    <module>jetty-ee11-osgi</module>
    <module>jetty-ee11-plus</module>
    <module>jetty-ee11-proxy</module>
    <module>jetty-ee11-quickstart</module>
    <module>jetty-ee11-servlet</module>
    <module>jetty-ee11-servlets</module>
    <module>jetty-ee11-tests</module>
    <module>jetty-ee11-webapp</module>
    <module>jetty-ee11-websocket</module>
  </modules>

  <properties>

    <ee11.jakarta.activation.api.version>2.1.3</ee11.jakarta.activation.api.version>
    <ee11.jakarta.mail.api.version>2.1.3</ee11.jakarta.mail.api.version>
    <ee11.jakarta.servlet.api.version>6.1.0</ee11.jakarta.servlet.api.version>
    <ee11.jakarta.servlet.jsp.api.version>4.0.0</ee11.jakarta.servlet.jsp.api.version>
    <ee11.jakarta.servlet.jsp.jstl.impl.version>4.0.0</ee11.jakarta.servlet.jsp.jstl.impl.version>
    <ee11.jakarta.xml.bind.api.version>4.0.5</ee11.jakarta.xml.bind.api.version>
    <ee11.jakarta.xml.bind.impl.version>4.0.9</ee11.jakarta.xml.bind.impl.version>
    <ee11.jakarta.xml.jaxws.impl.version>4.0.2</ee11.jakarta.xml.jaxws.impl.version>
    <ee11.jersey.version>4.0.2</ee11.jersey.version>
    <ee11.jsp.impl.version>11.0.22</ee11.jsp.impl.version>
    <ee11.mail.impl.version>2.0.2</ee11.mail.impl.version>
    <ee11.weld.version>6.0.4.Final</ee11.weld.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>jakarta.platform</groupId>
        <artifactId>jakarta.jakartaee-bom</artifactId>
        <version>${ee11.jakarta.bom.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.sun.mail</groupId>
        <artifactId>jakarta.mail</artifactId>
        <version>${ee11.mail.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>com.sun.xml.ws</groupId>
        <artifactId>jaxws-rt</artifactId>
        <version>{ee11.jakarta.xml.jaxws.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.xml.bind</groupId>
        <artifactId>jakarta.xml.bind-api</artifactId>
        <version>${ee11.jakarta.xml.bind.api.version}</version>
      </dependency>
      <!-- Jetty EE11 Dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-annotations</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-apache-jsp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-cdi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-fcgi-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-glassfish-jstl</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-jaspi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-jndi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-jspc-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-plus</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-quickstart</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-servlets</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.demos</groupId>
        <artifactId>jetty-ee11-demo-proxy-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.websocket</groupId>
        <artifactId>jetty-ee11-websocket-jakarta-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.websocket</groupId>
        <artifactId>jetty-ee11-websocket-jakarta-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.websocket</groupId>
        <artifactId>jetty-ee11-websocket-jakarta-common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.websocket</groupId>
        <artifactId>jetty-ee11-websocket-jakarta-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.websocket</groupId>
        <artifactId>jetty-ee11-websocket-jetty-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.websocket</groupId>
        <artifactId>jetty-ee11-websocket-jetty-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11.websocket</groupId>
        <artifactId>jetty-ee11-websocket-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>${ee11.jakarta.xml.bind.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.containers</groupId>
        <artifactId>jersey-container-servlet</artifactId>
        <version>${ee11.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.inject</groupId>
        <artifactId>jersey-hk2</artifactId>
        <version>${ee11.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.media</groupId>
        <artifactId>jersey-media-json-binding</artifactId>
        <version>${ee11.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.wasp</groupId>
        <artifactId>wasp</artifactId>
        <version>${ee11.jakarta.servlet.jsp.jstl.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.weld.servlet</groupId>
        <artifactId>weld-servlet-core</artifactId>
        <version>${ee11.weld.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-el</artifactId>
        <version>${ee11.jsp.impl.version}</version>
      </dependency>
      <!-- Jakarta EE11 Dependencies -->
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-jsp</artifactId>
        <version>${ee11.jsp.impl.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
