<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.tests</groupId>
    <artifactId>jetty-tests</artifactId>
    <version>12.1.9-SNAPSHOT</version>
  </parent>

  <artifactId>jetty-test-coreapps</artifactId>
  <packaging>pom</packaging>

  <name>Core WebApp :: Test WebApps</name>
  <description>Jetty Core WebApp :: Test WebApps</description>

  <modules>
    <module>jetty-test-coreapp-bad-init</module>
    <module>jetty-test-coreapp-demo</module>
    <module>jetty-test-coreapp-http2-client</module>
  </modules>

  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>
</project>
