# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Servlet 3.1 resource injection.

[environment]
ee9

[depends]
server
jndi
plus
ee9-security
ee9-webapp

[files]
maven://jakarta.enterprise/jakarta.enterprise.cdi-api/3.0.0/jar|lib/ee9/support/jakarta.enterprise.jakarta.enterprise.cdi-api-3.0.0.jar
maven://jakarta.inject/jakarta.inject-api/2.0.1/jar|lib/ee9/support/jakarta.inject.jakarta.inject-api-2.0.1.jar
maven://jakarta.interceptor/jakarta.interceptor-api/2.0.0/jar|lib/ee9/support/jakarta.interceptor.jakarta.interceptor-api-2.0.0.jar
maven://jakarta.transaction/jakarta.transaction-api/2.0.0/jar|lib/ee9/support/jakarta.transaction.jakarta.transaction-api-2.0.0.jar
maven://org.eclipse.jetty.ee9/jetty-ee9-plus/${jetty.version}/jar|lib/ee9/jetty-ee9-plus-${jetty.version}.jar

[lib]
lib/ee9/jetty-ee9-plus-${jetty.version}.jar
lib/ee9/support/jakarta.enterprise.jakarta.enterprise.cdi-api-3.0.0.jar
lib/ee9/support/jakarta.inject.jakarta.inject-api-2.0.1.jar
lib/ee9/support/jakarta.interceptor.jakarta.interceptor-api-2.0.0.jar
lib/ee9/support/jakarta.transaction.jakarta.transaction-api-2.0.0.jar
