# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Servlet 3.1 resource injection.

[environment]
ee9

[depends]
server
jndi
plus
ee9-security
ee9-webapp

[ini]
ee9.jakarta.inject.api.version?=@ee9.jakarta.inject.api.version@
jakarta.enterprise.cdi-api.version?=@jakarta.enterprise.cdi-api.version@
jakarta.interceptor-api.version?=@jakarta.interceptor-api.version@
jakarta.transaction-api.version?=@jakarta.transaction-api.version@

[files]
maven://jakarta.enterprise/jakarta.enterprise.cdi-api/${jakarta.enterprise.cdi-api.version}/jar|lib/ee9/support/jakarta.enterprise.jakarta.enterprise.cdi-api-${jakarta.enterprise.cdi-api.version}.jar
maven://jakarta.inject/jakarta.inject-api/${ee9.jakarta.inject.api.version}/jar|lib/ee9/support/jakarta.inject.jakarta.inject-api-${ee9.jakarta.inject.api.version}.jar
maven://jakarta.interceptor/jakarta.interceptor-api/${jakarta.interceptor-api.version}/jar|lib/ee9/support/jakarta.interceptor.jakarta.interceptor-api-${jakarta.interceptor-api.version}.jar
maven://jakarta.transaction/jakarta.transaction-api/${jakarta.transaction-api.version}/jar|lib/ee9/support/jakarta.transaction.jakarta.transaction-api-${jakarta.transaction-api.version}.jar
maven://org.eclipse.jetty.ee9/jetty-ee9-plus/${jetty.version}/jar|lib/ee9/jetty-ee9-plus-${jetty.version}.jar

[lib]
lib/ee9/jetty-ee9-plus-${jetty.version}.jar
lib/ee9/support/jakarta.enterprise.jakarta.enterprise.cdi-api-${jakarta.enterprise.cdi-api.version}.jar
lib/ee9/support/jakarta.inject.jakarta.inject-api-${ee9.jakarta.inject.api.version}.jar
lib/ee9/support/jakarta.interceptor.jakarta.interceptor-api-${jakarta.interceptor-api.version}.jar
lib/ee9/support/jakarta.transaction.jakarta.transaction-api-${jakarta.transaction-api.version}.jar
