//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-keystore-client-authn]]
==== Creating a KeyStore for Client Certificate Authentication

For the majority of secure web sites, it is the client (typically the browser) that validates the certificate sent by the server (by verifying the certificate chain).
This is the _server domain certificate_.

However, the TLS protocol supports a _mutual authentication_ mode where also the client must send a certificate to the server, that the server validates.

You typically want to sign the client certificate(s) with a server certificate that you control, and you must distribute the client certificate(s) to all the clients that need it, and redistribute the client certificates when they expire.
The _server authentication certificate_ may be different from the _server domain certificate_, but it's typically stored in the same KeyStore for simplicity (although under a different alias).

First, you want to create the private key and server authentication certificate that you will use to sign client certificates:

[source,subs=verbatim]
----
keytool
    -genkeypair
    -alias server_authn <1>
    -validity 90
    -keyalg RSA
    -keysize 2048
    -keystore keystore.p12 <2>
    -storetype pkcs12
    -dname "CN=server_authn, OU=Unit, O=Company, L=City, S=State, C=Country" <3>
    -ext bc=ca:true <4>
    -v
----
<1> use the `server_authn` alias to differentiate from the alias of the server certificate
<2> the KeyStore file
<3> the CN is not that important, since this certificate will not be validated by clients
<4> the extension with the basic constraints (more below)

IMPORTANT: The important difference with the xref:og-keystore-create[creation of a server certificate] is the _basic constraints_ extension (`bc`) that indicates that this certificates acts as a certificate authority (`ca:true`).

Now you want to export both the private key and server authentication certificate.
Unfortunately, the `keytool` program cannot export private keys, so you need to use a different command line program like `openssl`, or a graphical program like link:https://keystore-explorer.org/[KeyStore Explorer].

Let's use `openssl` to export the server authentication private key:

----
openssl
    pkcs12
    -in keystore.p12
    -nodes
    -nocerts
    -out server_authn.key
----

Now let's export the server authentication certificate:

----
keytool
    -exportcert
    -keystore keystore.p12
    -rfc
    -file server_authn.crt
    -v
----

At this point, you want to create a client KeyStore, so that you can sign the client certificate with the server authentication cryptographic material:

[source,subs=verbatim]
----
keytool
    -genkeypair
    -validity 90
    -keyalg RSA
    -keysize 2048
    -keystore client_keystore.p12 <1>
    -storetype pkcs12
    -dname "CN=client, OU=Unit, O=Company, L=City, S=State, C=Country" <2>
    -v
----
<1> the client KeyStore file
<2> the CN is not that important, since it will not be validated by the server

Now produce a certificate signing request (CSR):

----
keytool
    -certreq
    -file client.csr
    -keystore client_keystore.p12
----

Now you need to sign the CSR, but again the `keytool` program does not have this functionality, and you must resort again to use `openssl`:

----
openssl
    x509
    -req
    -days 90
    -in client.csr
    -CA server_authn.crt
    -CAkey server_authn.key
    -CAcreateserial
    -sha256
    -out signed.crt
----

Now you need to import the server authentication certificate and the signed client certificate into the client KeyStore.

First, the server authentication certificate:

----
keytool
    -importcert
    -alias ca
    -file server_authn.crt
    -keystore client_keystore.p12
    -v
----

Then, the signed client certificate:

----
keytool
    -importcert
    -file signed.crt
    -keystore client_keystore.p12
    -v
----

Now you can distribute `client_keystore.p12` to your client(s).

// TODO: add a section about renewal?

Refer to the section about configuring xref:og-protocols-ssl[secure protocols] to configure the secure connector to require client authentication.
