# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables the Jetty Quickstart module for rapid deployment of preconfigured web applications.

[environment]
ee11

[depend]
server
deploy

[lib]
lib/jetty-ee11-quickstart-${jetty.version}.jar

[xml]
etc/jetty-ee11-quickstart.xml

[ini-template]

# Modes are AUTO, GENERATE, QUICKSTART
# jetty.quickstart.mode=AUTO
# jetty.quickstart.origin=origin
# jetty.quickstart.xml=
