# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the Jetty Quickstart module for rapid deployment of preconfigured web applications.

[environment]
ee11

[depends]
server
ee11-annotations
ee11-webapp
ee11-plus

[xml]
etc/jetty-ee11-quickstart.xml

[files]
maven://org.eclipse.jetty.ee11/jetty-ee11-quickstart/${jetty.version}/jar|lib/ee11/jetty-ee11-quickstart-${jetty.version}.jar

[lib]
lib/ee11/jetty-ee11-quickstart-${jetty.version}.jar

[ini-template]

# Modes are AUTO, GENERATE, QUICKSTART
# jetty.quickstart.mode=AUTO
# jetty.quickstart.origin=origin
# jetty.quickstart.xml=
