//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-deploy]]
=== Web Application Deployment

Most of the time you want to be able to customize the deployment of your web applications, for example by changing the `contextPath`, or by adding JNDI entries, or by configuring virtual hosts, etc.

Jetty supports the deployment of each web application to a specific _environment_.
The available environments are:

* Java EE 8 -- Supports Servlet 4.0 (and associated specifications) in the `+javax.*+` packages.
* Jakarta EE 9 -- Supports Servlet 5.0 (and associated specifications) in the `+jakarta.*+` packages.
* Jakarta EE 10 -- Supports Servlet 6.0 (and associated specifications) in the `+jakarta.*+` packages.
* Jetty Core -- Supports web applications written against the Jetty `Handler` APIs, without any Servlet dependencies.

This means that you can simultaneously deploy an old Java EE 8 web application, say `old-ee8.war`, alongside a new Jakarta {ee-current-caps} web application, say `new-{ee-current}.war`, alongside a web application that only uses the Jetty `Handler` APIs, say `app-jetty.xml`.

The customization of the deployment (for example, web application context path, etc.) is performed by processing xref:og-deploy-jetty[Jetty context XML files].

The `deploy` module contains the `DeploymentManager` component that scans the `$JETTY_BASE/webapps` directory for changes, following the deployment rules described in xref:og-deploy-rules[this section].

For each specific environment there is a specific deploy module that you must enable:

* For Java EE 8, xref:og-module-eeN-deploy[`ee8-deploy`]
* For Java EE 9, xref:og-module-eeN-deploy[`ee9-deploy`]
* For Java {ee-current-caps}, xref:og-module-eeN-deploy[`{ee-current}-deploy`]
* For Jetty Core, xref:og-module-core-deploy[`core-deploy`]

Each of these modules provide the environment specific features, and depend on the `deploy` module that provides the scanning features.

include::deploy-hot-static.adoc[]
include::deploy-rules.adoc[]
include::deploy-jetty.adoc[]
include::deploy-jndi.adoc[]
include::deploy-virtual-hosts.adoc[]
include::deploy-extract-war.adoc[]
include::deploy-override-webxml.adoc[]

// TODO: move this section to its own file
// TODO: configuring from the Jetty context XML file happens before web.xml
//  What about jetty-web.xml? Can this be specified externally, e.g. WebAppContext.setJettyWebXml() ?
[[og-deploy-init-params]]
==== Configuring ``init-param``s

TODO

// TODO: see old_docs/deploying
