# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds Jetty EECommon utility servlets and filters available to a webapp.
Puts org.eclipse.jetty.ee.servlets on the server classpath
(CrossOriginFilter, DosFilter, MultiPartFilter, QoSFilter, etc.)
for use by all web applications.

[environment]
<inherit>

[depend]
ee-servlet

[lib]
lib/jetty-ee-servlets-${jetty.version}.jar

