# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Jakarta WebSocket Webapp

[environment]
ee11

[tags]
demo
webapp

[depends]
ee11-deploy
ext
ee11-servlets
ee11-websocket-jakarta

[files]
basehome:modules/demo.d/ee11-demo-jakarta-websocket.xml|webapps/ee11-demo-jakarta-websocket.xml
basehome:modules/demo.d/ee11-demo-jakarta-websocket.properties|webapps/ee11-demo-jakarta-websocket.properties
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-jakarta-websocket-webapp/${jetty.version}/war|webapps/ee11-demo-jakarta-websocket.war
