# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Template configuration file to apply to all web applications deployed in the EE9 environment.

[tags]
deployment

[depend]
ee9-deploy

[files]
basehome:modules/deployment.d/ee9-environment.properties|environments/ee9-environment.properties
basehome:modules/deployment.d/ee9-environment.xml|environments/ee9-environment.xml

