# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
This module enables support for Jakarta EE 9 web applications.

[environment]
ee9

[depend]
ee-webapp
ee9-servlet
ee9-security

[xml]
etc/jetty-ee9-webapp.xml

[lib]
lib/jetty-ee9-webapp-${jetty.version}.jar

[ini-template]
## Customize protected and hidden classes for this web application context.
#jetty.webapp.addProtectedClasses+=,org.example.
#jetty.webapp.addHiddenClasses+=,org.example.

## Default ContextHandler class for ee9 environment deployments
# jetty.deploy.defaultContextHandlerClass=org.eclipse.jetty.ee9.webapp.WebAppContext
