# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the EE9 DebugListener.
Generates additional logging regarding detailed request handling events.
Renames threads to include request URI.

[environment]
ee9

[tags]
server
debug

[depend]
ee9-deploy

[files]
logs/
basehome:modules/ee9-debug.d/ee9-debug.properties|webapps/ee9-debug.properties
basehome:modules/ee9-debug.d/jetty-ee9-debug.xml|etc/jetty-ee9-debug.xml

[ini-template]
## How many days to retain old log files
# jetty.debug.retainDays=14

## Should existing log be appended to
# jetty.debug.append=true

## Log directory for jetty debug logs
# jetty.debug.logs=./logs

## Timezone of the log entries
# jetty.debug.timezone=GMT

## Show Request/Response headers
# jetty.debug.showHeaders=true

## Rename threads while in context scope
# jetty.debug.renameThread=false

## Dump context as deployed
# jetty.debug.dumpContext=true

