# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Download and deploy the Test Spec webapp demo.

[environment]
ee10

[tags]
demo
webapp

[depends]
ee10-deploy
jdbc
ee10-jsp
ee10-annotations
ext
demo-realm
ee10-demo-mock-resources

[files]
basehome:modules/demo.d/ee10-demo-spec.xml|webapps/ee10-demo-spec.xml
basehome:modules/demo.d/ee10-demo-spec.properties|webapps/ee10-demo-spec.properties
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-spec-webapp/${jetty.version}/war|webapps/ee10-demo-spec.war
