# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Expose the Jetty WebSocket Client classes to deployed web applications.

[environment]
<inherit>

[tags]
websocket

[depend]
client
ee/common-annotations
websocket-jetty-client

[lib]
lib/jetty-ee-websocket-jetty-client-webapp-${jetty.version}.jar

