//
// ========================================================================
// Copyright (c) 1995-2021 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[pg-server-websocket-standard]]
==== Standard APIs Implementation

Jetty's implementation of the standard `javax.websocket` APIs is provided by the following Maven artifact (and its transitive dependencies):

[source,xml,subs=normal]
----
<dependency>
  <groupId>org.eclipse.jetty.websocket</groupId>
  <artifactId>websocket-javax-server</artifactId>
  <version>{version}</version>
</dependency>
----

[NOTE]
====
The `websocket-javax-server` artifact (and its transitive dependencies) should be present in the server class-path, and never in the web application's `/WEB-INF/lib` directory.
====

Jetty's implementation of the standard `javax.websocket` APIs can be configured in two ways:

* xref:pg-server-websocket-standard-explicit[Explicitly], by configuring the WebSocket endpoints via API calls.
* xref:pg-server-websocket-standard-automatic[Automatically], by configuring startup annotation scanning to lookup for WebSocket endpoints.

The configuration must be performed for every web application.

[[pg-server-websocket-standard-explicit]]
===== Explicit Configuration

Explicit configuration is used when your web application is represented by a xref:pg-server-http-handler-use-servlet-context[`ServletContextHandler`]:

[source,java,indent=0]
----
include::../../{doc_code}/org/eclipse/jetty/docs/programming/server/websocket/WebSocketServerDocs.java[tags=standardExplicit]
----

Calling `JavaxWebSocketServletContainerInitializer.configure(...)` must be done _before_ the `ServletContextHandler` is started, and configures the `javax.websocket` implementation for that web application context.

When the `ServletContextHandler` is started, the `JavaxWebSocketServletContainerInitializer` is invoked, which invokes the `Configurator` lambda (the second parameter passed to `JavaxWebSocketServletContainerInitializer.configure(...)`) which will allow you to explicitly configure the WebSocket endpoints using the standard API provided by `javax.websocket.server.ServerContainer`.

The xref:pg-websocket-endpoints[WebSocket endpoints] classes may be either annotated with the standard `javax.websocket` annotations, or extend the `javax.websocket.Endpoint` abstract class.

Under the hood, `JavaxWebSocketServletContainerInitializer` installs the `org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter`, which is the component that intercepts HTTP requests to upgrade to WebSocket and performs the upgrade.

[NOTE]
====
The `WebSocketUpgradeFilter` is installed under the filter name corresponding to its class name (that is, the string `"org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter"`) and with a filter mapping of `/*`.

Refer to the xref:pg-server-websocket-configure-filter[advanced `WebSocketUpgradeFilter` configuration section] for more information.
====

With the default configuration, every HTTP request flows first through the `WebSocketUpgradeFilter`.

If the HTTP request is an upgrade to WebSocket, `WebSocketUpgradeFilter` performs the upgrade and does not invoke any other Filter or Servlet.
From this point on, the communication happens with the WebSocket protocol, and HTTP components such as Filters and Servlets are not relevant anymore.

If the HTTP request is not an upgrade to WebSocket, `WebSocketUpgradeFilter` passes the request to the Filter chain of your web application, and eventually the request arrives to a Servlet to be processed (otherwise a `404 Not Found` response is returned to client).

[[pg-server-websocket-standard-automatic]]
===== Automatic Configuration

Automatic configuration is used when your web application is represented by a xref:pg-server-http-handler-use-webapp-context[`WebAppContext`]:

[source,java,indent=0]
----
include::../../{doc_code}/org/eclipse/jetty/docs/programming/server/websocket/WebSocketServerDocs.java[tags=standardAutomatic]
----

As you can see, there is nothing to do with respect to configuring the WebSocket support, because `WebAppContext` is already automatically configured with the `JavaxWebSocketConfiguration` that discovers the `JavaxWebSocketServletContainerInitializer` via the `ServiceLoader` mechanism because you have `websocket-javax-server-{version}.jar` in the server class-path.

When the `WebAppContext` is started, the `JavaxWebSocketServletContainerInitializer` is invoked with the list of classes that are annotated with the standard `javax.websocket` annotation `@ServerEndpoint`, or extend the standard class `javax.websocket.Endpoint`.

`JavaxWebSocketServletContainerInitializer` installs the `org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter` under the hood, exactly as explained in the xref:pg-server-websocket-standard-explicit[explicit configuration section].

[[pg-server-websocket-configure-filter]]
===== Advanced `WebSocketUpgradeFilter` Configuration

`JavaxWebSocketServletContainerInitializer` installs the `WebSocketUpgradeFilter` to handle HTTP requests that upgrade to WebSocket.

Typically, the `WebSocketUpgradeFilter` is not present in the `web.xml` configuration, and therefore `JavaxWebSocketServletContainerInitializer` creates a new `WebSocketUpgradeFilter` and installs it _before_ any other Filter declared in `web.xml`, under the default name of `"org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter"` and with path mapping `/*`.

However, if the `WebSocketUpgradeFilter` is already present in `web.xml` under the default name, then `JavaxWebSocketServletContainerInitializer` will use that declared in `web.xml` instead of creating a new one.

This allows you to customize:

* The filter order; for example, by configuring the `CrossOriginFilter` (or other filters) for increased security or authentication _before_ the `WebSocketUpgradeFilter`.
* The `WebSocketUpgradeFilter` configuration via ``init-param``s, that affects all `Session` instances created by this filter.
* The `WebSocketUpgradeFilter` path mapping.
* The possibility to have multiple ``WebSocketUpgradeFilter``s, mapped to different paths, each with its own configuration.

For example:

[source,xml,subs=verbatim]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
         version="4.0">

  <display-name>My WebSocket WebApp</display-name>

  <!-- The CrossOriginFilter *must* be the first --> <1>
  <filter>
    <filter-name>cross-origin</filter-name>
    <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
    <async-supported>true</async-supported>
  </filter>
  <filter-mapping>
    <filter-name>cross-origin</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>

  <!-- Configure the default WebSocketUpgradeFilter --> <2>
  <filter>
    <!-- The filter name must be the default WebSocketUpgradeFilter name -->
    <filter-name>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter</filter-name> <3>
    <filter-class>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter</filter-class>
    <!-- Configure at most 1 MiB text messages -->
    <init-param> <4>
      <param-name>maxTextMessageSize</param-name>
      <param-value>1048576</param-value>
    </init-param>
    <async-supported>true</async-supported>
  </filter>
  <filter-mapping>
    <filter-name>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter</filter-name>
    <!-- Use a more specific path mapping for WebSocket requests -->
    <url-pattern>/ws/*</url-pattern> <5>
  </filter-mapping>

</web-app>
----
<1> The `CrossOriginFilter` is the first to protect against link:https://owasp.org/www-community/attacks/csrf[cross-site request forgery attacks].
<2> The configuration for the _default_ `WebSocketUpgradeFilter`.
<3> Note the use of the _default_ `WebSocketUpgradeFilter` name.
<4> Specific configuration for `WebSocketUpgradeFilter` parameters.
<5> Use a more specific path mapping for `WebSocketUpgradeFilter`.

Note that using a more specific path mapping for WebSocket requests is also beneficial to the performance of normal HTTP requests: they do not go through the `WebSocketUpgradeFilter` (as they will not match its path mapping), saving the cost of analyzing them to see whether they are WebSocket upgrade requests or not.
