# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the Jetty HTTP client dependencies to the server classpath.

[tags]
client

[depends]
gzip-compression

[lib]
lib/jetty-alpn-client-${jetty.version}.jar
lib/jetty-alpn-java-client-${jetty.version}.jar
lib/jetty-client-${jetty.version}.jar
