# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
This module enables support for Jakarta EE 11 web applications.

[environment]
ee11

[depend]
ee-webapp
ee11-servlet
ee11-security

[xml]
etc/jetty-ee11-webapp.xml

[lib]
lib/jetty-ee11-webapp-${jetty.version}.jar

[ini-template]
# tag::ini-template[]
## Customize protected and hidden classes for this web application context.
#jetty.webapp.addProtectedClasses+=,org.example.
#jetty.webapp.addHiddenClasses+=,org.example.

## Default ContextHandler class for ee11 environment deployments
# jetty.deploy.defaultContextHandlerClass=org.eclipse.jetty.ee11.webapp.WebAppContext
# end::ini-template[]
