# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Expose the Jetty WebSocket Client classes to deployed web applications.

[environment]
ee12

[tags]
websocket

[depend]
ee/common-websocket-jetty-client-webapp
client
ee12-annotations
websocket-jetty-client

[lib]
lib/ee12-websocket/jetty-ee12-websocket-jetty-client-webapp-${jetty.version}.jar

