# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds OpenId Connect authentication to the server.

[environment]
ee8

[depend]
ee8-security
openid

[lib]
lib/jetty-ee8-openid-${jetty.version}.jar
