# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds OpenId Connect authentication to the server.

[environment]
ee8

[depends]
ee8-security
openid

[files]
maven://org.eclipse.jetty.ee8/jetty-ee8-openid/${project.version}/jar|lib/ee8/jetty-ee8-openid-${project.version}.jar

[lib]
lib/ee8/jetty-ee8-openid-${project.version}.jar
