# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Enables Annotation scanning for deployed web applications.

[depend]
plus

[lib]
lib/jetty-annotations-${jetty.version}.jar
lib/annotations/*.jar

[jpms]
add-modules:org.objectweb.asm

