<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.quic</groupId>
    <artifactId>jetty-quic</artifactId>
    <version>13.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>jetty-quic-client</artifactId>
  <name>Core :: QUIC :: Client</name>
  <description>Jetty QUIC Client Artifact</description>

  <properties>
    <bundle-symbolic-name>${project.groupId}.client</bundle-symbolic-name>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty.quic</groupId>
      <artifactId>jetty-quic-common</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.quic</groupId>
      <artifactId>jetty-quic-quiche-server</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>
