# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Download and deploy the Test Spec webapp demo for Servlet 6.1.

[environment]
ee11

[tags]
demo
webapp

[depends]
ee11-deploy
ext

[files]
basehome:modules/demo.d/ee11-demo-spec.properties|webapps/ee11-demo-spec-6-1.properties
maven://org.eclipse.jetty.demos/jetty-servlet6-demo-spec-6-1-webapp/${jetty.version}/war|webapps/ee11-demo-spec-6-1.war
