# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds servlet standard security handling to the classpath.

[environment]
ee9

[depends]
server
security
ee9-servlet

[files]
maven://org.eclipse.jetty.ee9/jetty-ee9-security/${project.version}/jar|lib/ee9/jetty-ee9-security-${project.version}.jar

[lib]
lib/ee9/jetty-ee9-security-${project.version}.jar
