# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds servlet standard security handling to the classpath.

[environment]
ee9

[depend]
server
security
ee9-servlet

[lib]
lib/jetty-ee9-security-${jetty.version}.jar
