<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.ee9</groupId>
    <artifactId>jetty-ee9-tests</artifactId>
    <version>12.1.13</version>
  </parent>
  <artifactId>jetty-ee9-test-sci-jar</artifactId>
  <name>EE9 :: Tests :: SCI Test JAR</name>
  <description>Jetty SCI Test JAR</description>
  <properties>
    <bundle-symbolic-name>${project.groupId}.tests.sci.jar</bundle-symbolic-name>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

</project>
