# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JASPI authentication for deployed web applications.

[environment]
<inherit>

[tags]
security

[depend]
ee/common-security
auth-config-factory

[lib]
lib/jetty-ee-jaspi-${jetty.version}.jar

[xml]
etc/jaspi/jetty-ee-jaspi-authmoduleconfig.xml

[files]
basehome:etc/jaspi/jetty-ee-jaspi-authmoduleconfig.xml|etc/jaspi/jetty-ee-jaspi-authmoduleconfig.xml

