# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee9

[depend]
ee9-plus
annotations

[ini]
ee9.jakarta.annotation.api.version?=@jakarta.annotation.api.version@

[lib]
lib/jetty-ee9-annotations-${jetty.version}.jar
lib/ee9-annotations/jakarta.annotation-api-${ee9.jakarta.annotation.api.version}.jar
