# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demo Async Rest webapp

[environment]
ee11

[tags]
demo
webapp

[depends]
ee11-deploy

[files]
maven://org.eclipse.jetty.ee11.demos/jetty-ee11-demo-async-rest-webapp/${jetty.version}/war|webapps/ee11-demo-async-rest.war

