# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the Jetty Quickstart module for rapid deployment of preconfigured web applications.

[environment]
ee12

[depend]
ee/common-quickstart
server
ee12-annotations
ee12-webapp
ee12-plus

[lib]
lib/jetty-ee12-quickstart-${jetty.version}.jar

[xml]
etc/jetty-ee12-quickstart.xml

[ini-template]

# Modes are AUTO, GENERATE, QUICKSTART
# jetty.quickstart.mode=AUTO
# jetty.quickstart.origin=origin
# jetty.quickstart.xml=
