# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee9

[depends]
ee9-servlet
ee9-annotations

[ini]
eclipse.jdt.ecj.version?=@eclipse.jdt.ecj.version@
ee9.jsp.impl.version?=@ee9.jsp.impl.version@

[files]
maven://org.eclipse.jdt/ecj/${eclipse.jdt.ecj.version}/jar|lib/ee9/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
maven://org.eclipse.jetty.ee9/jetty-ee9-apache-jsp/${project.version}/jar|lib/ee9/jetty-ee9-apache-jsp-${project.version}.jar
maven://org.mortbay.jasper/mortbay-apache-el/${ee9.jsp.impl.version}/jar|lib/ee9/support/org.mortbay.jasper.mortbay-apache-el-${ee9.jsp.impl.version}.jar
maven://org.mortbay.jasper/mortbay-apache-jsp/${ee9.jsp.impl.version}/jar|lib/ee9/support/org.mortbay.jasper.mortbay-apache-jsp-${ee9.jsp.impl.version}.jar

[lib]
lib/ee9/jetty-ee9-apache-jsp-${project.version}.jar
lib/ee9/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
lib/ee9/support/org.mortbay.jasper.mortbay-apache-el-${ee9.jsp.impl.version}.jar
lib/ee9/support/org.mortbay.jasper.mortbay-apache-jsp-${ee9.jsp.impl.version}.jar
