//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-xml]]
=== Jetty XML

// TODO: merge this small section into the syntax and maybe call it "Jetty XML Reference".

The Jetty XML format is a straightforward mapping of XML elements to Java APIs so that any object can be instantiated and getters, setters, and methods can be called.

The Jetty XML format is very similar to that of frameworks like Spring or Plexus, although it predates all of them and it's typically more powerful as it can invoke any Java API.

The Jetty XML format is used in xref:og-modules[Jetty modules] to create the Jetty server components, as well as in xref:og-deploy[Jetty XML context files] to configure web applications, but it can be used to call any Java API.

include::xml-syntax.adoc[]

// TODO: port the documentation from old_docs/jetty-xml/*.adoc
