# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Servlet resource injection. 

[environment]
ee10

[depends]
server
jndi
plus
ee10-security
ee10-webapp

[files]
maven://jakarta.enterprise/jakarta.enterprise.cdi-api/4.0.1/jar|lib/ee10/support/jakarta.enterprise.jakarta.enterprise.cdi-api-4.0.1.jar
maven://jakarta.enterprise/jakarta.enterprise.lang-model/4.0.1/jar|lib/ee10/support/jakarta.enterprise.jakarta.enterprise.lang-model-4.0.1.jar
maven://jakarta.inject/jakarta.inject-api/2.0.1/jar|lib/ee10/support/jakarta.inject.jakarta.inject-api-2.0.1.jar
maven://jakarta.interceptor/jakarta.interceptor-api/2.1.0/jar|lib/ee10/support/jakarta.interceptor.jakarta.interceptor-api-2.1.0.jar
maven://jakarta.transaction/jakarta.transaction-api/2.0.1/jar|lib/ee10/support/jakarta.transaction.jakarta.transaction-api-2.0.1.jar
maven://org.eclipse.jetty.ee10/jetty-ee10-plus/${jetty.version}/jar|lib/ee10/jetty-ee10-plus-${jetty.version}.jar

[lib]
lib/ee10/jetty-ee10-plus-${jetty.version}.jar
lib/ee10/support/jakarta.enterprise.jakarta.enterprise.cdi-api-4.0.1.jar
lib/ee10/support/jakarta.enterprise.jakarta.enterprise.lang-model-4.0.1.jar
lib/ee10/support/jakarta.inject.jakarta.inject-api-2.0.1.jar
lib/ee10/support/jakarta.interceptor.jakarta.interceptor-api-2.1.0.jar
lib/ee10/support/jakarta.transaction.jakarta.transaction-api-2.0.1.jar
