# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds OpenId Connect authentication to the server.

[environment]
ee9

[depends]
ee9-security
openid

[files]
maven://org.eclipse.jetty.ee9/jetty-ee9-openid/${jetty.version}/jar|lib/ee9/jetty-ee9-openid-${jetty.version}.jar

[lib]
lib/ee9/jetty-ee9-openid-${jetty.version}.jar
