# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds OpenId Connect authentication to the server.

[environment]
ee9

[depend]
ee9-security
openid

[lib]
lib/jetty-ee9-openid-${jetty.version}.jar