//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[pg-server-http-handler]]
==== Server Handlers

An `org.eclipse.jetty.server.Handler` is the component that processes incoming HTTP requests and eventually produces HTTP responses.

``Handler``s can process the HTTP request themselves, or they can be a ``Handler.Container``s that delegate HTTP request processing to one or more contained ``Handler``s.  This allows ``Handler``s to be organised as a tree comprised of:
* leaf ``Handler``s that return true from the `process(\...)` method, generate a response and succeed the ``Callback``.
* a ``Handler.Wrapper`` can be used to form a chain of ``Handler``s where request, response or callback objects are wrapped in the `process(\...)` method before being passed down the chain.
* a ``Handler.Collection`` contains a sequence of ``Handler``s, with each being called in series until one returns ``true`` from its `process(\...)` method.
* a specialized ``Handler.Container`` that may use attributes of the request (for example, the URI, or a header, etc.) to select from one or more contained ``Handler``s to delegate the HTTP request processing to.


A ``Handler`` tree is created by composing ``Handler``s together:

[source,java,indent=0]
----
include::../../{doc_code}/org/eclipse/jetty/docs/programming/server/http/HTTPServerDocs.java[tags=handlerTree]
----

The corresponding `Handler` tree structure looks like the following:

[source,screen]
----
Server
└── GzipHandler
    └── Handler.Collection
        ├── App1Handler
        └── App2Handler
----

Server applications should rarely write custom ``Handler``s, preferring instead to use existing ``Handler``s provided by the Jetty Server Libraries for managing web application contexts, security, HTTP sessions and Servlet support.
Refer to xref:pg-server-http-handler-use[this section] for more information about how to use the ``Handler``s provided by the Jetty Server Libraries.

However, in some cases the additional features are not required, or additional constraints on memory footprint, or performance, or just simplicity must be met.
In these cases, implementing your own `Handler` may be a better solution.
Refer to xref:pg-server-http-handler-implement[this section] for more information about how to write your own ``Handler``s.

// TODO: document ScopedHandler? Is this really necessary or just an implementation detail that application will never worry about?

include::server-http-handler-use.adoc[]
include::server-http-handler-implement.adoc[]
