# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Download and install some Demo Mock Resources

[environment]
ee8

[tags]
demo

[depends]
jdbc

[files]
maven://org.eclipse.jetty.demos/jetty-servlet4-demo-mock-resources/${jetty.version}/jar|lib/ee8/ee8-demo-mock-resources-${jetty.version}.jar

[lib]
lib/ee8/ee8-demo-mock-resources-${jetty.version}.jar
