# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Download and install some Demo Mock Resources

[environment]
ee10

[tags]
demo

[depends]
jdbc

[files]
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-mock-resources/${jetty.version}/jar|lib/ee10/jetty-servlet5-demo-mock-resources-${jetty.version}.jar

[lib]
lib/ee10/jetty-servlet5-demo-mock-resources-${jetty.version}.jar
