# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
This module enables support for Jakarta EE 10 web applications.

[environment]
ee10

[depend]
ee-webapp
ee10-servlet
ee10-security

[xml]
etc/jetty-ee10-webapp.xml

[lib]
lib/jetty-ee10-webapp-${jetty.version}.jar

[ini-template]
## Customize protected and hidden classes for this web application context.
#jetty.webapp.addProtectedClasses+=,org.example.
#jetty.webapp.addHiddenClasses+=,org.example.

## Default ContextHandler class for ee10 environment deployments
# jetty.deploy.defaultContextHandlerClass=org.eclipse.jetty.ee10.webapp.WebAppContext
