# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Template configuration file to apply to all web applications deployed in the EE10 environment.

[tags]
deployment

[depend]
ee10-deploy

[files]
basehome:modules/deployment.d/ee10-environment.properties|environments/ee10-environment.properties
basehome:modules/deployment.d/ee10-environment.xml|environments/ee10-environment.xml

