# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Template environments configuration files for the EE10 environment.

[tags]
deployment

[depend]
deployment-scanner

[files]
basehome:modules/deployment.d/ee10-environment.properties|environments/ee10-environment.properties
basehome:modules/deployment.d/ee10-environment.xml|environments/ee10-environment.xml

