# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee11

[depends]
ee11-servlet
ee11-annotations

[ini]
eclipse.jdt.ecj.version?=@eclipse.jdt.ecj.version@
ee11.jakarta.el.api.version?=@ee11.jakarta.el.api.version@
ee11.jsp.impl.version?=@ee11.jsp.impl.version@
ee11.jakarta.servlet.jsp.api.version?=@ee11.jakarta.servlet.jsp.api.version@

[files]
maven://jakarta.el/jakarta.el-api/${ee11.jakarta.el.api.version}/jar|lib/ee11/support/jakarta.el.jakarta.el-api-${ee11.jakarta.el.api.version}.jar
maven://jakarta.servlet.jsp/jakarta.servlet.jsp-api/${ee11.jakarta.servlet.jsp.api.version}/jar|lib/ee11/support/jakarta.servlet.jsp.jakarta.servlet.jsp-api-${ee11.jakarta.servlet.jsp.api.version}.jar
maven://org.eclipse.jdt/ecj/${eclipse.jdt.ecj.version}/jar|lib/ee11/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
maven://org.eclipse.jetty.ee11/jetty-ee11-apache-jsp/${jetty.version}/jar|lib/ee11/jetty-ee11-apache-jsp-${jetty.version}.jar
maven://org.mortbay.jasper/mortbay-apache-el/${ee11.jsp.impl.version}/jar|lib/ee11/support/org.mortbay.jasper.mortbay-apache-el-${ee11.jsp.impl.version}.jar
maven://org.mortbay.jasper/mortbay-apache-jsp/${ee11.jsp.impl.version}/jar|lib/ee11/support/org.mortbay.jasper.mortbay-apache-jsp-${ee11.jsp.impl.version}.jar

[lib]
lib/ee11/jetty-ee11-apache-jsp-${jetty.version}.jar
lib/ee11/support/jakarta.el.jakarta.el-api-${ee11.jakarta.el.api.version}.jar
lib/ee11/support/jakarta.servlet.jsp.jakarta.servlet.jsp-api-${ee11.jakarta.servlet.jsp.api.version}.jar
lib/ee11/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
lib/ee11/support/org.mortbay.jasper.mortbay-apache-el-${ee11.jsp.impl.version}.jar
lib/ee11/support/org.mortbay.jasper.mortbay-apache-jsp-${ee11.jsp.impl.version}.jar
