# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee11

[depend]
ee-apache-jsp
ee11-servlet
ee11-annotations

[lib]
lib/ee11-apache-jsp/@jakarta.el:jakarta.el-api@
lib/ee11-apache-jsp/@jakarta.servlet.jsp:jakarta.servlet.jsp-api@
lib/ee11-apache-jsp/@org.eclipse.jdt:ecj@
lib/ee11-apache-jsp/@org.mortbay.jasper:mortbay-apache-el@
lib/ee11-apache-jsp/@org.mortbay.jasper:mortbay-apache-jsp@
lib/jetty-ee11-apache-jsp-${jetty.version}.jar

