# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
<inherit>

[depend]
ee-servlet
ee-annotations

[lib]
lib/ee-apache-jsp/@jakarta.el:jakarta.el-api@
lib/ee-apache-jsp/@jakarta.servlet.jsp:jakarta.servlet.jsp-api@
lib/ee-apache-jsp/@org.eclipse.jdt:ecj@
lib/ee-apache-jsp/@org.mortbay.jasper:mortbay-apache-el@
lib/ee-apache-jsp/@org.mortbay.jasper:mortbay-apache-jsp@
lib/jetty-ee-apache-jsp-${jetty.version}.jar

