# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the Jetty EE11 JNDI reference factories

[environment]
ee11

[depend]
jndi

[lib]
lib/jetty-ee11-jndi-${jetty.version}.jar

[ini]
jetty.webapp.addHiddenClasses+=,-org.eclipse.jetty.ee11.jndi.factories.