# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds the Jetty EE11 JNDI reference factories

[environment]
ee11

[depend]
jndi

[lib]
lib/jetty-ee11-jndi-${jetty.version}.jar
