# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds Jetty EE12 utility servlets and filters available to a webapp.
Puts org.eclipse.jetty.ee.servlets on the server classpath
(CrossOriginFilter, DosFilter, MultiPartFilter, QoSFilter, etc.)
for use by all web applications.

[environment]
ee12

[depend]
ee/common-servlets
ee12-servlet

[lib]
lib/jetty-ee12-servlets-${jetty.version}.jar

