//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-begin-start]]
==== Starting Jetty

Eclipse Jetty as a standalone server has no graphical user interface, so configuring and running the server is done from the command line.

Recall from the xref:og-arch[architecture section] that Jetty is based on xref:og-modules[modules], that provides features, and on xref:og-arch-jetty-base[`$JETTY_BASE`], the place where you configure which module (and therefore which feature) you want to enable, and where you configure module parameters.

Jetty is started by executing `$JETTY_HOME/start.jar` from within a `$JETTY_BASE` directory, so first we need to create a `$JETTY_BASE`:

----
$ JETTY_BASE=/path/to/jetty.base
$ cd $JETTY_BASE
----

If you try to start Jetty from an empty `$JETTY_BASE` you get:

----
$ java -jar $JETTY_HOME/start.jar
----

[source,options=nowrap]
----
include::jetty[]
----

Jetty exited complaining that there are no modules enabled, since the `$JETTY_BASE` you just created is empty and therefore there is no configuration to read to assemble the Jetty server.

However, it shows that `start.jar` takes parameters, whose details can be found in xref:og-start[this section].

You can explore what modules are available out of the box via:

----
$ java -jar $JETTY_HOME/start.jar --list-modules=*
----

Let's try to enable the `http` module (see also xref:og-protocols-http[this section] for additional information):

----
$ java -jar $JETTY_HOME/start.jar --add-module=http
----

[source,options=nowrap]
----
include::jetty[args="--add-module=http"]
----

Now you can start Jetty:

----
$ java -jar $JETTY_HOME/start.jar
----

[source,subs=quotes,options=nowrap]
----
include::jetty[args="--module=http",highlight="(\{.*:8080})"]
----

Note how Jetty is listening on port `8080` for clear-text HTTP/1.1 connections.

After having enabled the `http` module, the `$JETTY_BASE` directory looks like this:

[source,subs=verbatim]
----
JETTY_BASE
├── resources
│   └── jetty-logging.properties <1>
└── start.d <2>
    └── http.ini <3>
----

<1> The `resources/jetty-logging.properties` file has been created because the `http` modules depends on the `server` module, which in turn depends on the `logging` module; the `logging` module created this file that can be configured to control the server logging level.
<2> The `start.d/` directory contains the configuration files for the modules.
<3> The `start.d/http.ini` file is the `http` module configuration file, where you can specify values for the `http` module properties.

In the `http.ini` file you can find the following content (among other content):

.http.ini
[source,subs=verbatim]
----
--module=http <1>
# jetty.http.port=8080 <2>
...
----

<1> This line enables the `http` module and should not be modified.
<2> This line is commented out and specifies the default value for the module property `jetty.http.port`, which is the network port that listens for clear-text HTTP connections.

You can change the module property `jetty.http.port` value directly from the command line:

----
$ java -jar $JETTY_HOME/start.jar jetty.http.port=9999
----

To make this change persistent, you can edit the `http.ini` file, uncomment the module property `jetty.http.port` and change its value to `9999`:

.http.ini
----
--module=http
jetty.http.port=9999
...
----

If you restart Jetty, the new value will be used:

----
$ java -jar $JETTY_HOME/start.jar
----

[source,subs=quotes,options=nowrap]
----
include::jetty[args="--module=http jetty.http.port=9999",highlight="(\{.*:9999})"]
----

Note how Jetty is now listening on port `9999` for clear-text HTTP/1.1 connections.

NOTE: If you want to enable support for different protocols such as secure HTTP/1.1 or HTTP/2 or HTTP/3, or configure Jetty behind a load balancer, read xref:og-protocols[this section].

The Jetty server is now up and running, but it has no web applications deployed, so it just replies with `404 Not Found` to every request.
It is time to xref:og-begin-deploy[deploy your web applications] to Jetty.

For more detailed information about the Jetty start mechanism, you can read the xref:og-arch-start[Jetty start mechanism] section.
