<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.eclipse.jetty.ee</groupId>
    <artifactId>jetty-ee</artifactId>
    <version>13.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>jetty-ee-bom</artifactId>
  <packaging>pom</packaging>
  <name>EE :: BOM</name>
  <description>Jetty EECommon APIs BOM artifact</description>

  <dependencyManagement>
    <dependencies>
      <!-- Jetty EECommon Dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-annotations</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-apache-jsp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-cdi</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-common</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-fcgi-proxy</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-glassfish-jstl</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-jaspi</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-jndi</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-jspc-maven-plugin</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-maven-plugin</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-plus</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-proxy</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-quickstart</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-servlet</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-servlets</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-webapp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.osgi</groupId>
        <artifactId>jetty-ee-osgi-alpn</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.osgi</groupId>
        <artifactId>jetty-ee-osgi-boot</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.osgi</groupId>
        <artifactId>jetty-ee-osgi-boot-jsp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-client</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-client-webapp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-common</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-server</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jetty-client-webapp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jetty-server</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-servlet</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>flatten-clean</id>
            <goals>
              <goal>clean</goal>
            </goals>
            <phase>clean</phase>
          </execution>
          <execution>
            <id>flatten</id>
            <goals>
              <goal>flatten</goal>
            </goals>
            <phase>process-resources</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
