# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demo Jetty Webapp

[tags]
demo
webapp

[environment]
ee11

[depends]
ee11-deploy
jdbc
ee11-jsp
ee11-jstl
ee11-annotations
ext
ee11-servlets
ee11-websocket-jakarta
ee11-websocket-jetty
demo-realm
ee11-demo-rewrite

[files]
webapps/ee11-demo-jetty.d/
basehome:modules/demo.d/ee11-demo-jetty.xml|webapps/ee11-demo-jetty.xml
basehome:modules/demo.d/ee11-demo-jetty-override-web.xml|webapps/ee11-demo-jetty.d/ee11-demo-jetty-override-web.xml
maven://org.eclipse.jetty.ee11.demos/jetty-ee11-demo-jetty-webapp/${jetty.version}/war|webapps/ee11-demo-jetty.war
