# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demonstrate the rewrite module.

[environment]
ee11

[tags]
demo

[depends]
rewrite

[xml]
etc/ee11-demo-rewrite-rules.xml

[files]
basehome:modules/demo.d/ee11-demo-rewrite-rules.xml|etc/ee11-demo-rewrite-rules.xml

