# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee10

[depends]
ee10-plus
annotations

[ini]
jakarta.annotation-api.version?=@jakarta.annotation-api.version@

[files]
maven://jakarta.annotation/jakarta.annotation-api/${jakarta.annotation-api.version}/jar|lib/ee10/support/jakarta.annotation.jakarta.annotation-api-${jakarta.annotation-api.version}.jar
maven://org.eclipse.jetty.ee10/jetty-ee10-annotations/${jetty.version}/jar|lib/ee10/jetty-ee10-annotations-${jetty.version}.jar

[lib]
lib/ee10/jetty-ee10-annotations-${jetty.version}.jar
lib/ee10/support/jakarta.annotation.jakarta.annotation-api-${jakarta.annotation-api.version}.jar
