# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee10

[depend]
ee/common-annotations
ee10-plus
annotations

[lib]
lib/jetty-ee10-annotations-${jetty.version}.jar
lib/ee10-annotations/@jakarta.annotation:jakarta.annotation-api@
