# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables standard Servlet handling.

[environment]
<inherit>

[depend]
server
sessions

[lib]
lib/@jakarta.servlet:jakarta.servlet-api@
lib/jetty-ee-servlet-${jetty.version}.jar
