//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-server-logging-server]]
===== Server Logging

Jetty uses the link:http://slf4j.org/[SLF4J] API for its logging.
SLF4J is a generic abstraction layer that is supported by many different logging frameworks (or SLF4J _bindings_).

Jetty provides a default binding via the `jetty-slf4j-impl` Maven artifact, but you can plug Jetty into the logging framework (or SLF4J _binding_) xref:og-server-logging-server-custom[of your choice].

Jetty's server logging is enabled by default with the `logging` Jetty module.
You typically won't have to enable the `logging` module directly, since it is a transitive dependency of the `server` module, and thus pulled in by many of the most commonly used modules.

The `logging` module is a xref:og-modules-names[_virtual_ module] and its default implementation is provided by the `logging-jetty` Jetty module, which uses the Jetty SLF4J binding.

[[og-server-logging-server-default]]
====== Default Configuration

Jetty's default SLF4J binding uses an _appender_ (`org.eclipse.jetty.logging.StdErrAppender`) to format a logging message with metadata (like a timestamp) before sending it to `System.err`.
The default `StdErrAppender` format is:

----
<datetime>:<level>:<logger name>:<thread name>:<message>
----

where `<datetime>` is a timestamp with the format `yyyy-MM-dd HH:mm:ss.SSS`.

You can configure the appender via a file named `jetty-logging.properties`, which must be found in the xref:og-start-start-class-path[class-path].
When you enable the `logging-jetty` module -- either directly or by transitive dependency, as in the following example -- Jetty automatically generates `jetty-logging.properties` for you in `$JETTY_BASE/resources/`:

----
$ java -jar $JETTY_HOME/start.jar --add-modules=http
----

[source,subs=quotes,options=nowrap]
----
include::jetty[args="--add-module=http",highlight="(logging-jetty *transitively enabled|copy.*\.properties)"]
----

You can specify the following configuration options in `jetty-logging.properties`:

`org.eclipse.jetty.LEVEL=`<logging level>::
Sets the logging level used by Jetty globally.
You can specify any of the usual SLF4J logging levels -- `TRACE`, `DEBUG`, `INFO` (default), `WARN` and `ERROR` -- plus two additional levels: `ALL` (an alias for `TRACE`) and `OFF` (disable logging entirely).
You can also configure a default logging level for specific loggers, or arbitrary logger trees:
* `com.example.MyComponent.LEVEL=DEBUG` (sets logging level of logger `com.example.MyComponent` to `DEBUG`)
* `com.example.LEVEL=DEBUG` (sets logging level of tree `+com.example.*+` to `DEBUG`)

`org.eclipse.jetty.logging.appender.NAME_CONDENSE=`<boolean>::
Specifies whether to condense logger names, so that for example `org.eclipse.jetty.util.QueuedThreadPool` becomes `oeju.QueuedThreadPool`.
Default value is `true`.

`org.eclipse.jetty.logging.appender.MESSAGE_ALIGN=`<integer>::
Specifies the column at which the logging `<message>` should be printed.
The value `0` specifies no alignment.
Default value is `0`.

`org.eclipse.jetty.logging.appender.MESSAGE_ESCAPE=`<boolean>::
Specifies whether to escape ISO control characters such as `\r` or `\n` present in the message.
Character `\r` is replaced with `<` and character `\n` is replaced with `|`; all other ISO control characters are replaced with `?`.
Default value is `false`.

`org.eclipse.jetty.logging.appender.ZONE_ID=`<timezone id>::
Specifies the timezone ID (such as `PST`, or `America/Los_Angeles` or `GMT-8:00`) for the `<datetime>` part of the logging line.
The empty string specifies the `UTC` timezone.
Default value is the local timezone.

`com.example.STACKS=`<boolean>::
Specifies whether to hide stack traces for some arbitrary logger tree `+com.example.*+`.
Default value is `true`

`org.eclipse.jetty.logging.jmx.context=`<class name>::
Configures the JMX context name, for use when xref:og-jmx[debugging via a JMX console].

When using the Jetty SLF4J binding, the logging levels can be dynamically changed via JMX, see xref:og-troubleshooting-logging[the troubleshooting section] for more information.

[[og-server-logging-server-default-rolling]]
====== Capturing Logs to a Rolling File

Logging to `System.err` may be fine at development time, but you will typically want to capture logs on disk for later inspection, or if you don't have a terminal access (for example, if you started Jetty as a service).

The `console-capture` Jetty module allows you to capture what is written to `System.out` and `System.err` and write it to a log file.
By default, `console-capture` logs to a file in the `$JETTY_BASE/logs/` directory.

See the xref:og-module-console-capture[`console-capture` module documentation] for details on configuring how logs are written to the `log` directory.

[NOTE]
====
The `console-capture` Jetty module should be used only in conjunction with the `logging-jetty` module, as other SLF4J bindings such as LogBack or Log4j2 have their own, more sophisticated, rolling file appenders.
====

[[og-server-logging-server-custom]]
====== Custom Configuration

You can use a different SLF4J binding if you are more familiar with other logging libraries, or if you need custom logging appenders.
There are a number of out-of-the-box Jetty modules that you can use:

* `logging-logback`, to use the link:http://logback.qos.ch/[LogBack] binding
* `logging-log4j2`, to use the link:https://logging.apache.org/log4j/2.x/[Log4j2] binding
* `logging-log4j1`, to use the link:https://logging.apache.org/log4j/1.2/[Log4j1] binding (note that Log4j 1.x is end-of-life)
* `logging-jul`, to use the `java.util.logging` binding
* `logging-noop`, to use the SLF4J no-operation binding (discards all logging)

[[og-server-logging-server-custom-logback]]
====== Logging with LogBack

To enable the `logging-logback` module, run:

----
$ java -jar $JETTY_HOME/start.jar --add-modules=logging-logback,http
----

Since LogBack is released under a license that is different from Jetty's, you will be prompted to accept the LogBack license:
Once you accept the LogBack license, your `$JETTY_BASE` directory will have the following structure:

----
$JETTY_BASE
├── lib
│   └── logging
│       ├── logback-classic-<version>.jar
│       └── logback-core-<version>.jar
├── resources
│   └── logback.xml
└── start.d
    ├── http.ini
    └── logging-logback.ini
----

Jetty downloaded the required LogBack `+*.jar+` files, and created a `$JETTY_BASE/resources/logback.xml` file for configuring your LogBack logging.
Please refer to the link:http://logback.qos.ch/manual/configuration.html[LogBack configuration manual] for more information about how to configure LogBack.

[[og-server-logging-server-custom-log4j2]]
====== Logging with Log4j2

To enable the `logging-log4j2` module, run:

----
$ java -jar $JETTY_HOME/start.jar --add-modules=logging-log4j2,http
----

After accepting the Log4j2 license, you will have the following directory structure:

----
$JETTY_BASE
├── lib
│   └── logging
│       ├── log4j-api-<version>.jar
│       ├── log4j-core-<version>.jar
│       └── log4j-slf4j2-impl-<version>.jar
├── resources
│   └── log4j2.xml
└── start.d
    ├── http.ini
    └── logging-log4j2.ini
----

Jetty downloaded the required Log4j2 `+*.jar+` files, and created a `$JETTY_BASE/resources/log4j2.xml` file that you can configure to customize your Log4j2 logging.

Please refer to the link:https://logging.apache.org/log4j/2.x/manual/configuration.html[Log4j2 configuration manual] for more information about how to configure Log4j2.

[[og-server-logging-server-bridges]]
====== Bridging Logging to SLF4J

When you use libraries that provide the features you need (for example, JDBC drivers), it may be possible that those libraries use a different logging framework than SLF4J.

SLF4J provides link:http://www.slf4j.org/legacy.html[bridges for legacy logging APIs] that allows you to bridge logging from one of these legacy logging frameworks to SLF4J.
Once the logging is bridged to SLF4J, you can use Jetty's xref:og-server-logging-server-default[default configuration] or a xref:og-server-logging-server-custom[custom configuration] so that your logging is centralized in one place.

Jetty provides several modules out of the box for bridging older logging frameworks to SLF4J:

* `logging-jul-capture` for bridging from `java.util.logging`
* `logging-jcl-capture` for bridging from Jakarta Commons Logging (JCL)
* `logging-log4j1-capture` for bridging from Apache Log4j

[[og-server-logging-server-bridge-jul]]
====== Bridging from `java.util.logging`

For libraries that use `java.util.logging` as their logging framework, you can enable Jetty's `logging-jul-capture` module:

----
$ java -jar $JETTY_HOME/start.jar --add-modules=logging-jul-capture
----

The `logging-jul-capture` module implies `--exec` and therefore xref:og-start-start[spawns a second JVM] because it needs to provide the system property `java.util.logging.config.file` (so that `java.util.logging` can read the configuration from the specified file), and because it needs to make available on the System ClassLoader the class `org.slf4j.bridge.SLF4JBridgeHandler`.

For example, a library that uses `java.util.logging` as its logging library is the Postgresql JDBC driver.
With the `logging-jul-capture` Jetty module, the logging follows this diagram:

[plantuml]
----
skinparam backgroundColor transparent
skinparam monochrome true
skinparam shadowing false

participant "Postgresql JDBC" as postgresql
participant java.util.logging
participant SLF4JBridgeHandler
participant Jetty
participant SLF4J
participant "Jetty SLF4J Binding" as binding


postgresql -> java.util.logging
java.util.logging -> SLF4JBridgeHandler
SLF4JBridgeHandler -> SLF4J
SLF4J -> binding
Jetty -> SLF4J
SLF4J -> binding
----

Note how Jetty logs directly to SLF4J, while the Postgresql JDBC driver logs to SLF4J through the `SLF4JBridgeHandler`.
They both arrive to the SLF4J binding, in this case the Jetty SLF4J binding (but could be any other SLF4J binding such as LogBack).

// TODO: add the other bridges
