# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Puts lib/ee11/ext jars on the ee11 classpath.

[tags]
classpath

[environment]
ee11

[lib]
lib/ee11/ext/**.jar

[files]
lib/
lib/ee11/
lib/ee11/ext/
