# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JSP for all web applications deployed on the server.

[environment]
ee11

[depend]
ee11-servlet
ee11-annotations
ee11-apache-jsp
