# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the Jetty Quickstart module for rapid deployment of preconfigured web applications.

[environment]
ee9

[depends]
server
ee9-annotations
ee9-webapp
ee9-plus

[xml]
etc/jetty-ee9-quickstart.xml

[files]
maven://org.eclipse.jetty.ee9/jetty-ee9-quickstart/${jetty.version}/jar|lib/ee9/jetty-ee9-quickstart-${jetty.version}.jar

[lib]
lib/ee9/jetty-ee9-quickstart-${jetty.version}.jar

[ini-template]

# Modes are AUTO, GENERATE, QUICKSTART
# jetty.quickstart.mode=AUTO
# jetty.quickstart.origin=origin
# jetty.quickstart.xml=
