# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demonstrate the rewrite module.

[tags]
demo

[depends]
rewrite

[xml]
etc/demo-rewrite-rules.xml

[files]
basehome:modules/demo.d/demo-rewrite-rules.xml|etc/demo-rewrite-rules.xml

