# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demonstrate a Moved Context Handler.

[tags]
demo

[depends]
deploy

[files]
basehome:modules/demo.d/demo-moved-context.xml|webapps/demo-moved-context.xml

