<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.ee</groupId>
    <artifactId>jetty-ee</artifactId>
    <version>13.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>jetty-ee-common</artifactId>
  <name>EE :: Common</name>
  <description>Jetty EE Common Artifact</description>

  <properties>
    <bundle-symbolic-name>${project.groupId}.common</bundle-symbolic-name>
    <spotbugs.onlyAnalyze>org.eclipse.jetty.ee.common.*</spotbugs.onlyAnalyze>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-slf4j-impl</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.tests</groupId>
      <artifactId>jetty-test-multipart</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <DynamicImport-Package>jakarta.servlet,jakarta.servlet.*</DynamicImport-Package>
          </instructions>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>@{argLine} ${jetty.surefire.argLine} --add-reads org.eclipse.jetty.ee.common=org.eclipse.jetty.logging</argLine>
          <excludes>
            <!-- This class modifies internal JVM statics, and causes problems in parallel testing -->
            <exclude>org.eclipse.jetty.ee.common.WebAppClassLoaderUrlStreamTest</exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
