# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JASPI authentication for deployed web applications.

[environment]
ee

[tags]
security

[depend]
ee-security
auth-config-factory

[lib]
lib/jetty-ee-jaspi-${jetty.version}.jar
lib/ee-jaspi/@jakarta.authentication:jakarta.authentication-api@

[xml]
etc/jaspi/jetty-ee-jaspi-authmoduleconfig.xml

[files]
basehome:etc/jaspi/jetty-ee-jaspi-authmoduleconfig.xml|etc/jaspi/jetty-ee-jaspi-authmoduleconfig.xml

