# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JASPI basic authentication the /test context path.

[environment]
ee

[tags]
security

[depend]
jaspi

[xml]
etc/jaspi/jetty-ee-jaspi-demo.xml

[files]
basehome:etc/jaspi/jetty-ee-jaspi-demo.xml|etc/jaspi/jetty-ee-jaspi-demo.xml
