# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo EE10 JAAS webapp

[environment]
ee10

[tags]
demo
webapp

[depends]
demo-jaas
ee10-deploy
jaas
jdbc
ee10-jsp
ee10-annotations
ext

[files]
basehome:modules/demo.d/ee10-demo-jaas.xml|webapps/ee10-demo-jaas.xml
basehome:modules/demo.d/ee10-demo-jaas.properties|webapps/ee10-demo-jaas.properties
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-jaas-webapp/${jetty.version}/war|webapps/ee10-demo-jaas.war

