# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demo EE11 JAAS webapp

[environment]
ee11

[tags]
demo
webapp

[depends]
demo-jaas
ee11-deploy
jaas
jdbc
ee11-jsp
ee11-annotations
ext

[files]
basehome:modules/demo.d/ee11-demo-jaas.xml|webapps/ee11-demo-jaas.xml
maven://org.eclipse.jetty.demos/jetty-servlet5-demo-jaas-webapp/${jetty.version}/war|webapps/ee11-demo-jaas.war
