# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Configures Jetty to use the "CdiSpiDecorator" as the default CDI mode.
This mode uses the CDI SPI to integrate an arbitrary CDI implementation.

[environment]
<inherit>

[tag]
cdi

[provides]
cdi-mode

[depend]
ee-cdi

[ini]
jetty.cdi.mode=CdiSpiDecorator
