# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Proxy Webapp

[environment]
ee10

[tags]
demo
webapp

[depends]
ee10-deploy

[files]
basehome:modules/demo.d/ee10-demo-proxy.properties|webapps/ee10-demo-proxy.properties
maven://org.eclipse.jetty.ee10.demos/jetty-ee10-demo-proxy-webapp/${jetty.version}/war|webapps/ee10-demo-proxy.war
