# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Download and deploy the Test Spec webapp demo.

[environment]
ee11

[tags]
demo
webapp

[depends]
deploy
jdbc
ee11-jsp
ee11-annotations
ext
demo-realm
ee11-demo-mock-resources

[files]
basehome:modules/demo.d/ee11-demo-spec.xml|webapps/ee11-demo-spec.xml
maven://org.eclipse.jetty.ee11.demos/jetty-ee11-demo-spec-webapp/${jetty.version}/war|webapps/ee11-demo-spec.war
