# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Configures Jetty to use the "CdiDecoratingListener" as the default CDI mode.
This mode that allows a webapp to register it's own CDI decorator.

[environment]
<inherit>

[tag]
cdi

[provides]
cdi-mode

[depend]
ee/common-cdi

[ini]
jetty.cdi.mode=CdiDecoratingListener
