<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-project</artifactId>
    <version>13.0.0-SNAPSHOT</version>
  </parent>
  <groupId>org.eclipse.jetty.ee</groupId>
  <artifactId>jetty-ee</artifactId>
  <packaging>pom</packaging>
  <name>EECommon</name>

  <modules>
    <module>jetty-ee-annotations</module>
    <module>jetty-ee-apache-jsp</module>
    <module>jetty-ee-bom</module>
    <module>jetty-ee-cdi</module>
    <module>jetty-ee-common</module>
    <module>jetty-ee-demos</module>
    <module>jetty-ee-fcgi-proxy</module>
    <module>jetty-ee-glassfish-jstl</module>
    <module>jetty-ee-home</module>
    <module>jetty-ee-jaspi</module>
    <module>jetty-ee-jndi</module>
    <module>jetty-ee-jspc-maven-plugin</module>
    <module>jetty-ee-maven-plugin</module>
    <module>jetty-ee-osgi</module>
    <module>jetty-ee-plus</module>
    <module>jetty-ee-proxy</module>
    <module>jetty-ee-quickstart</module>
    <module>jetty-ee-servlet</module>
    <module>jetty-ee-servlets</module>
    <module>jetty-ee-test-resources</module>
    <module>jetty-ee-tests</module>
    <module>jetty-ee-webapp</module>
    <module>jetty-ee-websocket</module>
  </modules>

  <properties>

    <ee.jakarta.activation.api.version>2.1.3</ee.jakarta.activation.api.version>
    <ee.jakarta.mail.api.version>2.1.3</ee.jakarta.mail.api.version>
    <ee.jakarta.servlet.api.version>6.1.0</ee.jakarta.servlet.api.version>
    <ee.jakarta.servlet.jsp.api.version>4.0.0</ee.jakarta.servlet.jsp.api.version>
    <ee.jakarta.servlet.jsp.jstl.impl.version>4.0.0</ee.jakarta.servlet.jsp.jstl.impl.version>
    <ee.jakarta.xml.bind.api.version>4.0.5</ee.jakarta.xml.bind.api.version>
    <ee.jakarta.xml.bind.impl.version>4.0.7</ee.jakarta.xml.bind.impl.version>
    <ee.jakarta.xml.jaxws.impl.version>4.0.2</ee.jakarta.xml.jaxws.impl.version>
    <ee.jersey.version>4.0.2</ee.jersey.version>
    <ee.jsp.impl.version>11.0.10.1</ee.jsp.impl.version>
    <ee.mail.impl.version>2.0.2</ee.mail.impl.version>
    <ee.weld.version>6.0.4.Final</ee.weld.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>jakarta.platform</groupId>
        <artifactId>jakarta.jakartaee-bom</artifactId>
        <version>${ee.jakarta.bom.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.sun.mail</groupId>
        <artifactId>jakarta.mail</artifactId>
        <version>${ee.mail.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>com.sun.xml.ws</groupId>
        <artifactId>jaxws-rt</artifactId>
        <version>{ee.jakarta.xml.jaxws.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.xml.bind</groupId>
        <artifactId>jakarta.xml.bind-api</artifactId>
        <version>${ee.jakarta.xml.bind.api.version}</version>
      </dependency>
      <!-- Jetty EECommon Dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-annotations</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-apache-jsp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-cdi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-fcgi-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-glassfish-jstl</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-jaspi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-jndi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-jspc-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-plus</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-quickstart</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-servlets</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-test-resources</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.demos</groupId>
        <artifactId>jetty-ee-demo-proxy-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jakarta-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jetty-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-jetty-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee.websocket</groupId>
        <artifactId>jetty-ee-websocket-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>${ee.jakarta.xml.bind.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.containers</groupId>
        <artifactId>jersey-container-servlet</artifactId>
        <version>${ee.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.inject</groupId>
        <artifactId>jersey-hk2</artifactId>
        <version>${ee.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.media</groupId>
        <artifactId>jersey-media-json-binding</artifactId>
        <version>${ee.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.wasp</groupId>
        <artifactId>wasp</artifactId>
        <version>${ee.jakarta.servlet.jsp.jstl.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.weld.servlet</groupId>
        <artifactId>weld-servlet-core</artifactId>
        <version>${ee.weld.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-el</artifactId>
        <version>${ee.jsp.impl.version}</version>
      </dependency>
      <!-- Jakarta EECommon Dependencies -->
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-jsp</artifactId>
        <version>${ee.jsp.impl.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
