# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables the MSIE rewrite rule for MSIE 5 and 6 known bugs.

[depend]
rewrite

[files]
basehome:modules/rewrite/rewrite-msie.xml|etc/rewrite-msie.xml

[xml]
etc/rewrite-msie.xml
