# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Enables JASPI basic authentication the /test context path.

[tags]
security

[depend]
jaspi

[xml]
etc/jaspi/jaspi-demo.xml

[files]
basehome:etc/jaspi/jaspi-demo.xml|etc/jaspi/jaspi-demo.xml
