# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Provides a DefaultAuthConfigFactory for jaspi

[tags]
security

[depend]
security

[provide]
auth-config-factory

[xml]
etc/jaspi/jaspi-default.xml
