# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demonstrate the rewrite module.

[environment]
ee8

[tags]
demo

[depends]
rewrite

[xml]
etc/ee8-demo-rewrite-rules.xml

[files]
basehome:modules/demo.d/ee8-demo-rewrite-rules.xml|etc/ee8-demo-rewrite-rules.xml

