# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demonstrate a Moved Context Handler.

[environment]
ee8

[tags]
demo

[depends]
ee8-deploy

[files]
basehome:modules/demo.d/ee8-demo-moved-context.xml|webapps/ee8-demo-moved-context.xml

