<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.eclipse.jetty.ee12</groupId>
    <artifactId>jetty-ee12</artifactId>
    <version>13.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>jetty-ee12-bom</artifactId>
  <packaging>pom</packaging>
  <name>EE12 :: BOM</name>
  <description>Jetty EE12 APIs BOM artifact</description>

  <dependencyManagement>
    <dependencies>
      <!-- Jetty EE12 Dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-annotations</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-apache-jsp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-cdi</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-fcgi-proxy</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-glassfish-jstl</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-jaspi</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-jndi</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-jspc-maven-plugin</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-maven-plugin</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-plus</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-proxy</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-quickstart</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-servlet</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-servlets</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-webapp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.osgi</groupId>
        <artifactId>jetty-ee12-osgi-alpn</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.osgi</groupId>
        <artifactId>jetty-ee12-osgi-boot</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.osgi</groupId>
        <artifactId>jetty-ee12-osgi-boot-jsp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-client</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-client-webapp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-common</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-server</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jetty-client-webapp</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jetty-server</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-servlet</artifactId>
        <version>13.0.0-SNAPSHOT</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>flatten-clean</id>
            <goals>
              <goal>clean</goal>
            </goals>
            <phase>clean</phase>
          </execution>
          <execution>
            <id>flatten</id>
            <goals>
              <goal>flatten</goal>
            </goals>
            <phase>process-resources</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
