# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Servlet resource injection. 

[environment]
ee11

[depends]
server
jndi
plus
ee11-security
ee11-webapp

[files]
maven://jakarta.enterprise/jakarta.enterprise.cdi-api/4.1.0/jar|lib/ee11/support/jakarta.enterprise.jakarta.enterprise.cdi-api-4.1.0.jar
maven://jakarta.enterprise/jakarta.enterprise.lang-model/4.1.0/jar|lib/ee11/support/jakarta.enterprise.jakarta.enterprise.lang-model-4.1.0.jar
maven://jakarta.inject/jakarta.inject-api/2.0.1/jar|lib/ee11/support/jakarta.inject.jakarta.inject-api-2.0.1.jar
maven://jakarta.interceptor/jakarta.interceptor-api/2.2.0/jar|lib/ee11/support/jakarta.interceptor.jakarta.interceptor-api-2.2.0.jar
maven://jakarta.transaction/jakarta.transaction-api/2.0.1/jar|lib/ee11/support/jakarta.transaction.jakarta.transaction-api-2.0.1.jar
maven://org.eclipse.jetty.ee11/jetty-ee11-plus/${jetty.version}/jar|lib/ee11/jetty-ee11-plus-${jetty.version}.jar

[lib]
lib/ee11/jetty-ee11-plus-${jetty.version}.jar
lib/ee11/support/jakarta.enterprise.jakarta.enterprise.cdi-api-4.1.0.jar
lib/ee11/support/jakarta.enterprise.jakarta.enterprise.lang-model-4.1.0.jar
lib/ee11/support/jakarta.inject.jakarta.inject-api-2.0.1.jar
lib/ee11/support/jakarta.interceptor.jakarta.interceptor-api-2.2.0.jar
lib/ee11/support/jakarta.transaction.jakarta.transaction-api-2.0.1.jar
