# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the Jetty Quickstart module for rapid deployment of preconfigured web applications.

[environment]
ee8

[depends]
server
ee8-annotations
ee8-webapp
ee8-plus

[xml]
etc/jetty-ee8-quickstart.xml

[files]
maven://org.eclipse.jetty.ee8/jetty-ee8-quickstart/${project.version}/jar|lib/ee8/jetty-ee8-quickstart-${project.version}.jar

[lib]
lib/ee8/jetty-ee8-quickstart-${project.version}.jar

[ini-template]

# Modes are AUTO, GENERATE, QUICKSTART
# jetty.quickstart.mode=AUTO
# jetty.quickstart.origin=origin
# jetty.quickstart.xml=
