# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Provides a DefaultAuthConfigFactory for jaspi

[environment]
ee10

[tags]
security

[depend]
ee10-security

[provide]
auth-config-factory

[xml]
etc/jaspi/jetty-ee10-jaspi-default.xml
