# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JASPI authentication for deployed web applications.

[environment]
ee10

[tags]
security

[depends]
ee10-security
auth-config-factory

[xml]
etc/jaspi/jetty-ee10-jaspi-authmoduleconfig.xml

[ini]
jakarta.authentication-api.version?=@jakarta.authentication-api.version@

[files]
basehome:etc/jaspi/jetty-ee10-jaspi-authmoduleconfig.xml|etc/jaspi/jetty-ee10-jaspi-authmoduleconfig.xml
maven://jakarta.authentication/jakarta.authentication-api/${jakarta.authentication-api.version}/jar|lib/ee10/support/jakarta.authentication.jakarta.authentication-api-${jakarta.authentication-api.version}.jar
maven://org.eclipse.jetty.ee10/jetty-ee10-jaspi/${jetty.version}/jar|lib/ee10/jetty-ee10-jaspi-${jetty.version}.jar

[lib]
lib/ee10/jetty-ee10-jaspi-${jetty.version}.jar
lib/ee10/support/jakarta.authentication.jakarta.authentication-api-${jakarta.authentication-api.version}.jar
