# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables JASPI basic authentication the /test context path.

[environment]
ee10

[tags]
security

[depend]
jaspi

[xml]
etc/jaspi/jetty-ee10-jaspi-demo.xml

[files]
basehome:etc/jaspi/jetty-ee10-jaspi-demo.xml|etc/jaspi/jetty-ee10-jaspi-demo.xml
