# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
A meta module to enable all core demo modules.

[environment]
core

[tags]
demo

[depends]
http
https
http2
test-keystore
work
demo-root
demo-moved-context
core-environment
