# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables JSTL for all web applications deployed on the server.

[environment]
ee10

[depend]
ee10-jsp
ee10-glassfish-jstl
