# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
A meta module to enable all EE11 demo modules.

[environment]
ee11

[tags]
demo

[depends]
http
https
http2
test-keystore
work
demo-root
ee11-environment
ee11-demo-async-rest
ee11-demo-jaas
ee11-demo-jetty
ee11-demo-proxy
ee11-demo-rewrite
ee11-demo-jndi
ee11-demo-spec
ee11-demo-spec-6-1
ee11-demo-jsp
ee11-demo-jspc

[ini-template]
# Websocket chat examples needs websocket enabled
# Don't start for all contexts (set to true in test.xml context)
org.eclipse.jetty.websocket.jsr356=false
