# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables JSTL for all web applications deployed on the server.

[environment]
ee9

[depend]
ee9-jsp
ee9-glassfish-jstl
