# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Enables JSP for all web applications deployed on the server.

[depend]
servlet
annotations
apache-jsp

