# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Enables JSTL for all web applications deployed on the server.

[depend]
jsp
apache-jstl

