# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Enables JSTL for all web applications deployed on the server.

[depend]
jsp
apache-jstl

