# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Configures Jetty logging to use SLF4J No-Op Implementation.

[tags]
logging

[provides]
logging

[depends]
logging/slf4j
