# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
This module causes Jetty to stop immediately after starting.
This is good for testing configuration and/or precompiling quickstart webapps

[xml]
etc/jetty-stop.xml
