# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds Sign-In with Ethereum (SIWE) authentication to the server.

[depend]
security

[lib]
lib/jetty-siwe-${jetty.version}.jar