# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables GCloud Datastore API and implementation.

[tags]
3rdparty
gcloud

[depends]
gcloud
logging-jcl-capture
logging-jul-capture

