<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.ee.osgi</groupId>
    <artifactId>jetty-ee-osgi</artifactId>
    <version>13.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>jetty-ee-osgi-boot-jsp</artifactId>
  <name>EE :: OSGi :: Boot JSP</name>
  <description>Jetty OSGi Boot JSP bundle</description>
  <properties>
    <bundle-symbolic-name>${project.groupId}.boot.jsp</bundle-symbolic-name>
    <spotbugs.onlyAnalyze>org.eclipse.jetty.ee.osgi.boot.jsp.*</spotbugs.onlyAnalyze>
  </properties>
  <dependencies>
    <!-- Servlet Deps -->
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-deploy</artifactId>
    </dependency>
    <!-- JSP Deps -->
    <dependency>
      <groupId>org.eclipse.jetty.ee</groupId>
      <artifactId>jetty-ee-apache-jsp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.platform</groupId>
      <artifactId>org.eclipse.osgi</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.platform</groupId>
      <artifactId>org.eclipse.osgi.services</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee.osgi</groupId>
      <artifactId>jetty-ee-osgi-boot</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>

      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Bundle-Name>Jetty-OSGi-Jasper Integration</Bundle-Name>
            <Bundle-Classpath/>
            <Fragment-Host>org.eclipse.jetty.ee.osgi.boot</Fragment-Host>
            <Import-Package>!jakarta.*,!org.apache.*,!org.glassfish.*,${osgi.slf4j.import.packages},
              org.eclipse.jdt.*;resolution:=optional,
              org.eclipse.jdt.core.compiler.*;resolution:=optional,
              com.sun.el;resolution:=optional,
              com.sun.el.lang;resolution:=optional,
              com.sun.el.parser;resolution:=optional,
              com.sun.el.util;resolution:=optional,
              org.eclipse.jetty.ee.jsp;version="[$(version;===;${parsedVersion.osgiVersion}),$(version;==+;${parsedVersion.osgiVersion}))";resolution:=optional,
              org.osgi.*,
              org.xml.*;resolution:=optional,
              org.xml.sax.*;resolution:=optional,
              javax.xml.*;resolution:=optional,
              org.w3c.dom;resolution:=optional,
              org.w3c.dom.ls;resolution:=optional,
              javax.xml.parser;resolution:=optional</Import-Package>
            <DynamicImport-Package>org.eclipse.jetty.ee.jsp.*;version="[$(version;===;${parsedVersion.osgiVersion}),$(version;==+;${parsedVersion.osgiVersion}))",
                org.apache.jasper,
                org.apache.jasper.*,
                org.apache.el,
                org.apache.el.*,
                org.apache.tomcat,
                org.apache.tomcat.*,
                org.apache.taglibs.*,
                org.glassfish.wasp.*,
                jakarta.*</DynamicImport-Package>
            <_noee>true</_noee>
          </instructions>
        </configuration>
      </plugin>
      <!-- necessary because 10.0.0-M5 is not a valid osgi version -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>set-jsp-api-version</id>
            <goals>
              <goal>parse-version</goal>
            </goals>
            <phase>validate</phase>
            <configuration>
              <versionString>${ee.jakarta.servlet.jsp.api.version}</versionString>
              <propertyPrefix>jspApi</propertyPrefix>
            </configuration>
          </execution>
          <execution>
            <id>set-jsp-impl-version</id>
            <goals>
              <goal>parse-version</goal>
            </goals>
            <phase>validate</phase>
            <configuration>
              <versionString>${ee.jsp.impl.version}</versionString>
              <propertyPrefix>jspImpl</propertyPrefix>
            </configuration>
          </execution>
          <execution>
            <id>set-servlet-api-version</id>
            <goals>
              <goal>parse-version</goal>
            </goals>
            <phase>validate</phase>
            <configuration>
              <versionString>${ee.jakarta.servlet.api.version}</versionString>
              <propertyPrefix>servletApi</propertyPrefix>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
