//
// ========================================================================
// Copyright (c) 1995-2020 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under
// the terms of the Eclipse Public License 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0
//
// This Source Code may also be made available under the following
// Secondary Licenses when the conditions for such availability set
// forth in the Eclipse Public License, v. 2.0 are satisfied:
// the Apache License v2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[jetty-dump-tool]]
=== Jetty Dump Tool

The dump feature in Jetty provides a good snapshot of the status of the threadpool, select sets, classloaders, and so forth.
To get maximum detail from the dump, you need to `setDetailDump(true)` on any `QueuedThreadPools` you are using.
You can do this by a direct call if you are embedding Jetty, or in `jetty.xml`.

[[configuring-dump-feature]]
==== Configuring the Dump Feature in jetty.xml

You can request that Jetty do a dump immediately after starting and just before stopping by calling the appropriate setters on the `Server` instance. 
This can be accomplished in `jetty.xml` with:

[source, xml, subs="{sub-order}"]
----
<Set name="dumpAfterStart">true</Set>
<Set name="dumpBeforeStop">true</Set>
----

[[extra-threadpool-info]]
==== Extra ThreadPool Information

You can get additional detail from the `QueuedThreadPool` if `setDetailedDump(true)` is called on the thread pool instance. 
Do this in `jetty.xml` as follows:

[source, xml, subs="{sub-order}"]
----
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <!-- ==================================== -->
  <!-- Server Thread Pool                   --> 
  <!-- ==================================== -->
  <Set name="ThreadPool">
     <!-- Default queued blocking threadpool -->
     <New class="org.eclipse.jetty.util.thread.QueuedThreadPool">
       <Set name="minThreads">10</Set>
       <Set name="maxThreads">200</Set>
       <Set name="detailedDump">true</Set>
     </New>
  </Set>
----

[[dump-tool-via-jmx]]
==== Using the Dump Feature via JMX

The `dump` method is on the Server instance and many of its nested components (Handlers, Connectors, and so forth). 
Dumps may be obtained by calling these methods either in code or via JMX (see xref:using-jmx[]).

The Server MBean has a `dump()` method, which dumps everything, plus a `dumpStdErr()` operation that dumps to StdErr rather than replying to JConsole.

[[examing-jetty-dump]]
==== Examining a Jetty Dump

This is a dump of the stock jetty-home with demo modules enabled and extra threadpool information:

....
Server@5ace1ed4{STARTING}[{VERSION},sto=5000] - STARTING
+= QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  += ReservedThreadExecutor@6a4d7f76{s=0/20,p=0} - STARTED
|  +> threads size=33
|     +> qtp815992954-63-acceptor-3@39a862d4-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} WAITING tid=63 prio=3 ACCEPTING
|     +> qtp815992954-35 RUNNABLE tid=35 prio=5 SELECTING
|     +> qtp815992954-53 RUNNABLE tid=53 prio=5 SELECTING
|     +> qtp815992954-54 RUNNABLE tid=54 prio=5 SELECTING
|     +> qtp815992954-62-acceptor-2@33edc3bc-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} WAITING tid=62 prio=3 ACCEPTING
|     +> qtp815992954-27 RUNNABLE tid=27 prio=5 SELECTING
|     +> qtp815992954-60-acceptor-0@4c1bfff-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} RUNNABLE tid=60 prio=3 ACCEPTING
|     +> qtp815992954-47-acceptor-3@fdf2136-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443} WAITING tid=47 prio=3 ACCEPTING
|     +> qtp815992954-56 RUNNABLE tid=56 prio=5 SELECTING
|     +> qtp815992954-31 RUNNABLE tid=31 prio=5 SELECTING
|     +> qtp815992954-40 RUNNABLE tid=40 prio=5 SELECTING
|     +> qtp815992954-29 RUNNABLE tid=29 prio=5 SELECTING
|     +> qtp815992954-46-acceptor-2@81dc61a-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443} WAITING tid=46 prio=3 ACCEPTING
|     +> qtp815992954-30 RUNNABLE tid=30 prio=5 SELECTING
|     +> qtp815992954-32 RUNNABLE tid=32 prio=5 SELECTING
|     +> qtp815992954-51 RUNNABLE tid=51 prio=5 SELECTING
|     +> qtp815992954-43 RUNNABLE tid=43 prio=5 SELECTING
|     +> qtp815992954-58 RUNNABLE tid=58 prio=5 SELECTING
|     +> qtp815992954-33 RUNNABLE tid=33 prio=5 SELECTING
|     +> qtp815992954-59 RUNNABLE tid=59 prio=5 SELECTING
|     +> qtp815992954-50 RUNNABLE tid=50 prio=5 SELECTING
|     +> qtp815992954-57 RUNNABLE tid=57 prio=5 SELECTING
|     +> qtp815992954-61-acceptor-1@41da2368-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} WAITING tid=61 prio=3 ACCEPTING
|     +> qtp815992954-45-acceptor-1@ed6bace-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443} WAITING tid=45 prio=3 ACCEPTING
|     +> qtp815992954-49 RUNNABLE tid=49 prio=5 SELECTING
|     +> qtp815992954-28 RUNNABLE tid=28 prio=5 SELECTING
|     +> qtp815992954-55 RUNNABLE tid=55 prio=5 SELECTING
|     +> qtp815992954-44-acceptor-0@3fc2660d-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443} RUNNABLE tid=44 prio=3 ACCEPTING
|     +> qtp815992954-34 RUNNABLE tid=34 prio=5 SELECTING
|     +> qtp815992954-36 RUNNABLE tid=36 prio=5 SELECTING
|     +> qtp815992954-39 RUNNABLE tid=39 prio=5 SELECTING
|     +> qtp815992954-52 RUNNABLE tid=52 prio=5 SELECTING
|     +> qtp815992954-48 RUNNABLE tid=48 prio=5 SELECTING
+- org.eclipse.jetty.io.ArrayByteBufferPool@10ec523c
+= ScheduledExecutorScheduler@de3a06f{STARTED} - STARTED
|  +> java.base@15.0.1/jdk.internal.misc.Unsafe.park(Native Method)
|  +> java.base@15.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
|  +> java.base@15.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1661)
|  +> java.base@15.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
|  +> java.base@15.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
|  +> java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056)
|  +> java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116)
|  +> java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
|  +> java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
+= ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443} - STARTED
|  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  +~ ScheduledExecutorScheduler@de3a06f{STARTED} - STARTED
|  +- org.eclipse.jetty.io.ArrayByteBufferPool@10ec523c
|  +- org.eclipse.jetty.server.AbstractConnector$1@53dfacba
|  += SelectorManager@ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443} - STARTED
|  |  += ManagedSelector@245a060f{STARTED} id=0 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@6edaa77a/SelectorProducer@1e63d216/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.092562342-06:00 - STARTED
|  |  |  |  +- SelectorProducer@1e63d216
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.090612448-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.091676614-06:00 size=0
|  |  += ManagedSelector@62ddd21b{STARTED} id=1 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@16c3ca31/SelectorProducer@2d195ee4/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.094644326-06:00 - STARTED
|  |  |  |  +- SelectorProducer@2d195ee4
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.093781421-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.093968576-06:00 size=0
|  |  += ManagedSelector@2d6aca33{STARTED} id=2 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@21ab988f/SelectorProducer@29314cc9/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.095922056-06:00 - STARTED
|  |  |  |  +- SelectorProducer@29314cc9
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.095197674-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.095368267-06:00 size=0
|  |  += ManagedSelector@4e38d975{STARTED} id=3 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@35f8a9d3/SelectorProducer@48ea2003/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.097448317-06:00 - STARTED
|  |  |  |  +- SelectorProducer@48ea2003
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.096753862-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.096926579-06:00 size=0
|  |  += ManagedSelector@6b1e7ad3{STARTED} id=4 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@63e5e5b4/SelectorProducer@13a37e2a/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.099117048-06:00 - STARTED
|  |  |  |  +- SelectorProducer@13a37e2a
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.097936953-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.0981201-06:00 size=0
|  |  += ManagedSelector@a50ae65{STARTED} id=5 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@1280851e/SelectorProducer@5e840abf/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.100359692-06:00 - STARTED
|  |  |  |  +- SelectorProducer@5e840abf
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.09962457-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.099770186-06:00 size=0
|  |  += ManagedSelector@56de6d6b{STARTED} id=6 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@5972d253/SelectorProducer@4fcc0416/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.10179457-06:00 - STARTED
|  |  |  |  +- SelectorProducer@4fcc0416
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.100872464-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.101051042-06:00 size=0
|  |  += ManagedSelector@31e32ea2{STARTED} id=7 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@1473b8c0/SelectorProducer@5b5c0057/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.10296641-06:00 - STARTED
|  |  |  |  +- SelectorProducer@5b5c0057
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.102380751-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.102503072-06:00 size=0
|  |  += ManagedSelector@749f539e{STARTED} id=8 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@5ca1f591/SelectorProducer@551de37d/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.104231086-06:00 - STARTED
|  |  |  |  +- SelectorProducer@551de37d
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.103405772-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.10356803-06:00 size=0
|  |  += ManagedSelector@6ef81f31{STARTED} id=9 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@6075b2d3/SelectorProducer@33abde31/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.105263922-06:00 - STARTED
|  |  |  |  +- SelectorProducer@33abde31
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.10468728-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.104805794-06:00 size=0
|  |  += ManagedSelector@997d532{STARTED} id=10 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@273842a6/SelectorProducer@6a969fb8/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.107084882-06:00 - STARTED
|  |  |  |  +- SelectorProducer@6a969fb8
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.106301468-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.106493542-06:00 size=0
|  |  += ManagedSelector@7a18e8d{STARTED} id=11 keys=0 selected=0 updates=0 - STARTED
|  |     += EatWhatYouKill@3028e50e/SelectorProducer@5560bcdf/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.108228108-06:00 - STARTED
|  |     |  +- SelectorProducer@5560bcdf
|  |     |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |     +> updates @ 2020-12-02T10:49:32.107542699-06:00 size=0
|  |     +> keys @ 2020-12-02T10:49:32.10776994-06:00 size=0
|  += SslConnectionFactory@4b14c583{SSL->alpn} - STARTED
|  |  +~ Server@3a7442c7[provider=null,keyStore=file:///home/user/my-base/etc/test-keystore.p12,trustStore=file:///home/user/my-base/etc/test-keystore.p12] - STARTED
|  += ALPNServerConnectionFactory@4c9f8c13{[alpn],null,[]} - STARTED
|  += HTTP2ServerConnectionFactory@41e1e210[h2] - STARTED
|  |  +- HTTP2SessionContainer@b558294[size=0]
|  |  |  +> java.util.concurrent.ConcurrentHashMap$KeySetView@0(size=0)
|  |  +- HttpConfiguration@5b3f3ba0{32768/8192,8192/8192,https://:0,[SecureRequestCustomizer@4bdc8b5d]}
|  |     +> customizers size=1
|  |     |  +> SecureRequestCustomizer@4bdc8b5d
|  |     +> formEncodedMethods size=2
|  |     |  +> POST
|  |     |  +> PUT
|  |     +> outputBufferSize=32768
|  |     +> outputAggregationSize=8192
|  |     +> requestHeaderSize=8192
|  |     +> responseHeaderSize=8192
|  |     +> headerCacheSize=1024
|  |     +> secureScheme=https
|  |     +> securePort=0
|  |     +> idleTimeout=-1
|  |     +> sendDateHeader=true
|  |     +> sendServerVersion=true
|  |     +> sendXPoweredBy=false
|  |     +> delayDispatchUntilContent=true
|  |     +> persistentConnectionsEnabled=true
|  |     +> maxErrorDispatches=10
|  |     +> minRequestDataRate=0
|  |     +> minResponseDataRate=0
|  |     +> requestCookieCompliance=org.eclipse.jetty.http.CookieCompliance@5d1e09bc
|  |     +> responseCookieCompliance=org.eclipse.jetty.http.CookieCompliance@5d1e09bc
|  |     +> notifyRemoteAsyncErrors=true
|  |     +> relativeRedirectAllowed=false
|  += HttpConnectionFactory@120f102b[HTTP/1.1] - STARTED
|  |  +- HttpConfiguration@5b3f3ba0{32768/8192,8192/8192,https://:0,[SecureRequestCustomizer@4bdc8b5d]}
|  |     +> customizers size=1
|  |     |  +> SecureRequestCustomizer@4bdc8b5d
|  |     +> formEncodedMethods size=2
|  |     |  +> POST
|  |     |  +> PUT
|  |     +> outputBufferSize=32768
|  |     +> outputAggregationSize=8192
|  |     +> requestHeaderSize=8192
|  |     +> responseHeaderSize=8192
|  |     +> headerCacheSize=1024
|  |     +> secureScheme=https
|  |     +> securePort=0
|  |     +> idleTimeout=-1
|  |     +> sendDateHeader=true
|  |     +> sendServerVersion=true
|  |     +> sendXPoweredBy=false
|  |     +> delayDispatchUntilContent=true
|  |     +> persistentConnectionsEnabled=true
|  |     +> maxErrorDispatches=10
|  |     +> minRequestDataRate=0
|  |     +> minResponseDataRate=0
|  |     +> requestCookieCompliance=org.eclipse.jetty.http.CookieCompliance@5d1e09bc
|  |     +> responseCookieCompliance=org.eclipse.jetty.http.CookieCompliance@5d1e09bc
|  |     +> notifyRemoteAsyncErrors=true
|  |     +> relativeRedirectAllowed=false
|  +- sun.nio.ch.ServerSocketChannelImpl[/[0:0:0:0:0:0:0:0]:8443]
|  +- qtp815992954-44-acceptor-0@3fc2660d-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443}
|  +- qtp815992954-45-acceptor-1@ed6bace-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443}
|  +- qtp815992954-46-acceptor-2@81dc61a-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443}
|  +- qtp815992954-47-acceptor-3@fdf2136-ServerConnector@31058f85{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443}
+= Server@3a7442c7[provider=null,keyStore=file:///home/user/my-base/etc/test-keystore.p12,trustStore=file:///home/user/my-base/etc/test-keystore.p12] - STARTED
|  +> trustAll=false
|  +> Protocol Selections
|  |  +> Enabled size=4
|  |  |  +> TLSv1
|  |  |  +> TLSv1.1
|  |  |  +> TLSv1.2
|  |  |  +> TLSv1.3
|  |  +> Disabled size=2
|  |     +> SSLv2Hello - ConfigExcluded:'SSLv2Hello' JVM:disabled
|  |     +> SSLv3 - ConfigExcluded:'SSLv3' JVM:disabled
|  +> Cipher Suite Selections
|     +> Enabled size=31
|     |  +> TLS_AES_128_GCM_SHA256
|     |  +> TLS_AES_256_GCM_SHA384
|     |  +> TLS_CHACHA20_POLY1305_SHA256
|     |  +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
|     |  +> TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
|     |  +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
|     |  +> TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
|     |  +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
|     |  +> TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
|     |  +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
|     |  +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_EMPTY_RENEGOTIATION_INFO_SCSV
|     +> Disabled size=18
|        +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'^TLS_RSA_.*$'
+= DeploymentManager@53093491{STARTED} - STARTED
|  += class org.eclipse.jetty.deploy.providers.WebAppProvider@21719a0[file:///home/user/my-base/webapps/] - STARTED
|     +- java.util.HashMap@83467828{size=8}
|     |  +@ /home/user/my-base/webapps/demo-jndi.xml = App[o.e.j.w.WebAppContext@7fc4780b{Test JNDI WebApp,/test-jndi,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jndi.war},/home/user/my-base/webapps/demo-jndi.xml]
|     |  +@ /home/user/my-base/webapps/root = App[o.e.j.w.WebAppContext@3c01cfa1{root,/,file:///home/user/my-base/webapps/root/,AVAILABLE}{/home/user/my-base/webapps/root},/home/user/my-base/webapps/root]
|     |  +@ /home/user/my-base/webapps/demo-async-rest.war = App[o.e.j.w.WebAppContext@45d2ade3{Async REST Webservice Example,/demo-async-rest,[file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/, jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/demo-async-rest-jar-{VERSION}.jar!/META-INF/resources],AVAILABLE}{/home/user/my-base/webapps/demo-async-rest.war},/home/user/my-base/webapps/demo-async-rest.war]
|     |  +@ /home/user/my-base/webapps/demo-proxy.war = App[o.e.j.w.WebAppContext@727eb8cb{Transparent Proxy WebApp,/proxy,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-proxy.war},/home/user/my-base/webapps/demo-proxy.war]
|     |  +@ /home/user/my-base/webapps/demo-spec.xml = App[o.e.j.w.WebAppContext@5b7a8434{Test Annotations WebApp,/test-spec,[file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/, jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-web-fragment-{VERSION}.jar!/META-INF/resources],AVAILABLE}{/home/user/my-base/webapps/demo-spec.war},/home/user/my-base/webapps/demo-spec.xml]
|     |  +@ /home/user/my-base/webapps/demo-jetty.xml = App[o.e.j.w.WebAppContext@1fb669c3{Test WebApp,/test,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jetty.war},/home/user/my-base/webapps/demo-jetty.xml]
|     |  +@ /home/user/my-base/webapps/demo-jaas.xml = App[o.e.j.w.WebAppContext@1869fbd2{JAAS Test,/test-jaas,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jaas.war},/home/user/my-base/webapps/demo-jaas.xml]
|     |  +@ /home/user/my-base/webapps/demo-moved-context.xml = App[o.e.j.s.h.MovedContextHandler@632ceb35{/oldContextPath,null,AVAILABLE},/home/user/my-base/webapps/demo-moved-context.xml]
|     +- class org.eclipse.jetty.deploy.PropertiesConfigurationManager@6b3871d6{null}
|     |  +> java.util.HashMap@0{size=0}
|     += Scanner@37095ded{STARTED} - STARTED
+= HashLoginService@2eb79cbe[Test Realm] - STARTED
|  +- org.eclipse.jetty.security.DefaultIdentityService@2ca6546f
|  += PropertyUserStore@43826ec[users.count=6][cfg=/home/user/my-base/etc/demo-realm.properties] - STARTED
+= RewriteHandler@7923f5b3{STARTED} - STARTED
|  +- org.eclipse.jetty.rewrite.handler.RuleContainer[ht]
|  |  +> org.eclipse.jetty.rewrite.handler.MsieSslRule[ht]
|  |  +> org.eclipse.jetty.rewrite.handler.HeaderPatternRule[hT][/favicon.ico][Cache-Control,Max-Age=3600,public]
|  |  +> org.eclipse.jetty.rewrite.handler.RewritePatternRule[ht][/test/rewrite/][/test/rewrite/info.html]
|  |  +> org.eclipse.jetty.rewrite.handler.RewritePatternRule[ht][/test/some/old/context][/test/rewritten/newcontext]
|  |  +> org.eclipse.jetty.rewrite.handler.RewritePatternRule[ht][/test/rewrite/for/*][/test/rewritten/]
|  |  +> org.eclipse.jetty.rewrite.handler.RewriteRegexRule[ht][(.*?)/reverse/([^/]*)/(.*)][$1/reverse/$3/$2]
|  |  +> org.eclipse.jetty.rewrite.handler.CookiePatternRule[ht][/*][visited,yes]
|  |  +> org.eclipse.jetty.rewrite.handler.RedirectPatternRule[HT][/test/redirect/*][302>/test/redirected]
|  |  +> org.eclipse.jetty.rewrite.handler.ResponsePatternRule[HT][/400Error][400,ResponsePatternRule Demo]
|  += HandlerList@11841b15{STARTED} - STARTED
|     += ContextHandlerCollection@73877e19{STARTED} - STARTED
|     |  += o.e.j.w.WebAppContext@7fc4780b{Test JNDI WebApp,/test-jndi,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jndi.war} - STARTED
|     |  |  += org.eclipse.jetty.server.session.SessionHandler2065730373==dftMaxIdleSec=1800 - STARTED
|     |  |  |  += ConstraintSecurityHandler@5bfc257{STARTED} - STARTED
|     |  |  |  |  +- knownAuthenticatorFactories size=1
|     |  |  |  |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@34523d46
|     |  |  |  |  += ServletHandler@7cedfa63{STARTED} - STARTED
|     |  |  |  |  |  +> listeners ServletHandler@7cedfa63{STARTED} size=2
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@3e83c18{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@783efb48{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  +> filters ServletHandler@7cedfa63{STARTED} size=1
|     |  |  |  |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter==org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@463b4ac8{inst=true,async=true,src=EMBEDDED:null} - STARTED
|     |  |  |  |  |  |     +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@5d235104
|     |  |  |  |  |  |        +> org.eclipse.jetty.websocket.core.server.WebSocketMappings@4e8e8621
|     |  |  |  |  |  |           +> PathMappings[size=0]
|     |  |  |  |  |  |              +> java.util.TreeSet@0(size=0)
|     |  |  |  |  |  +> filterMappings ServletHandler@7cedfa63{STARTED} size=1
|     |  |  |  |  |  |  +> [/*]/[]/[REQUEST]=>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter
|     |  |  |  |  |  +> servlets ServletHandler@7cedfa63{STARTED} size=3
|     |  |  |  |  |  |  +> default==org.eclipse.jetty.servlet.DefaultServlet@5c13d641{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.servlet.DefaultServlet@2b0b4d53
|     |  |  |  |  |  |  |  +> initParams size=9
|     |  |  |  |  |  |  |     +> dirAllowed=true
|     |  |  |  |  |  |  |     +> maxCacheSize=256000000
|     |  |  |  |  |  |  |     +> maxCachedFileSize=200000000
|     |  |  |  |  |  |  |     +> welcomeServlets=false
|     |  |  |  |  |  |  |     +> useFileMappedBuffer=true
|     |  |  |  |  |  |  |     +> acceptRanges=true
|     |  |  |  |  |  |  |     +> etags=false
|     |  |  |  |  |  |  |     +> maxCachedFiles=2048
|     |  |  |  |  |  |  |     +> redirectWelcome=false
|     |  |  |  |  |  |  +> jsp==org.eclipse.jetty.jsp.JettyJspServlet@19c47{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.jsp.JettyJspServlet@7068f7ca
|     |  |  |  |  |  |  |  +> initParams size=4
|     |  |  |  |  |  |  |     +> compilerSourceVM=1.8
|     |  |  |  |  |  |  |     +> compilerTargetVM=1.8
|     |  |  |  |  |  |  |     +> scratchdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/jsp
|     |  |  |  |  |  |  |     +> xpoweredBy=false
|     |  |  |  |  |  |  +> JNDITest==com.acme.JNDITest@9d72fcfb{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |  |  |  |     +> NotAsync:com.acme.JNDITest@38548b19
|     |  |  |  |  |  +> servletMappings ServletHandler@7cedfa63{STARTED} size=3
|     |  |  |  |  |     +> [/]=>default
|     |  |  |  |  |     +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
|     |  |  |  |  |     +> [/test/*]=>JNDITest
|     |  |  |  |  +~ HashLoginService@2eb79cbe[Test Realm] - STARTED
|     |  |  |  |  +~ org.eclipse.jetty.security.DefaultIdentityService@2ca6546f
|     |  |  |  |  +- org.eclipse.jetty.security.authentication.BasicAuthenticator@41aaedaa
|     |  |  |  |  +> roles size=1
|     |  |  |  |  |  +> java.util.concurrent.CopyOnWriteArraySet@0(size=0)
|     |  |  |  |  +> constraints size=1
|     |  |  |  |     +> java.util.concurrent.CopyOnWriteArrayList@de6b0c3b(size=2)
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@303a5119
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@75b3673
|     |  |  |  += org.eclipse.jetty.server.session.DefaultSessionCache@1bcb79c2[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|     |  |  |  |  += org.eclipse.jetty.server.session.NullSessionDataStore@d1a10ac[passivating=false,graceSec=3600] - STARTED
|     |  |  |  +~ DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|     |  |  += ErrorPageErrorHandler@31fc71ab{STARTED} - STARTED
|     |  |  +- java:comp org.eclipse.jetty.jndi.NamingContext@71391b3f[name=comp,parent=org.eclipse.jetty.jndi.NamingContext@2cfbeac4,bindings.size=2]
|     |  |  |  +@ UserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |  +@ env = org.eclipse.jetty.jndi.NamingContext@12db3386[name=env,parent=org.eclipse.jetty.jndi.NamingContext@71391b3f,bindings.size=7]
|     |  |  |     +@ __ = org.eclipse.jetty.jndi.NamingContext@4078695f[name=__,parent=org.eclipse.jetty.jndi.NamingContext@12db3386,bindings.size=4]
|     |  |  |     |  +@ wiggle = org.eclipse.jetty.plus.jndi.EnvEntry@79a1728c{name=wiggle,OverrideWebXml=true}
|     |  |  |     |  +@ gargle = org.eclipse.jetty.plus.jndi.EnvEntry@a7f0ab6{name=gargle,OverrideWebXml=true}
|     |  |  |     |  +@ woggle = org.eclipse.jetty.plus.jndi.EnvEntry@41f35f7c{name=woggle,OverrideWebXml=false}
|     |  |  |     |  +@ svr = org.eclipse.jetty.plus.jndi.EnvEntry@42c2f48c{name=svr,OverrideWebXml=true}
|     |  |  |     +@ wiggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@7fc4780b/wiggle|
|     |  |  |     +@ mail = org.eclipse.jetty.jndi.NamingContext@3005db4a[name=mail,parent=org.eclipse.jetty.jndi.NamingContext@12db3386,bindings.size=1]
|     |  |  |     |  +@ Session = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@7fc4780b/mail/Session|
|     |  |  |     +@ gargle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@7fc4780b/gargle|
|     |  |  |     +@ jdbc = org.eclipse.jetty.jndi.NamingContext@425d5d46[name=jdbc,parent=org.eclipse.jetty.jndi.NamingContext@12db3386,bindings.size=1]
|     |  |  |     |  +@ mydatasource1 = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@7fc4780b/jdbc/mydatasource|
|     |  |  |     +@ woggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: woggle|
|     |  |  |     +@ svr = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@7fc4780b/svr|
|     |  |  += JettyServerFrameHandlerFactory@198ef2ce{STARTED} - STARTED
|     |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  += JettyWebSocketServerContainer@4cbd03e7{STARTED} - STARTED
|     |  |  |  += SessionTracker@52fc5eb1{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  += JavaxWebSocketServerContainer@7a639ec5{STARTED} - STARTED
|     |  |  |  += SessionTracker@14151bc5{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  +- org.eclipse.jetty.servlet.listener.ELContextCleaner@3013909b
|     |  |  +- org.eclipse.jetty.servlet.listener.IntrospectorCleaner@2a49fe
|     |  |  +> WebAppClassLoader{Test JNDI WebApp}@47f9738
|     |  |  |  +> URLs size=1
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/webapp/WEB-INF/classes/
|     |  |  |  +> startJarLoader@3d012ddd
|     |  |  +> Systemclasses Test JNDI WebApp@7fc4780b size=18
|     |  |  |  +> java.
|     |  |  |  +> javax.
|     |  |  |  +> org.eclipse.jetty.jaas.
|     |  |  |  +> org.eclipse.jetty.jndi.
|     |  |  |  +> org.eclipse.jetty.jsp.
|     |  |  |  +> org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter
|     |  |  |  +> org.eclipse.jetty.servlets.PushSessionCacheFilter
|     |  |  |  +> org.eclipse.jetty.util.annotations.
|     |  |  |  +> org.eclipse.jetty.websocket.api.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> org.eclipse.jetty.websocket.server.
|     |  |  |  +> org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.w3c.
|     |  |  |  +> org.xml.
|     |  |  +> Serverclasses Test JNDI WebApp@7fc4780b size=23
|     |  |  |  +> -org.eclipse.jetty.apache.
|     |  |  |  +> -org.eclipse.jetty.jaas.
|     |  |  |  +> -org.eclipse.jetty.jndi.
|     |  |  |  +> -org.eclipse.jetty.jsp.
|     |  |  |  +> -org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.listener.
|     |  |  |  +> -org.eclipse.jetty.servlets.
|     |  |  |  +> -org.eclipse.jetty.util.annotations.
|     |  |  |  +> -org.eclipse.jetty.websocket.api.
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> -org.eclipse.jetty.websocket.server.
|     |  |  |  +> -org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.eclipse.jdt.
|     |  |  |  +> org.eclipse.jetty.
|     |  |  |  +> org.eclipse.jetty.logging.
|     |  |  |  +> org.eclipse.jetty.server.config.
|     |  |  |  +> org.eclipse.jetty.server.internal.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.internal
|     |  |  |  +> org.objectweb.asm.
|     |  |  |  +> org.slf4j.
|     |  |  +> Configurations Test JNDI WebApp@7fc4780b size=15
|     |  |  |  +> org.eclipse.jetty.webapp.WebInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebXmlConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.MetaInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.FragmentConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JaasConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JndiConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JspConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.JavaxWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebAppConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.ServletsConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration
|     |  |  |  +> org.eclipse.jetty.annotations.AnnotationConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration
|     |  |  +> Handler attributes Test JNDI WebApp@7fc4780b size=8
|     |  |  |  +> javax.servlet.context.tempdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-
|     |  |  |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |  |  |  +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@5aae8eb5
|     |  |  |  +> org.eclipse.jetty.webapp.tmpResourceBase=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/webapp
|     |  |  |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |  |  |  +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@76954a33
|     |  |  |  +> org.apache.catalina.jsp_classpath=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/webapp/WEB-INF/classes
|     |  |  |  +> org.eclipse.jetty.jndi.EnvConfiguration=[org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@24a298a6, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@982bb90, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@27f74733, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@7bef452c, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@4bb8855f, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@57fae983, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@4a29f290, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@4bee18dc]
|     |  |  +> Context attributes Test JNDI WebApp@7fc4780b size=8
|     |  |  |  +> org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=3]
|     |  |  |  +> org.eclipse.jetty.websocket.api.WebSocketContainer=JettyWebSocketServerContainer@4cbd03e7{STARTED}
|     |  |  |  +> resourceCache=ResourceCache[null,org.eclipse.jetty.servlet.DefaultServlet@2b0b4d53]@1156841091
|     |  |  |  +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@7906578e
|     |  |  |  +> org.eclipse.jetty.websocket.core.WebSocketComponents=WebSocketServerComponents@8a62297{STARTED}
|     |  |  |  +> javax.websocket.server.ServerContainer=JavaxWebSocketServerContainer@7a639ec5{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.server.WebSocketMappings=org.eclipse.jetty.websocket.core.server.WebSocketMappings@4e8e8621
|     |  |  |  +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@61a91912
|     |  |  +> EventListeners o.e.j.w.WebAppContext@7fc4780b{Test JNDI WebApp,/test-jndi,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jndi_war-_test-jndi-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jndi.war} size=5
|     |  |  |  +> JettyServerFrameHandlerFactory@198ef2ce{STARTED} - STARTED
|     |  |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  |  +> JettyWebSocketServerContainer@4cbd03e7{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@52fc5eb1{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> JavaxWebSocketServerContainer@7a639ec5{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@14151bc5{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@3013909b
|     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@2a49fe
|     |  |  +> Initparams Test JNDI WebApp@7fc4780b size=0
|     |  += o.e.j.w.WebAppContext@3c01cfa1{root,/,file:///home/user/my-base/webapps/root/,AVAILABLE}{/home/user/my-base/webapps/root} - STARTED
|     |  |  += org.eclipse.jetty.server.session.SessionHandler392403246==dftMaxIdleSec=1800 - STARTED
|     |  |  |  += ConstraintSecurityHandler@5c92166b{STARTED} - STARTED
|     |  |  |  |  +- knownAuthenticatorFactories size=1
|     |  |  |  |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@34523d46
|     |  |  |  |  += ServletHandler@659925f4{STARTED} - STARTED
|     |  |  |  |  |  +> listeners ServletHandler@659925f4{STARTED} size=2
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@4cd1c1dc{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@47f08b81{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  +> filters ServletHandler@659925f4{STARTED} size=1
|     |  |  |  |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter==org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@2b58f754{inst=true,async=true,src=EMBEDDED:null} - STARTED
|     |  |  |  |  |  |     +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@b9dfc5a
|     |  |  |  |  |  |        +> org.eclipse.jetty.websocket.core.server.WebSocketMappings@2787de58
|     |  |  |  |  |  |           +> PathMappings[size=0]
|     |  |  |  |  |  |              +> java.util.TreeSet@0(size=0)
|     |  |  |  |  |  +> filterMappings ServletHandler@659925f4{STARTED} size=1
|     |  |  |  |  |  |  +> [/*]/[]/[REQUEST]=>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter
|     |  |  |  |  |  +> servlets ServletHandler@659925f4{STARTED} size=2
|     |  |  |  |  |  |  +> default==org.eclipse.jetty.servlet.DefaultServlet@5c13d641{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.servlet.DefaultServlet@659a2455
|     |  |  |  |  |  |  |  +> initParams size=9
|     |  |  |  |  |  |  |     +> dirAllowed=true
|     |  |  |  |  |  |  |     +> maxCacheSize=256000000
|     |  |  |  |  |  |  |     +> maxCachedFileSize=200000000
|     |  |  |  |  |  |  |     +> welcomeServlets=false
|     |  |  |  |  |  |  |     +> useFileMappedBuffer=true
|     |  |  |  |  |  |  |     +> acceptRanges=true
|     |  |  |  |  |  |  |     +> etags=false
|     |  |  |  |  |  |  |     +> maxCachedFiles=2048
|     |  |  |  |  |  |  |     +> redirectWelcome=false
|     |  |  |  |  |  |  +> jsp==org.eclipse.jetty.jsp.JettyJspServlet@19c47{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |     +> NotAsync:org.eclipse.jetty.jsp.JettyJspServlet@267517e4
|     |  |  |  |  |  |     +> initParams size=4
|     |  |  |  |  |  |        +> compilerSourceVM=1.8
|     |  |  |  |  |  |        +> compilerTargetVM=1.8
|     |  |  |  |  |  |        +> scratchdir=/home/user/my-base/work/jetty-0_0_0_0-8443-root-_-any-/jsp
|     |  |  |  |  |  |        +> xpoweredBy=false
|     |  |  |  |  |  +> servletMappings ServletHandler@659925f4{STARTED} size=2
|     |  |  |  |  |     +> [/]=>default
|     |  |  |  |  |     +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
|     |  |  |  |  +~ HashLoginService@2eb79cbe[Test Realm] - STARTED
|     |  |  |  |  +~ org.eclipse.jetty.security.DefaultIdentityService@2ca6546f
|     |  |  |  |  +- org.eclipse.jetty.security.authentication.BasicAuthenticator@426e505c
|     |  |  |  |  +> roles size=1
|     |  |  |  |  |  +> java.util.concurrent.CopyOnWriteArraySet@0(size=0)
|     |  |  |  |  +> constraints size=1
|     |  |  |  |     +> java.util.concurrent.CopyOnWriteArrayList@74d05838(size=2)
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@5b022357
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@6f8e0cee
|     |  |  |  += org.eclipse.jetty.server.session.DefaultSessionCache@614aeccc[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|     |  |  |  |  += org.eclipse.jetty.server.session.NullSessionDataStore@5116ac09[passivating=false,graceSec=3600] - STARTED
|     |  |  |  +~ DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|     |  |  += ErrorPageErrorHandler@1bc425e7{STARTED} - STARTED
|     |  |  +- java:comp org.eclipse.jetty.jndi.NamingContext@4b2a30d[name=comp,parent=org.eclipse.jetty.jndi.NamingContext@2cfbeac4,bindings.size=2]
|     |  |  |  +@ UserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |  +@ env = org.eclipse.jetty.jndi.NamingContext@322803db[name=env,parent=org.eclipse.jetty.jndi.NamingContext@4b2a30d,bindings.size=2]
|     |  |  |     +@ __ = org.eclipse.jetty.jndi.NamingContext@56ba8773[name=__,parent=org.eclipse.jetty.jndi.NamingContext@322803db,bindings.size=1]
|     |  |  |     |  +@ woggle = org.eclipse.jetty.plus.jndi.EnvEntry@41f35f7c{name=woggle,OverrideWebXml=false}
|     |  |  |     +@ woggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: woggle|
|     |  |  += JettyServerFrameHandlerFactory@6ceb7b5e{STARTED} - STARTED
|     |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  += JettyWebSocketServerContainer@7dd00705{STARTED} - STARTED
|     |  |  |  += SessionTracker@f14e5bf{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  += JavaxWebSocketServerContainer@d176a31{STARTED} - STARTED
|     |  |  |  += SessionTracker@3a91d146{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  +- org.eclipse.jetty.servlet.listener.ELContextCleaner@4784013e
|     |  |  +- org.eclipse.jetty.servlet.listener.IntrospectorCleaner@6f952d6c
|     |  |  +> WebAppClassLoader{root}@d5ae57e
|     |  |  |  +> URLs size=0
|     |  |  |  +> startJarLoader@3d012ddd
|     |  |  +> Systemclasses root@3c01cfa1 size=18
|     |  |  |  +> java.
|     |  |  |  +> javax.
|     |  |  |  +> org.eclipse.jetty.jaas.
|     |  |  |  +> org.eclipse.jetty.jndi.
|     |  |  |  +> org.eclipse.jetty.jsp.
|     |  |  |  +> org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter
|     |  |  |  +> org.eclipse.jetty.servlets.PushSessionCacheFilter
|     |  |  |  +> org.eclipse.jetty.util.annotations.
|     |  |  |  +> org.eclipse.jetty.websocket.api.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> org.eclipse.jetty.websocket.server.
|     |  |  |  +> org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.w3c.
|     |  |  |  +> org.xml.
|     |  |  +> Serverclasses root@3c01cfa1 size=23
|     |  |  |  +> -org.eclipse.jetty.apache.
|     |  |  |  +> -org.eclipse.jetty.jaas.
|     |  |  |  +> -org.eclipse.jetty.jndi.
|     |  |  |  +> -org.eclipse.jetty.jsp.
|     |  |  |  +> -org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.listener.
|     |  |  |  +> -org.eclipse.jetty.servlets.
|     |  |  |  +> -org.eclipse.jetty.util.annotations.
|     |  |  |  +> -org.eclipse.jetty.websocket.api.
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> -org.eclipse.jetty.websocket.server.
|     |  |  |  +> -org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.eclipse.jdt.
|     |  |  |  +> org.eclipse.jetty.
|     |  |  |  +> org.eclipse.jetty.logging.
|     |  |  |  +> org.eclipse.jetty.server.config.
|     |  |  |  +> org.eclipse.jetty.server.internal.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.internal
|     |  |  |  +> org.objectweb.asm.
|     |  |  |  +> org.slf4j.
|     |  |  +> Configurations root@3c01cfa1 size=15
|     |  |  |  +> org.eclipse.jetty.webapp.WebInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebXmlConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.MetaInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.FragmentConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JaasConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JndiConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JspConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.JavaxWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebAppConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.ServletsConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration
|     |  |  |  +> org.eclipse.jetty.annotations.AnnotationConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration
|     |  |  +> Handler attributes root@3c01cfa1 size=5
|     |  |  |  +> javax.servlet.context.tempdir=/home/user/my-base/work/jetty-0_0_0_0-8443-root-_-any-
|     |  |  |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |  |  |  +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@5965844d
|     |  |  |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |  |  |  +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@6d4a65c6
|     |  |  +> Context attributes root@3c01cfa1 size=8
|     |  |  |  +> org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=3]
|     |  |  |  +> org.eclipse.jetty.websocket.api.WebSocketContainer=JettyWebSocketServerContainer@7dd00705{STARTED}
|     |  |  |  +> resourceCache=ResourceCache[null,org.eclipse.jetty.servlet.DefaultServlet@659a2455]@178259104
|     |  |  |  +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@4c98a6d5
|     |  |  |  +> org.eclipse.jetty.websocket.core.WebSocketComponents=WebSocketServerComponents@8a62297{STARTED}
|     |  |  |  +> javax.websocket.server.ServerContainer=JavaxWebSocketServerContainer@d176a31{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.server.WebSocketMappings=org.eclipse.jetty.websocket.core.server.WebSocketMappings@2787de58
|     |  |  |  +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@392a04e7
|     |  |  +> EventListeners o.e.j.w.WebAppContext@3c01cfa1{root,/,file:///home/user/my-base/webapps/root/,AVAILABLE}{/home/user/my-base/webapps/root} size=5
|     |  |  |  +> JettyServerFrameHandlerFactory@6ceb7b5e{STARTED} - STARTED
|     |  |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  |  +> JettyWebSocketServerContainer@7dd00705{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@f14e5bf{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> JavaxWebSocketServerContainer@d176a31{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@3a91d146{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@4784013e
|     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@6f952d6c
|     |  |  +> Initparams root@3c01cfa1 size=0
|     |  += o.e.j.w.WebAppContext@45d2ade3{Async REST Webservice Example,/demo-async-rest,[file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/, jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/demo-async-rest-jar-{VERSION}.jar!/META-INF/resources],AVAILABLE}{/home/user/my-base/webapps/demo-async-rest.war} - STARTED
|     |  |  += org.eclipse.jetty.server.session.SessionHandler133177937==dftMaxIdleSec=1800 - STARTED
|     |  |  |  += ConstraintSecurityHandler@dffa30b{STARTED} - STARTED
|     |  |  |  |  +- knownAuthenticatorFactories size=1
|     |  |  |  |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@34523d46
|     |  |  |  |  += ServletHandler@4d8126f{STARTED} - STARTED
|     |  |  |  |  |  +> listeners ServletHandler@4d8126f{STARTED} size=2
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@6d3c232f{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@6b587673{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  +> filters ServletHandler@4d8126f{STARTED} size=1
|     |  |  |  |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter==org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@4cc76301{inst=true,async=true,src=EMBEDDED:null} - STARTED
|     |  |  |  |  |  |     +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@1bcf67e8
|     |  |  |  |  |  |        +> org.eclipse.jetty.websocket.core.server.WebSocketMappings@5f404594
|     |  |  |  |  |  |           +> PathMappings[size=0]
|     |  |  |  |  |  |              +> java.util.TreeSet@0(size=0)
|     |  |  |  |  |  +> filterMappings ServletHandler@4d8126f{STARTED} size=1
|     |  |  |  |  |  |  +> [/*]/[]/[REQUEST]=>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter
|     |  |  |  |  |  +> servlets ServletHandler@4d8126f{STARTED} size=4
|     |  |  |  |  |  |  +> default==org.eclipse.jetty.servlet.DefaultServlet@5c13d641{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.servlet.DefaultServlet@53692008
|     |  |  |  |  |  |  |  +> initParams size=9
|     |  |  |  |  |  |  |     +> dirAllowed=true
|     |  |  |  |  |  |  |     +> maxCacheSize=256000000
|     |  |  |  |  |  |  |     +> maxCachedFileSize=200000000
|     |  |  |  |  |  |  |     +> welcomeServlets=false
|     |  |  |  |  |  |  |     +> useFileMappedBuffer=true
|     |  |  |  |  |  |  |     +> acceptRanges=true
|     |  |  |  |  |  |  |     +> etags=false
|     |  |  |  |  |  |  |     +> maxCachedFiles=2048
|     |  |  |  |  |  |  |     +> redirectWelcome=false
|     |  |  |  |  |  |  +> jsp==org.eclipse.jetty.jsp.JettyJspServlet@19c47{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.jsp.JettyJspServlet@7b2a3ff8
|     |  |  |  |  |  |  |  +> initParams size=4
|     |  |  |  |  |  |  |     +> compilerSourceVM=1.8
|     |  |  |  |  |  |  |     +> compilerTargetVM=1.8
|     |  |  |  |  |  |  |     +> scratchdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/jsp
|     |  |  |  |  |  |  |     +> xpoweredBy=false
|     |  |  |  |  |  |  +> SerialRestServlet==org.eclipse.jetty.demos.SerialRestServlet@461411d{jsp=null,order=-1,inst=false,async=false,src=DESCRIPTOR:jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/demo-async-rest-jar-{VERSION}.jar!/META-INF/web-fragment.xml} - STARTED
|     |  |  |  |  |  |  |  +> class org.eclipse.jetty.demos.SerialRestServlet
|     |  |  |  |  |  |  +> AsyncRestServlet==org.eclipse.jetty.demos.AsyncRestServlet@73eb9bd5{jsp=null,order=-1,inst=false,async=true,src=DESCRIPTOR:jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/demo-async-rest-jar-{VERSION}.jar!/META-INF/web-fragment.xml} - STARTED
|     |  |  |  |  |  |     +> class org.eclipse.jetty.demos.AsyncRestServlet
|     |  |  |  |  |  +> servletMappings ServletHandler@4d8126f{STARTED} size=4
|     |  |  |  |  |     +> [/]=>default
|     |  |  |  |  |     +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
|     |  |  |  |  |     +> [/testSerial]=>SerialRestServlet
|     |  |  |  |  |     +> [/testAsync]=>AsyncRestServlet
|     |  |  |  |  +~ HashLoginService@2eb79cbe[Test Realm] - STARTED
|     |  |  |  |  +~ org.eclipse.jetty.security.DefaultIdentityService@2ca6546f
|     |  |  |  |  +- org.eclipse.jetty.security.authentication.BasicAuthenticator@1bbae752
|     |  |  |  |  +> roles size=1
|     |  |  |  |  |  +> java.util.concurrent.CopyOnWriteArraySet@0(size=0)
|     |  |  |  |  +> constraints size=1
|     |  |  |  |     +> java.util.concurrent.CopyOnWriteArrayList@d85abdea(size=2)
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@460b6d54
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@5cf87cfd
|     |  |  |  += org.eclipse.jetty.server.session.DefaultSessionCache@76075d65[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|     |  |  |  |  += org.eclipse.jetty.server.session.NullSessionDataStore@3a4ba480[passivating=false,graceSec=3600] - STARTED
|     |  |  |  +~ DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|     |  |  += ErrorPageErrorHandler@27b71f50{STARTED} - STARTED
|     |  |  +- java:comp org.eclipse.jetty.jndi.NamingContext@383790cf[name=comp,parent=org.eclipse.jetty.jndi.NamingContext@2cfbeac4,bindings.size=2]
|     |  |  |  +@ UserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |  +@ env = org.eclipse.jetty.jndi.NamingContext@74971ed9[name=env,parent=org.eclipse.jetty.jndi.NamingContext@383790cf,bindings.size=2]
|     |  |  |     +@ __ = org.eclipse.jetty.jndi.NamingContext@131fcb6f[name=__,parent=org.eclipse.jetty.jndi.NamingContext@74971ed9,bindings.size=1]
|     |  |  |     |  +@ woggle = org.eclipse.jetty.plus.jndi.EnvEntry@41f35f7c{name=woggle,OverrideWebXml=false}
|     |  |  |     +@ woggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: woggle|
|     |  |  += JettyServerFrameHandlerFactory@ccd1bc3{STARTED} - STARTED
|     |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  += JettyWebSocketServerContainer@878537d{STARTED} - STARTED
|     |  |  |  += SessionTracker@4455f57d{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  += JavaxWebSocketServerContainer@29fc1a2b{STARTED} - STARTED
|     |  |  |  += SessionTracker@4d0b0fd4{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  +- org.eclipse.jetty.servlet.listener.ELContextCleaner@7a24eb3
|     |  |  +- org.eclipse.jetty.servlet.listener.IntrospectorCleaner@6c37bd27
|     |  |  +> WebAppClassLoader{Async REST Webservice Example}@3af17be2
|     |  |  |  +> URLs size=10
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/classes/
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/demo-async-rest-jar-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-alpn-client-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-slf4j-impl-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-util-ajax-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/slf4j-api-2.0.0-alpha1.jar
|     |  |  |  +> startJarLoader@3d012ddd
|     |  |  +> Systemclasses Async REST Webservice Example@45d2ade3 size=18
|     |  |  |  +> java.
|     |  |  |  +> javax.
|     |  |  |  +> org.eclipse.jetty.jaas.
|     |  |  |  +> org.eclipse.jetty.jndi.
|     |  |  |  +> org.eclipse.jetty.jsp.
|     |  |  |  +> org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter
|     |  |  |  +> org.eclipse.jetty.servlets.PushSessionCacheFilter
|     |  |  |  +> org.eclipse.jetty.util.annotations.
|     |  |  |  +> org.eclipse.jetty.websocket.api.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> org.eclipse.jetty.websocket.server.
|     |  |  |  +> org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.w3c.
|     |  |  |  +> org.xml.
|     |  |  +> Serverclasses Async REST Webservice Example@45d2ade3 size=23
|     |  |  |  +> -org.eclipse.jetty.apache.
|     |  |  |  +> -org.eclipse.jetty.jaas.
|     |  |  |  +> -org.eclipse.jetty.jndi.
|     |  |  |  +> -org.eclipse.jetty.jsp.
|     |  |  |  +> -org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.listener.
|     |  |  |  +> -org.eclipse.jetty.servlets.
|     |  |  |  +> -org.eclipse.jetty.util.annotations.
|     |  |  |  +> -org.eclipse.jetty.websocket.api.
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> -org.eclipse.jetty.websocket.server.
|     |  |  |  +> -org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.eclipse.jdt.
|     |  |  |  +> org.eclipse.jetty.
|     |  |  |  +> org.eclipse.jetty.logging.
|     |  |  |  +> org.eclipse.jetty.server.config.
|     |  |  |  +> org.eclipse.jetty.server.internal.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.internal
|     |  |  |  +> org.objectweb.asm.
|     |  |  |  +> org.slf4j.
|     |  |  +> Configurations Async REST Webservice Example@45d2ade3 size=15
|     |  |  |  +> org.eclipse.jetty.webapp.WebInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebXmlConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.MetaInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.FragmentConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JaasConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JndiConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JspConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.JavaxWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebAppConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.ServletsConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration
|     |  |  |  +> org.eclipse.jetty.annotations.AnnotationConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration
|     |  |  +> Handler attributes Async REST Webservice Example@45d2ade3 size=7
|     |  |  |  +> javax.servlet.context.tempdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-
|     |  |  |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |  |  |  +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@25d3cfc8
|     |  |  |  +> org.eclipse.jetty.webapp.tmpResourceBase=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp
|     |  |  |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |  |  |  +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@30331109
|     |  |  |  +> org.apache.catalina.jsp_classpath=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/classes:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/demo-async-rest-jar-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-alpn-client-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-slf4j-impl-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/jetty-util-ajax-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/slf4j-api-2.0.0-alpha1.jar
|     |  |  +> Context attributes Async REST Webservice Example@45d2ade3 size=8
|     |  |  |  +> org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=3]
|     |  |  |  +> org.eclipse.jetty.websocket.api.WebSocketContainer=JettyWebSocketServerContainer@878537d{STARTED}
|     |  |  |  +> resourceCache=ResourceCache[null,org.eclipse.jetty.servlet.DefaultServlet@53692008]@628164202
|     |  |  |  +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@74fe5966
|     |  |  |  +> org.eclipse.jetty.websocket.core.WebSocketComponents=WebSocketServerComponents@8a62297{STARTED}
|     |  |  |  +> javax.websocket.server.ServerContainer=JavaxWebSocketServerContainer@29fc1a2b{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.server.WebSocketMappings=org.eclipse.jetty.websocket.core.server.WebSocketMappings@5f404594
|     |  |  |  +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@4fe875be
|     |  |  +> EventListeners o.e.j.w.WebAppContext@45d2ade3{Async REST Webservice Example,/demo-async-rest,[file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/, jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-async-rest_war-_demo-async-rest-any-/webapp/WEB-INF/lib/demo-async-rest-jar-{VERSION}.jar!/META-INF/resources],AVAILABLE}{/home/user/my-base/webapps/demo-async-rest.war} size=5
|     |  |  |  +> JettyServerFrameHandlerFactory@ccd1bc3{STARTED} - STARTED
|     |  |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  |  +> JettyWebSocketServerContainer@878537d{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@4455f57d{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> JavaxWebSocketServerContainer@29fc1a2b{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@4d0b0fd4{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@7a24eb3
|     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@6c37bd27
|     |  |  +> Initparams Async REST Webservice Example@45d2ade3 size=0
|     |  += o.e.j.w.WebAppContext@727eb8cb{Transparent Proxy WebApp,/proxy,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-proxy.war} - STARTED
|     |  |  += org.eclipse.jetty.server.session.SessionHandler1736150547==dftMaxIdleSec=1800 - STARTED
|     |  |  |  += ConstraintSecurityHandler@4a9486c0{STARTED} - STARTED
|     |  |  |  |  +- knownAuthenticatorFactories size=1
|     |  |  |  |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@34523d46
|     |  |  |  |  += ServletHandler@4c27d39d{STARTED} - STARTED
|     |  |  |  |  |  +> listeners ServletHandler@4c27d39d{STARTED} size=2
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@40ee0a22{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@7bde1f3a{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  +> filters ServletHandler@4c27d39d{STARTED} size=1
|     |  |  |  |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter==org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@548e76f1{inst=true,async=true,src=EMBEDDED:null} - STARTED
|     |  |  |  |  |  |     +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@15923407
|     |  |  |  |  |  |        +> org.eclipse.jetty.websocket.core.server.WebSocketMappings@67dba613
|     |  |  |  |  |  |           +> PathMappings[size=0]
|     |  |  |  |  |  |              +> java.util.TreeSet@0(size=0)
|     |  |  |  |  |  +> filterMappings ServletHandler@4c27d39d{STARTED} size=1
|     |  |  |  |  |  |  +> [/*]/[]/[REQUEST]=>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter
|     |  |  |  |  |  +> servlets ServletHandler@4c27d39d{STARTED} size=3
|     |  |  |  |  |  |  +> default==org.eclipse.jetty.servlet.DefaultServlet@5c13d641{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.servlet.DefaultServlet@57540fd0
|     |  |  |  |  |  |  |  +> initParams size=9
|     |  |  |  |  |  |  |     +> dirAllowed=true
|     |  |  |  |  |  |  |     +> maxCacheSize=256000000
|     |  |  |  |  |  |  |     +> maxCachedFileSize=200000000
|     |  |  |  |  |  |  |     +> welcomeServlets=false
|     |  |  |  |  |  |  |     +> useFileMappedBuffer=true
|     |  |  |  |  |  |  |     +> acceptRanges=true
|     |  |  |  |  |  |  |     +> etags=false
|     |  |  |  |  |  |  |     +> maxCachedFiles=2048
|     |  |  |  |  |  |  |     +> redirectWelcome=false
|     |  |  |  |  |  |  +> jsp==org.eclipse.jetty.jsp.JettyJspServlet@19c47{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.jsp.JettyJspServlet@5cf8edcf
|     |  |  |  |  |  |  |  +> initParams size=4
|     |  |  |  |  |  |  |     +> compilerSourceVM=1.8
|     |  |  |  |  |  |  |     +> compilerTargetVM=1.8
|     |  |  |  |  |  |  |     +> scratchdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/jsp
|     |  |  |  |  |  |  |     +> xpoweredBy=false
|     |  |  |  |  |  |  +> JavadocTransparentProxy==org.eclipse.jetty.proxy.ProxyServlet$Transparent@8ab9c012{jsp=null,order=1,inst=true,async=true,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |  |  |  |     +> org.eclipse.jetty.proxy.ProxyServlet$Transparent@58cec85b
|     |  |  |  |  |  |     +> initParams size=2
|     |  |  |  |  |  |        +> hostHeader=www.eclipse.org
|     |  |  |  |  |  |        +> proxyTo=https://www.eclipse.org/jetty/javadoc/
|     |  |  |  |  |  +> servletMappings ServletHandler@4c27d39d{STARTED} size=3
|     |  |  |  |  |     +> [/]=>default
|     |  |  |  |  |     +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
|     |  |  |  |  |     +> [/current/*]=>JavadocTransparentProxy
|     |  |  |  |  +~ HashLoginService@2eb79cbe[Test Realm] - STARTED
|     |  |  |  |  +~ org.eclipse.jetty.security.DefaultIdentityService@2ca6546f
|     |  |  |  |  +- org.eclipse.jetty.security.authentication.BasicAuthenticator@629f066f
|     |  |  |  |  +> roles size=1
|     |  |  |  |  |  +> java.util.concurrent.CopyOnWriteArraySet@0(size=0)
|     |  |  |  |  +> constraints size=1
|     |  |  |  |     +> java.util.concurrent.CopyOnWriteArrayList@a1e2ff4f(size=2)
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@1542af63
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@ecfbe91
|     |  |  |  += org.eclipse.jetty.server.session.DefaultSessionCache@20ed3303[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|     |  |  |  |  += org.eclipse.jetty.server.session.NullSessionDataStore@3adbe50f[passivating=false,graceSec=3600] - STARTED
|     |  |  |  +~ DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|     |  |  += ErrorPageErrorHandler@3a627c80{STARTED} - STARTED
|     |  |  +- java:comp org.eclipse.jetty.jndi.NamingContext@49aa766b[name=comp,parent=org.eclipse.jetty.jndi.NamingContext@2cfbeac4,bindings.size=2]
|     |  |  |  +@ UserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |  +@ env = org.eclipse.jetty.jndi.NamingContext@963176[name=env,parent=org.eclipse.jetty.jndi.NamingContext@49aa766b,bindings.size=2]
|     |  |  |     +@ __ = org.eclipse.jetty.jndi.NamingContext@65004ff6[name=__,parent=org.eclipse.jetty.jndi.NamingContext@963176,bindings.size=1]
|     |  |  |     |  +@ woggle = org.eclipse.jetty.plus.jndi.EnvEntry@41f35f7c{name=woggle,OverrideWebXml=false}
|     |  |  |     +@ woggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: woggle|
|     |  |  += JettyServerFrameHandlerFactory@4cafa9aa{STARTED} - STARTED
|     |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  += JettyWebSocketServerContainer@562c877a{STARTED} - STARTED
|     |  |  |  += SessionTracker@67001148{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  += JavaxWebSocketServerContainer@989da1{STARTED} - STARTED
|     |  |  |  += SessionTracker@31cb96e1{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  +- org.eclipse.jetty.servlet.listener.ELContextCleaner@3eed0f5
|     |  |  +- org.eclipse.jetty.servlet.listener.IntrospectorCleaner@64030b91
|     |  |  +> WebAppClassLoader{Transparent Proxy WebApp}@2c715e84
|     |  |  |  +> URLs size=9
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/classes/
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-alpn-client-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-proxy-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-slf4j-impl-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/slf4j-api-2.0.0-alpha1.jar
|     |  |  |  +> startJarLoader@3d012ddd
|     |  |  +> Systemclasses Transparent Proxy WebApp@727eb8cb size=18
|     |  |  |  +> java.
|     |  |  |  +> javax.
|     |  |  |  +> org.eclipse.jetty.jaas.
|     |  |  |  +> org.eclipse.jetty.jndi.
|     |  |  |  +> org.eclipse.jetty.jsp.
|     |  |  |  +> org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter
|     |  |  |  +> org.eclipse.jetty.servlets.PushSessionCacheFilter
|     |  |  |  +> org.eclipse.jetty.util.annotations.
|     |  |  |  +> org.eclipse.jetty.websocket.api.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> org.eclipse.jetty.websocket.server.
|     |  |  |  +> org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.w3c.
|     |  |  |  +> org.xml.
|     |  |  +> Serverclasses Transparent Proxy WebApp@727eb8cb size=23
|     |  |  |  +> -org.eclipse.jetty.apache.
|     |  |  |  +> -org.eclipse.jetty.jaas.
|     |  |  |  +> -org.eclipse.jetty.jndi.
|     |  |  |  +> -org.eclipse.jetty.jsp.
|     |  |  |  +> -org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.listener.
|     |  |  |  +> -org.eclipse.jetty.servlets.
|     |  |  |  +> -org.eclipse.jetty.util.annotations.
|     |  |  |  +> -org.eclipse.jetty.websocket.api.
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> -org.eclipse.jetty.websocket.server.
|     |  |  |  +> -org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.eclipse.jdt.
|     |  |  |  +> org.eclipse.jetty.
|     |  |  |  +> org.eclipse.jetty.logging.
|     |  |  |  +> org.eclipse.jetty.server.config.
|     |  |  |  +> org.eclipse.jetty.server.internal.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.internal
|     |  |  |  +> org.objectweb.asm.
|     |  |  |  +> org.slf4j.
|     |  |  +> Configurations Transparent Proxy WebApp@727eb8cb size=15
|     |  |  |  +> org.eclipse.jetty.webapp.WebInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebXmlConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.MetaInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.FragmentConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JaasConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JndiConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JspConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.JavaxWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebAppConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.ServletsConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration
|     |  |  |  +> org.eclipse.jetty.annotations.AnnotationConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration
|     |  |  +> Handler attributes Transparent Proxy WebApp@727eb8cb size=7
|     |  |  |  +> javax.servlet.context.tempdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-
|     |  |  |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |  |  |  +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@2032e725
|     |  |  |  +> org.eclipse.jetty.webapp.tmpResourceBase=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp
|     |  |  |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |  |  |  +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@4d23015c
|     |  |  |  +> org.apache.catalina.jsp_classpath=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/classes:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-alpn-client-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-proxy-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-slf4j-impl-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/WEB-INF/lib/slf4j-api-2.0.0-alpha1.jar
|     |  |  +> Context attributes Transparent Proxy WebApp@727eb8cb size=9
|     |  |  |  +> org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=3]
|     |  |  |  +> org.eclipse.jetty.websocket.api.WebSocketContainer=JettyWebSocketServerContainer@562c877a{STARTED}
|     |  |  |  +> resourceCache=ResourceCache[null,org.eclipse.jetty.servlet.DefaultServlet@57540fd0]@943659381
|     |  |  |  +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@441cc260
|     |  |  |  +> JavadocTransparentProxy.HttpClient=HttpClient@37d3d232{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.WebSocketComponents=WebSocketServerComponents@8a62297{STARTED}
|     |  |  |  +> javax.websocket.server.ServerContainer=JavaxWebSocketServerContainer@989da1{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.server.WebSocketMappings=org.eclipse.jetty.websocket.core.server.WebSocketMappings@67dba613
|     |  |  |  +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@73a00e09
|     |  |  +> EventListeners o.e.j.w.WebAppContext@727eb8cb{Transparent Proxy WebApp,/proxy,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-proxy_war-_demo-proxy-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-proxy.war} size=5
|     |  |  |  +> JettyServerFrameHandlerFactory@4cafa9aa{STARTED} - STARTED
|     |  |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  |  +> JettyWebSocketServerContainer@562c877a{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@67001148{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> JavaxWebSocketServerContainer@989da1{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@31cb96e1{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@3eed0f5
|     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@64030b91
|     |  |  +> Initparams Transparent Proxy WebApp@727eb8cb size=0
|     |  += o.e.j.w.WebAppContext@5b7a8434{Test Annotations WebApp,/test-spec,[file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/, jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-web-fragment-{VERSION}.jar!/META-INF/resources],AVAILABLE}{/home/user/my-base/webapps/demo-spec.war} - STARTED
|     |  |  += org.eclipse.jetty.server.session.SessionHandler652007616==dftMaxIdleSec=10800 - STARTED
|     |  |  |  += ConstraintSecurityHandler@66e889df{STARTED} - STARTED
|     |  |  |  |  +- knownAuthenticatorFactories size=1
|     |  |  |  |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@34523d46
|     |  |  |  |  += ServletHandler@444548a0{STARTED} - STARTED
|     |  |  |  |  |  +> listeners ServletHandler@444548a0{STARTED} size=5
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@3766c667{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@773c0293{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  +> com.acme.test.TestListener@55b8dbda{src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |  |  |  |  +> com.acme.test.AnnotatedListener@3b569985{src=ANNOTATION:com.acme.test.AnnotatedListener} - STARTED
|     |  |  |  |  |  |  +> com.acme.initializer.FooInitializer$FooListener@3a022576{src=JAVAX_API:null} - STARTED
|     |  |  |  |  |  +> filters ServletHandler@444548a0{STARTED} size=1
|     |  |  |  |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter==org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@515f4131{inst=true,async=true,src=EMBEDDED:null} - STARTED
|     |  |  |  |  |  |     +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@2dbd803f
|     |  |  |  |  |  |        +> org.eclipse.jetty.websocket.core.server.WebSocketMappings@3e48e859
|     |  |  |  |  |  |           +> PathMappings[size=0]
|     |  |  |  |  |  |              +> java.util.TreeSet@0(size=0)
|     |  |  |  |  |  +> filterMappings ServletHandler@444548a0{STARTED} size=1
|     |  |  |  |  |  |  +> [/*]/[]/[REQUEST]=>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter
|     |  |  |  |  |  +> servlets ServletHandler@444548a0{STARTED} size=10
|     |  |  |  |  |  |  +> default==org.eclipse.jetty.servlet.DefaultServlet@5c13d641{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.servlet.DefaultServlet@31ddd4a4
|     |  |  |  |  |  |  |  +> initParams size=9
|     |  |  |  |  |  |  |     +> dirAllowed=true
|     |  |  |  |  |  |  |     +> maxCacheSize=256000000
|     |  |  |  |  |  |  |     +> maxCachedFileSize=200000000
|     |  |  |  |  |  |  |     +> welcomeServlets=false
|     |  |  |  |  |  |  |     +> useFileMappedBuffer=true
|     |  |  |  |  |  |  |     +> acceptRanges=true
|     |  |  |  |  |  |  |     +> etags=false
|     |  |  |  |  |  |  |     +> maxCachedFiles=2048
|     |  |  |  |  |  |  |     +> redirectWelcome=false
|     |  |  |  |  |  |  +> jsp==org.eclipse.jetty.jsp.JettyJspServlet@19c47{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.jsp.JettyJspServlet@1a5f7e7c
|     |  |  |  |  |  |  |  +> initParams size=4
|     |  |  |  |  |  |  |     +> compilerSourceVM=1.8
|     |  |  |  |  |  |  |     +> compilerTargetVM=1.8
|     |  |  |  |  |  |  |     +> scratchdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/jsp
|     |  |  |  |  |  |  |     +> xpoweredBy=false
|     |  |  |  |  |  |  +> AnnotationTest==com.acme.test.AnnotationTest@1a674081{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:RunAs:com.acme.test.AnnotationTest@5b22b970
|     |  |  |  |  |  |  |  +> initParams size=3
|     |  |  |  |  |  |  |     +> extra2=345
|     |  |  |  |  |  |  |     +> fromAnnotation=xyz
|     |  |  |  |  |  |  |     +> extra1=123
|     |  |  |  |  |  |  +> RoleAnnotationTest==com.acme.test.RoleAnnotationTest@a7e37697{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:com.acme.test.RoleAnnotationTest@22d1886d
|     |  |  |  |  |  |  +> Multi==com.acme.test.MultiPartTest@473e519{jsp=null,order=2,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:com.acme.test.MultiPartTest@7df60067
|     |  |  |  |  |  |  +> com.acme.test.SecuredServlet==com.acme.test.SecuredServlet@f7e523cd{jsp=null,order=2147483647,inst=true,async=false,src=ANNOTATION:com.acme.test.SecuredServlet} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:com.acme.test.SecuredServlet@1cbb3d3b
|     |  |  |  |  |  |  +> com.acme.test.AsyncListenerServlet==com.acme.test.AsyncListenerServlet@cb673b2a{jsp=null,order=-1,inst=false,async=true,src=ANNOTATION:com.acme.test.AsyncListenerServlet} - STARTED
|     |  |  |  |  |  |  |  +> class com.acme.test.AsyncListenerServlet
|     |  |  |  |  |  |  +> com.acme.test.ClassLoaderServlet==com.acme.test.ClassLoaderServlet@b51e63af{jsp=null,order=-1,inst=false,async=false,src=ANNOTATION:com.acme.test.ClassLoaderServlet} - STARTED
|     |  |  |  |  |  |  |  +> class com.acme.test.ClassLoaderServlet
|     |  |  |  |  |  |  +> Fragment==com.acme.fragment.FragmentServlet@a17d4670{jsp=null,order=-1,inst=false,async=false,src=DESCRIPTOR:jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-web-fragment-{VERSION}.jar!/META-INF/web-fragment.xml} - STARTED
|     |  |  |  |  |  |  |  +> class com.acme.fragment.FragmentServlet
|     |  |  |  |  |  |  +> dynamic.jsp==org.eclipse.jetty.jsp.JettyJspServlet@f083ae18{jsp=/dynamic.jsp,order=-1,inst=false,async=false,src=JAVAX_API:null} - STARTED
|     |  |  |  |  |  |     +> class org.eclipse.jetty.jsp.JettyJspServlet
|     |  |  |  |  |  |     +> initParams size=4
|     |  |  |  |  |  |        +> compilerSourceVM=1.8
|     |  |  |  |  |  |        +> compilerTargetVM=1.8
|     |  |  |  |  |  |        +> jspFile=/dynamic.jsp
|     |  |  |  |  |  |        +> xpoweredBy=false
|     |  |  |  |  |  +> servletMappings ServletHandler@444548a0{STARTED} size=10
|     |  |  |  |  |     +> [/]=>default
|     |  |  |  |  |     +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
|     |  |  |  |  |     +> [/test/*]=>AnnotationTest
|     |  |  |  |  |     +> [/role/*]=>RoleAnnotationTest
|     |  |  |  |  |     +> [/multi/*]=>Multi
|     |  |  |  |  |     +> [/sec/*]=>com.acme.test.SecuredServlet
|     |  |  |  |  |     +> [/asy/*]=>com.acme.test.AsyncListenerServlet
|     |  |  |  |  |     +> [/classloader]=>com.acme.test.ClassLoaderServlet
|     |  |  |  |  |     +> [/fragment/*]=>Fragment
|     |  |  |  |  |     +> [/dynamicjsp/*]=>dynamic.jsp
|     |  |  |  |  +~ HashLoginService@2eb79cbe[Test Realm] - STARTED
|     |  |  |  |  +~ org.eclipse.jetty.security.DefaultIdentityService@2ca6546f
|     |  |  |  |  +- org.eclipse.jetty.security.authentication.FormAuthenticator@529cfee5
|     |  |  |  |  +> roles size=1
|     |  |  |  |  |  +> java.util.concurrent.CopyOnWriteArraySet@2d5cd4a8(size=4)
|     |  |  |  |  |     +: admin
|     |  |  |  |  |     +: server-administrator
|     |  |  |  |  |     +: user
|     |  |  |  |  |     +: client
|     |  |  |  |  +> constraints size=1
|     |  |  |  |     +> java.util.concurrent.CopyOnWriteArrayList@88079198(size=4)
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@7ca0863b
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@319854f0
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@748fe51d
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@415156bf
|     |  |  |  +- com.acme.test.TestListener@393881f0
|     |  |  |  +- com.acme.test.AnnotatedListener@4af46df3
|     |  |  |  += org.eclipse.jetty.server.session.DefaultSessionCache@4158debd[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|     |  |  |  |  += org.eclipse.jetty.server.session.NullSessionDataStore@af78c87[passivating=false,graceSec=3600] - STARTED
|     |  |  |  +~ DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|     |  |  += ErrorPageErrorHandler@773dab28{STARTED} - STARTED
|     |  |  +- java:comp org.eclipse.jetty.jndi.NamingContext@1ecfcbc9[name=comp,parent=org.eclipse.jetty.jndi.NamingContext@2cfbeac4,bindings.size=2]
|     |  |  |  +@ UserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |  +@ env = org.eclipse.jetty.jndi.NamingContext@1965539b[name=env,parent=org.eclipse.jetty.jndi.NamingContext@1ecfcbc9,bindings.size=8]
|     |  |  |     +@ __ = org.eclipse.jetty.jndi.NamingContext@2fc07784[name=__,parent=org.eclipse.jetty.jndi.NamingContext@1965539b,bindings.size=2]
|     |  |  |     |  +@ woggle = org.eclipse.jetty.plus.jndi.EnvEntry@41f35f7c{name=woggle,OverrideWebXml=false}
|     |  |  |     |  +@ maxAmount = org.eclipse.jetty.plus.jndi.EnvEntry@353efdbf{name=maxAmount,OverrideWebXml=true}
|     |  |  |     +@ someAmount = 0.99
|     |  |  |     +@ com.acme.test.AnnotationTest = org.eclipse.jetty.jndi.NamingContext@55cff952[name=com.acme.test.AnnotationTest,parent=org.eclipse.jetty.jndi.NamingContext@1965539b,bindings.size=4]
|     |  |  |     |  +@ myDatasource = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@5b7a8434/jdbc/mydatasource|
|     |  |  |     |  +@ avgAmount = 1.25
|     |  |  |     |  +@ maxAmount = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@5b7a8434/maxAmount|
|     |  |  |     |  +@ myUserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |     +@ com.acme.test.TestListener$ValidListener = org.eclipse.jetty.jndi.NamingContext@660591fb[name=com.acme.test.TestListener$ValidListener,parent=org.eclipse.jetty.jndi.NamingContext@1965539b,bindings.size=1]
|     |  |  |     |  +@ maxAmount = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@5b7a8434/maxAmount|
|     |  |  |     +@ com.acme.test.AnnotatedListener = org.eclipse.jetty.jndi.NamingContext@4a55a6e8[name=com.acme.test.AnnotatedListener,parent=org.eclipse.jetty.jndi.NamingContext@1965539b,bindings.size=1]
|     |  |  |     |  +@ maxAmount = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@5b7a8434/maxAmount|
|     |  |  |     +@ woggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: woggle|
|     |  |  |     +@ maxAmount = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@5b7a8434/maxAmount|
|     |  |  |     +@ com.acme.test.TestListener = org.eclipse.jetty.jndi.NamingContext@8c46918[name=com.acme.test.TestListener,parent=org.eclipse.jetty.jndi.NamingContext@1965539b,bindings.size=1]
|     |  |  |        +@ maxAmount = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: org.eclipse.jetty.webapp.WebAppContext@5b7a8434/maxAmount|
|     |  |  += JavaxWebSocketServerContainer@226b143b{STARTED} - STARTED
|     |  |  |  += SessionTracker@682bd3c4{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  += JettyServerFrameHandlerFactory@f2e4acf{STARTED} - STARTED
|     |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  += JettyWebSocketServerContainer@24097e9b{STARTED} - STARTED
|     |  |  |  += SessionTracker@5eb97ced{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  +- org.eclipse.jetty.servlet.listener.ELContextCleaner@68ba310d
|     |  |  +- org.eclipse.jetty.servlet.listener.IntrospectorCleaner@153f66e7
|     |  |  +- com.acme.test.TestListener@393881f0
|     |  |  +- com.acme.test.AnnotatedListener@4af46df3
|     |  |  +- com.acme.initializer.FooInitializer$FooListener@7aad3f7d
|     |  |  +> WebAppClassLoader{Test Annotations WebApp}@1556f2dd
|     |  |  |  +> URLs size=3
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/classes/
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-container-initializer-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-web-fragment-{VERSION}.jar
|     |  |  |  +> startJarLoader@3d012ddd
|     |  |  +> Systemclasses Test Annotations WebApp@5b7a8434 size=18
|     |  |  |  +> java.
|     |  |  |  +> javax.
|     |  |  |  +> org.eclipse.jetty.jaas.
|     |  |  |  +> org.eclipse.jetty.jndi.
|     |  |  |  +> org.eclipse.jetty.jsp.
|     |  |  |  +> org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter
|     |  |  |  +> org.eclipse.jetty.servlets.PushSessionCacheFilter
|     |  |  |  +> org.eclipse.jetty.util.annotations.
|     |  |  |  +> org.eclipse.jetty.websocket.api.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> org.eclipse.jetty.websocket.server.
|     |  |  |  +> org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.w3c.
|     |  |  |  +> org.xml.
|     |  |  +> Serverclasses Test Annotations WebApp@5b7a8434 size=23
|     |  |  |  +> -org.eclipse.jetty.apache.
|     |  |  |  +> -org.eclipse.jetty.jaas.
|     |  |  |  +> -org.eclipse.jetty.jndi.
|     |  |  |  +> -org.eclipse.jetty.jsp.
|     |  |  |  +> -org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.listener.
|     |  |  |  +> -org.eclipse.jetty.servlets.
|     |  |  |  +> -org.eclipse.jetty.util.annotations.
|     |  |  |  +> -org.eclipse.jetty.websocket.api.
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> -org.eclipse.jetty.websocket.server.
|     |  |  |  +> -org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.eclipse.jdt.
|     |  |  |  +> org.eclipse.jetty.
|     |  |  |  +> org.eclipse.jetty.logging.
|     |  |  |  +> org.eclipse.jetty.server.config.
|     |  |  |  +> org.eclipse.jetty.server.internal.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.internal
|     |  |  |  +> org.objectweb.asm.
|     |  |  |  +> org.slf4j.
|     |  |  +> Configurations Test Annotations WebApp@5b7a8434 size=15
|     |  |  |  +> org.eclipse.jetty.webapp.WebInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebXmlConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.MetaInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.FragmentConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JaasConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JndiConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JspConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.JavaxWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebAppConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.ServletsConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration
|     |  |  |  +> org.eclipse.jetty.annotations.AnnotationConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration
|     |  |  +> Handler attributes Test Annotations WebApp@5b7a8434 size=12
|     |  |  |  +> javax.servlet.context.tempdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-
|     |  |  |  +> response-character-encoding=utf-8
|     |  |  |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |  |  |  +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@6f667ad1
|     |  |  |  +> org.eclipse.jetty.webapp.tmpResourceBase=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp
|     |  |  |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |  |  |  +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@566d0c69
|     |  |  |  +> org.apache.catalina.jsp_classpath=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/classes:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-container-initializer-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-web-fragment-{VERSION}.jar
|     |  |  |  +> default-context-path=/test-spec
|     |  |  |  +> org.eclipse.jetty.jndi.EnvConfiguration=[org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@388b401d, org.eclipse.jetty.plus.webapp.EnvConfiguration$Bound@2bcec6a6]
|     |  |  |  +> javax.servlet.context.orderedLibs=[demo-container-initializer-{VERSION}.jar, demo-web-fragment-{VERSION}.jar]
|     |  |  |  +> request-character-encoding=utf-8
|     |  |  +> Context attributes Test Annotations WebApp@5b7a8434 size=20
|     |  |  |  +> com.acme.AnnotationTest.listenerRegoTest=true
|     |  |  |  +> org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=3]
|     |  |  |  +> org.eclipse.jetty.websocket.api.WebSocketContainer=JettyWebSocketServerContainer@24097e9b{STARTED}
|     |  |  |  +> resourceCache=ResourceCache[null,org.eclipse.jetty.servlet.DefaultServlet@31ddd4a4]@2007138812
|     |  |  |  +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@4912d525
|     |  |  |  +> com.acme.AnnotationTest.sclInjectTest=true
|     |  |  |  +> org.eclipse.jetty.websocket.core.WebSocketComponents=WebSocketServerComponents@8a62297{STARTED}
|     |  |  |  +> com.acme.AnnotationTest.complete=true
|     |  |  |  +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@2bfbffb2
|     |  |  |  +> com.acme.AnnotationTest.sclInjectWebListenerTest=true
|     |  |  |  +> com.acme.Foo=[class com.acme.test.ClassLoaderServlet, class javax.servlet.GenericServlet, class com.acme.test.AsyncListenerServlet, class com.acme.test.Bar, class com.acme.test.SecuredServlet, class javax.servlet.http.HttpServlet, class com.acme.test.MultiPartTest, class com.acme.test.RoleAnnotationTest, class com.acme.test.AnnotationTest, class com.acme.fragment.FragmentServlet, class com.acme.test.TestListener]
|     |  |  |  +> com.acme.AnnotationTest.listenerTest=true
|     |  |  |  +> com.acme.AnnotationTest.programListenerInjectTest=true
|     |  |  |  +> com.acme.AnnotationTest.sclGetSessionTimeout=true
|     |  |  |  +> javax.websocket.server.ServerContainer=JavaxWebSocketServerContainer@226b143b{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.server.WebSocketMappings=org.eclipse.jetty.websocket.core.server.WebSocketMappings@3e48e859
|     |  |  |  +> com.acme.AnnotationTest.invalidListenerRegoTest=true
|     |  |  |  +> com.acme.jsp.file=true
|     |  |  |  +> com.acme.AnnotationTest.sclFromSclRegoTest=true
|     |  |  |  +> com.acme.AnnotationTest.sclSetSessionTimeout=true
|     |  |  +> EventListeners o.e.j.w.WebAppContext@5b7a8434{Test Annotations WebApp,/test-spec,[file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/, jar:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-spec_war-_test-spec-any-/webapp/WEB-INF/lib/demo-web-fragment-{VERSION}.jar!/META-INF/resources],AVAILABLE}{/home/user/my-base/webapps/demo-spec.war} size=8
|     |  |  |  +> JavaxWebSocketServerContainer@226b143b{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@682bd3c4{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> JettyServerFrameHandlerFactory@f2e4acf{STARTED} - STARTED
|     |  |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  |  +> JettyWebSocketServerContainer@24097e9b{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@5eb97ced{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@68ba310d
|     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@153f66e7
|     |  |  |  +> com.acme.test.TestListener@393881f0
|     |  |  |  +> com.acme.test.AnnotatedListener@4af46df3
|     |  |  |  +> com.acme.initializer.FooInitializer$FooListener@7aad3f7d
|     |  |  +> Initparams Test Annotations WebApp@5b7a8434 size=0
|     |  += o.e.j.w.WebAppContext@1fb669c3{Test WebApp,/test,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jetty.war} - STARTED
|     |  |  += ErrorPageErrorHandler@765df79d{STARTED} - STARTED
|     |  |  += GzipHandler@151335cb{STARTED,min=2048,inflate=-1} - STARTED
|     |  |  |  += org.eclipse.jetty.server.session.SessionHandler1249337777==dftMaxIdleSec=3240 - STARTED
|     |  |  |     += ConstraintSecurityHandler@3e850122{STARTED} - STARTED
|     |  |  |     |  +- knownAuthenticatorFactories size=1
|     |  |  |     |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@34523d46
|     |  |  |     |  += ServletHandler@27fde870{STARTED} - STARTED
|     |  |  |     |  |  +> listeners ServletHandler@27fde870{STARTED} size=5
|     |  |  |     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@2b4c3c29{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@5ac7aa18{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |     |  |  |  +> com.acme.TestListener@4cdd2c73{src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  +> com.acme.TagListener@4abf3f0{src=JAVAX_API:null} - STARTED
|     |  |  |     |  |  |  +> com.acme.AddListServletRequestListener@4e4c3a38{src=JAVAX_API:null} - STARTED
|     |  |  |     |  |  +> filters ServletHandler@27fde870{STARTED} size=4
|     |  |  |     |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter==org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@3961a41a{inst=true,async=true,src=EMBEDDED:null} - STARTED
|     |  |  |     |  |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@293cde83
|     |  |  |     |  |  |  |     +> org.eclipse.jetty.websocket.core.server.WebSocketMappings@c27d163
|     |  |  |     |  |  |  |        +> PathMappings[size=1]
|     |  |  |     |  |  |  |           +> java.util.TreeSet@71c94a0d(size=1)
|     |  |  |     |  |  |  |              +: MappedResource[pathSpec=UriTemplatePathSpec@71c949ee{/javax.websocket/},resource=CreatorNegotiator@57c88764{JsrCreator[@com.acme.JavaxWebSocketChat],org.eclipse.jetty.websocket.javax.server.internal.JavaxWebSocketServerFrameHandlerFactory@78faea5f}]
|     |  |  |     |  |  |  +> PushFilter==org.eclipse.jetty.servlets.PushCacheFilter@37fdfb05{inst=true,async=true,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter@5e39850
|     |  |  |     |  |  |  +> QoSFilter==org.eclipse.jetty.servlets.QoSFilter@1603dc2f{inst=true,async=true,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> org.eclipse.jetty.servlets.QoSFilter@143d9a93
|     |  |  |     |  |  |  |  +> initParams size=2
|     |  |  |     |  |  |  |     +> maxRequests=10000
|     |  |  |     |  |  |  |     +> managedAttr=true
|     |  |  |     |  |  |  +> TestFilter==com.acme.TestFilter@398474a2{inst=true,async=true,src=JAVAX_API:null} - STARTED
|     |  |  |     |  |  |     +> com.acme.TestFilter@61799544
|     |  |  |     |  |  |     +> initParams size=1
|     |  |  |     |  |  |        +> remote=false
|     |  |  |     |  |  +> filterMappings ServletHandler@27fde870{STARTED} size=4
|     |  |  |     |  |  |  +> [/*]/[]/[REQUEST]=>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter
|     |  |  |     |  |  |  +> [/*]/[]/[ASYNC, REQUEST]=>PushFilter
|     |  |  |     |  |  |  +> [/*]/[]/[ASYNC, REQUEST]=>QoSFilter
|     |  |  |     |  |  |  +> [/*]/[]/[ASYNC, INCLUDE, REQUEST, FORWARD, ERROR]=>TestFilter
|     |  |  |     |  |  +> servlets ServletHandler@27fde870{STARTED} size=17
|     |  |  |     |  |  |  +> default==org.eclipse.jetty.servlet.DefaultServlet@5c13d641{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:org.eclipse.jetty.servlet.DefaultServlet@325bb9a6
|     |  |  |     |  |  |  |  +> initParams size=10
|     |  |  |     |  |  |  |     +> dirAllowed=true
|     |  |  |     |  |  |  |     +> maxCacheSize=256000000
|     |  |  |     |  |  |  |     +> maxCachedFileSize=200000000
|     |  |  |     |  |  |  |     +> welcomeServlets=false
|     |  |  |     |  |  |  |     +> precompressed=true
|     |  |  |     |  |  |  |     +> useFileMappedBuffer=true
|     |  |  |     |  |  |  |     +> acceptRanges=true
|     |  |  |     |  |  |  |     +> etags=false
|     |  |  |     |  |  |  |     +> maxCachedFiles=2048
|     |  |  |     |  |  |  |     +> redirectWelcome=false
|     |  |  |     |  |  |  +> jsp==org.eclipse.jetty.jsp.JettyJspServlet@19c47{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:org.eclipse.jetty.jsp.JettyJspServlet@1d12b024
|     |  |  |     |  |  |  |  +> initParams size=4
|     |  |  |     |  |  |  |     +> compilerSourceVM=1.8
|     |  |  |     |  |  |  |     +> compilerTargetVM=1.8
|     |  |  |     |  |  |  |     +> scratchdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/jsp
|     |  |  |     |  |  |  |     +> xpoweredBy=false
|     |  |  |     |  |  |  +> Login==com.acme.LoginServlet@462ff49{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:com.acme.LoginServlet@72fe8a4f
|     |  |  |     |  |  |  +> Hello==com.acme.HelloWorld@42628b2{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:com.acme.HelloWorld@43effd89
|     |  |  |     |  |  |  +> Dump==com.acme.Dump@20ae14{jsp=null,order=1,inst=true,async=true,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> RunAs:com.acme.Dump@2c16fadb
|     |  |  |     |  |  |  |  +> initParams size=1
|     |  |  |     |  |  |  |     +> servlet-override-example=a servlet value
|     |  |  |     |  |  |  +> Session==com.acme.SessionDump@d9891a76{jsp=null,order=5,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:com.acme.SessionDump@248deced
|     |  |  |     |  |  |  +> Cookie==com.acme.CookieDump@78a4f684{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:com.acme.CookieDump@2227a6c1
|     |  |  |     |  |  |  +> Dispatch==com.acme.DispatchServlet@14d3a89a{jsp=null,order=1,inst=true,async=true,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> com.acme.DispatchServlet@1e9804b9
|     |  |  |     |  |  |  +> CGI==org.eclipse.jetty.servlets.CGI@10465{jsp=null,order=1,inst=true,async=true,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> org.eclipse.jetty.servlets.CGI@543e593
|     |  |  |     |  |  |  +> Chat==com.acme.ChatServlet@200778{jsp=null,order=1,inst=true,async=true,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> com.acme.ChatServlet@4e628b52
|     |  |  |     |  |  |  +> WSChat==com.acme.WebSocketChatServlet@99274454{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:com.acme.WebSocketChatServlet@51ec2df1
|     |  |  |     |  |  |  +> Rewrite==com.acme.RewriteServlet@a4dac96c{jsp=null,order=-1,inst=false,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> class com.acme.RewriteServlet
|     |  |  |     |  |  |  +> SecureMode==com.acme.SecureModeServlet@d45951da{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:com.acme.SecureModeServlet@f8f56b9
|     |  |  |     |  |  |  +> foo.jsp==org.eclipse.jetty.jsp.JettyJspServlet@d7583f1f{jsp=/jsp/foo/foo.jsp,order=-1,inst=false,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> class org.eclipse.jetty.jsp.JettyJspServlet
|     |  |  |     |  |  |  |  +> initParams size=4
|     |  |  |     |  |  |  |     +> compilerSourceVM=1.8
|     |  |  |     |  |  |  |     +> compilerTargetVM=1.8
|     |  |  |     |  |  |  |     +> jspFile=/jsp/foo/foo.jsp
|     |  |  |     |  |  |  |     +> xpoweredBy=false
|     |  |  |     |  |  |  +> TestServlet==com.acme.TestServlet@c246e533{jsp=null,order=10,inst=true,async=false,src=DESCRIPTOR:file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/web.xml} - STARTED
|     |  |  |     |  |  |  |  +> NotAsync:com.acme.TestServlet@15fa55a6
|     |  |  |     |  |  |  +> RegoTest==com.acme.RegTest@dafcd1ad{jsp=null,order=-1,inst=false,async=false,src=JAVAX_API:null} - STARTED
|     |  |  |     |  |  |  |  +> class com.acme.RegTest
|     |  |  |     |  |  |  +> RegoTest2==com.acme.RegTest@849d6425{jsp=null,order=-1,inst=false,async=false,src=JAVAX_API:null} - STARTED
|     |  |  |     |  |  |     +> class com.acme.RegTest
|     |  |  |     |  |  +> servletMappings ServletHandler@27fde870{STARTED} size=18
|     |  |  |     |  |     +> [/]=>default
|     |  |  |     |  |     +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
|     |  |  |     |  |     +> [/login/*]=>Login
|     |  |  |     |  |     +> [/hello/*]=>Hello
|     |  |  |     |  |     +> [/dump/*, *.dump]=>Dump
|     |  |  |     |  |     +> [/session/*]=>Session
|     |  |  |     |  |     +> [/cookie/*]=>Cookie
|     |  |  |     |  |     +> [/dispatch/*]=>Dispatch
|     |  |  |     |  |     +> [/cgi-bin/*]=>CGI
|     |  |  |     |  |     +> [/chat/*]=>Chat
|     |  |  |     |  |     +> [/ws/*]=>WSChat
|     |  |  |     |  |     +> [/rewritten/*, /redirected/*]=>Rewrite
|     |  |  |     |  |     +> [/secureMode/*]=>SecureMode
|     |  |  |     |  |     +> [/jsp/foo/]=>foo.jsp
|     |  |  |     |  |     +> [/testservlet/*]=>TestServlet
|     |  |  |     |  |     +> [*.more]=>Dump
|     |  |  |     |  |     +> [/rego/*]=>RegoTest
|     |  |  |     |  |     +> [/rego2/*]=>RegoTest2
|     |  |  |     |  +~ HashLoginService@2eb79cbe[Test Realm] - STARTED
|     |  |  |     |  +~ org.eclipse.jetty.security.DefaultIdentityService@2ca6546f
|     |  |  |     |  +- org.eclipse.jetty.security.authentication.FormAuthenticator@4f186450
|     |  |  |     |  +> roles size=1
|     |  |  |     |  |  +> java.util.concurrent.CopyOnWriteArraySet@7e49e0dd(size=3)
|     |  |  |     |  |     +: server-administrator
|     |  |  |     |  |     +: admin
|     |  |  |     |  |     +: user
|     |  |  |     |  +> constraints size=1
|     |  |  |     |     +> java.util.concurrent.CopyOnWriteArrayList@528618f2(size=13)
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@7fab4be7
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@a64e035
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@4d74c3ba
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@41c204a0
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@64138b0c
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@49dbaaf3
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@22d9c961
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@736f3e9e
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@bdc8014
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@1f443fae
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@73ba6fe6
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@79ab34c1
|     |  |  |     |        +: org.eclipse.jetty.security.ConstraintMapping@1698d7c0
|     |  |  |     +- com.acme.TestListener@281f23f2
|     |  |  |     +- com.acme.TagListener@87abc48
|     |  |  |     += org.eclipse.jetty.server.session.DefaultSessionCache@28d79cba[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|     |  |  |     |  += org.eclipse.jetty.server.session.NullSessionDataStore@782168b7[passivating=false,graceSec=3600] - STARTED
|     |  |  |     +~ DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|     |  |  +- java:comp org.eclipse.jetty.jndi.NamingContext@29f0c4f2[name=comp,parent=org.eclipse.jetty.jndi.NamingContext@2cfbeac4,bindings.size=2]
|     |  |  |  +@ UserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |  +@ env = org.eclipse.jetty.jndi.NamingContext@7435a578[name=env,parent=org.eclipse.jetty.jndi.NamingContext@29f0c4f2,bindings.size=2]
|     |  |  |     +@ __ = org.eclipse.jetty.jndi.NamingContext@6093d508[name=__,parent=org.eclipse.jetty.jndi.NamingContext@7435a578,bindings.size=1]
|     |  |  |     |  +@ woggle = org.eclipse.jetty.plus.jndi.EnvEntry@41f35f7c{name=woggle,OverrideWebXml=false}
|     |  |  |     +@ woggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: woggle|
|     |  |  += JettyServerFrameHandlerFactory@13047d7d{STARTED} - STARTED
|     |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  += JettyWebSocketServerContainer@3c7cfcbb{STARTED} - STARTED
|     |  |  |  += SessionTracker@65bb9029{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  += JavaxWebSocketServerContainer@1bfe3203{STARTED} - STARTED
|     |  |  |  += SessionTracker@2b214b94{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  +- org.eclipse.jetty.servlet.listener.ELContextCleaner@70e3f36f
|     |  |  +- org.eclipse.jetty.servlet.listener.IntrospectorCleaner@49601f82
|     |  |  +- com.acme.TestListener@281f23f2
|     |  |  +- com.acme.TagListener@87abc48
|     |  |  +- org.eclipse.jetty.server.handler.ManagedAttributeListener@23e44287
|     |  |  +- com.acme.AddListServletRequestListener@2b8d084
|     |  |  +~ org.eclipse.jetty.servlets.PushCacheFilter@5e39850
|     |  |  +~ org.eclipse.jetty.servlets.QoSFilter@143d9a93
|     |  |  +> WebAppClassLoader{Test WebApp}@410e94e
|     |  |  |  +> URLs size=3
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/classes/
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/lib/jetty-slf4j-impl-{VERSION}.jar
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/lib/slf4j-api-2.0.0-alpha1.jar
|     |  |  |  +> startJarLoader@3d012ddd
|     |  |  +> Systemclasses Test WebApp@1fb669c3 size=18
|     |  |  |  +> java.
|     |  |  |  +> javax.
|     |  |  |  +> org.eclipse.jetty.jaas.
|     |  |  |  +> org.eclipse.jetty.jndi.
|     |  |  |  +> org.eclipse.jetty.jsp.
|     |  |  |  +> org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter
|     |  |  |  +> org.eclipse.jetty.servlets.PushSessionCacheFilter
|     |  |  |  +> org.eclipse.jetty.util.annotations.
|     |  |  |  +> org.eclipse.jetty.websocket.api.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> org.eclipse.jetty.websocket.server.
|     |  |  |  +> org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.w3c.
|     |  |  |  +> org.xml.
|     |  |  +> Serverclasses Test WebApp@1fb669c3 size=24
|     |  |  |  +> -org.eclipse.jetty.apache.
|     |  |  |  +> -org.eclipse.jetty.jaas.
|     |  |  |  +> -org.eclipse.jetty.jndi.
|     |  |  |  +> -org.eclipse.jetty.jsp.
|     |  |  |  +> -org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.listener.
|     |  |  |  +> -org.eclipse.jetty.servlets.
|     |  |  |  +> -org.eclipse.jetty.util.
|     |  |  |  +> -org.eclipse.jetty.util.annotations.
|     |  |  |  +> -org.eclipse.jetty.websocket.api.
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> -org.eclipse.jetty.websocket.server.
|     |  |  |  +> -org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.eclipse.jdt.
|     |  |  |  +> org.eclipse.jetty.
|     |  |  |  +> org.eclipse.jetty.logging.
|     |  |  |  +> org.eclipse.jetty.server.config.
|     |  |  |  +> org.eclipse.jetty.server.internal.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.internal
|     |  |  |  +> org.objectweb.asm.
|     |  |  |  +> org.slf4j.
|     |  |  +> Configurations Test WebApp@1fb669c3 size=15
|     |  |  |  +> org.eclipse.jetty.webapp.WebInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebXmlConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.MetaInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.FragmentConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JaasConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JndiConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JspConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.JavaxWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebAppConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.ServletsConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration
|     |  |  |  +> org.eclipse.jetty.annotations.AnnotationConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration
|     |  |  +> Handler attributes Test WebApp@1fb669c3 size=8
|     |  |  |  +> javax.servlet.context.tempdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-
|     |  |  |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |  |  |  +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@6daf2337
|     |  |  |  +> org.eclipse.jetty.webapp.tmpResourceBase=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp
|     |  |  |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |  |  |  +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@24fabd0f
|     |  |  |  +> org.apache.catalina.jsp_classpath=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/classes:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/lib/jetty-slf4j-impl-{VERSION}.jar:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/WEB-INF/lib/slf4j-api-2.0.0-alpha1.jar
|     |  |  |  +> org.eclipse.jetty.websocket.javax=true
|     |  |  +> Context attributes Test WebApp@1fb669c3 size=10
|     |  |  |  +> QoSFilter=org.eclipse.jetty.servlets.QoSFilter@143d9a93
|     |  |  |  +> org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=3]
|     |  |  |  +> org.eclipse.jetty.websocket.api.WebSocketContainer=JettyWebSocketServerContainer@3c7cfcbb{STARTED}
|     |  |  |  +> resourceCache=ResourceCache[null,org.eclipse.jetty.servlet.DefaultServlet@325bb9a6]@621486957
|     |  |  |  +> PushFilter=org.eclipse.jetty.servlets.PushCacheFilter@5e39850
|     |  |  |  +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@61f3fbb8
|     |  |  |  +> org.eclipse.jetty.websocket.core.WebSocketComponents=WebSocketServerComponents@8a62297{STARTED}
|     |  |  |  +> javax.websocket.server.ServerContainer=JavaxWebSocketServerContainer@1bfe3203{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.server.WebSocketMappings=org.eclipse.jetty.websocket.core.server.WebSocketMappings@c27d163
|     |  |  |  +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@7551da2a
|     |  |  +> EventListeners o.e.j.w.WebAppContext@1fb669c3{Test WebApp,/test,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jetty_war-_test-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jetty.war} size=9
|     |  |  |  +> JettyServerFrameHandlerFactory@13047d7d{STARTED} - STARTED
|     |  |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  |  +> JettyWebSocketServerContainer@3c7cfcbb{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@65bb9029{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> JavaxWebSocketServerContainer@1bfe3203{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@2b214b94{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@70e3f36f
|     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@49601f82
|     |  |  |  +> com.acme.TestListener@281f23f2
|     |  |  |  +> com.acme.TagListener@87abc48
|     |  |  |  +> org.eclipse.jetty.server.handler.ManagedAttributeListener@23e44287
|     |  |  |  +> com.acme.AddListServletRequestListener@2b8d084
|     |  |  +> Initparams Test WebApp@1fb669c3 size=2
|     |  |     +> org.eclipse.jetty.server.context.ManagedAttributes=PushFilter,QoSFilter,TransparentProxy.ThreadPool,TransparentProxy.HttpClient
|     |  |     +> context-override-example=a context value
|     |  += o.e.j.w.WebAppContext@1869fbd2{JAAS Test,/test-jaas,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jaas.war} - STARTED
|     |  |  += org.eclipse.jetty.server.session.SessionHandler70386506==dftMaxIdleSec=1800 - STARTED
|     |  |  |  += ConstraintSecurityHandler@78de58ea{STARTED} - STARTED
|     |  |  |  |  +- knownAuthenticatorFactories size=1
|     |  |  |  |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@34523d46
|     |  |  |  |  += JAASLoginService@60e5272{STARTED} - STARTED
|     |  |  |  |  |  += PropertyUserStoreManager@7d755813{STARTED} - STARTED
|     |  |  |  |  += ServletHandler@69c93ca4{STARTED} - STARTED
|     |  |  |  |  |  +> listeners ServletHandler@69c93ca4{STARTED} size=2
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@63da207f{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@173373b4{src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  +> filters ServletHandler@69c93ca4{STARTED} size=1
|     |  |  |  |  |  |  +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter==org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@4905c46b{inst=true,async=true,src=EMBEDDED:null} - STARTED
|     |  |  |  |  |  |     +> org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter@40d10481
|     |  |  |  |  |  |        +> org.eclipse.jetty.websocket.core.server.WebSocketMappings@60dd3c23
|     |  |  |  |  |  |           +> PathMappings[size=0]
|     |  |  |  |  |  |              +> java.util.TreeSet@0(size=0)
|     |  |  |  |  |  +> filterMappings ServletHandler@69c93ca4{STARTED} size=1
|     |  |  |  |  |  |  +> [/*]/[]/[REQUEST]=>org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter
|     |  |  |  |  |  +> servlets ServletHandler@69c93ca4{STARTED} size=2
|     |  |  |  |  |  |  +> default==org.eclipse.jetty.servlet.DefaultServlet@5c13d641{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |  |  +> NotAsync:org.eclipse.jetty.servlet.DefaultServlet@52b6319f
|     |  |  |  |  |  |  |  +> initParams size=9
|     |  |  |  |  |  |  |     +> dirAllowed=true
|     |  |  |  |  |  |  |     +> maxCacheSize=256000000
|     |  |  |  |  |  |  |     +> maxCachedFileSize=200000000
|     |  |  |  |  |  |  |     +> welcomeServlets=false
|     |  |  |  |  |  |  |     +> useFileMappedBuffer=true
|     |  |  |  |  |  |  |     +> acceptRanges=true
|     |  |  |  |  |  |  |     +> etags=false
|     |  |  |  |  |  |  |     +> maxCachedFiles=2048
|     |  |  |  |  |  |  |     +> redirectWelcome=false
|     |  |  |  |  |  |  +> jsp==org.eclipse.jetty.jsp.JettyJspServlet@19c47{jsp=null,order=0,inst=true,async=false,src=DESCRIPTOR:file:///home/user/jetty-home-{VERSION}/etc/webdefault.xml} - STARTED
|     |  |  |  |  |  |     +> NotAsync:org.eclipse.jetty.jsp.JettyJspServlet@5e9456ae
|     |  |  |  |  |  |     +> initParams size=4
|     |  |  |  |  |  |        +> compilerSourceVM=1.8
|     |  |  |  |  |  |        +> compilerTargetVM=1.8
|     |  |  |  |  |  |        +> scratchdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-/jsp
|     |  |  |  |  |  |        +> xpoweredBy=false
|     |  |  |  |  |  +> servletMappings ServletHandler@69c93ca4{STARTED} size=2
|     |  |  |  |  |     +> [/]=>default
|     |  |  |  |  |     +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
|     |  |  |  |  +- org.eclipse.jetty.security.DefaultIdentityService@16a9a4f1
|     |  |  |  |  +- org.eclipse.jetty.security.authentication.FormAuthenticator@1f1cae23
|     |  |  |  |  +> roles size=1
|     |  |  |  |  |  +> java.util.concurrent.CopyOnWriteArraySet@67a8e8b(size=1)
|     |  |  |  |  |     +: roleA
|     |  |  |  |  +> constraints size=1
|     |  |  |  |     +> java.util.concurrent.CopyOnWriteArrayList@eea8e5f7(size=3)
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@7c455e96
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@985696
|     |  |  |  |        +: org.eclipse.jetty.security.ConstraintMapping@5bcde458
|     |  |  |  += org.eclipse.jetty.server.session.DefaultSessionCache@215a34b4[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|     |  |  |  |  += org.eclipse.jetty.server.session.NullSessionDataStore@77bd7fe7[passivating=false,graceSec=3600] - STARTED
|     |  |  |  +~ DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|     |  |  += ErrorPageErrorHandler@35d3ab60{STARTED} - STARTED
|     |  |  +- java:comp org.eclipse.jetty.jndi.NamingContext@10876a6[name=comp,parent=org.eclipse.jetty.jndi.NamingContext@2cfbeac4,bindings.size=2]
|     |  |  |  +@ UserTransaction = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: UserTransaction|
|     |  |  |  +@ env = org.eclipse.jetty.jndi.NamingContext@71870da7[name=env,parent=org.eclipse.jetty.jndi.NamingContext@10876a6,bindings.size=2]
|     |  |  |     +@ __ = org.eclipse.jetty.jndi.NamingContext@6dd91637[name=__,parent=org.eclipse.jetty.jndi.NamingContext@71870da7,bindings.size=1]
|     |  |  |     |  +@ woggle = org.eclipse.jetty.plus.jndi.EnvEntry@41f35f7c{name=woggle,OverrideWebXml=false}
|     |  |  |     +@ woggle = Reference Class Name: javax.naming.LinkRef|Type: LinkAddress|Content: woggle|
|     |  |  += JettyServerFrameHandlerFactory@45792847{STARTED} - STARTED
|     |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  += JettyWebSocketServerContainer@706cb08{STARTED} - STARTED
|     |  |  |  += SessionTracker@4e25147a{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  += JavaxWebSocketServerContainer@6b68cb27{STARTED} - STARTED
|     |  |  |  += SessionTracker@675ffd1d{STARTED} - STARTED
|     |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  +- org.eclipse.jetty.servlet.listener.ELContextCleaner@56303475
|     |  |  +- org.eclipse.jetty.servlet.listener.IntrospectorCleaner@30506c0d
|     |  |  +> WebAppClassLoader{JAAS Test}@4565a70a
|     |  |  |  +> URLs size=1
|     |  |  |  |  +> file:/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-/webapp/WEB-INF/classes/
|     |  |  |  +> startJarLoader@3d012ddd
|     |  |  +> Systemclasses JAAS Test@1869fbd2 size=18
|     |  |  |  +> java.
|     |  |  |  +> javax.
|     |  |  |  +> org.eclipse.jetty.jaas.
|     |  |  |  +> org.eclipse.jetty.jndi.
|     |  |  |  +> org.eclipse.jetty.jsp.
|     |  |  |  +> org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> org.eclipse.jetty.servlets.PushCacheFilter
|     |  |  |  +> org.eclipse.jetty.servlets.PushSessionCacheFilter
|     |  |  |  +> org.eclipse.jetty.util.annotations.
|     |  |  |  +> org.eclipse.jetty.websocket.api.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> org.eclipse.jetty.websocket.server.
|     |  |  |  +> org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.w3c.
|     |  |  |  +> org.xml.
|     |  |  +> Serverclasses JAAS Test@1869fbd2 size=23
|     |  |  |  +> -org.eclipse.jetty.apache.
|     |  |  |  +> -org.eclipse.jetty.jaas.
|     |  |  |  +> -org.eclipse.jetty.jndi.
|     |  |  |  +> -org.eclipse.jetty.jsp.
|     |  |  |  +> -org.eclipse.jetty.servlet.DefaultServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.NoJspServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.StatisticsServlet
|     |  |  |  +> -org.eclipse.jetty.servlet.listener.
|     |  |  |  +> -org.eclipse.jetty.servlets.
|     |  |  |  +> -org.eclipse.jetty.util.annotations.
|     |  |  |  +> -org.eclipse.jetty.websocket.api.
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.client.JavaxWebSocketClientContainerProvider
|     |  |  |  +> -org.eclipse.jetty.websocket.javax.server.config.
|     |  |  |  +> -org.eclipse.jetty.websocket.server.
|     |  |  |  +> -org.eclipse.jetty.websocket.servlet.
|     |  |  |  +> org.eclipse.jdt.
|     |  |  |  +> org.eclipse.jetty.
|     |  |  |  +> org.eclipse.jetty.logging.
|     |  |  |  +> org.eclipse.jetty.server.config.
|     |  |  |  +> org.eclipse.jetty.server.internal.
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.internal
|     |  |  |  +> org.objectweb.asm.
|     |  |  |  +> org.slf4j.
|     |  |  +> Configurations JAAS Test@1869fbd2 size=15
|     |  |  |  +> org.eclipse.jetty.webapp.WebInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebXmlConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.MetaInfConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.FragmentConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JaasConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JndiConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JspConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.javax.server.config.JavaxWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.WebAppConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.ServletsConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration
|     |  |  |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration
|     |  |  |  +> org.eclipse.jetty.annotations.AnnotationConfiguration
|     |  |  |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration
|     |  |  +> Handler attributes JAAS Test@1869fbd2 size=7
|     |  |  |  +> javax.servlet.context.tempdir=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-
|     |  |  |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |  |  |  +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@1dcca8d3
|     |  |  |  +> org.eclipse.jetty.webapp.tmpResourceBase=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-/webapp
|     |  |  |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |  |  |  +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@5631962
|     |  |  |  +> org.apache.catalina.jsp_classpath=/home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-/webapp/WEB-INF/classes
|     |  |  +> Context attributes JAAS Test@1869fbd2 size=8
|     |  |  |  +> org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=3]
|     |  |  |  +> org.eclipse.jetty.websocket.api.WebSocketContainer=JettyWebSocketServerContainer@706cb08{STARTED}
|     |  |  |  +> resourceCache=ResourceCache[null,org.eclipse.jetty.servlet.DefaultServlet@52b6319f]@1386677799
|     |  |  |  +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@6124287a
|     |  |  |  +> org.eclipse.jetty.websocket.core.WebSocketComponents=WebSocketServerComponents@8a62297{STARTED}
|     |  |  |  +> javax.websocket.server.ServerContainer=JavaxWebSocketServerContainer@6b68cb27{STARTED}
|     |  |  |  +> org.eclipse.jetty.websocket.core.server.WebSocketMappings=org.eclipse.jetty.websocket.core.server.WebSocketMappings@60dd3c23
|     |  |  |  +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@19569ebd
|     |  |  +> EventListeners o.e.j.w.WebAppContext@1869fbd2{JAAS Test,/test-jaas,file:///home/user/my-base/work/jetty-0_0_0_0-8443-demo-jaas_war-_test-jaas-any-/webapp/,AVAILABLE}{/home/user/my-base/webapps/demo-jaas.war} size=5
|     |  |  |  +> JettyServerFrameHandlerFactory@45792847{STARTED} - STARTED
|     |  |  |  |  +> java.util.concurrent.ConcurrentHashMap@0{size=0}
|     |  |  |  +> JettyWebSocketServerContainer@706cb08{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@4e25147a{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> JavaxWebSocketServerContainer@6b68cb27{STARTED} - STARTED
|     |  |  |  |  += SessionTracker@675ffd1d{STARTED} - STARTED
|     |  |  |  |     +> java.util.Collections$SetFromMap@0(size=0)
|     |  |  |  +> org.eclipse.jetty.servlet.listener.ELContextCleaner@56303475
|     |  |  |  +> org.eclipse.jetty.servlet.listener.IntrospectorCleaner@30506c0d
|     |  |  +> Initparams JAAS Test@1869fbd2 size=0
|     |  += o.e.j.s.h.MovedContextHandler@632ceb35{/oldContextPath,null,AVAILABLE} - STARTED
|     |     += Redirector@4632cfc{STARTED} - STARTED
|     |     +> No ClassLoader
|     |     +> handler attributes o.e.j.s.h.MovedContextHandler@632ceb35{/oldContextPath,null,AVAILABLE} size=2
|     |     |  +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$
|     |     |  +> org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}]
|     |     +> context attributes o.e.j.s.h.MovedContextHandler@632ceb35{/oldContextPath,null,AVAILABLE} size=0
|     |     +> initparams o.e.j.s.h.MovedContextHandler@632ceb35{/oldContextPath,null,AVAILABLE} size=0
|     += DefaultHandler@6e1f8469{STARTED} - STARTED
+= ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} - STARTED
|  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  +~ ScheduledExecutorScheduler@de3a06f{STARTED} - STARTED
|  +- org.eclipse.jetty.io.ArrayByteBufferPool@10ec523c
|  +- org.eclipse.jetty.server.AbstractConnector$1@2e380628
|  += HttpConnectionFactory@69fb6037[HTTP/1.1] - STARTED
|  |  +- HttpConfiguration@3b6c624{32768/8192,8192/8192,https://:0,[]}
|  |     +> customizers size=0
|  |     +> formEncodedMethods size=2
|  |     |  +> POST
|  |     |  +> PUT
|  |     +> outputBufferSize=32768
|  |     +> outputAggregationSize=8192
|  |     +> requestHeaderSize=8192
|  |     +> responseHeaderSize=8192
|  |     +> headerCacheSize=1024
|  |     +> secureScheme=https
|  |     +> securePort=0
|  |     +> idleTimeout=-1
|  |     +> sendDateHeader=true
|  |     +> sendServerVersion=true
|  |     +> sendXPoweredBy=false
|  |     +> delayDispatchUntilContent=true
|  |     +> persistentConnectionsEnabled=true
|  |     +> maxErrorDispatches=10
|  |     +> minRequestDataRate=0
|  |     +> minResponseDataRate=0
|  |     +> requestCookieCompliance=org.eclipse.jetty.http.CookieCompliance@5d1e09bc
|  |     +> responseCookieCompliance=org.eclipse.jetty.http.CookieCompliance@5d1e09bc
|  |     +> notifyRemoteAsyncErrors=true
|  |     +> relativeRedirectAllowed=false
|  += SelectorManager@ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} - STARTED
|  |  += ManagedSelector@1eaf1e62{STARTED} id=0 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@c81fd12/SelectorProducer@62e6a3ec/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.180963791-06:00 - STARTED
|  |  |  |  +- SelectorProducer@62e6a3ec
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.180371329-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.180719288-06:00 size=0
|  |  += ManagedSelector@5754de72{STARTED} id=1 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@31ee96f4/SelectorProducer@320494b6/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.181852504-06:00 - STARTED
|  |  |  |  +- SelectorProducer@320494b6
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.181259802-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.181625074-06:00 size=0
|  |  += ManagedSelector@652ab8d9{STARTED} id=2 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@14fc5d40/SelectorProducer@51e0301d/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.182570454-06:00 - STARTED
|  |  |  |  +- SelectorProducer@51e0301d
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.18212479-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.182339266-06:00 size=0
|  |  += ManagedSelector@47d7bfb3{STARTED} id=3 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@770b3be0/SelectorProducer@1eb6e1c/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.183255632-06:00 - STARTED
|  |  |  |  +- SelectorProducer@1eb6e1c
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.182822802-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.183043801-06:00 size=0
|  |  += ManagedSelector@51dbd6e4{STARTED} id=4 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@2b8bd14b/SelectorProducer@5f13be1/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.183923207-06:00 - STARTED
|  |  |  |  +- SelectorProducer@5f13be1
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.183495266-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.183714712-06:00 size=0
|  |  += ManagedSelector@5f303ecd{STARTED} id=5 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@50d3bf39/SelectorProducer@25a73de1/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.184567197-06:00 - STARTED
|  |  |  |  +- SelectorProducer@25a73de1
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.184219067-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.184366436-06:00 size=0
|  |  += ManagedSelector@29852487{STARTED} id=6 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@771db12c/SelectorProducer@3afae281/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.185231916-06:00 - STARTED
|  |  |  |  +- SelectorProducer@3afae281
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.184816309-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.18501228-06:00 size=0
|  |  += ManagedSelector@26ae880a{STARTED} id=7 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@260f2144/SelectorProducer@3c017078/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.185759465-06:00 - STARTED
|  |  |  |  +- SelectorProducer@3c017078
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.185480397-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.185621474-06:00 size=0
|  |  += ManagedSelector@51827393{STARTED} id=8 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@3be4f71/SelectorProducer@5c645b43/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.186288778-06:00 - STARTED
|  |  |  |  +- SelectorProducer@5c645b43
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.18594154-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.186148001-06:00 size=0
|  |  += ManagedSelector@6bd16207{STARTED} id=9 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@298d9a05/SelectorProducer@58399d82/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.186723722-06:00 - STARTED
|  |  |  |  +- SelectorProducer@58399d82
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.186431057-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.186588666-06:00 size=0
|  |  += ManagedSelector@26f96b85{STARTED} id=10 keys=0 selected=0 updates=0 - STARTED
|  |  |  += EatWhatYouKill@46d8f407/SelectorProducer@3c0036b/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.187168905-06:00 - STARTED
|  |  |  |  +- SelectorProducer@3c0036b
|  |  |  |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |  |  +> updates @ 2020-12-02T10:49:32.18687068-06:00 size=0
|  |  |  +> keys @ 2020-12-02T10:49:32.187033689-06:00 size=0
|  |  += ManagedSelector@17814b1c{STARTED} id=11 keys=0 selected=0 updates=0 - STARTED
|  |     += EatWhatYouKill@7ac9af2a/SelectorProducer@7bb004b8/PRODUCING/p=false/QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-12-02T10:49:32.187565065-06:00 - STARTED
|  |     |  +- SelectorProducer@7bb004b8
|  |     |  +~ QueuedThreadPool[qtp815992954]@30a3107a{STARTED,10<=33<=200,i=0,r=20,q=0}[ReservedThreadExecutor@6a4d7f76{s=0/20,p=0}] - STARTED
|  |     +> updates @ 2020-12-02T10:49:32.187307968-06:00 size=0
|  |     +> keys @ 2020-12-02T10:49:32.187452382-06:00 size=0
|  +- sun.nio.ch.ServerSocketChannelImpl[/[0:0:0:0:0:0:0:0]:8080]
|  +- qtp815992954-60-acceptor-0@4c1bfff-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
|  +- qtp815992954-61-acceptor-1@41da2368-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
|  +- qtp815992954-62-acceptor-2@33edc3bc-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
|  +- qtp815992954-63-acceptor-3@39a862d4-ServerConnector@a064117{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
+= ErrorHandler@78e89bfe{STARTED} - STARTED
+= InflaterPool@652ce654{STARTED,size=0,capacity=200} - STARTED
+= DeflaterPool@522ba524{STARTED,size=0,capacity=200} - STARTED
+= WebSocketServerComponents@8a62297{STARTED} - STARTED
|  +~ InflaterPool@652ce654{STARTED,size=0,capacity=200} - STARTED
|  +~ DeflaterPool@522ba524{STARTED,size=0,capacity=200} - STARTED
+= DefaultSessionIdManager@6fca2a8f{STARTED}[worker=node0] - STARTED
|  += HouseKeeper@29c5ee1d{STARTED}[interval=600000, ownscheduler=false] - STARTED
+> startJarLoader@3d012ddd
   +> URLs size=52
   |  +> file:/home/user/my-base/resources/
   |  +> file:/home/user/jetty-home-{VERSION}/lib/logging/slf4j-api-2.0.0-alpha1.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/logging/jetty-slf4j-impl-{VERSION}.jar
   |  +> file:/home/user/my-base/lib/ext/demo-mock-resources-{VERSION}.jar
   |  +> file:/home/user/my-base/lib/ext/jakarta.transaction-api-1.3.2.jar
   |  +> file:/home/user/my-base/lib/ext/javax.mail.glassfish-1.4.1.v201005082020.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-servlet-api-4.0.5.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-http-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-server-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-xml-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-util-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-io-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-alpn-java-server-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-alpn-client-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-alpn-server-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-jndi-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-security-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-servlet-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-webapp-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-plus-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jakarta.transaction-api-1.3.2.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-annotations-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/annotations/asm-9.0.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/annotations/asm-analysis-9.0.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/annotations/asm-commons-9.0.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/annotations/asm-tree-9.0.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/annotations/jakarta.annotation-api-1.3.5.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/apache-jsp/org.eclipse.jdt.ecj-3.19.0.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/apache-jsp/org.eclipse.jetty.apache-jsp-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/apache-jsp/org.mortbay.jasper.apache-el-9.0.29.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/apache-jsp/org.mortbay.jasper.apache-jsp-9.0.29.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/apache-jstl/org.apache.taglibs.taglibs-standard-impl-1.2.5.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/apache-jstl/org.apache.taglibs.taglibs-standard-spec-1.2.5.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-client-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-deploy-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-jaas-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-servlets-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-core-common-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-core-client-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-core-server-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-servlet-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/jetty-javax-websocket-api-1.1.2.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-javax-client-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-javax-common-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-javax-server-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-jetty-api-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-jetty-common-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/websocket/websocket-jetty-server-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/jetty-rewrite-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/http2/http2-common-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/http2/http2-hpack-{VERSION}.jar
   |  +> file:/home/user/jetty-home-{VERSION}/lib/http2/http2-server-{VERSION}.jar
   +> jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487
      +> packages size=4
      |  +> package org.eclipse.jetty.start.config
      |  +> package org.eclipse.jetty.start.builders
      |  +> package org.eclipse.jetty.start.shaded.util
      |  +> package org.eclipse.jetty.start
      +> jdk.internal.loader.ClassLoaders$PlatformClassLoader@48b22fd4
         +> packages size=13
            +> package sun.security.ec
            +> package java.sql
            +> package sun.security.jgss
            +> package com.sun.security.sasl.gsskerb
            +> package sun.util.resources.provider
            +> package org.jcp.xml.dsig.internal.dom
            +> package sun.util.resources.cldr.provider
            +> package sun.security.smartcardio
            +> package javax.sql
            +> package sun.security.ec.point
            +> package sun.security.pkcs11.wrapper
            +> package com.sun.jndi.dns
            +> package sun.security.pkcs11
key: +- bean, += managed, +~ unmanaged, +? auto, +: iterable, +] array, +@ map, +> undefined
.... 
