# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Enables use of the apache implementation of JSP.

[lib]
lib/apache-jsp/*.jar

