# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee11

[depends]
ee11-apache-jsp

[ini]
ee11.jakarta.servlet.jsp.jstl.impl.version?=@ee11.jakarta.servlet.jsp.jstl.impl.version@

[files]
maven://jakarta.servlet.jsp.jstl/jakarta.servlet.jsp.jstl-api/3.0.2/jar|lib/ee11/support/jakarta.servlet.jsp.jstl.jakarta.servlet.jsp.jstl-api-3.0.2.jar
maven://org.glassfish.wasp/wasp/${ee11.jakarta.servlet.jsp.jstl.impl.version}/jar|lib/ee11/support/org.glassfish.wasp.wasp-${ee11.jakarta.servlet.jsp.jstl.impl.version}.jar

[lib]
lib/ee11/support/jakarta.servlet.jsp.jstl.jakarta.servlet.jsp.jstl-api-3.0.2.jar
lib/ee11/support/org.glassfish.wasp.wasp-${ee11.jakarta.servlet.jsp.jstl.impl.version}.jar
