# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee11

[depends]
ee11-apache-jsp

[ini]
ee11.jakarta.servlet.jsp.jstl.api.version?=@jakarta.servlet.jsp.jstl.api.version@
ee11.jakarta.servlet.jsp.jstl.impl.version?=@jakarta.servlet.jsp.jstl.impl.version@

[lib]
lib/ee11-glassfish-jstl/jakarta.servlet.jsp.jstl.jakarta.servlet.jsp.jstl-api-${ee11.jakarta.servlet.jsp.jstl.api.version}.jar
lib/ee11-glassfish-jstl/org.glassfish.web.jakarta.servlet.jsp.jstl-${ee11.jakarta.servlet.jsp.jstl.impl.version}.jar
