//
// ========================================================================
// Copyright (c) 1995-2020 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under
// the terms of the Eclipse Public License 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0
//
// This Source Code may also be made available under the following
// Secondary Licenses when the conditions for such availability set
// forth in the Eclipse Public License, v. 2.0 are satisfied:
// the Apache License v2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[eg-server-http]]
=== HTTP Server Libraries

The Eclipse Jetty Project has historically provided libraries to embed an HTTP
server and a Servlet Container.

The Maven artifact coordinates are:

[source,xml,subs=normal]
----
<dependency>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-server</artifactId>
  <version>{version}</version>
</dependency>
----

An `org.eclipse.jetty.server.Server` instance is the central component that
links together a collection of ``Connector``s and a collection of
``Handler``s, with threads from a `ThreadPool` doing the work.

[plantuml]
----
skinparam backgroundColor transparent
skinparam monochrome true
skinparam shadowing false
skinparam padding 5

scale 1.5

hide members
hide circle

Server - ThreadPool
Connectors - Server
Server -- Handlers
----

The components that accept connections from clients are
`org.eclipse.jetty.server.Connector` implementations.

When a Jetty server interprets the HTTP protocol (both HTTP/1.1 and HTTP/2),
it uses `org.eclipse.jetty.server.Handler` instances to process incoming
requests and eventually produce responses.

A `Server` must be created, configured and started:

[source,java,indent=0]
----
include::../../{doc_code}/embedded/server/http/HTTPServerDocs.java[tags=simple]
----

The example above shows the simplest HTTP/1.1 server; it has no support for
HTTP sessions, for HTTP authentication, or for any of the features required
by the Servlet specification.

All these features are provided by the Jetty Server Libraries and server
applications only need to put the required components together to provide
all the required features.
// TODO: link to a place where we discuss the handlers in more details.

include::server-http-connector.adoc[]
include::server-http-handler.adoc[]
