# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Experimental Common Compression API.

[tags]
server
handler
compression
experimental

[depend]
server

[lib]
lib/compression/jetty-compression-api-${jetty.version}.jar


