//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

package org.eclipse.jetty.quic.server.internal;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.atomic.AtomicLong;

import org.eclipse.jetty.io.CyclicTimeouts;
import org.eclipse.jetty.io.EndPoint;
import org.eclipse.jetty.io.RetainableByteBuffer;
import org.eclipse.jetty.quic.api.QuicVersion;
import org.eclipse.jetty.quic.api.Session;
import org.eclipse.jetty.quic.api.frames.ConnectionCloseFrame;
import org.eclipse.jetty.quic.api.frames.Frame;
import org.eclipse.jetty.quic.api.frames.HandshakeDoneFrame;
import org.eclipse.jetty.quic.api.frames.NewTokenFrame;
import org.eclipse.jetty.quic.api.frames.TransportParameters;
import org.eclipse.jetty.quic.api.tls.ext.QuicTransportParametersExtension;
import org.eclipse.jetty.quic.common.EncryptionLevel;
import org.eclipse.jetty.quic.common.QuicSession;
import org.eclipse.jetty.quic.common.StreamId;
import org.eclipse.jetty.quic.common.packets.InitialPacket;
import org.eclipse.jetty.quic.common.packets.Packet;
import org.eclipse.jetty.quic.common.packets.PacketNumbers;
import org.eclipse.jetty.quic.common.packets.PacketProtector;
import org.eclipse.jetty.quic.common.packets.RetryPacket;
import org.eclipse.jetty.quic.common.packets.VersionNegotiationPacket;
import org.eclipse.jetty.quic.common.tls.HandshakeData;
import org.eclipse.jetty.quic.server.QuicServerQuicConfiguration;
import org.eclipse.jetty.quic.server.internal.tls.ServerTLSEngine;
import org.eclipse.jetty.quic.util.ErrorCode;
import org.eclipse.jetty.quic.util.QuicException;
import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.tls.CertificateMessage;
import org.eclipse.jetty.tls.CertificateVerifyMessage;
import org.eclipse.jetty.tls.ClientHelloMessage;
import org.eclipse.jetty.tls.FinishedMessage;
import org.eclipse.jetty.tls.Message;
import org.eclipse.jetty.tls.TLSException;
import org.eclipse.jetty.util.Callback;
import org.eclipse.jetty.util.Promise;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/// The server-specific implementation of [QuicSession].
public class ServerQuicSession extends QuicSession implements CyclicTimeouts.Expirable
{
    private static final Logger LOG = LoggerFactory.getLogger(ServerQuicSession.class);

    private final AtomicLong biStreamIds = new AtomicLong();
    private final AtomicLong uniStreamIds = new AtomicLong();
    private long expireNanoTime = Long.MAX_VALUE;
    private byte[] originalDestinationConnectionId;

    public ServerQuicSession(Connector connector, QuicServerQuicConfiguration configuration, ServerQuicConnection connection, PacketNumbers packetNumbers, ServerTLSEngine tlsEngine, Session.Listener listener, EndPoint endPoint)
    {
        super(connector.getExecutor(), connector.getScheduler(), connector.getByteBufferPool(), configuration, connection, packetNumbers, tlsEngine, listener, endPoint);
        // Link the ServerTLSEngine back to this session to
        // send the TLS messages generated by ServerTLSEngine.
        tlsEngine.addMessageListener(this::sendTLSMessages);
        // Link the ServerTLSEngine back to this session to
        // be notified when the TLS handshake is complete.
        tlsEngine.addHandshakeListener(this::handshakeComplete);
    }

    @Override
    public QuicServerQuicConfiguration getQuicConfiguration()
    {
        return (QuicServerQuicConfiguration)super.getQuicConfiguration();
    }

    @Override
    public ServerTLSEngine getTLSEngine()
    {
        return (ServerTLSEngine)super.getTLSEngine();
    }

    @Override
    public ServerQuicConnection getQuicConnection()
    {
        return (ServerQuicConnection)super.getQuicConnection();
    }

    void initialize(byte[] dstConnectionId)
    {
        PacketProtector packetProtector = getTLSEngine().getPacketProtector();
        packetProtector.allocateInitialKeys(getQuicVersion(), dstConnectionId);
    }

    @Override
    public void setIdleTimeout(long idleTimeout)
    {
        super.setIdleTimeout(idleTimeout);
        notIdle();
        getQuicConnection().schedule(this);
    }

    @Override
    public boolean onIdleTimeout(TimeoutException timeout)
    {
        boolean result = super.onIdleTimeout(timeout);
        if (!result)
            notIdle();
        return result;
    }

    @Override
    public long getExpireNanoTime()
    {
        return expireNanoTime;
    }

    private void notIdle()
    {
        expireNanoTime = CyclicTimeouts.Expirable.calcExpireNanoTime(getIdleTimeout());
    }

    @Override
    public int getUDPPayloadLength()
    {
        return getQuicConfiguration().getUDPPayloadLength();
    }

    @Override
    protected InitialPacket newInitialPacket(List<Frame> frames)
    {
        // TODO: token creation and validation.
        byte[] token = new byte[0];
        return new InitialPacket(getQuicVersion(), getDestinationConnectionId(), getSourceConnectionId(), token, getPacketNumbers().nextPacketNumber(EncryptionLevel.INITIAL), frames);
    }

    @Override
    public long newStreamId(boolean bidirectional)
    {
        AtomicLong streamIds = bidirectional ? biStreamIds : uniStreamIds;
        return StreamId.newStreamId(streamIds.getAndIncrement(), bidirectional, false);
    }

    @Override
    protected void processPacket(Packet packet)
    {
        try
        {
            switch (packet)
            {
                case InitialPacket initialPacket -> processInitialPacket(initialPacket);
                default -> super.processPacket(packet);
            }
        }
        catch (Throwable x)
        {
            fail(x);
        }
    }

    private void processInitialPacket(InitialPacket packet) throws Exception
    {
        QuicVersion clientQuicVersion = packet.quicVersion();
        List<QuicVersion> serverQuicVersions = getQuicConfiguration().getQuicVersions();
        if (!serverQuicVersions.contains(clientQuicVersion))
        {
            if (LOG.isDebugEnabled())
                LOG.debug("unsupported quic version {} in {} on {}", clientQuicVersion, packet, this);

            VersionNegotiationPacket versionNegotiationPacket = new VersionNegotiationPacket(getDestinationConnectionId(), getSourceConnectionId(), serverQuicVersions);
            packet(versionNegotiationPacket);

            if (LOG.isDebugEnabled())
                LOG.debug("dropping {} on {}", packet, this);
            return;
        }

        setQuicVersion(clientQuicVersion);
        getTLSEngine().getTLSConfiguration().setQuicVersion(getQuicVersion());

        byte[] token = packet.token();
        if (token.length == 0)
        {
            if (LOG.isDebugEnabled())
                LOG.debug("no token in {} on {}", packet, this);

            // Store the odcid to be used for the next InitialPacket and for the RetryPacket.
            originalDestinationConnectionId = packet.destinationConnectionId();

            token = getQuicConfiguration().getTokenFactory().newRetryToken(getRemoteSocketAddress(), originalDestinationConnectionId);
            RetryPacket retryPacket = new RetryPacket(clientQuicVersion, getDestinationConnectionId(), getSourceConnectionId(), token, null);
            RetainableByteBuffer.Mutable retryAccumulator = new RetainableByteBuffer.DynamicCapacity(getByteBufferPool(), false, -1, 0, 0);
            generateRetryPacket(retryAccumulator, retryPacket);
            byte[] integrity = getTLSEngine().getPacketProtector().generateRetryIntegrity(retryAccumulator, originalDestinationConnectionId);
            retryPacket = retryPacket.withIntegrity(integrity);
            packet(retryPacket);

            if (LOG.isDebugEnabled())
                LOG.debug("dropping {} on {}", packet, this);
            return;
        }

        boolean valid = getQuicConfiguration().getTokenFactory().isTokenValid(getRemoteSocketAddress(), originalDestinationConnectionId, token);
        if (LOG.isDebugEnabled())
            LOG.debug("token {} in {} on {}", valid ? "valid" : "invalid", packet, this);
        if (!valid)
            throw new QuicException(ErrorCode.INVALID_TOKEN_ERROR, "invalid_token");
        // Process the InitialPacket.
        super.processPacket(packet);
    }

    @Override
    protected void processMessage(Message message)
    {
        switch (message)
        {
            // TODO: verify QuicTransportParametersExtension in ClientHello, etc.
            case ClientHelloMessage clientHello -> processClientHello(clientHello);
            case CertificateMessage certificate -> getTLSEngine().onMessageParsed(certificate);
            case CertificateVerifyMessage certificateVerify -> getTLSEngine().onMessageParsed(certificateVerify);
            case FinishedMessage finished -> getTLSEngine().onMessageParsed(finished);
            default -> throw new IllegalStateException("unexpected message " + message);
        }
    }

    private void processClientHello(ClientHelloMessage clientHello)
    {
        TransportParameters transportParameters = clientHello.extensions().stream()
            .filter(ext -> ext instanceof QuicTransportParametersExtension)
            .map(QuicTransportParametersExtension.class::cast)
            .findFirst()
            .map(QuicTransportParametersExtension::transportParameters)
            .orElse(null);

        // TODO: apply verifications to TransportParameters as per RFC.

        processTransportParameters(transportParameters);

        getTLSEngine().onMessageParsed(clientHello);
    }

    private void handshakeComplete(HandshakeData data, Throwable failure)
    {
        if (failure == null)
            handshakeSuccessful(data);
        else
            handshakeFailure(failure);
    }

    private void handshakeSuccessful(HandshakeData data)
    {
        try
        {
            notifyOpen();
            List<Frame> frames = new ArrayList<>();
            frames.add(new HandshakeDoneFrame());
            byte[] token = getQuicConfiguration().getTokenFactory().newToken(getRemoteSocketAddress());
            frames.add(new NewTokenFrame(token));
            // TODO: send also NewConnectionIdFrames.
            frames(frames, Callback.from(Callback.NOOP, this::fail));
        }
        catch (Throwable x)
        {
            fail(x);
        }
    }

    private void handshakeFailure(Throwable failure)
    {
        // TODO: notifyFailure()?
        // RFC-9000[20.1]: convert TLS alerts into CRYPTO_ERRORs.
        long code = ErrorCode.INTERNAL_ERROR.code();
        if (failure instanceof TLSException tls)
            code = ErrorCode.CRYPTO_ERROR.code() + tls.getAlert().code();
        disconnect(new ConnectionCloseFrame(code, failure.getMessage(), 0x06), failure, Promise.Invocable.noop()/*TODO*/);
    }

    /*
    @Override
    public long newStreamId(boolean bidirectional)
    {
        return StreamId.newStreamId(streamIds.getAndIncrement(), bidirectional, false);
    }

    Runnable process(SocketAddress remoteAddress, ByteBuffer cipherBuffer)
    {
        try
        {
            feed(remoteAddress, cipherBuffer);

            if (isConnectionEstablished())
            {
                if (!isOpen())
                {
                    if (!validateConnection())
                        return null;
                    open();
                    if (LOG.isDebugEnabled())
                        LOG.debug("opened {}", this);
                }
                // Return a task because we want 1 thread per active session.
                return getProducerTask();
            }
            else
            {
                flush();
                return null;
            }
        }
        catch (Throwable x)
        {
            if (LOG.isDebugEnabled())
                LOG.atDebug().setCause(x).log("process failure for {}", this);
            ConnectionCloseFrame frame = new ConnectionCloseFrame(ErrorCode.CONNECTION_REFUSED_ERROR.code(), "session_failure");
            disconnect(frame, x, Promise.Invocable.noop());
            return null;
        }
    }

    private boolean validateConnection()
    {
        if (getConnection().getSslContextFactory().getNeedClientAuth() && getPeerCertificates() == null)
        {
            ConnectionCloseFrame frame = new ConnectionCloseFrame(ErrorCode.CONNECTION_REFUSED_ERROR.code(), "missing_peer_certificates");
            disconnect(frame, new SSLHandshakeException(frame.reason()), Promise.Invocable.noop());
            return false;
        }
        return true;
    }

    @Override
    public void feed(SocketAddress remoteAddress, ByteBuffer cipherBuffer) throws IOException
    {
        // While the connection ID remains the same,
        // the remote address may change so store it again.
        this.remoteAddress = remoteAddress;
        notIdle();
        super.feed(remoteAddress, cipherBuffer);
    }

    Runnable getProducerTask()
    {
        return producer;
    }

    @Override
    public void flush()
    {
        notIdle();
        super.flush();
    }

    private class StreamsProducerTask extends Invocable.Task.Abstract
    {
        private StreamsProducerTask()
        {
            // Must be EITHER so that its invocation is not deferred,
            // since this task may process a stream that would unblock
            // stalled threads.
            // NON_BLOCKING could have worked too, but EITHER provides
            // parallelization of session processing which is a plus.
            super(InvocationType.EITHER);
        }

        @Override
        public void run()
        {
            produce();
        }

        @Override
        public String toString()
        {
            return "%s@%x".formatted(TypeUtil.toShortName(getClass()), hashCode());
        }
    }
*/
}
