//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

package org.eclipse.jetty.quic.server.internal;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.jetty.io.CyclicTimeouts;
import org.eclipse.jetty.io.RateControl;
import org.eclipse.jetty.io.RetainableByteBuffer;
import org.eclipse.jetty.quic.api.Session;
import org.eclipse.jetty.quic.api.frames.CryptoFrame;
import org.eclipse.jetty.quic.api.frames.Frame;
import org.eclipse.jetty.quic.api.frames.HandshakeDoneFrame;
import org.eclipse.jetty.quic.api.frames.NewTokenFrame;
import org.eclipse.jetty.quic.api.frames.TransportParameters;
import org.eclipse.jetty.quic.common.EncryptionLevel;
import org.eclipse.jetty.quic.common.FlowController;
import org.eclipse.jetty.quic.common.PacketTracker;
import org.eclipse.jetty.quic.common.QuicSession;
import org.eclipse.jetty.quic.common.StreamsController;
import org.eclipse.jetty.quic.common.packets.HandshakePacket;
import org.eclipse.jetty.quic.common.packets.InitialPacket;
import org.eclipse.jetty.quic.common.packets.Packet;
import org.eclipse.jetty.quic.common.packets.PacketNumbers;
import org.eclipse.jetty.quic.common.packets.PacketProtector;
import org.eclipse.jetty.quic.common.packets.RetryPacket;
import org.eclipse.jetty.quic.common.tls.HandshakeData;
import org.eclipse.jetty.quic.common.tls.TLSEngine;
import org.eclipse.jetty.quic.common.tls.ext.QuicTransportParametersExtension;
import org.eclipse.jetty.quic.server.QuicServerQuicConfiguration;
import org.eclipse.jetty.quic.server.internal.tls.ServerTLSEngine;
import org.eclipse.jetty.quic.util.ErrorCode;
import org.eclipse.jetty.quic.util.QuicException;
import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.tls.CertificateMessage;
import org.eclipse.jetty.tls.CertificateVerifyMessage;
import org.eclipse.jetty.tls.ClientHelloMessage;
import org.eclipse.jetty.tls.FinishedMessage;
import org.eclipse.jetty.tls.Message;
import org.eclipse.jetty.util.Callback;
import org.eclipse.jetty.util.thread.Invocable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.eclipse.jetty.util.thread.Invocable.InvocationType.NON_BLOCKING;

/// The server-specific implementation of [QuicSession].
public class ServerQuicSession extends QuicSession implements CyclicTimeouts.Expirable
{
    private static final Logger LOG = LoggerFactory.getLogger(ServerQuicSession.class);

    private long expireNanoTime = Long.MAX_VALUE;
    private boolean retryPacketSent;
    private volatile boolean remoteAddressValidated;

    public ServerQuicSession(Connector connector, QuicServerQuicConfiguration configuration, ServerQuicConnection connection, PacketTracker packetTracker, PacketNumbers packetNumbers, ServerTLSEngine tlsEngine, RateControl rateControl, FlowController flowController, StreamsController streamsController, Session.Listener listener)
    {
        super(connector.getExecutor(), connector.getScheduler(), connector.getByteBufferPool(), configuration, connection, packetTracker, packetNumbers, tlsEngine, rateControl, flowController, streamsController, listener, false);
        // Link the ServerTLSEngine back to this session to
        // send the TLS messages generated by ServerTLSEngine.
        tlsEngine.addMessageListener(new TLSEngine.MessageListener()
        {
            @Override
            public void onOutgoingMessages(EncryptionLevel encryptionLevel, List<Message> messages, Callback callback)
            {
                sendTLSMessages(encryptionLevel, messages, callback);
            }
        });

        // Link the ServerTLSEngine back to this session to
        // be notified when the TLS handshake is complete.
        tlsEngine.addHandshakeListener(this::handshakeComplete);
    }

    @Override
    public QuicServerQuicConfiguration getQuicConfiguration()
    {
        return (QuicServerQuicConfiguration)super.getQuicConfiguration();
    }

    @Override
    public ServerTLSEngine getTLSEngine()
    {
        return (ServerTLSEngine)super.getTLSEngine();
    }

    @Override
    public ServerQuicConnection getQuicConnection()
    {
        return (ServerQuicConnection)super.getQuicConnection();
    }

    void initialize(byte[] dstConnectionId)
    {
        setDestinationConnectionId(dstConnectionId);
        PacketProtector packetProtector = getTLSEngine().getPacketProtector();
        packetProtector.generateInitialKeys(getQuicVersion(), dstConnectionId);
        getTLSEngine().getTLSConfiguration().setQuicVersion(getQuicVersion());
        getTLSEngine().initialize();
    }

    @Override
    public void setIdleTimeout(long idleTimeout)
    {
        super.setIdleTimeout(idleTimeout);
        notIdle();
        getQuicConnection().schedule(this);
    }

    @Override
    public long getExpireNanoTime()
    {
        return expireNanoTime;
    }

    protected void notIdle()
    {
        expireNanoTime = CyclicTimeouts.Expirable.calcExpireNanoTime(getIdleTimeout());
    }

    @Override
    public int getUDPPayloadLength()
    {
        return getQuicConfiguration().getUDPPayloadLength();
    }

    @Override
    protected InitialPacket newInitialPacket(List<Frame> frames)
    {
        // TODO: token creation and validation.
        byte[] token = new byte[0];
        return new InitialPacket(getQuicVersion(), getDestinationConnectionId(), getSourceConnectionId(), token, getPacketNumbers().nextPacketNumber(EncryptionLevel.INITIAL), frames);
    }

    @Override
    protected List<Invocable.Task> processPacket(Packet packet)
    {
        try
        {
            return switch (packet)
            {
                case InitialPacket initialPacket ->
                {
                    if (processInitialPacket(initialPacket))
                        yield super.processPacket(packet);
                    yield List.of();
                }
                case HandshakePacket handshakePacket ->
                    processHandshakePacket(handshakePacket);
                default -> super.processPacket(packet);
            };
        }
        catch (Throwable x)
        {
            fail(x, false);
            return List.of();
        }
    }

    private boolean processInitialPacket(InitialPacket packet) throws Exception
    {
        // RFC-9000 #14.1: servers must not accept small initial packets.
        if (packet.length() < InitialPacket.MIN_LENGTH)
            throw new QuicException(ErrorCode.PROTOCOL_VIOLATION_ERROR, "invalid_initial_packet");

        if (packet.frames().getFirst() instanceof CryptoFrame)
        {
            byte[] token = packet.token();
            if (token == null || token.length == 0)
            {
                if (LOG.isDebugEnabled())
                    LOG.debug("no token in {} on {}", packet, this);

                // Store the odcid to be used for the next InitialPacket and for the RetryPacket.
                byte[] origDstConnectionId = packet.destinationConnectionId();
                setOriginalDestinationConnectionId(origDstConnectionId);

                // RFC-9001 #5.2: initial secrets must be regenerated with the scid.
                getTLSEngine().getPacketProtector().generateInitialKeys(getQuicVersion(), getSourceConnectionId());

                token = getQuicConfiguration().getTokenFactory().newRetryToken(getRemoteSocketAddress(), origDstConnectionId);
                RetryPacket retryPacket = new RetryPacket(packet.quicVersion(), packet.sourceConnectionId(), getSourceConnectionId(), token, null);
                RetainableByteBuffer.Mutable retryAccumulator = new RetainableByteBuffer.DynamicCapacity(getByteBufferPool(), false, -1, 0, 0);
                generateRetryPacket(retryAccumulator, retryPacket);
                byte[] integrity = getTLSEngine().createRetryIntegrity(retryAccumulator, origDstConnectionId);
                retryPacketSent = true;
                retryPacket = retryPacket.withIntegrity(integrity);
                packet(retryPacket, Callback.NOOP);

                if (LOG.isDebugEnabled())
                    LOG.debug("dropping {} on {}", packet, this);
                return false;
            }

            TransportParameters transportParameters = getTLSEngine().getTLSConfiguration().getTransportParameters();
            transportParameters.put(TransportParameters.Ids.INITIAL_SOURCE_CONNECTION_ID, getSourceConnectionId());
            if (retryPacketSent)
                transportParameters.put(TransportParameters.Ids.RETRY_SOURCE_CONNECTION_ID, getSourceConnectionId());
            notifyPrepare(transportParameters);
            configure(transportParameters, true);

            boolean valid = getQuicConfiguration().getTokenFactory().isTokenValid(getRemoteSocketAddress(), getOriginalDestinationConnectionId(), token);
            if (LOG.isDebugEnabled())
                LOG.debug("token {} in {} on {}", valid ? "valid" : "invalid", packet, this);
            if (!valid)
                throw new QuicException(ErrorCode.INVALID_TOKEN_ERROR, "invalid_token");

            if (retryPacketSent)
                remoteAddressValidated = true;
        }
        return true;
    }

    private List<Invocable.Task> processHandshakePacket(HandshakePacket packet)
    {
        remoteAddressValidated = true;
        return super.processPacket(packet);
    }

    @Override
    public boolean isRemoteAddressValidated()
    {
        return remoteAddressValidated;
    }

    @Override
    protected void processMessage(Message message)
    {
        switch (message)
        {
            case ClientHelloMessage clientHello -> processClientHello(clientHello);
            case CertificateMessage certificate -> getTLSEngine().onMessage(EncryptionLevel.HANDSHAKE, certificate);
            case CertificateVerifyMessage certificateVerify -> getTLSEngine().onMessage(EncryptionLevel.HANDSHAKE, certificateVerify);
            case FinishedMessage finished -> getTLSEngine().onMessage(EncryptionLevel.HANDSHAKE, finished);
            default -> throw new IllegalStateException("unexpected message " + message);
        }
    }

    private void processClientHello(ClientHelloMessage clientHello)
    {
        TransportParameters transportParameters = clientHello.extensions().stream()
            .filter(ext -> ext instanceof QuicTransportParametersExtension)
            .map(QuicTransportParametersExtension.class::cast)
            .findFirst()
            .map(QuicTransportParametersExtension::transportParameters)
            .orElse(null);

        processTransportParameters(transportParameters);

        getTLSEngine().onMessage(EncryptionLevel.INITIAL, clientHello);
    }

    private void handshakeComplete(HandshakeData data, Throwable failure)
    {
        if (failure == null)
            handshakeSuccessful(data);
        else
            handshakeFailure(failure);
    }

    private void handshakeSuccessful(HandshakeData data)
    {
        try
        {
            // RFC-9001 #4.9.2: handshake keys must be discarded when the TLS handshake is confirmed.
            discardEncryptionLevel(EncryptionLevel.HANDSHAKE);
            setEncryptionLevel(EncryptionLevel.ONE_RTT);

            emitOpen();

            List<Frame> frames = new ArrayList<>();
            frames.add(new HandshakeDoneFrame());
            byte[] token = getQuicConfiguration().getTokenFactory().newToken(getRemoteSocketAddress());
            frames.add(new NewTokenFrame(token));
            // TODO: add NewConnectionIdFrames.

            frames(frames, Callback.from(NON_BLOCKING, () -> {}, x -> fail(x, false)));
        }
        catch (Throwable x)
        {
            fail(x, false);
        }
    }

    private void handshakeFailure(Throwable failure)
    {
        fail(failure, false);
    }
}
