//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[cg-community]]
== Participate in the Community

One of the best ways to start contribute and work with Eclipse Jetty is to get plugged into one of the existing communities.
In any one of these you will come across users of neophyte to expert experience and as time permits the developers of Jetty themselves.

[[cg-mailing-lists]]
=== Mailing Lists

There are a number of mailing lists available within the Jetty project:

* https://dev.eclipse.org/mailman/listinfo/jetty-dev[Jetty Developers] is for narrowly focused technical discussion regarding Jetty internals. (http://dev.eclipse.org/mhonarc/lists/jetty-dev/[Archives])
* https://dev.eclipse.org/mailman/listinfo/jetty-users[Jetty Users] is for questions of broad interest to the community of Jetty users. (http://dev.eclipse.org/mhonarc/lists/jetty-users/[Archives])
* https://dev.eclipse.org/mailman/listinfo/jetty-announce[Jetty Announcements] is for announcements about new releases and other updates from the project's maintainers. (http://dev.eclipse.org/mhonarc/lists/jetty-announce/[Archives])

[[cg-stackoverflow]]
=== Stack Overflow

From a simple support perspective it is hard to beat http://stackoverflow.com[StackOverflow] for interacting with a Jetty community.
Numerous users have asked and had answered their questions on the platform by other users and developers alike.

* Check out the general https://stackoverflow.com/questions/tagged/jetty[Jetty] tag!
* The https://stackoverflow.com/questions/tagged/embedded-jetty[Embedded-Jetty] tag has a fair amount of traffic as well.

[[cg-issues]]
=== Github: Issues and Features

While not necessarily a support channel for solving a specific user problem, the issue tracker for Eclipse Jetty is a great location for addressing issues or suggesting features you want to see (or ideally contribute) in Jetty.

When you file a Github Issue in the Eclipse Jetty project there are a number of *labels* available and we encourage to you use them appropriately.

* http://github.com/eclipse/jetty.project[Issues at Github].

We have additionally identified and labeled a number of issues that may be appropriate for users of different levels of expertise that might want to contribute to Jetty but not have a specific goal or issue in mind.

* https://github.com/eclipse/jetty.project/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22[Help Wanted]

Long story short, if you are interested in getting involved with the community, there are a number of options available and you are encouraged to participate at whatever level you like!
