//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[cg-submitting-patches]]
== Submitting Patches

We wholeheartedly welcome contributions to Jetty.
While not every contribution will be accepted, our commitment is to work with interested parties on the things they care about.

[[cg-git-config]]
=== Configuring git

The email in your git commits must match the email you used to <<cg-eca,sign the Eclipse Contributor Agreement>>.
As such, you'll likely want to configure `user.email` in git accordingly.
See link:https://help.github.com/articles/setting-your-email-in-git[this guide] on GitHub for details on how to do so.

[[cg-commit-messages]]
==== Writing commit messages

If your pull request addresses a particular issue in our repository, then the commit message should reference the issue.
Specifically, the message should follow the form *Issue #<XXX> <description of the commit>*:

[source, shell]
----
$ git commit -s -m "Issue #123 resolving the issue by adding widget"
----

Using this format will ensure that the commit will be included in `VERSIONS.txt` upon new releases of Jetty.


[[cg-making-the-commit]]
=== Signing the commit

You must sign off on every commit in your pull request using git's https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff[signoff] feature (`git commit -s`).
Without this signoff, your patch will be automatically rejected before it can be incorporated into to the Jetty repository.
*There is nothing the Jetty committers can do to bypass this check.*


[NOTE]
.Why do my commits need the signoff flag if I already signed the ECA?
====
By signing the ECA, you are indicating that you are free to contribute to Eclipse; however, that doesn't mean every line of code you ever write is subject to the agreement!
Signing off on your individual commits clearly indicates that you are submitting your code under the auspices of the ECA.
====

[TIP]
====
If you made a commit but forgot to pass the `-s` flag, you can retroactively add a signoff by running:

[source,shell]
----
git commit --amend --signoff
----
====

[[cg-pull-requests]]
=== Creating pull requests

Please see https://help.github.com/articles/creating-a-pull-request[GitHub's documentation for creating pull requests].

[[cg-time-frames]]
=== Time frames

We do our best to process contributions in a timely fashion.
Please note that we can only handle pull requests with actively engaged parties.
We reserve the right to abandon pull requests whose authors do not respond in a timely fashion.

We will generally adhere to the following time frames for contributions:

Invalid Pull Requests - 1 week::
These pull requests do not follow the contribution requirements for some reason -- e.g., a missing contributor agreement or mismatched email signature.
We will try and follow up with the pull request author to resolve the issue.
If we do not hear from the contributor after a week we will close the pull request.

Valid Pull Requests - 2 weeks::
If the pull request can be immediately merged, we will do so.
Otherwise, we will follow up with the author in a comment to discuss what additional actions must be taken before the change can be landed.
If the original contributor does not respond within two weeks, we may close the commit, or make some variation of the commit ourselves.
