# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Expose the Jetty WebSocket Client classes to deployed web applications.

[environment]
ee11

[tags]
websocket

[depends]
client
ee11-annotations
websocket-jetty-client

[files]
maven://org.eclipse.jetty.ee11.websocket/jetty-ee11-websocket-jetty-client-webapp/${project.version}/jar|lib/ee11/jetty-ee11-websocket-jetty-client-webapp-${project.version}.jar

[lib]
lib/ee11/jetty-ee11-websocket-jetty-client-webapp-${project.version}.jar
