# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables an un-assembled Maven webapp to run in a Jetty distribution.

[environment]
ee

[depends]
server
ee-webapp
ee-annotations

[lib]
lib/ee-maven/*.jar

[xml]
etc/jetty-ee-maven.xml
