//
// ========================================================================
// Copyright (c) 1995-2021 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-module-threadpool]]
===== Module `threadpool`

The `threadpool` module allows you to configure the server-wide thread pool.

The thread pool creates threads on demand up to `maxThreads`, and idle them out if they are not used.

Since Jetty uses the thread pool internally to execute critical tasks, it is not recommended to constrain the thread pool to small values of `maxThreads` with the purpose of limiting HTTP request concurrency, as this could very likely cause a server lockup when Jetty needs to run a critical task but there are no threads available.
Start with the default value of `maxThreads`, and tune for larger values if needed.

The module file is `$JETTY_HOME/modules/threadpool.mod`:

----
include::{JETTY_HOME}/modules/threadpool.mod[]
----

Among the configurable properties, the most relevant are:

`jetty.threadPool.detailedDump`::
Whether the thread pool should dump the whole stack trace of each thread, or just the topmost stack frame -- defaults to `false`.

`jetty.threadPool.idleTimeout`::
The time, in milliseconds, after which an idle thread is released from the pool -- defaults to 60000, i.e. 60 seconds.

`jetty.threadPool.maxThreads`::
The max number of threads pooled by the thread pool -- defaults to 200.
