//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-module-threadpool-virtual-preview]]
===== Module `threadpool-virtual-preview`

The `threadpool-virtual-preview` module allows you to configure the server-wide thread pool, similarly to what you can do with the xref:og-module-threadpool[`threadpool`] Jetty module, but also specify to use virtual threads, introduced as a preview feature in Java 19.

NOTE: To enable preview features, this module needs to specify the `+--enable-preview+` command line option using the xref:og-modules-directive-exec[[exec\] directive], and as such it will fork another JVM.

Refer to the xref:og-module-threadpool[`threadpool`] Jetty module for the general features provided by that Jetty module that also this Jetty module provides.

The module properties to configure the thread pool are:

----
include::{JETTY_HOME}/modules/threadpool-virtual-preview.mod[tags=documentation]
----

The specific properties to configure virtual threads are:

`jetty.threadPool.virtual.namePrefix`::
The name prefix to use for the virtual thread names.

`jetty.threadPool.virtual.allowSetThreadLocals`::
Whether virtual threads are allowed to set thread locals.

`jetty.threadPool.useVirtualThreads`::
Whether virtual threads inherit the values of `InheritableThreadLocal` variables.
