//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[pg-server-session-handler]]
==== The SessionHandler

A `SessionHandler` is a `Handler` that implements the `SessionManager`, and is thus responsible for the creation, maintenance and propagation of sessions.
There are `SessionHandlers` for both the core and the various servlet environments.

Note that in the servlet environments, each `ServletContextHandler` or `WebAppContext` has at most a single `SessionHandler`.

===== Configuration

The majority of configuration for the `SessionHandler` can be done via `web.xml` `<session-config>` declarations, or the `javax.servlet.SessionCookieConfig` api.
There are also a few jetty-specific configuration methods that we will cover here:

setCheckingRemoteSessionIdEncoding::
Boolean, default `false`.
This controls whether response urls will be encoded with the session id as a path parameter when the URL is destined for a remote node.
In servlet environments, this can also be configured by:
* setting the `org.eclipse.jetty.session.CheckingRemoteSessionIdEncoding` context init parameter

setMaxInactiveInterval::
Integer, seconds.
This is the amount of time after which an unused session may be scavenged.
In servlet environments this can also be configured by:

* defining the `<session-config><session-timeout/></session-config>` element in `web.xml`, although take note that this element is specified in _minutes_ but this method uses _seconds_.
* calling the `ServletContext.setSessionTimeout(int)` method, where the timeout is configured in _minutes_.

setHttpOnly::
Boolean, default `false`.
If `true`, the session cookie will not be exposed to client-side scripting code.
In servlet environments this can also be configured by:

* using `SessionCookieConfig.setHttpOnly(boolean)` method
* defining the `<session-config><cookie-config><http-only/></cookie-config></session-config>` element in `web.xml`

[[pg-server-session-handler-refreshcookie]]
setRefreshCookieAge::
Integer, seconds, default is `-1`.
This controls resetting the session cookie when `SessionCookieConfig.setMaxAge(int)` is non-zero.
See also xref:pg-server-session-handler-maxAge[setting the max session cookie age with an init parameter].
If the amount of time since the session cookie was last set exceeds this time, the session cookie is regenerated to keep the session cookie valid.

setSameSite::
`HttpCookie.SameSite`, default `null`.
The values are `HttpCookie.SameSite.NONE`, `HttpCookie.SameSite.STRICT`, `HttpCookie.SameSite.LAX`.

setSecureRequestOnly::
Boolean, default `true`.
If `true` and the request is HTTPS, the set session cookie will be marked as `secure`, meaning the client will only send the session cookie to the server on subsequent requests over HTTPS.
In servlet environments this can also be configured by:

* using the `SessionCookieConfig.setSecure(true)` method, in which case the set session cookie will _always_ be marked as `secure`, even if the request triggering the creation of the cookie was not over HTTPS.

setSessionCookie::
String, default is `JSESSIONID`.
This is the name of the session cookie.
In servlet environments, this can alternatively be configured by:

* using `SessionCookieConfig.setName(String)` method
* setting the `org.eclipse.jetty.session.SessionCookie` context init parameter.

setSessionIdPathParameterName::
String, default is `jsessionid`.
This is the name of the path parameter used to transmit the session id on request URLs, and on encoded URLS in responses.
In servlet environments, this can alternatively be configured by:

* setting the `org.eclipse.jetty.session.SessionIdPathParameterName` context init parameter

setSessionTrackingModes::
`Set<SessionTrackingMode>`.
Default is `SessionTrackingMode.COOKIE`, `SessionTrackingMode.URL`.
This can also be configured by:

* using the `setSessionTrackingModes(Set<javax.servlet.SessionTrackingMode>)` method
* using the `javax.servlet.ServletContext.setSessionTrackingModes<Set<javax.servlet.SessionTrackingMode>)` method
* defining up to three ``<tracking-mode>``s for the `<session-config>` element in `web.xml`

setUsingCookies::
Boolean, default `true`.
Determines whether or not the `SessionHandler` will look for session cookies on requests, and will set session cookies on responses.
If `false` session ids must be transmitted as path params on URLs.

[[pg-server-session-handler-maxAge]]
setMaxAge::
This is the maximum number of seconds that the session cookie will be considered to be valid.
By default, the cookie has no maximum validity time.
See also xref:pg-server-session-handler-refreshcookie[refreshing the session cookie].
In servlet environments, this can also be configured by:

* calling the `ServletContext.getSessionCookieConfig().setMaxAge(int)` method.
* setting the `org.eclipse.jetty.session.MaxAge` context init parameter

setSessionDomain::
String, default `null`.
This is the domain of the session cookie.
In servlet environments, this can also be configured by:

* calling the `ServletContext.getSessionCookieConfig().setDomain(String)` method
* defining the `<session-config><cookie-config><domain/></cookie-config></session-config>` element in `web.xml`
* setting the `org.eclipse.jetty.session.SessionDomain` context init parameter

setSessionPath::
String, default `null`.
This is used when creating a new session cookie.
If nothing is configured, the context path is used instead, defaulting to `/`.
In servlet environments, this can also be configured by:

* calling the `ServletContext.getSessionCookieConfig().setPath(String)` method
* defining the `<session-config><cookie-config><path/></cookie-config></session-config>` element in `web.xml`
* setting the `org.eclipse.jetty.session.SessionPath` context init parameter

===== Statistics

Some statistics about the sessions for a context can be obtained from the `SessionHandler`, either by calling the methods directly or via `jmx`:

sessionsCreated::
This is the total number of sessions that have been created for this context since Jetty started.

sessionTimeMax::
The longest period of time a session was valid in this context before being invalidated.

sessionTimeMean::
The average period of time a session in this context was valid.

sessionTimeStdDev::
The standard deviation of the session validity times for this context.

sessionTimeTotal::
The total time that all sessions in this context have remained valid.

