//
// ========================================================================
// Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[pg-server-session-datastore-jdbc]]
===== The JDBCSessionDataStore

The `JDBCSessionDataStore` supports persistent storage of session data in a relational database.
To do that, it requires a `DatabaseAdaptor` that handles the differences between databases (eg Oracle, Postgres etc), and a `SessionTableSchema` that allows for the customization of table and column names.

[plantuml]
----
class JDBCSessionDataStore
class DatabaseAdaptor
class SessionTableSchema

JDBCSessionDataStore "1" *-- "1" DatabaseAdaptor
JDBCSessionDataStore "1" *-- "1" SessionTableSchema
----

`SessionData` is stored in a table with one row per session.
This is the table, with the table name, column names and type keywords at their default settings:


[caption="Table:"]
.JettySessions
[frame=all]
[cols=12*,options="header"]
|===
|sessionId
|contextPath
|virtualHost
|lastNode
|accessTime
|lastAccessTime
|createTime
|cookieTime
|lastSavedTime
|expiryTime
|maxInterval
|map
|120 varchar|60 varchar|60 varchar|60 varchar|long|long|long|long|long|long|long|blob
|===

The name of the table and all columns can be configured using the `SessionTableSchema` class described below.
Many databases use different keywords for the `long`, `blob` and `varchar` types, so you can explicitly configure these if jetty cannot determine what they should be at runtime based on the metadata available from a db connection using the `DatabaseAdaptor` class described below.

====== Configuration

The link:{javadoc-url}/org/eclipse/jetty/server/session/JDBCSessionDataStore.html[JDBCSessionDataStore] and corresponding link:{javadoc-url}/org/eclipse/jetty/server/session/JDBCSessionDataStoreFactory.html[JDBCSessionDataStoreFactory] supports the following configuration:

include::session-sessiondatastore.adoc[tag=common-datastore-config]

DatabaseAdaptor::
The `DatabaseAdaptor` can connect to a database either via a `javax.sql.Datasource` or a `java.sql.Driver`.
Additionally, a database-specific keyword can be configured for the `blob`, `varchar` and `long` types.
Note that the `DatabaseAdaptor` tries to automatically detect the type of the database from the first connection and select the appropriate type keywords, however you may need to explicitly configure them if you're not using `Postgres` or `Oracle`.

  datasource:::
  This can either be a `Datasource` instance or the jndi name of a `Datasource` to look up.
[source,java,indent=0]
----
include::../../{doc_code}/org/eclipse/jetty/docs/programming/server/session/SessionDocs.java[tags=dbaDatasource]
----

  driverInfo:::
  This is the name or instance of a jdbc `Driver` class and a connection url.
[source,java,indent=0]
----
include::../../{doc_code}/org/eclipse/jetty/docs/programming/server/session/SessionDocs.java[tags=dbaDriver]
----

  blobType:::
  Default `blob` or `bytea` for Postgres.

  longType:::
  Default `bigint` or `number(20)` for Oracle.

  stringType:::
  Default `varchar`.
  

SessionTableSchema::
  schemaName:::
  catalogName:::
The exact meaning of these two are dependent on your database vendor, but can broadly be described as further scoping for the session table name.
See https://en.wikipedia.org/wiki/Database_schema and https://en.wikipedia.org/wiki/Database_catalog.
These extra scoping names can come into play at startup time when Jetty determines if the session table already exists, or otherwise creates it on-the-fly.
If you have employed either of these concepts when you pre-created the session table, or you want to ensure that Jetty uses them when it auto-creates the session table, then you have two options: either set them explicitly, or let Jetty infer them from a database connection.
If you leave them unset, then no scoping will be done.
If you use the special value `INFERRED`, Jetty will determine them from a database connection.

  tableName:::
Default `JettySessions`.
This is the name of the table in which session data is stored.

  accessTimeColumn:::
Default `accessTime`.
This is the name of the column that stores the time - in ms since the epoch - at which a session was last accessed

  contextPathColumn:::
Default `contextPath`.
This is the name of the column that stores the `contextPath` of a session.

  cookieTimeColumn:::
Default `cookieTime`.
This is the name of the column that stores the time - in ms since the epoch - that the cookie was last set for a session.

  createTimeColumn:::
Default `createTime`.
This is the name of the column that stores the time - in ms since the epoch - at which a session was created.

  expiryTimeColumn:::
Default `expiryTime`.
This is name of the column that stores - in ms since the epoch - the time at which a session will expire.

  lastAccessTimeColumn:::
Default `lastAccessTime`.
This is the name of the column that stores the time - in ms since the epoch - that a session was previously accessed.

  lastSavedTimeColumn:::
Default `lastSavedTime`.
This is the name of the column that stores the time - in ms since the epoch - at which a session was last written.

  idColumn:::
Default `sessionId`.
This is the name of the column that stores the id of a session.

  lastNodeColumn:::
Default `lastNode`.
This is the name of the column that stores the `workerName` of the last node to write a session.

  virtualHostColumn:::
Default `virtualHost`.
This is the name of the column that stores the first virtual host of the context of a session.

  maxIntervalColumn:::
Default `maxInterval`.
This is the name of the column that stores the interval - in ms - during which a session can be idle before being considered expired.

  mapColumn:::
Default `map`.
This is the name of the column that stores the serialized attributes of a session.

