//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[pg-server-session-architecture]]
==== Session Architecture
==== Introduction
Jetty session support has been architected to provide a core implementation that is independent of the servlet specification.
This allows programmers who use core Jetty - without the servlet api - to still have classic servlet session-like support for their `Requests` and `Handlers`.

Jetty also adapts these core classes to each of the various servlet specification environments to deliver classic `HttpSessions` for `Servlets`, `Filters` etc.

We provide full support for the session lifecycle, in addition to L1 and L2 caching, and a number of options for persisting session data.
These features are all available to both core and servlet environments.

==== Terminology

In order to set the scene for our discussion of sessions in Jetty, here are some of the most important concepts that we  will refer to throughout the documentation.

SessionIdManager::: responsible for allocation of unique session ids. A `Server` can have at most 1 `SessionIdManager`.
HouseKeeper:::  responsible for orchestrating the detection and removal of expired sessions.  A `SessionIdManager` can have at most `HouseKeeper`.
SessionManager::: responsible for managing the lifecycle of sessions.
SessionHandler::: an implementation of `SessionManager` that adapts sessions to either the core or servlet specification environment. Each context has at most 1 `SessionHandler`.
SessionCache::: an L1 cache of in-use `ManagedSession` objects
Session::: a session that can be associated with a request
ManagedSession::: a `Session` that supports caching and lifecycle management
SessionData::: encapsulates the attributes and metadata associated with a `Session`
SessionDataStore::: responsible for creating, persisting and reading `SessionData`
CachingSessionDataStore::: an L2 cache of `SessionData`

Diagrammatically, these concepts can be represented as:

[plantuml]
----
title Session Composition Diagram
class Server

interface SessionIdManager

class HouseKeeper

interface SessionManager

class SessionHandler

interface SessionCache

interface SessionDataStore

class CachingSessionDataStore

interface Session

class ManagedSession

class SessionData

class Request

Server "1" *-down- "1" SessionIdManager
SessionIdManager "1" *-left- "1" HouseKeeper
Server "1" *-down- "n" SessionHandler
Request "1" *-down- "0/1" Session
SessionManager "1" *-down- "1" SessionCache
SessionManager <|-- SessionHandler
SessionCache "1" *-down- "1" SessionDataStore
SessionCache  o-down- ManagedSession
ManagedSession "1" *-- "1" SessionData
Session <|-- ManagedSession
SessionDataStore --> SessionData: CRUD
SessionDataStore <|-- CachingSessionDataStore
CachingSessionDataStore o- SessionData
----

