# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
This module enables support for Jakarta EE 11 web applications.

[environment]

[depend]
ee-webapp
ee-servlet
ee-security

[xml]
etc/jetty-ee-webapp.xml

[lib]
lib/jetty-ee-webapp-${jetty.version}.jar

[ini-template]
# tag::ini-template[]
## Customize protected and hidden classes for this web application context.
#jetty.webapp.addProtectedClasses+=,org.example.
#jetty.webapp.addHiddenClasses+=,org.example.

## Default ContextHandler class for ee environment deployments
# jetty.deploy.defaultContextHandlerClass=org.eclipse.jetty.ee.webapp.WebAppContext
# end::ini-template[]
