# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Template configuration file to apply to all web applications deployed in the EE11 environment.

[tags]
deployment

[depend]
ee11-deploy

[files]
basehome:modules/deployment.d/ee11-environment.properties|environments/ee11-environment.properties
basehome:modules/deployment.d/ee11-environment.xml|environments/ee11-environment.xml

