<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.quic</groupId>
    <artifactId>jetty-quic</artifactId>
    <version>12.1.8</version>
  </parent>
  <artifactId>jetty-quic-api</artifactId>
  <name>Core :: QUIC :: APIs</name>
  <description>Jetty QUIC API Artifact</description>

  <properties>
    <bundle-symbolic-name>${project.groupId}.api</bundle-symbolic-name>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-io</artifactId>
    </dependency>
  </dependencies>

</project>
