# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
JDBC Datasource connections for session storage.

[depends]
jdbc

[xml]
etc/sessions/jdbc/datasource.xml
