# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
JDBC Driver connections for session storage.

[depend]
jdbc

[xml]
etc/sessions/jdbc/driver.xml
