# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
JDBC Driver connections for session storage.

[depend]
jdbc

[xml]
etc/sessions/jdbc/driver.xml
