//
// ========================================================================
// Copyright (c) 1995-2020 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under
// the terms of the Eclipse Public License 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0
//
// This Source Code may also be made available under the following
// Secondary Licenses when the conditions for such availability set
// forth in the Eclipse Public License, v. 2.0 are satisfied:
// the Apache License v2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[websocket-jetty-api-session]]
=== WebSocket Session

The link:{JDURL}/org/eclipse/jetty/websocket/api/Session.html[Session] object can be used to:

The Connection State (is it open or not).

[source, java, subs="{sub-order}"]
----
if(session.isOpen()) {
  // send message
}
----

Is the Connection Secure.

[source, java, subs="{sub-order}"]
----
if(session.isSecure()) {
  // connection is using 'wss://'
}
----

What was in the Upgrade Request and Response.

[source, java, subs="{sub-order}"]
----
UpgradeRequest req = session.getUpgradeRequest();
String channelName = req.getParameterMap().get("channelName");

UpgradeResponse resp = session.getUpgradeResponse();
String subprotocol = resp.getAcceptedSubProtocol();
----

What is the Local and Remote Address.

[source, java, subs="{sub-order}"]
----
SocketAddress remoteAddr = session.getRemoteAddress();
----

Get and Set the Idle Timeout

[source, java, subs="{sub-order}"]
----
session.setIdleTimeout(Duration.ofMillis(2000));
----
