# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Example of a module

[depend]
base

[after]
optional

[lib]
lib/main.jar
lib/other.jar

[xml]
etc/main.xml

[files]
maindir/

[ini]
main.prop=value0

[ini-template]
### main example configuration
main.prop=valueT
