@startuml

IDLE:
PROCESSING:
PROCESSING_SUCCESS_CALLED:
PROCESSING_FAILED_CALLED:
PROCESSING_ABORT:
PROCESSING_ABORT_CALLED:
PENDING:
PENDING_ABORT_CALLED:
FINISHED:

[*] --> IDLE

IDLE --> PROCESSING: iterate()
IDLE --> FINISHED: abort(x)

PROCESSING --> IDLE: a=IDLE
PROCESSING --> FINISHED: a=SUCCEEDED
PROCESSING --> PENDING: a=SCHEDULED
PROCESSING --> PROCESSING_SUCCESS_CALLED: succeeded()
PROCESSING --> PROCESSING_FAILED_CALLED: failed(x)
PROCESSING --> PROCESSING_ABORT: abort(x)

PENDING --> PROCESSING: succeeded()
PENDING --> FINISHED: failed(x)
PENDING --> PENDING_ABORT_CALLED: abort(x)

PROCESSING_SUCCESS_CALLED --> PROCESSING: a=SCHEDULED
PROCESSING_SUCCESS_CALLED --> PROCESSING_ABORT_CALLED: abort(x)

PROCESSING_FAILED_CALLED --> FINISHED: a=SCHEDULED
PROCESSING_FAILED_CALLED --> PROCESSING_ABORT_CALLED: abort(x)

PROCESSING_ABORT --> FINISHED: a=IDLE
PROCESSING_ABORT --> FINISHED: a=SUCCEEDED
PROCESSING_ABORT --> PENDING_ABORT_CALLED: a=SCHEDULED
PROCESSING_ABORT --> PROCESSING_ABORT_CALLED: succeeded()
PROCESSING_ABORT --> PROCESSING_ABORT_CALLED: failed(x)
PROCESSING_ABORT --> PROCESSING_ABORT: abort(x)

PENDING_ABORT_CALLED --> FINISHED: succeeded()
PENDING_ABORT_CALLED --> FINISHED: failed(x)
PENDING_ABORT_CALLED --> PENDING_ABORT_CALLED: abort(x)

PROCESSING_ABORT_CALLED -> FINISHED: a=*
PROCESSING_ABORT_CALLED -> ABORTING: abort(x)

@enduml