@startuml

IDLE:
PROCESSING:
PROCESSING_CALLED:
PROCESSING_ABORTED:
PROCESSING_CALLED_ABORT:
PENDING:
PENDING_ABORT:
COMPLETE:

[*] --> IDLE

/' iterate() '/
IDLE --> PROCESSING: iterate()

/' processing() '/
PROCESSING --> IDLE: a=IDLE
PROCESSING --> PENDING: a=SCHEDULED
PROCESSING --> COMPLETE: a=SUCCEEDED

PROCESSING_CALLED --> PROCESSING: a=SCHEDULED

PROCESSING_ABORTED --> COMPLETE: a=IDLE
PROCESSING_ABORTED --> COMPLETE: a=SUCCEEDED
PROCESSING_ABORTED --> PENDING_ABORT: a=SCHEDULED

PROCESSING_CALLED_ABORT -> COMPLETE: a=IDLE
PROCESSING_CALLED_ABORT -> COMPLETE: a=SCHEDULED
PROCESSING_CALLED_ABORT -> COMPLETE: a=SUCCEEDED

/' succeeded() '/
PROCESSING --> PROCESSING_CALLED: succeeded()
PROCESSING_ABORTED --> PROCESSING_CALLED_ABORT: succeeded()
PENDING --> PROCESSING: succeeded()
PENDING_ABORT --> COMPLETE: succeeded()

/' failed(x) '/
PROCESSING --> PROCESSING_CALLED: failed(x)
PROCESSING_ABORTED --> PROCESSING_CALLED_ABORT: failed(x)
PENDING --> COMPLETE: failed(x)
PENDING_ABORT --> COMPLETE: failed(x)

/' abort(x) '/
IDLE --> COMPLETE: abort(x)
PROCESSING --> PROCESSING_ABORTED: abort(x)
PROCESSING_CALLED --> PROCESSING_CALLED_ABORT: abort(x)
PROCESSING_ABORTED --> PROCESSING_ABORTED: abort(x)
PROCESSING_CALLED_ABORT -> PROCESSING_CALLED_ABORT: abort(x)
PENDING --> PENDING_ABORT: abort(x)
PENDING_ABORT --> PENDING_ABORT: abort(x)


@enduml