//  ========================================================================
//  Copyright (c) 1995-2016 Mort Bay Consulting Pty. Ltd.
//  ========================================================================
//  All rights reserved. This program and the accompanying materials
//  are made available under the terms of the Eclipse Public License v1.0
//  and Apache License v2.0 which accompanies this distribution.
//
//      The Eclipse Public License is available at
//      http://www.eclipse.org/legal/epl-v10.html
//
//      The Apache License v2.0 is available at
//      http://www.opensource.org/licenses/apache2.0.php
//
//  You may elect to redistribute this code under either of these licenses.
//  ========================================================================

[[static-content-deployment]]
=== Configuring Static Content Deployment

Should you want to serve purely static content, you can use the Jetty
Deployment Descriptor XML concepts and the internal ResourceHandler to
setup simple serving of static content. Just create a file called
`scratch.xml` in the `${jetty.home}/webapps` directory and paste these
file contents in it.

[source,xml]
----

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">
<Configure class="org.eclipse.jetty.server.handler.ContextHandler">
  <Set name="contextPath">/scratch</Set>
  <Set name="handler">
    <New class="org.eclipse.jetty.server.handler.ResourceHandler">
      <Set name="resourceBase">/home/jesse/scratch</Set>
      <Set name="directoriesListed">true</Set>
    </New>
  </Set>
</Configure>


----

This is a very basic setup for serving static files, if you want
advanced static file serving, use the
link:{JXURL}/org/eclipse/jetty/servlet/DefaultServlet.html[DefaultServlet].
