# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables all available compression algorithms in CompressionHandler.

[tags]
server
handler
compression
brotli
gzip
zstandard

[depend]
compression-brotli
compression-gzip
compression-zstandard
