# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the Brotli compression algorithm in CompressionHandler.

[tags]
server
handler
compression
brotli

[depend]
brotli-compression
compression

[xml]
etc/jetty-compression-brotli.xml

[ini-template]
# tag::documentation[]
## Minimum content length after which brotli is enabled
# jetty.compression.brotli.minCompressSize=48

## Buffer Size for Decoder
# jetty.compression.brotli.decoder.bufferSize=16384

## Buffer Size for Encoder
# jetty.compression.brotli.encoder.bufferSize=4096

## Compression Level for Encoder
# valid values from 0 to 11
# jetty.compression.brotli.encoder.compressionLevel=11

## Strategy for Encoder
# 0 = Generic
# 1 = Text
# 2 = Font
# jetty.compression.brotli.encoder.strategy=0

## Brotli log2(LZ window size) for Encoder
# valid values from 10 to 24
# jetty.compression.brotli.encoder.lgWindow=22
# end::documentation[]
