//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

= HTTP/3 Server Library

In the vast majority of cases, server applications should use the generic, high-level, xref:server/http.adoc[HTTP server library] that also provides HTTP/3 support via the HTTP/3 connector and ``ConnectionFactory``s as described in details xref:server/http.adoc#connector-protocol-http3[here].

The low-level HTTP/3 server library has been designed for those applications that need low-level access to HTTP/3 features such as _sessions_, _streams_ and _frames_, and this is quite a rare use case.

See also the correspondent xref:client/http3.adoc[HTTP/3 client library].

[[intro]]
== Introduction

The Maven artifact coordinates for the HTTP/3 server library are the following:

[,xml,subs=attributes+]
----
<dependency>
  <groupId>org.eclipse.jetty.http3</groupId>
  <artifactId>jetty-http3-server</artifactId>
  <version>{jetty-version}</version>
</dependency>
----

The HTTP/3 protocol is layered on top of the underlying QUIC protocol.

The QUIC protocol implementation underlying HTTP/3 is provided by Jetty classes that wrap the link:https://github.com/cloudflare/quiche[Quiche] native library, so you need also the following artifact:

[,xml,subs=attributes+]
----
<dependency>
  <groupId>org.eclipse.jetty.quic</groupId>
  <artifactId>jetty-quic-quiche-server</artifactId>
  <version>{jetty-version}</version>
</dependency>
----

Furthermore, the binding to the Quiche native library has two implementations: one based on link:https://github.com/java-native-access/jna[JNA] that works with Java 17 or later, and one based on JDK's https://openjdk.org/jeps/454[Foreign Function & Memory (FFM)] APIs that works with Java 22 or later.

You must choose the binding you want to use (depending on the Java version you are using), with either of the following artifacts:

[,xml,subs=attributes+]
----
<dependency>
  <groupId>org.eclipse.jetty.quic</groupId>
  <artifactId>jetty-quic-quiche-jna</artifactId>
  <version>{jetty-version}</version>
</dependency>
----

[,xml,subs=attributes+]
----
<dependency>
  <groupId>org.eclipse.jetty.quic</groupId>
  <artifactId>jetty-quic-quiche-foreign</artifactId>
  <version>{jetty-version}</version>
</dependency>
----

[WARNING]
====
HTTP/3 support is considered experimental, meaning that:

* It is not suited for production use, for reasons such as bad performance, instability, incompleteness, etc.
* The APIs can change in incompatible ways between micro releases, for example classes or methods may be removed or method signature may be changed incompatibly.
====

[NOTE]
====
Since Java 22, the JVM emits a warning message when Java code tries to access code in native libraries.
For example with Java 25:

----
WARNING: A restricted method in java.lang.foreign.AddressLayout has been called
WARNING: java.lang.foreign.AddressLayout::withTargetLayout has been called by org.eclipse.jetty.quic.quiche.foreign.NativeHelper in an unnamed module (file:/home/simon/opensource/jetty/12.1.x/jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/target/classes/)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
----

To avoid the warning, you can start the JVM as suggested by the warning message above, by adding `--enable-native-access=ALL-UNNAMED` on the command line.
This grants any code in the class-path access to any native library.

If you are running in JPMS mode, you can explicitly grant access just to the JPMS module(s) that require it.
To grant Jetty access to the Quiche native library, use `--enable-native-access=org.eclipse.jetty.quic.quiche.foreign`.
This grants only to the Jetty JPMS module `org.eclipse.jetty.quic.quiche.foreign` in the module-path access to any native library.
====

When a client wants to establish a connection with a server, the QUIC protocol establishes the connection with the server, represented by a QUIC _session_.

A QUIC _session_ typically has a long life -- once the connection is established, it remains active until it is not used anymore (and therefore it is closed by the idle timeout mechanism), until a fatal error occurs (for example, a network failure), or if one of the peers decides unilaterally to close the connection.

There is a 1-to-1 relationship between a QUIC _session_ and an HTTP/3 _session_, defined by class `org.eclipse.jetty.http3.api.Session.Server`.

The QUIC protocol is multiplexed, that is it allows multiple, independent, QUIC _streams_ to exchange data to and from the server, over a single connection.
Therefore, a single QUIC _session_ manages multiple concurrent QUIC _streams_.

There is a 1-to-1 relationship between a QUIC _stream_ and an HTTP/3 _stream_, defined by class `org.eclipse.jetty.http3.api.Stream.Server`.

Each HTTP/3 request/response cycle is carried by an HTTP/3 _stream_, and has typically a very short life compared to the _session_: a _stream_ only exists for the duration of the request/response cycle and then disappears.

// TODO: flow control?
//[[pg-server-http3-flow-control]]
//==== HTTP/3 Flow Control
//
//include::../../http3.adoc[tag=flowControl]
//
//How a server application should handle HTTP/3 flow control is discussed in details in <<request,this section>>.

[[setup]]
== Server Setup

The low-level HTTP/3 support is provided by `org.eclipse.jetty.http3.server.RawHTTP3ServerConnectionFactory` and `org.eclipse.jetty.http3.api.Session.Server.Listener`:

[,java,indent=0]
----
include::code:example$src/main/java/org/eclipse/jetty/docs/programming/server/http3/HTTP3ServerDocs.java[tags=setup]
----

Where server applications using the xref:server/http.adoc[high-level server library] deal with HTTP requests and responses in ``Handler``s, server applications using the low-level HTTP/3 server library deal directly with HTTP/3 __session__s, __stream__s and __frame__s in a `Session.Server.Listener` implementation.

The `Session.Server.Listener` interface defines a number of methods that are invoked by the implementation upon the occurrence of HTTP/3 events, and that server applications can override to react to those events.

Please refer to the `Session.Server.Listener` link:{javadoc-url}/org/eclipse/jetty/http3/api/Session.Server.Listener.html[javadocs] for the complete list of events.

The first event is the _accept_ event and happens when a client opens a new QUIC connection to the server and the server accepts the connection.
This is the first occasion where server applications have access to the HTTP/3 `Session` object:

[,java,indent=0]
----
include::code:example$src/main/java/org/eclipse/jetty/docs/programming/server/http3/HTTP3ServerDocs.java[tags=accept]
----

After the QUIC connection has been established, both client and server must send an HTTP/3 `SETTINGS` frame to exchange their HTTP/3 configuration.
This generates the _preface_ event, where applications can customize the HTTP/3 configuration by returning a map of settings that the implementation will send to the other peer:

[,java,indent=0]
----
include::code:example$src/main/java/org/eclipse/jetty/docs/programming/server/http3/HTTP3ServerDocs.java[tags=preface]
----

[[request]]
== Receiving a Request

Receiving an HTTP request from the client, and sending a response, creates a _stream_ that encapsulates the exchange of HTTP/3 frames that compose the request and the response.

An HTTP request is made of a `HEADERS` frame, that carries the request method, the request URI and the request headers, and optional `DATA` frames that carry the request content.

Receiving the `HEADERS` frame opens the `Stream`:

[,java,indent=0]
----
include::code:example$src/main/java/org/eclipse/jetty/docs/programming/server/http3/HTTP3ServerDocs.java[tags=request]
----

Server applications should return a `Stream.Server.Listener` implementation from `onRequest(\...)` to be notified of events generated by the client, such as `HEADERS` frame carrying the request headers, `DATA` frames carrying request content, or a failure event indicating that the client wants to cancel the request, or an idle timeout event indicating that the client was supposed to send more frames, but it did not.

The example below shows how to receive request content:

[,java,indent=0]
----
include::code:example$src/main/java/org/eclipse/jetty/docs/programming/server/http3/HTTP3ServerDocs.java[tags=requestContent]
----

// TODO: flow control?
//include::../../http3.adoc[tag=apiFlowControl]

[[response]]
== Sending a Response

After receiving an HTTP request, a server application must send an HTTP response.

An HTTP response is typically composed of a `HEADERS` frame containing the HTTP status code and the response headers, and optionally one or more `DATA` frames containing the response content bytes.

The HTTP/3 protocol also supports response trailers (that is, headers that are sent after the response content) that also are sent using a `HEADERS` frame.

A server application can send a response in this way:

[,java,indent=0]
----
include::code:example$src/main/java/org/eclipse/jetty/docs/programming/server/http3/HTTP3ServerDocs.java[tags=response;!exclude]
----

[[terminate]]
== Terminating a Request

A server application may decide that it does not want to accept the request.
For example, it may throttle the client because it sent too many requests in a time window, or the request is invalid (and does not deserve a proper HTTP response), etc.

A request can be abruptly terminated in this way:

[,java,indent=0]
----
include::code:example$src/main/java/org/eclipse/jetty/docs/programming/server/http3/HTTP3ServerDocs.java[tags=terminate;!exclude]
----
