# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
<inherit>

[depend]
ee/common-servlet
ee/common-annotations

[lib]
lib/jetty-ee-apache-jsp-${jetty.version}.jar

