# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
<inherit>

[depend]
ee/common-servlet
ee/common-annotations

[lib]
lib/ee-apache-jsp/@org.eclipse.jdt:ecj@
lib/ee-apache-jsp/@org.mortbay.jasper:mortbay-apache-el@
lib/ee-apache-jsp/@org.mortbay.jasper:mortbay-apache-jsp@
lib/jetty-ee-apache-jsp-${jetty.version}.jar

