# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee9

[lib]
lib/ee9-glassfish-jstl/*.jar
