# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enable the Jetty WebSocket API support for deployed web applications.

[environment]
ee8

[tags]
websocket

[depends]
websocket-core-server
ee8-annotations

[files]
maven://org.eclipse.jetty.ee8.websocket/jetty-ee8-websocket-jetty-api/${jetty.version}/jar|lib/ee8/jetty-ee8-websocket-jetty-api-${jetty.version}.jar
maven://org.eclipse.jetty.ee8.websocket/jetty-ee8-websocket-jetty-common/${jetty.version}/jar|lib/ee8/jetty-ee8-websocket-jetty-common-${jetty.version}.jar
maven://org.eclipse.jetty.ee8.websocket/jetty-ee8-websocket-jetty-server/${jetty.version}/jar|lib/ee8/jetty-ee8-websocket-jetty-server-${jetty.version}.jar
maven://org.eclipse.jetty.ee8.websocket/jetty-ee8-websocket-servlet/${jetty.version}/jar|lib/ee8/jetty-ee8-websocket-servlet-${jetty.version}.jar

[lib]
lib/ee8/jetty-ee8-websocket-jetty-api-${jetty.version}.jar
lib/ee8/jetty-ee8-websocket-jetty-common-${jetty.version}.jar
lib/ee8/jetty-ee8-websocket-jetty-server-${jetty.version}.jar
lib/ee8/jetty-ee8-websocket-servlet-${jetty.version}.jar
