//
//  ========================================================================
//  Copyright (c) 1995-2018 Mort Bay Consulting Pty. Ltd.
//  ========================================================================
//  All rights reserved. This program and the accompanying materials
//  are made available under the terms of the Eclipse Public License v1.0
//  and Apache License v2.0 which accompanies this distribution.
//
//      The Eclipse Public License is available at
//      http://www.eclipse.org/legal/epl-v10.html
//
//      The Apache License v2.0 is available at
//      http://www.opensource.org/licenses/apache2.0.php
//
//  You may elect to redistribute this code under either of these licenses.
//  ========================================================================
//

[[troubleshooting-reporting]]

=== Preparing an Issue Report

After link:#troubleshooting-diagnose[diagnosing] an issue and link:#troubleshooting-analyze[analyzing] it, you may already have a pretty good idea of how to resolve it.
If you do not there are plenty of resources you can turn to for help.
Before you do, however, it is strongly recommended that you take the time to write up a detailed report of the issue.
While this may seem time consuming good, well-constructed reports are extremely important for those helping you.

==== What to Include

===== Jetty Version

Knowing the exact version of Jetty you are running on is key to helping solve your issue.
Be specific - reporting an issue and simply reporting the version Jetty 8 or Jetty 9 isn't particularly helpful when you consider Jetty 8 had two major version releases (8.0 and 8.1) both with several versions each; Jetty 9 has had four so far, some with more than 20 releases each!
Many versions of Jetty evolve over the course of years and will include many changes from one release to another.

When you report the version it should include as much detail as possible::
* *Good:* Jetty 9.4
* *Better:* Jetty 9.4.10
* *Best:* Jetty 9.4.10.v20180503

Version numbers are added to the naming of all tars, jars, and zip files distributed by the Jetty team.
If you are working with the Jetty distribution, you can quickly check the version of by running the server with the `--version` argument.

[source, screen, subs="{sub-order}"]
----
$ java -jar ${JETTY.HOME}/start.jar --version
----

____
[NOTE]
When reporting the Jetty version, it is also very helpful to include the Java version you are using as well.
Again, be specific - reporting Java 9 is helpful, but Java 9.0.4 is even more so.
____

===== When The Issue Occurred

Believe it or not, sometimes it is very helpful to know what time the issue manifested itself.
Both the sever time and/or time zone where the server is located can be helpful in diagnosing issues.

===== Server Status

It is easy enough to report that the sever has crashed, but that offers very in little in the way of practical information.
Stack traces are an invaluable resource (and definitely include these in their entirety), but so too is knowing how the server was running otherwise.
Some things to consider include:

* What was the CPU and RAM usage of the server at the time of the crash?
* How many clients were connected, and what did the number of requests look like?
* *MORE?*

===== Reproducing the Issue

Paramount to any issue/bug report are steps for reproduction.
Simply put, if you cannot reproduce the issue, it is unlikely whomever you are asking for help will be able to either.
Further, reproduction steps should be clear, and include as much relevant information as possible.

Reproduction steps should not only include what happened in the moments up to the issue/crash, but also any related configuration that may have precipitated it.
For example, if everything was running correctly and you happened to make changes to the allowed SSL Ciphers, you would need to detail exactly what you changed in your issue report.
Further, when it is possible, try starting a fresh server instance up and applying the same changes, following the same steps, and recording the results.
Does this instance also crash?
If so, do you receive the same error?

When possible, it is recommended to share a sample project or code snippet that reproduces the issue.
link:https://github.com/[GitHub], which is discussed in the section on link:#troubleshooting-support-resources[Where to Find Help], is a free and easy way to upload entire projects that you can share with others for assistance.
