//
//  ========================================================================
//  Copyright (c) 1995-2018 Mort Bay Consulting Pty. Ltd.
//  ========================================================================
//  All rights reserved. This program and the accompanying materials
//  are made available under the terms of the Eclipse Public License v1.0
//  and Apache License v2.0 which accompanies this distribution.
//
//      The Eclipse Public License is available at
//      http://www.eclipse.org/legal/epl-v10.html
//
//      The Apache License v2.0 is available at
//      http://www.opensource.org/licenses/apache2.0.php
//
//  You may elect to redistribute this code under either of these licenses.
//  ========================================================================
//

[[troubleshooting-report]]

=== Preparing an Issue Report

After link:#troubleshooting-diagnose[diagnosing] an issue and link:#troubleshooting-analyze[analyzing] it, you may already have a pretty good idea of how to resolve it.
If you do not there are plenty of resources you can turn to for help.
Before you do, however, it is strongly recommended that you take the time to write up a detailed report of the issue.
In a time-sensitive situation this may seem time consuming, but good, well-constructed reports are extremely important for those helping you.

==== What to Include

General good practices when reporting problems::
* Report version, repeatability, etc.
* Determine and report the time and timezone of the incident
* For all log/debug reports provided, give a description of when they were taken and the state of the server.
* Practice these steps on a good working server and save the results for comparison.
** Have known health check URIs that you can hit etc.
