# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables support for EE11 FastCGI proxying.

[environment]
ee11

[tags]
fcgi
proxy

[depends]
fcgi

[files]
maven://org.eclipse.jetty.ee11/jetty-ee11-fcgi-proxy/${project.version}/jar|lib/ee11/jetty-ee11-fcgi-proxy-${project.version}.jar
maven://org.eclipse.jetty.ee11/jetty-ee11-proxy/${project.version}/jar|lib/ee11/jetty-ee11-proxy-${project.version}.jar

[lib]
lib/ee11/jetty-ee11-fcgi-proxy-${project.version}.jar
lib/ee11/jetty-ee11-proxy-${project.version}.jar
