# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee11

[depend]
ee11-plus
annotations

[lib]
lib/jetty-ee11-annotations-${jetty.version}.jar
lib/ee11-annotations/@jakarta.annotation:jakarta.annotation-api@
