# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee11

[depends]
ee11-plus
annotations

[ini]
ee11.jakarta.annotation.api.version?=@ee11.jakarta.annotation.api.version@

[files]
maven://jakarta.annotation/jakarta.annotation-api/${ee11.jakarta.annotation.api.version}/jar|lib/ee11/support/jakarta.annotation.jakarta.annotation-api-${ee11.jakarta.annotation.api.version}.jar
maven://org.eclipse.jetty.ee11/jetty-ee11-annotations/${jetty.version}/jar|lib/ee11/jetty-ee11-annotations-${jetty.version}.jar

[lib]
lib/ee11/jetty-ee11-annotations-${jetty.version}.jar
lib/ee11/support/jakarta.annotation.jakarta.annotation-api-${ee11.jakarta.annotation.api.version}.jar
