# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee12

[depends]
ee12-apache-jsp

[lib]
lib/ee12-glassfish-jstl/@jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api@
lib/ee12-glassfish-jstl/@org.glassfish.wasp:wasp@
