# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Provides a DefaultAuthConfigFactory for jaspi

[environment]
ee12

[tags]
security

[depend]
ee12-security

[provide]
auth-config-factory

[xml]
etc/jaspi/jetty-ee12-jaspi-default.xml
