//  ========================================================================
//  Copyright (c) 1995-2016 Mort Bay Consulting Pty. Ltd.
//  ========================================================================
//  All rights reserved. This program and the accompanying materials
//  are made available under the terms of the Eclipse Public License v1.0
//  and Apache License v2.0 which accompanies this distribution.
//
//      The Eclipse Public License is available at
//      http://www.eclipse.org/legal/epl-v10.html
//
//      The Apache License v2.0 is available at
//      http://www.opensource.org/licenses/apache2.0.php
//
//  You may elect to redistribute this code under either of these licenses.
//  ========================================================================

[[jetty-dump-tool]]
=== Jetty Dump Tool

The dump feature in Jetty provides a good snapshot of the status of the threadpool, select sets, classloaders, and so forth. 
To get maximum detail from the dump, you need to `setDetailDump(true)` on any `QueuedThreadPools` you are using. 
You can do this by a direct call if you are embedding Jetty, or in `jetty.xml`.

[[configuring-dump-feature]]
==== Configuring the Dump Feature in jetty.xml

You can request that Jetty do a dump immediately after starting and just before stopping by calling the appropriate setters on the `Server` instance. 
This can be accomplished in `jetty.xml` with:

[source, xml, subs="{sub-order}"]
----
<Set name="dumpAfterStart">true</Set>
<Set name="dumpBeforeStop">true</Set>
----

[[extra-threadpool-info]]
==== Extra ThreadPool Information

You can get additional detail from the `QueuedThreadPool` if `setDetailedDump(true)` is called on the thread pool instance. 
Do this in `jetty.xml` as follows:

[source, xml, subs="{sub-order}"]
----
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <!-- ==================================== -->
  <!-- Server Thread Pool                   --> 
  <!-- ==================================== -->
  <Set name="ThreadPool">
     <!-- Default queued blocking threadpool -->
     <New class="org.eclipse.jetty.util.thread.QueuedThreadPool">
       <Set name="minThreads">10</Set>
       <Set name="maxThreads">200</Set>
       <Set name="detailedDump">true</Set>
     </New>
  </Set>
----

[[dump-tool-via-jmx]]
==== Using the Dump Feature via JMX

The `dump` method is on the Server instance and many of its nested components (Handlers, Connectors, and so forth). 
Dumps may be obtained by calling these methods either in code or via JMX (see xref:using-jmx[]).

The Server MBean has a `dump()` method, which dumps everything, plus a `dumpStdErr()` operation that dumps to StdErr rather than replying to JConsole.

[[examing-jetty-distro-dump]]
==== Examining a Jetty Distribution Dump

This is a dump of the stock jetty-distribution with extra threadpool information:

....
org.eclipse.jetty.server.Server@76f08fe1 - STARTING
 += qtp1062680061{STARTED,10<=13<=200,i=1,q=0} - STARTED
 |   +- 12 qtp1062680061-12-selector-0 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 13 qtp1062680061-13-selector-6 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 14 qtp1062680061-14-selector-5 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 15 qtp1062680061-15-acceptor-0-ServerConnector@3d0f282{HTTP/1.1}{0.0.0.0:9090} BLOCKED
 |   |   +- sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:210)
 |   |   +- org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:284)
 |   |   +- org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:460)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 16 qtp1062680061-16-selector-1 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 17 qtp1062680061-17-selector-2 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 18 qtp1062680061-18-selector-3 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 19 qtp1062680061-19-selector-4 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 20 qtp1062680061-20-selector-7 RUNNABLE
 |   |   +- sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   |   +- sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:159)
 |   |   +- sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
 |   |   +- sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 |   |   +- sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:435)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 21 qtp1062680061-21-acceptor-1-ServerConnector@3d0f282{HTTP/1.1}{0.0.0.0:9090} RUNNABLE
 |   |   +- sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
 |   |   +- sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:226)
 |   |   +- org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:284)
 |   |   +- org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:460)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 49 qtp1062680061-49-acceptor-2-ServerConnector@3d0f282{HTTP/1.1}{0.0.0.0:9090} BLOCKED
 |   |   +- sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:210)
 |   |   +- org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:284)
 |   |   +- org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:460)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 50 qtp1062680061-50-acceptor-3-ServerConnector@3d0f282{HTTP/1.1}{0.0.0.0:9090} BLOCKED
 |   |   +- sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:210)
 |   |   +- org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:284)
 |   |   +- org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:460)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
 |   |   +- java.lang.Thread.run(Thread.java:722)
 |   +- 52 qtp1062680061-52 TIMED_WAITING IDLE
 += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@725f5 - STARTED
 += org.eclipse.jetty.server.handler.HandlerCollection@58b37561 - STARTED
 |   += org.eclipse.jetty.server.handler.ContextHandlerCollection@64c6e290 - STARTED
 |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   += o.e.j.w.WebAppContext@7ea88b1c{/async-rest,[file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/, jar:file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/example-async-rest-jar-9.0.2.v20130417.jar!/META-INF/resources/],AVAILABLE}{/async-rest.war} - STARTED
 |   |   |   += org.eclipse.jetty.server.session.SessionHandler@6dfb8d2e - STARTED
 |   |   |   |   += org.eclipse.jetty.server.session.HashSessionManager@6cb83869 - STARTED
 |   |   |   |   += org.eclipse.jetty.security.ConstraintSecurityHandler@2848c90e - STARTED
 |   |   |   |   |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@52b12fef
 |   |   |   |   |   += org.eclipse.jetty.servlet.ServletHandler@46bac287 - STARTED
 |   |   |   |   |   |   += default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true - STARTED
 |   |   |   |   |   |   |   +- maxCacheSize=256000000
 |   |   |   |   |   |   |   +- etags=true
 |   |   |   |   |   |   |   +- dirAllowed=true
 |   |   |   |   |   |   |   +- gzip=true
 |   |   |   |   |   |   |   +- maxCachedFileSize=200000000
 |   |   |   |   |   |   |   +- redirectWelcome=false
 |   |   |   |   |   |   |   +- acceptRanges=true
 |   |   |   |   |   |   |   +- welcomeServlets=false
 |   |   |   |   |   |   |   +- aliases=false
 |   |   |   |   |   |   |   +- useFileMappedBuffer=true
 |   |   |   |   |   |   |   +- maxCachedFiles=2048
 |   |   |   |   |   |   +- [/]=>default
 |   |   |   |   |   |   += jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true - STARTED
 |   |   |   |   |   |   |   +- logVerbosityLevel=DEBUG
 |   |   |   |   |   |   |   +- fork=false
 |   |   |   |   |   |   |   +- com.sun.appserv.jsp.classpath=/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar:/home/user/jetty-distribution-{VERSION}/resources:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/start.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/opt/local/lib/libsvnjavahl-1.0.dylib:/System/Library/Java/Extensions/AppleScriptEngine.jar:/System/Library/Java/Extensions/dns_sd.jar:/System/Library/Java/Extensions/j3daudio.jar:/System/Library/Java/Extensions/j3dcore.jar:/System/Library/Java/Extensions/j3dutils.jar:/System/Library/Java/Extensions/jai_codec.jar:/System/Library/Java/Extensions/jai_core.jar:/System/Library/Java/Extensions/libAppleScriptEngine.jnilib:/System/Library/Java/Extensions/libJ3D.jnilib:/System/Library/Java/Extensions/libJ3DAudio.jnilib:/System/Library/Java/Extensions/libJ3DUtils.jnilib:/System/Library/Java/Extensions/libmlib_jai.jnilib:/System/Library/Java/Extensions/libQTJNative.jnilib:/System/Library/Java/Extensions/mlibwrapper_jai.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/System/Library/Java/Extensions/QTJava.zip:/System/Library/Java/Extensions/vecmath.jar:/usr/lib/java/libjdns_sd.jnilib
 |   |   |   |   |   |   |   +- scratchdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/jsp
 |   |   |   |   |   |   |   +- xpoweredBy=false
 |   |   |   |   |   |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
 |   |   |   |   |   |   += SerialRestServlet@461411d==org.eclipse.jetty.example.asyncrest.SerialRestServlet,-1,false - STARTED
 |   |   |   |   |   |   +- [/testSerial]=>SerialRestServlet
 |   |   |   |   |   |   += AsyncRestServlet@73eb9bd5==org.eclipse.jetty.example.asyncrest.AsyncRestServlet,-1,false - STARTED
 |   |   |   |   |   |   +- [/testAsync]=>AsyncRestServlet
 |   |   |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |   |   += HashLoginService[Test Realm] - STARTED
 |   |   |   |   |   +- org.eclipse.jetty.security.DefaultIdentityService@d2539a6
 |   |   |   |   |   +- org.eclipse.jetty.security.authentication.BasicAuthenticator@7b239469
 |   |   |   |   |   |
 |   |   |   |   |   +> HashLoginService[Test Realm] - STARTED
 |   |   |   |   |   +> org.eclipse.jetty.security.DefaultIdentityService@d2539a6
 |   |   |   |   |   +> org.eclipse.jetty.security.authentication.BasicAuthenticator@7b239469
 |   |   |   |   |   +> []
 |   |   |   |   |   +> /={TRACE={RoleInfo,F,C[]}}
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   += org.eclipse.jetty.servlet.ErrorPageErrorHandler@3c121009 - STARTED
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |
 |   |   |   +> WebAppClassLoader=Async REST Webservice Example@52934ea0
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/classes/
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/example-async-rest-jar-9.0.2.v20130417.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-util-ajax-{VERSION}.jar
 |   |   |   |   +- startJarLoader@7194b34a
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/resources/
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar
 |   |   |   |       +- sun.misc.Launcher$AppClassLoader@19d1b44b
 |   |   |   |           +- file:/home/user/jetty-distribution-{VERSION}/start.jar
 |   |   |   |           +- sun.misc.Launcher$ExtClassLoader@1693b52b
 |   |   |   +> javax.servlet.context.tempdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-
 |   |   |   +> org.apache.catalina.jsp_classpath=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/classes:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/example-async-rest-jar-9.0.2.v20130417.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/jetty-util-ajax-{VERSION}.jar
 |   |   |   +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/servlet-api-[^/]*\.jar$
 |   |   |   +> com.sun.jsp.taglibraryCache={}
 |   |   |   +> com.sun.jsp.tagFileJarUrlsCache={}
 |   |   += o.e.j.s.h.MovedContextHandler@5e0c8d24{/oldContextPath,null,AVAILABLE} - STARTED
 |   |   |   += org.eclipse.jetty.server.handler.MovedContextHandler$Redirector@2a4200d3 - STARTED
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |
 |   |   |   +> No ClassLoader
 |   |   |   +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/servlet-api-[^/]*\.jar$
 |   |   += o.e.j.w.WebAppContext@6f01ba6f{/,file:/home/user/jetty-distribution-{VERSION}/webapps/ROOT/,AVAILABLE}{/ROOT} - STARTED
 |   |   |   += org.eclipse.jetty.server.session.SessionHandler@5a770658 - STARTED
 |   |   |   |   += org.eclipse.jetty.server.session.HashSessionManager@746a95ae - STARTED
 |   |   |   |   += org.eclipse.jetty.security.ConstraintSecurityHandler@1890e38 - STARTED
 |   |   |   |   |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@6242c657
 |   |   |   |   |   += org.eclipse.jetty.servlet.ServletHandler@debac27 - STARTED
 |   |   |   |   |   |   += default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true - STARTED
 |   |   |   |   |   |   |   +- maxCacheSize=256000000
 |   |   |   |   |   |   |   +- etags=true
 |   |   |   |   |   |   |   +- dirAllowed=true
 |   |   |   |   |   |   |   +- gzip=true
 |   |   |   |   |   |   |   +- maxCachedFileSize=200000000
 |   |   |   |   |   |   |   +- redirectWelcome=false
 |   |   |   |   |   |   |   +- acceptRanges=true
 |   |   |   |   |   |   |   +- welcomeServlets=false
 |   |   |   |   |   |   |   +- aliases=false
 |   |   |   |   |   |   |   +- useFileMappedBuffer=true
 |   |   |   |   |   |   |   +- maxCachedFiles=2048
 |   |   |   |   |   |   +- [/]=>default
 |   |   |   |   |   |   += jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true - STARTED
 |   |   |   |   |   |   |   +- logVerbosityLevel=DEBUG
 |   |   |   |   |   |   |   +- fork=false
 |   |   |   |   |   |   |   +- com.sun.appserv.jsp.classpath=/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar:/home/user/jetty-distribution-{VERSION}/resources:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/start.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/opt/local/lib/libsvnjavahl-1.0.dylib:/System/Library/Java/Extensions/AppleScriptEngine.jar:/System/Library/Java/Extensions/dns_sd.jar:/System/Library/Java/Extensions/j3daudio.jar:/System/Library/Java/Extensions/j3dcore.jar:/System/Library/Java/Extensions/j3dutils.jar:/System/Library/Java/Extensions/jai_codec.jar:/System/Library/Java/Extensions/jai_core.jar:/System/Library/Java/Extensions/libAppleScriptEngine.jnilib:/System/Library/Java/Extensions/libJ3D.jnilib:/System/Library/Java/Extensions/libJ3DAudio.jnilib:/System/Library/Java/Extensions/libJ3DUtils.jnilib:/System/Library/Java/Extensions/libmlib_jai.jnilib:/System/Library/Java/Extensions/libQTJNative.jnilib:/System/Library/Java/Extensions/mlibwrapper_jai.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/System/Library/Java/Extensions/QTJava.zip:/System/Library/Java/Extensions/vecmath.jar:/usr/lib/java/libjdns_sd.jnilib
 |   |   |   |   |   |   |   +- scratchdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-ROOT-_-any-/jsp
 |   |   |   |   |   |   |   +- xpoweredBy=false
 |   |   |   |   |   |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
 |   |   |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |   |   +~ HashLoginService[Test Realm] - STARTED
 |   |   |   |   |   +- org.eclipse.jetty.security.DefaultIdentityService@d2539a6
 |   |   |   |   |   +- org.eclipse.jetty.security.authentication.BasicAuthenticator@6b733b94
 |   |   |   |   |   |
 |   |   |   |   |   +> HashLoginService[Test Realm] - STARTED
 |   |   |   |   |   +> org.eclipse.jetty.security.DefaultIdentityService@d2539a6
 |   |   |   |   |   +> org.eclipse.jetty.security.authentication.BasicAuthenticator@6b733b94
 |   |   |   |   |   +> []
 |   |   |   |   |   +> /={TRACE={RoleInfo,F,C[]}}
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   += org.eclipse.jetty.servlet.ErrorPageErrorHandler@3c41a9ce - STARTED
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |
 |   |   |   +> WebAppClassLoader=ROOT@7af33249
 |   |   |   |   +- startJarLoader@7194b34a
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/resources/
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar
 |   |   |   |       +- sun.misc.Launcher$AppClassLoader@19d1b44b
 |   |   |   |           +- file:/home/user/jetty-distribution-{VERSION}/start.jar
 |   |   |   |           +- sun.misc.Launcher$ExtClassLoader@1693b52b
 |   |   |   +> javax.servlet.context.tempdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-ROOT-_-any-
 |   |   |   +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/servlet-api-[^/]*\.jar$
 |   |   |   +> com.sun.jsp.taglibraryCache={}
 |   |   |   +> com.sun.jsp.tagFileJarUrlsCache={}
 |   |   += o.e.j.s.h.ContextHandler@7b2dffdf{/javadoc,file:/home/user/jetty-distribution-{VERSION}/javadoc,AVAILABLE} - STARTED
 |   |   |   += org.eclipse.jetty.server.handler.ResourceHandler@8f9c8a7 - STARTED
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |
 |   |   |   +> No ClassLoader
 |   |   |   +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/servlet-api-[^/]*\.jar$
 |   |   += o.e.j.w.WebAppContext@716d9094{/test,file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/,AVAILABLE}{/test.war} - STARTED
 |   |   |   += org.eclipse.jetty.server.session.SessionHandler@336abd81 - STARTED
 |   |   |   |   += org.eclipse.jetty.server.session.HashSessionManager@1246f8d0 - STARTED
 |   |   |   |   += org.eclipse.jetty.security.ConstraintSecurityHandler@7179290f - STARTED
 |   |   |   |   |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@17d41d12
 |   |   |   |   |   += org.eclipse.jetty.servlet.ServletHandler@5034037e - STARTED
 |   |   |   |   |   |   += default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true - STARTED
 |   |   |   |   |   |   |   +- maxCacheSize=256000000
 |   |   |   |   |   |   |   +- etags=true
 |   |   |   |   |   |   |   +- dirAllowed=true
 |   |   |   |   |   |   |   +- gzip=true
 |   |   |   |   |   |   |   +- maxCachedFileSize=200000000
 |   |   |   |   |   |   |   +- redirectWelcome=false
 |   |   |   |   |   |   |   +- acceptRanges=true
 |   |   |   |   |   |   |   +- welcomeServlets=false
 |   |   |   |   |   |   |   +- aliases=false
 |   |   |   |   |   |   |   +- useFileMappedBuffer=true
 |   |   |   |   |   |   |   +- maxCachedFiles=2048
 |   |   |   |   |   |   +- [/]=>default
 |   |   |   |   |   |   += jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true - STARTED
 |   |   |   |   |   |   |   +- logVerbosityLevel=DEBUG
 |   |   |   |   |   |   |   +- fork=false
 |   |   |   |   |   |   |   +- com.sun.appserv.jsp.classpath=/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar:/home/user/jetty-distribution-{VERSION}/resources:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/start.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/opt/local/lib/libsvnjavahl-1.0.dylib:/System/Library/Java/Extensions/AppleScriptEngine.jar:/System/Library/Java/Extensions/dns_sd.jar:/System/Library/Java/Extensions/j3daudio.jar:/System/Library/Java/Extensions/j3dcore.jar:/System/Library/Java/Extensions/j3dutils.jar:/System/Library/Java/Extensions/jai_codec.jar:/System/Library/Java/Extensions/jai_core.jar:/System/Library/Java/Extensions/libAppleScriptEngine.jnilib:/System/Library/Java/Extensions/libJ3D.jnilib:/System/Library/Java/Extensions/libJ3DAudio.jnilib:/System/Library/Java/Extensions/libJ3DUtils.jnilib:/System/Library/Java/Extensions/libmlib_jai.jnilib:/System/Library/Java/Extensions/libQTJNative.jnilib:/System/Library/Java/Extensions/mlibwrapper_jai.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/System/Library/Java/Extensions/QTJava.zip:/System/Library/Java/Extensions/vecmath.jar:/usr/lib/java/libjdns_sd.jnilib
 |   |   |   |   |   |   |   +- scratchdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/jsp
 |   |   |   |   |   |   |   +- xpoweredBy=false
 |   |   |   |   |   |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
 |   |   |   |   |   |   += QoSFilter - STARTED
 |   |   |   |   |   |   |   +- managedAttr=true
 |   |   |   |   |   |   |   +- maxRequests=10000
 |   |   |   |   |   |   +- [/*]/[]==0=>QoSFilter
 |   |   |   |   |   |   += MultiPart - STARTED
 |   |   |   |   |   |   |   +- deleteFiles=true
 |   |   |   |   |   |   +- [/dump/*]/[]==0=>MultiPart
 |   |   |   |   |   |   += GzipFilter - STARTED
 |   |   |   |   |   |   |   +- bufferSize=8192
 |   |   |   |   |   |   |   +- excludedAgents=MSIE 6.0
 |   |   |   |   |   |   |   +- userAgent=(?:Mozilla[^\(]*\(compatible;\s*+([^;]*);.*)|(?:.*?([^\s]+/[^\s]+).*)
 |   |   |   |   |   |   |   +- mimeTypes=text/plain,application/xml
 |   |   |   |   |   |   |   +- uncheckedPrintWriter=true
 |   |   |   |   |   |   |   +- cacheSize=1024
 |   |   |   |   |   |   |   +- minGzipSize=2048
 |   |   |   |   |   |   +- [/dump/gzip/*, *.txt]/[]==0=>GzipFilter
 |   |   |   |   |   |   += Login@462ff49==com.acme.LoginServlet,1,true - STARTED
 |   |   |   |   |   |   +- [/login/*]=>Login
 |   |   |   |   |   |   += Hello@42628b2==com.acme.HelloWorld,1,true - STARTED
 |   |   |   |   |   |   +- [/hello/*]=>Hello
 |   |   |   |   |   |   += Dump@20ae14==com.acme.Dump,1,true - STARTED
 |   |   |   |   |   |   |   +- servlet-override-example=a servlet value
 |   |   |   |   |   |   +- [/dump/*, *.dump]=>Dump
 |   |   |   |   |   |   += Session@d9891a76==com.acme.SessionDump,5,true - STARTED
 |   |   |   |   |   |   +- [/session/*]=>Session
 |   |   |   |   |   |   += Cookie@78a4f684==com.acme.CookieDump,1,true - STARTED
 |   |   |   |   |   |   +- [/cookie/*]=>Cookie
 |   |   |   |   |   |   += Dispatch@14d3a89a==com.acme.DispatchServlet,1,true - STARTED
 |   |   |   |   |   |   +- [/dispatch/*]=>Dispatch
 |   |   |   |   |   |   += CGI@10465==org.eclipse.jetty.servlets.CGI,1,true - STARTED
 |   |   |   |   |   |   +- [/cgi-bin/*]=>CGI
 |   |   |   |   |   |   += Chat@200778==com.acme.ChatServlet,1,true - STARTED
 |   |   |   |   |   |   +- [/chat/*]=>Chat
 |   |   |   |   |   |   += WSChat@99274454==com.acme.WebSocketChatServlet,1,true - STARTED
 |   |   |   |   |   |   +- [/ws/*]=>WSChat
 |   |   |   |   |   |   += Rewrite@a4dac96c==com.acme.RewriteServlet,-1,false - STARTED
 |   |   |   |   |   |   +- [/rewritten/*, /redirected/*]=>Rewrite
 |   |   |   |   |   |   += SecureMode@d45951da==com.acme.SecureModeServlet,1,true - STARTED
 |   |   |   |   |   |   +- [/secureMode/*]=>SecureMode
 |   |   |   |   |   |   += foo.jsp@d7583f1f==org.apache.jasper.servlet.JspServlet,-1,false - STARTED
 |   |   |   |   |   |   +- [/jsp/foo/]=>foo.jsp
 |   |   |   |   |   |   +- [*.more]=>Dump
 |   |   |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |   |   |   += RegoTest@dafcd1ad==com.acme.RegTest,-1,false - STARTED
 |   |   |   |   |   |   +- [/rego/*]=>RegoTest
 |   |   |   |   |   |   += RegoTest2@849d6425==com.acme.RegTest,-1,false - STARTED
 |   |   |   |   |   |   +- [/rego2/*]=>RegoTest2
 |   |   |   |   |   |   += TestFilter - STARTED
 |   |   |   |   |   |   |   +- remote=false
 |   |   |   |   |   |   +- [/*]/[]==31=>TestFilter
 |   |   |   |   |   += HashLoginService[Test Realm] - STARTED
 |   |   |   |   |   +- org.eclipse.jetty.security.authentication.FormAuthenticator@1fa291f2
 |   |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   |   |   +- org.eclipse.jetty.security.DefaultIdentityService@41917d6d
 |   |   |   |   |   |
 |   |   |   |   |   +> HashLoginService[Test Realm] - STARTED
 |   |   |   |   |   +> org.eclipse.jetty.security.DefaultIdentityService@41917d6d
 |   |   |   |   |   +> org.eclipse.jetty.security.authentication.FormAuthenticator@1fa291f2
 |   |   |   |   |   +> [server-administrator, *, admin, user]
 |   |   |   |   |   +> /rego2/*={*={RoleInfo,C[server-administrator]}}
 |   |   |   |   |   +> *.htm={*={RoleInfo,C[server-administrator, *, admin, user]}}
 |   |   |   |   |   +> /dump/auth/ssl/*={*={RoleInfo[]}}
 |   |   |   |   |   +> /dump/auth/noaccess/*={*={RoleInfo,F,C[]}}
 |   |   |   |   |   +> /auth/*={*={RoleInfo,F,C[]}}
 |   |   |   |   |   +> /dump/auth/admin/*={*={RoleInfo,C[admin]}}
 |   |   |   |   |   +> /dump/auth/relax/*={GET={RoleInfo[]}, HEAD={RoleInfo[]}}
 |   |   |   |   |   +> /rego/*={*={RoleInfo,C[admin]}}
 |   |   |   |   |   +> /dump/auth/*={*={RoleInfo,C[server-administrator, *, admin, user]}}
 |   |   |   |   |   +> /={TRACE={RoleInfo,F,C[]}}
 |   |   |   |   |   +> /auth/relax.txt={GET={RoleInfo[]}, HEAD={RoleInfo[]}}
 |   |   |   |   |   +> /auth2/*={*={RoleInfo,C[server-administrator, *, admin, user]}}
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   += org.eclipse.jetty.servlet.ErrorPageErrorHandler@24bf7a86 - STARTED
 |   |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |   |   +- org.eclipse.jetty.servlets.QoSFilter@6df3d1f5
 |   |   |   |
 |   |   |   +> WebAppClassLoader=Test WebApp@3e2f3adb
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/classes/
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-continuation-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-servlets-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/websocket-api-9.0.2.v20130417.jar
 |   |   |   |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/websocket-servlet-9.0.2.v20130417.jar
 |   |   |   |   +- startJarLoader@7194b34a
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/resources/
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar
 |   |   |   |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar
 |   |   |   |       +- sun.misc.Launcher$AppClassLoader@19d1b44b
 |   |   |   |           +- file:/home/user/jetty-distribution-{VERSION}/start.jar
 |   |   |   |           +- sun.misc.Launcher$ExtClassLoader@1693b52b
 |   |   |   +> org.eclipse.jetty.server.context.ManagedAttributes=QoSFilter,TransparentProxy.ThreadPool,TransparentProxy.HttpClient
 |   |   |   +> context-override-example=a context value
 |   |   |   +> javax.servlet.context.tempdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-
 |   |   |   +> org.apache.catalina.jsp_classpath=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/classes:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-continuation-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-servlets-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/websocket-api-9.0.2.v20130417.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/WEB-INF/lib/websocket-servlet-9.0.2.v20130417.jar
 |   |   |   +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/servlet-api-[^/]*\.jar$
 |   |   |   +> QoSFilter=org.eclipse.jetty.servlets.QoSFilter@6df3d1f5
 |   |   |   +> com.sun.jsp.taglibraryCache={}
 |   |   |   +> com.sun.jsp.tagFileJarUrlsCache={}
 |   |   += o.e.j.w.WebAppContext@4ac92718{/proxy,file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/,AVAILABLE}{/xref-proxy.war} - STARTED
 |   |       += org.eclipse.jetty.server.session.SessionHandler@5c25bf03 - STARTED
 |   |       |   += org.eclipse.jetty.server.session.HashSessionManager@33053093 - STARTED
 |   |       |   += org.eclipse.jetty.security.ConstraintSecurityHandler@3bab0b5a - STARTED
 |   |       |   |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@11ad5296
 |   |       |   |   += org.eclipse.jetty.servlet.ServletHandler@a08feeb - STARTED
 |   |       |   |   |   += default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true - STARTED
 |   |       |   |   |   |   +- maxCacheSize=256000000
 |   |       |   |   |   |   +- etags=true
 |   |       |   |   |   |   +- dirAllowed=true
 |   |       |   |   |   |   +- gzip=true
 |   |       |   |   |   |   +- maxCachedFileSize=200000000
 |   |       |   |   |   |   +- redirectWelcome=false
 |   |       |   |   |   |   +- acceptRanges=true
 |   |       |   |   |   |   +- welcomeServlets=false
 |   |       |   |   |   |   +- aliases=false
 |   |       |   |   |   |   +- useFileMappedBuffer=true
 |   |       |   |   |   |   +- maxCachedFiles=2048
 |   |       |   |   |   +- [/]=>default
 |   |       |   |   |   += jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true - STARTED
 |   |       |   |   |   |   +- logVerbosityLevel=DEBUG
 |   |       |   |   |   |   +- fork=false
 |   |       |   |   |   |   +- com.sun.appserv.jsp.classpath=/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar:/home/user/jetty-distribution-{VERSION}/resources:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar:/home/user/jetty-distribution-{VERSION}/start.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/opt/local/lib/libsvnjavahl-1.0.dylib:/System/Library/Java/Extensions/AppleScriptEngine.jar:/System/Library/Java/Extensions/dns_sd.jar:/System/Library/Java/Extensions/j3daudio.jar:/System/Library/Java/Extensions/j3dcore.jar:/System/Library/Java/Extensions/j3dutils.jar:/System/Library/Java/Extensions/jai_codec.jar:/System/Library/Java/Extensions/jai_core.jar:/System/Library/Java/Extensions/libAppleScriptEngine.jnilib:/System/Library/Java/Extensions/libJ3D.jnilib:/System/Library/Java/Extensions/libJ3DAudio.jnilib:/System/Library/Java/Extensions/libJ3DUtils.jnilib:/System/Library/Java/Extensions/libmlib_jai.jnilib:/System/Library/Java/Extensions/libQTJNative.jnilib:/System/Library/Java/Extensions/mlibwrapper_jai.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/System/Library/Java/Extensions/QTJava.zip:/System/Library/Java/Extensions/vecmath.jar:/usr/lib/java/libjdns_sd.jnilib
 |   |       |   |   |   |   +- scratchdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/jsp
 |   |       |   |   |   |   +- xpoweredBy=false
 |   |       |   |   |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
 |   |       |   |   |   += XrefTransparentProxy@b0222797==org.eclipse.jetty.proxy.ProxyServlet$Transparent,1,true - STARTED
 |   |       |   |   |   |   +- proxyTo=http://download.eclipse.org/jetty/stable-9
 |   |       |   |   |   |   +- hostHeader=download.eclipse.org
 |   |       |   |   |   +- [/xref/*]=>XrefTransparentProxy
 |   |       |   |   |   += JavadocTransparentProxy@8ab9c012==org.eclipse.jetty.proxy.ProxyServlet$Transparent,1,true - STARTED
 |   |       |   |   |   |   +- proxyTo=http://download.eclipse.org/jetty/stable-9
 |   |       |   |   |   |   +- hostHeader=download.eclipse.org
 |   |       |   |   |   +- [/apidocs/*]=>JavadocTransparentProxy
 |   |       |   |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |       |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |       |   |   +~ HashLoginService[Test Realm] - STARTED
 |   |       |   |   +- org.eclipse.jetty.security.DefaultIdentityService@d2539a6
 |   |       |   |   +- org.eclipse.jetty.security.authentication.BasicAuthenticator@5497fb72
 |   |       |   |   |
 |   |       |   |   +> HashLoginService[Test Realm] - STARTED
 |   |       |   |   +> org.eclipse.jetty.security.DefaultIdentityService@d2539a6
 |   |       |   |   +> org.eclipse.jetty.security.authentication.BasicAuthenticator@5497fb72
 |   |       |   |   +> []
 |   |       |   |   +> /={TRACE={RoleInfo,F,C[]}}
 |   |       |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |       += org.eclipse.jetty.servlet.ErrorPageErrorHandler@321f8d38 - STARTED
 |   |       |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |       +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   |       |
 |   |       +> WebAppClassLoader=Transparent Proxy WebApp@3570713d
 |   |       |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/classes/
 |   |       |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar
 |   |       |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar
 |   |       |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar
 |   |       |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-proxy-{VERSION}.jar
 |   |       |   +- file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar
 |   |       |   +- startJarLoader@7194b34a
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/resources/
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar
 |   |       |       +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar
 |   |       |       +- sun.misc.Launcher$AppClassLoader@19d1b44b
 |   |       |           +- file:/home/user/jetty-distribution-{VERSION}/start.jar
 |   |       |           +- sun.misc.Launcher$ExtClassLoader@1693b52b
 |   |       +> javax.servlet.context.tempdir=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-
 |   |       +> org.apache.catalina.jsp_classpath=/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/classes:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-client-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-http-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-io-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-proxy-{VERSION}.jar:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/WEB-INF/lib/jetty-util-{VERSION}.jar
 |   |       +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/servlet-api-[^/]*\.jar$
 |   |       +> JavadocTransparentProxy.HttpClient=org.eclipse.jetty.client.HttpClient@580f016d
 |   |       +> XrefTransparentProxy.HttpClient=org.eclipse.jetty.client.HttpClient@70c7e52b
 |   |       +> com.sun.jsp.taglibraryCache={}
 |   |       +> com.sun.jsp.tagFileJarUrlsCache={}
 |   += org.eclipse.jetty.server.handler.DefaultHandler@4de4926a - STARTED
 |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   += org.eclipse.jetty.server.handler.RequestLogHandler@3dc087a2 - STARTED
 |   |   += org.eclipse.jetty.server.AsyncNCSARequestLog@108a1cf6 - STARTED
 |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 +- org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   +- [/rego/*]=>RegoTest=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=RegoTest,id=0
 |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@17d41d12=org.eclipse.jetty.security:context=test,type=defaultauthenticatorfactory,id=0
 |   +- org.eclipse.jetty.server.session.HashSessionManager@1246f8d0=org.eclipse.jetty.server.session:context=test,type=hashsessionmanager,id=0
 |   +- org.eclipse.jetty.security.ConstraintSecurityHandler@1890e38=org.eclipse.jetty.security:context=ROOT,type=constraintsecurityhandler,id=0
 |   +- WSChat@99274454==com.acme.WebSocketChatServlet,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=WSChat,id=0
 |   +- org.eclipse.jetty.deploy.DeploymentManager@c8e4be2=org.eclipse.jetty.deploy:type=deploymentmanager,id=0
 |   +- org.eclipse.jetty.jmx.MBeanContainer@644a5ddd=org.eclipse.jetty.jmx:type=mbeancontainer,id=0
 |   +- [/dump/gzip/*, *.txt]/[]==0=>GzipFilter=org.eclipse.jetty.servlet:context=test,type=filtermapping,name=GzipFilter,id=0
 |   +- Hello@42628b2==com.acme.HelloWorld,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Hello,id=0
 |   +- [/]=>default=org.eclipse.jetty.servlet:context=xref-proxy,type=servletmapping,name=default,id=0
 |   +- [/login/*]=>Login=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Login,id=0
 |   +- org.eclipse.jetty.server.handler.DefaultHandler@4de4926a=org.eclipse.jetty.server.handler:type=defaulthandler,id=0
 |   +- org.eclipse.jetty.server.session.SessionHandler@5c25bf03=org.eclipse.jetty.server.session:context=xref-proxy,type=sessionhandler,id=0
 |   +- [/ws/*]=>WSChat=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=WSChat,id=0
 |   +- o.e.j.w.WebAppContext@6f01ba6f{/,file:/home/user/jetty-distribution-{VERSION}/webapps/ROOT/,AVAILABLE}{/ROOT}=org.eclipse.jetty.webapp:context=ROOT,type=webappcontext,id=0
 |   +- o.e.j.w.WebAppContext@7ea88b1c{/async-rest,[file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/, jar:file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/example-async-rest-jar-9.0.2.v20130417.jar!/META-INF/resources/],AVAILABLE}{/async-rest.war}=org.eclipse.jetty.webapp:context=async-rest,type=webappcontext,id=0
 |   +- ServerConnector@3d0f282{HTTP/1.1}{0.0.0.0:9090}=org.eclipse.jetty.server:context=HTTP/1.1@3d0f282,type=serverconnector,id=0
 |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@6242c657=org.eclipse.jetty.security:context=ROOT,type=defaultauthenticatorfactory,id=0
 |   +- JavadocTransparentProxy@8ab9c012==org.eclipse.jetty.proxy.ProxyServlet$Transparent,1,true=org.eclipse.jetty.servlet:context=xref-proxy,type=servletholder,name=JavadocTransparentProxy,id=0
 |   +- [/dump/*, *.dump]=>Dump=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Dump,id=0
 |   +- [/jsp/foo/]=>foo.jsp=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=foo.jsp,id=0
 |   +- org.eclipse.jetty.servlet.ServletHandler@46bac287=org.eclipse.jetty.servlet:context=async-rest,type=servlethandler,id=0
 |   +- GzipFilter=org.eclipse.jetty.servlet:context=test,type=filterholder,name=GzipFilter,id=0
 |   +- o.e.j.w.WebAppContext@4ac92718{/proxy,file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/,AVAILABLE}{/xref-proxy.war}=org.eclipse.jetty.webapp:context=xref-proxy,type=webappcontext,id=0
 |   +- qtp1062680061{STARTED,10<=13<=200,i=1,q=0}=org.eclipse.jetty.util.thread:type=queuedthreadpool,id=0
 |   +- org.eclipse.jetty.server.session.HashSessionManager@33053093=org.eclipse.jetty.server.session:context=xref-proxy,type=hashsessionmanager,id=0
 |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@52b12fef=org.eclipse.jetty.security:context=async-rest,type=defaultauthenticatorfactory,id=0
 |   +- Login@462ff49==com.acme.LoginServlet,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Login,id=0
 |   +- org.eclipse.jetty.security.authentication.BasicAuthenticator@7b239469=org.eclipse.jetty.security.authentication:context=async-rest,type=basicauthenticator,id=0
 |   +- MultiPart=org.eclipse.jetty.servlet:context=test,type=filterholder,name=MultiPart,id=0
 |   +- default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true=org.eclipse.jetty.servlet:context=xref-proxy,type=servletholder,name=default,id=0
 |   +- default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true=org.eclipse.jetty.servlet:context=ROOT,type=servletholder,name=default,id=0
 |   +- default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true=org.eclipse.jetty.servlet:context=async-rest,type=servletholder,name=default,id=0
 |   +- default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=default,id=0
 |   +- org.eclipse.jetty.server.session.HashSessionManager@746a95ae=org.eclipse.jetty.server.session:context=ROOT,type=hashsessionmanager,id=0
 |   +- RegoTest2@849d6425==com.acme.RegTest,-1,false=org.eclipse.jetty.servlet:context=test,type=servletholder,name=RegoTest2,id=0
 |   +- org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@6f0ac4be=org.eclipse.jetty.server:context=HTTP/1.1@3d0f282,type=serverconnector$serverconnectormanager,id=0
 |   +- [/]=>default=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=default,id=0
 |   +- SecureMode@d45951da==com.acme.SecureModeServlet,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=SecureMode,id=0
 |   +- org.eclipse.jetty.security.authentication.BasicAuthenticator@6b733b94=org.eclipse.jetty.security.authentication:context=ROOT,type=basicauthenticator,id=0
 |   +- org.eclipse.jetty.server.session.SessionHandler@6dfb8d2e=org.eclipse.jetty.server.session:context=async-rest,type=sessionhandler,id=0
 |   +- org.eclipse.jetty.security.DefaultIdentityService@41917d6d=org.eclipse.jetty.security:context=test,type=defaultidentityservice,id=0
 |   +- jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true=org.eclipse.jetty.servlet:context=xref-proxy,type=servletholder,name=jsp,id=0
 |   +- jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true=org.eclipse.jetty.servlet:context=ROOT,type=servletholder,name=jsp,id=0
 |   +- jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true=org.eclipse.jetty.servlet:context=async-rest,type=servletholder,name=jsp,id=0
 |   +- jsp@19c47==org.apache.jasper.servlet.JspServlet,0,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=jsp,id=0
 |   +- [/*]/[]==31=>TestFilter=org.eclipse.jetty.servlet:context=test,type=filtermapping,name=TestFilter,id=0
 |   +- org.eclipse.jetty.server.session.HashSessionManager@6cb83869=org.eclipse.jetty.server.session:context=async-rest,type=hashsessionmanager,id=0
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@30ad8942=org.eclipse.jetty.io:context=HTTP/1.1@3d0f282,type=arraybytebufferpool,id=0
 |   +- [/cgi-bin/*]=>CGI=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=CGI,id=0
 |   +- org.eclipse.jetty.server.handler.HandlerCollection@58b37561=org.eclipse.jetty.server.handler:type=handlercollection,id=0
 |   +- Session@d9891a76==com.acme.SessionDump,5,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Session,id=0
 |   +- org.eclipse.jetty.servlet.ServletHandler@a08feeb=org.eclipse.jetty.servlet:context=xref-proxy,type=servlethandler,id=0
 |   +- org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@725f5=org.eclipse.jetty.util.thread:type=scheduledexecutorscheduler,id=0
 |   +- [/*]/[]==0=>QoSFilter=org.eclipse.jetty.servlet:context=test,type=filtermapping,name=QoSFilter,id=0
 |   +- org.eclipse.jetty.server.session.SessionHandler@5a770658=org.eclipse.jetty.server.session:context=ROOT,type=sessionhandler,id=0
 |   +- org.eclipse.jetty.server.session.SessionHandler@336abd81=org.eclipse.jetty.server.session:context=test,type=sessionhandler,id=0
 |   +- o.e.j.s.h.ContextHandler@7b2dffdf{/javadoc,file:/home/user/jetty-distribution-{VERSION}/javadoc,AVAILABLE}=org.eclipse.jetty.server.handler:context=javadoc,type=contexthandler,id=0
 |   +- org.eclipse.jetty.servlets.QoSFilter@6df3d1f5=org.eclipse.jetty.servlets:context=test,type=qosfilter,id=0
 |   +- [*.more]=>Dump=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Dump,id=1
 |   +- Dump@20ae14==com.acme.Dump,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Dump,id=0
 |   +- HttpConnectionFactory@5e47b1b9{HTTP/1.1}=org.eclipse.jetty.server:context=HTTP/1.1@3d0f282,type=httpconnectionfactory,id=0
 |   +- org.eclipse.jetty.servlet.ServletHandler@debac27=org.eclipse.jetty.servlet:context=ROOT,type=servlethandler,id=0
 |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp=org.eclipse.jetty.servlet:context=xref-proxy,type=servletmapping,name=jsp,id=0
 |   +- org.eclipse.jetty.server.handler.MovedContextHandler$Redirector@2a4200d3=org.eclipse.jetty.server.handler:context=oldContextPath,type=movedcontexthandler$redirector,id=0
 |   +- TestFilter=org.eclipse.jetty.servlet:context=test,type=filterholder,name=TestFilter,id=0
 |   +- Rewrite@a4dac96c==com.acme.RewriteServlet,-1,false=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Rewrite,id=0
 |   +- [/dispatch/*]=>Dispatch=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Dispatch,id=0
 |   +- [/testSerial]=>SerialRestServlet=org.eclipse.jetty.servlet:context=async-rest,type=servletmapping,name=SerialRestServlet,id=0
 |   +- org.eclipse.jetty.servlet.ErrorPageErrorHandler@24bf7a86=org.eclipse.jetty.servlet:context=test,type=errorpageerrorhandler,id=0
 |   +- [/secureMode/*]=>SecureMode=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=SecureMode,id=0
 |   +- [/]=>default=org.eclipse.jetty.servlet:context=async-rest,type=servletmapping,name=default,id=0
 |   +- Dispatch@14d3a89a==com.acme.DispatchServlet,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Dispatch,id=0
 |   +- org.eclipse.jetty.server.handler.ContextHandlerCollection@64c6e290=org.eclipse.jetty.server.handler:type=contexthandlercollection,id=0
 |   +- org.eclipse.jetty.security.ConstraintSecurityHandler@2848c90e=org.eclipse.jetty.security:context=async-rest,type=constraintsecurityhandler,id=0
 |   +- [/rego2/*]=>RegoTest2=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=RegoTest2,id=0
 |   +- [/rewritten/*, /redirected/*]=>Rewrite=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Rewrite,id=0
 |   +- org.eclipse.jetty.servlet.ServletHandler@5034037e=org.eclipse.jetty.servlet:context=test,type=servlethandler,id=0
 |   +- org.eclipse.jetty.servlet.ErrorPageErrorHandler@3c121009=org.eclipse.jetty.servlet:context=async-rest,type=errorpageerrorhandler,id=0
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:9090]=sun.nio.ch:context=HTTP/1.1@3d0f282,type=serversocketchannelimpl,id=0
 |   +- org.eclipse.jetty.security.ConstraintSecurityHandler@7179290f=org.eclipse.jetty.security:context=test,type=constraintsecurityhandler,id=0
 |   +- org.eclipse.jetty.server.session.HashSessionIdManager@289eb857=org.eclipse.jetty.server.session:type=hashsessionidmanager,id=0
 |   +- org.eclipse.jetty.security.authentication.BasicAuthenticator@5497fb72=org.eclipse.jetty.security.authentication:context=xref-proxy,type=basicauthenticator,id=0
 |   +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@11ad5296=org.eclipse.jetty.security:context=xref-proxy,type=defaultauthenticatorfactory,id=0
 |   +- [/dump/*]/[]==0=>MultiPart=org.eclipse.jetty.servlet:context=test,type=filtermapping,name=MultiPart,id=0
 |   +- o.e.j.s.h.MovedContextHandler@5e0c8d24{/oldContextPath,null,AVAILABLE}=org.eclipse.jetty.server.handler:context=oldContextPath,type=movedcontexthandler,id=0
 |   +- QoSFilter=org.eclipse.jetty.servlet:context=test,type=filterholder,name=QoSFilter,id=0
 |   +- org.eclipse.jetty.security.authentication.FormAuthenticator@1fa291f2=org.eclipse.jetty.security.authentication:context=test,type=formauthenticator,id=0
 |   +- o.e.j.w.WebAppContext@716d9094{/test,file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/,AVAILABLE}{/test.war}=org.eclipse.jetty.webapp:context=test,type=webappcontext,id=0
 |   +- [/]=>default=org.eclipse.jetty.servlet:context=ROOT,type=servletmapping,name=default,id=0
 |   +- [/hello/*]=>Hello=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Hello,id=0
 |   +- [/chat/*]=>Chat=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Chat,id=0
 |   +- [/testAsync]=>AsyncRestServlet=org.eclipse.jetty.servlet:context=async-rest,type=servletmapping,name=AsyncRestServlet,id=0
 |   +- org.eclipse.jetty.security.DefaultIdentityService@d2539a6=org.eclipse.jetty.security:context=async-rest,type=defaultidentityservice,id=0
 |   +- org.eclipse.jetty.server.handler.RequestLogHandler@3dc087a2=org.eclipse.jetty.server.handler:type=requestloghandler,id=0
 |   +- org.eclipse.jetty.servlet.ErrorPageErrorHandler@321f8d38=org.eclipse.jetty.servlet:context=xref-proxy,type=errorpageerrorhandler,id=0
 |   +- org.eclipse.jetty.server.handler.ResourceHandler@8f9c8a7=org.eclipse.jetty.server.handler:context=javadoc,type=resourcehandler,id=0
 |   +- CGI@10465==org.eclipse.jetty.servlets.CGI,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=CGI,id=0
 |   +- SerialRestServlet@461411d==org.eclipse.jetty.example.asyncrest.SerialRestServlet,-1,false=org.eclipse.jetty.servlet:context=async-rest,type=servletholder,name=SerialRestServlet,id=0
 |   +- HashLoginService[Test Realm]=org.eclipse.jetty.security:type=hashloginservice,id=0
 |   +- AsyncRestServlet@73eb9bd5==org.eclipse.jetty.example.asyncrest.AsyncRestServlet,-1,false=org.eclipse.jetty.servlet:context=async-rest,type=servletholder,name=AsyncRestServlet,id=0
 |   +- org.eclipse.jetty.server.Server@76f08fe1=org.eclipse.jetty.server:type=server,id=0
 |   +- org.eclipse.jetty.servlet.ErrorPageErrorHandler@3c41a9ce=org.eclipse.jetty.servlet:context=ROOT,type=errorpageerrorhandler,id=0
 |   +- [/apidocs/*]=>JavadocTransparentProxy=org.eclipse.jetty.servlet:context=xref-proxy,type=servletmapping,name=JavadocTransparentProxy,id=0
 |   +- Chat@200778==com.acme.ChatServlet,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Chat,id=0
 |   +- [/cookie/*]=>Cookie=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Cookie,id=0
 |   +- [/session/*]=>Session=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=Session,id=0
 |   +- org.eclipse.jetty.deploy.providers.WebAppProvider@7b26b7df=org.eclipse.jetty.deploy.providers:type=webappprovider,id=0
 |   +- org.eclipse.jetty.server.AsyncNCSARequestLog@108a1cf6=org.eclipse.jetty.server:type=asyncncsarequestlog,id=0
 |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp=org.eclipse.jetty.servlet:context=test,type=servletmapping,name=jsp,id=0
 |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp=org.eclipse.jetty.servlet:context=ROOT,type=servletmapping,name=jsp,id=0
 |   +- HashLoginService[Test Realm]=org.eclipse.jetty.security:context=test,type=hashloginservice,id=0
 |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp=org.eclipse.jetty.servlet:context=async-rest,type=servletmapping,name=jsp,id=0
 |   +- foo.jsp@d7583f1f==org.apache.jasper.servlet.JspServlet,-1,false=org.eclipse.jetty.servlet:context=test,type=servletholder,name=foo.jsp,id=0
 |   +- RegoTest@dafcd1ad==com.acme.RegTest,-1,false=org.eclipse.jetty.servlet:context=test,type=servletholder,name=RegoTest,id=0
 |   +- [/xref/*]=>XrefTransparentProxy=org.eclipse.jetty.servlet:context=xref-proxy,type=servletmapping,name=XrefTransparentProxy,id=0
 |   +- org.eclipse.jetty.security.ConstraintSecurityHandler@3bab0b5a=org.eclipse.jetty.security:context=xref-proxy,type=constraintsecurityhandler,id=0
 |   +- HttpConfiguration@703b16bb{32768,8192/8192,https://:8443,[]}=org.eclipse.jetty.server:context=HTTP/1.1@3d0f282,type=httpconfiguration,id=0
 |   +- org.eclipse.jetty.util.log.Log@dda4f7b=org.eclipse.jetty.util.log:type=log,id=0
 |   +- Cookie@78a4f684==com.acme.CookieDump,1,true=org.eclipse.jetty.servlet:context=test,type=servletholder,name=Cookie,id=0
 |   +- XrefTransparentProxy@b0222797==org.eclipse.jetty.proxy.ProxyServlet$Transparent,1,true=org.eclipse.jetty.servlet:context=xref-proxy,type=servletholder,name=XrefTransparentProxy,id=0
 +- org.eclipse.jetty.util.log.Log@dda4f7b
 += ServerConnector@3d0f282{HTTP/1.1}{0.0.0.0:9090} - STARTED
 |   +~ org.eclipse.jetty.server.Server@76f08fe1 - STARTING
 |   +~ qtp1062680061{STARTED,10<=13<=200,i=1,q=0} - STARTED
 |   +~ org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@725f5 - STARTED
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@30ad8942
 |   += HttpConnectionFactory@5e47b1b9{HTTP/1.1} - STARTED
 |   |   +- HttpConfiguration@703b16bb{32768,8192/8192,https://:8443,[]}
 |   |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   += org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@6f0ac4be - STARTED
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@61454787 keys=0 selected=0 id=0
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@a0c508b keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@2e7bdad4 keys=0 selected=0 id=1
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@5825168 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@2eae85ab keys=0 selected=0 id=2
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@6faa85f6 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@244112c0 keys=0 selected=0 id=3
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@10c6f695 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@7666b8cd keys=0 selected=0 id=4
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@17836c59 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@353e531e keys=0 selected=0 id=5
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@2095f259 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@5459c1c5 keys=0 selected=0 id=6
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@142c7195 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@71d4f78b keys=0 selected=0 id=7
 |   |       +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:459)
 |   |       +- sun.nio.ch.KQueueSelectorImpl@16bdab45 keys=0
 |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:9090]
 += org.eclipse.jetty.deploy.DeploymentManager@c8e4be2 - STARTED
 |   +~ org.eclipse.jetty.deploy.providers.WebAppProvider@7b26b7df - STARTED
 |   +~ org.eclipse.jetty.jmx.MBeanContainer@644a5ddd
 +~ HashLoginService[Test Realm] - STARTED
 += org.eclipse.jetty.server.session.HashSessionIdManager@289eb857 - STARTED
 |
 +> startJarLoader@7194b34a
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-xml-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/servlet-api-3.0.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-http-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-continuation-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-server-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-security-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-servlet-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-webapp-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-deploy-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-client-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-jmx-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/com.sun.el-2.2.0.v201303151357.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.el-2.2.0.v201303151357.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/javax.servlet.jsp-2.2.0.v201112011158.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.jasper.glassfish-2.2.2.v201112011158.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jsp/org.eclipse.jdt.core-3.8.2.v20130121.jar
     +- file:/home/user/jetty-distribution-{VERSION}/resources/
     +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-api-9.0.2.v20130417.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-common-9.0.2.v20130417.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-server-9.0.2.v20130417.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/websocket/websocket-servlet-9.0.2.v20130417.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-util-{VERSION}.jar
     +- file:/home/user/jetty-distribution-{VERSION}/lib/jetty-io-{VERSION}.jar
     +- sun.misc.Launcher$AppClassLoader@19d1b44b
         +- file:/home/user/jetty-distribution-{VERSION}/start.jar
         +- sun.misc.Launcher$ExtClassLoader@1693b52b
2013-04-29 14:38:39.422:INFO:oejs.Server:Thread-2: Graceful shutdown org.eclipse.jetty.server.Server@76f08fe1 by  Mon Apr 29 14:38:44 CDT 2013
2013-04-29 14:38:39.429:INFO:oejs.ServerConnector:Thread-2: Stopped ServerConnector@3d0f282{HTTP/1.1}{0.0.0.0:9090}
2013-04-29 14:38:39.444:INFO:oejsl.ELContextCleaner:Thread-2: javax.el.BeanELResolver purged
2013-04-29 14:38:39.444:INFO:oejsh.ContextHandler:Thread-2: stopped o.e.j.w.WebAppContext@4ac92718{/proxy,file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-xref-proxy.war-_xref-proxy-any-/webapp/,UNAVAILABLE}{/xref-proxy.war}
2013-04-29 14:38:39.447:INFO:oejsl.ELContextCleaner:Thread-2: javax.el.BeanELResolver purged
2013-04-29 14:38:39.447:INFO:oejsh.ContextHandler:Thread-2: stopped o.e.j.w.WebAppContext@716d9094{/test,file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-test.war-_test-any-/webapp/,UNAVAILABLE}{/test.war}
2013-04-29 14:38:39.455:INFO:oejsh.ContextHandler:Thread-2: stopped o.e.j.s.h.ContextHandler@7b2dffdf{/javadoc,file:/home/user/jetty-distribution-{VERSION}/javadoc,UNAVAILABLE}
2013-04-29 14:38:39.456:INFO:oejsl.ELContextCleaner:Thread-2: javax.el.BeanELResolver purged
2013-04-29 14:38:39.456:INFO:oejsh.ContextHandler:Thread-2: stopped o.e.j.w.WebAppContext@6f01ba6f{/,file:/home/user/jetty-distribution-{VERSION}/webapps/ROOT/,UNAVAILABLE}{/ROOT}
2013-04-29 14:38:39.456:INFO:oejsh.ContextHandler:Thread-2: stopped o.e.j.s.h.MovedContextHandler@5e0c8d24{/oldContextPath,null,UNAVAILABLE}
2013-04-29 14:38:39.457:INFO:oejsl.ELContextCleaner:Thread-2: javax.el.BeanELResolver purged
2013-04-29 14:38:39.457:INFO:oejsh.ContextHandler:Thread-2: stopped o.e.j.w.WebAppContext@7ea88b1c{/async-rest,[file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/, jar:file:/private/var/folders/br/kbs2g3753c54wmv4j31pnw5r0000gn/T/jetty-0.0.0.0-9090-async-rest.war-_async-rest-any-/webapp/WEB-INF/lib/example-async-rest-jar-9.0.2.v20130417.jar!/META-INF/resources/],UNAVAILABLE}{/async-rest.war}
.... 
