<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-project</artifactId>
    <version>13.0.0-SNAPSHOT</version>
  </parent>
  <groupId>org.eclipse.jetty.ee12</groupId>
  <artifactId>jetty-ee12</artifactId>
  <packaging>pom</packaging>
  <name>EE12</name>

  <modules>
    <module>jetty-ee12-annotations</module>
    <module>jetty-ee12-apache-jsp</module>
    <module>jetty-ee12-bom</module>
    <module>jetty-ee12-cdi</module>
    <module>jetty-ee12-demos</module>
    <module>jetty-ee12-fcgi-proxy</module>
    <module>jetty-ee12-glassfish-jstl</module>
    <module>jetty-ee12-home</module>
    <module>jetty-ee12-jaspi</module>
    <module>jetty-ee12-jndi</module>
    <module>jetty-ee12-jspc-maven-plugin</module>
    <module>jetty-ee12-maven-plugin</module>
    <module>jetty-ee12-osgi</module>
    <module>jetty-ee12-plus</module>
    <module>jetty-ee12-proxy</module>
    <module>jetty-ee12-quickstart</module>
    <module>jetty-ee12-servlet</module>
    <module>jetty-ee12-servlets</module>
    <module>jetty-ee12-tests</module>
    <module>jetty-ee12-webapp</module>
    <module>jetty-ee12-websocket</module>
  </modules>

  <properties>
    <ee12.jakarta.activation.api.version>2.1.3</ee12.jakarta.activation.api.version>
    <ee12.jakarta.mail.api.version>2.1.3</ee12.jakarta.mail.api.version>
    <!-- ee12.jakarta.servlet.api.version>6.2.0-M2</ee12.jakarta.servlet.api.version -->
    <ee12.jakarta.servlet.jsp.api.version>4.0.0</ee12.jakarta.servlet.jsp.api.version>
    <ee12.jakarta.servlet.jsp.jstl.impl.version>4.0.0</ee12.jakarta.servlet.jsp.jstl.impl.version>
    <ee12.jakarta.xml.bind.api.version>4.0.5</ee12.jakarta.xml.bind.api.version>
    <ee12.jakarta.xml.bind.impl.version>4.0.7</ee12.jakarta.xml.bind.impl.version>
    <ee12.jakarta.xml.jaxws.impl.version>4.0.2</ee12.jakarta.xml.jaxws.impl.version>
    <ee12.jersey.version>4.0.2</ee12.jersey.version>
    <ee12.jsp.impl.version>11.0.10.1</ee12.jsp.impl.version>
    <ee12.mail.impl.version>2.0.2</ee12.mail.impl.version>
    <ee12.weld.version>6.0.4.Final</ee12.weld.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- EE12-UPDATE
      <dependency>
        <groupId>jakarta.platform</groupId>
        <artifactId>jakarta.jakartaee-bom</artifactId>
        <version>${ee12.jakarta.bom.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
       -->
      <dependency>
        <groupId>org.eclipse.jetty.ee</groupId>
        <artifactId>jetty-ee-bom</artifactId>
        <version>${project.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.sun.mail</groupId>
        <artifactId>jakarta.mail</artifactId>
        <version>${ee12.mail.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>com.sun.xml.ws</groupId>
        <artifactId>jaxws-rt</artifactId>
        <version>{ee12.jakarta.xml.jaxws.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.xml.bind</groupId>
        <artifactId>jakarta.xml.bind-api</artifactId>
        <version>${ee12.jakarta.xml.bind.api.version}</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>3.0.0</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.activation</groupId>
        <artifactId>jakarta.activation-api</artifactId>
        <version>2.2.0-M2</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.mail</groupId>
        <artifactId>jakarta.mail-api</artifactId>
        <version>2.2.0-M1</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.interceptor</groupId>
        <artifactId>jakarta.interceptor-api</artifactId>
        <version>2.2.0</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.inject</groupId>
        <artifactId>jakarta.inject-api</artifactId>
        <version>2.0.1</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.enterprise</groupId>
        <artifactId>jakarta.enterprise.cdi-api</artifactId>
        <version>5.0.0.Beta1</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.enterprise</groupId>
        <artifactId>jakarta.enterprise.lang-model</artifactId>
        <version>5.0.0.Beta1</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.el</groupId>
        <artifactId>jakarta.el-api</artifactId>
        <version>6.1.0-M2</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>3.0.0</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.authentication</groupId>
        <artifactId>jakarta.authentication-api</artifactId>
        <version>3.1.0</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.transaction</groupId>
        <artifactId>jakarta.transaction-api</artifactId>
        <version>2.0.1</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.websocket</groupId>
        <artifactId>jakarta.websocket-api</artifactId>
        <version>2.3.0-M2</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.websocket</groupId>
        <artifactId>jakarta.websocket-client-api</artifactId>
        <version>2.3.0-M2</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.servlet</groupId>
        <artifactId>jakarta.servlet-api</artifactId>
        <version>6.2.0-M2</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.servlet.jsp</groupId>
        <artifactId>jakarta.servlet.jsp-api</artifactId>
        <version>4.1.0-M2</version>
      </dependency>
      <!-- EE12-UPDATE : Remove once jakarta-ee12-bom exists -->
      <dependency>
        <groupId>jakarta.servlet.jsp.jstl</groupId>
        <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
        <version>3.1.0-M1</version>
      </dependency>
      <!-- Jetty EE12 Dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-annotations</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-apache-jsp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-cdi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-fcgi-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-glassfish-jstl</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-jaspi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-jndi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-jspc-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-plus</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-quickstart</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-servlets</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12</groupId>
        <artifactId>jetty-ee12-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.demos</groupId>
        <artifactId>jetty-ee12-demo-proxy-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jakarta-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jetty-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-jetty-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee12.websocket</groupId>
        <artifactId>jetty-ee12-websocket-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>${ee12.jakarta.xml.bind.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.containers</groupId>
        <artifactId>jersey-container-servlet</artifactId>
        <version>${ee12.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.inject</groupId>
        <artifactId>jersey-hk2</artifactId>
        <version>${ee12.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.media</groupId>
        <artifactId>jersey-media-json-binding</artifactId>
        <version>${ee12.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.wasp</groupId>
        <artifactId>wasp</artifactId>
        <version>${ee12.jakarta.servlet.jsp.jstl.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.weld.servlet</groupId>
        <artifactId>weld-servlet-core</artifactId>
        <version>${ee12.weld.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-el</artifactId>
        <version>${ee12.jsp.impl.version}</version>
      </dependency>
      <!-- Jakarta EE12 Dependencies -->
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-jsp</artifactId>
        <version>${ee12.jsp.impl.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
