# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Proxy Webapp

[environment]
<inherit>

[tags]
demo
webapp

[depends]
ee-deploy

[files]
basehome:modules/demo.d/ee-demo-proxy.properties|webapps/ee-demo-proxy.properties
maven://org.eclipse.jetty.ee.demos/jetty-ee-demo-proxy-webapp/${jetty.version}/war|webapps/ee-demo-proxy.war
