# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables support for the GZIP compression algorithm.

[tags]
compression
gzip

[lib]
lib/jetty-compression-common-${jetty.version}.jar
lib/jetty-compression-gzip-${jetty.version}.jar
