# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Expose the Jetty WebSocket Client classes to deployed web applications.

[tags]
websocket

[environment]
ee9

[depend]
websocket-core-client
ee9-annotations

[lib]
lib/ee9-websocket/jetty-ee9-websocket-jetty-api-${jetty.version}.jar
lib/ee9-websocket/jetty-ee9-websocket-jetty-common-${jetty.version}.jar
lib/ee9-websocket/jetty-ee9-websocket-jetty-client-${jetty.version}.jar
lib/ee9-websocket/jetty-ee9-websocket-jetty-client-webapp-${jetty.version}.jar
