# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Expose the Jetty WebSocket Client classes to deployed web applications.

[tags]
websocket

[environment]
ee9

[depend]
client
ee9-annotations

[lib]
lib/jetty-websocket-core-common-${jetty.version}.jar
lib/jetty-websocket-core-client-${jetty.version}.jar
lib/ee9-websocket/jetty-ee9-websocket-jetty-api-${jetty.version}.jar
lib/ee9-websocket/jetty-ee9-websocket-jetty-common-${jetty.version}.jar
lib/ee9-websocket/jetty-ee9-websocket-jetty-client-${jetty.version}.jar
lib/ee9-websocket/jetty-ee9-websocket-jetty-client-webapp-${jetty.version}.jar
