# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Servlet 3.1 resource injection.

[environment]
ee8

[depends]
server
jndi
plus
ee8-security
ee8-webapp

[ini]
ee8.jakarta.transaction-api.version?=@ee8.jakarta.transaction-api.version@

[files]
maven://jakarta.transaction/jakarta.transaction-api/${ee8.jakarta.transaction-api.version}/jar|lib/ee8/support/jakarta.transaction.jakarta.transaction-api-${ee8.jakarta.transaction-api.version}.jar
maven://org.eclipse.jetty.ee8/jetty-ee8-plus/${jetty.version}/jar|lib/ee8/jetty-ee8-plus-${jetty.version}.jar

[lib]
lib/ee8/jetty-ee8-plus-${jetty.version}.jar
lib/ee8/support/jakarta.transaction.jakarta.transaction-api-${ee8.jakarta.transaction-api.version}.jar
