# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Servlet 3.1 resource injection.

[environment]
ee8

[depends]
server
jndi
plus
ee8-security
ee8-webapp

[files]
maven://jakarta.transaction/jakarta.transaction-api/1.3.3/jar|lib/ee8/support/jakarta.transaction.jakarta.transaction-api-1.3.3.jar
maven://org.eclipse.jetty.ee8/jetty-ee8-plus/${jetty.version}/jar|lib/ee8/jetty-ee8-plus-${jetty.version}.jar

[lib]
lib/ee8/jetty-ee8-plus-${jetty.version}.jar
lib/ee8/support/jakarta.transaction.jakarta.transaction-api-1.3.3.jar
