# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Handler

[tags]
demo
handler

[depends]
server

[files]
basehome:modules/demo.d/demo-handler.xml|etc/demo-handler.xml
maven://org.eclipse.jetty.demos/jetty-core-demo-handler/${jetty.version}/jar|lib/jetty-core-demo-handler.jar

[xml]
etc/demo-handler.xml

[lib]
lib/jetty-core-demo-handler.jar
