# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Server/port connections for Mongo session storage.

[xml]
etc/sessions/mongo/session-store-by-address.xml

