# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Puts lib/ee10/ext jars on the ee10 classpath.

[tags]
classpath

[environment]
ee10

[lib]
lib/ee10/ext/**.jar

[files]
lib/
lib/ee10/
lib/ee10/ext/
