# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Jetty WebSocket Webapp

[environment]
ee12

[tags]
demo
webapp

[depends]
ee12-deploy
ext
ee12-websocket-jetty

[files]
basehome:modules/demo.d/ee12-demo-jetty-websocket.xml|webapps/ee12-demo-jetty-websocket.xml
basehome:modules/demo.d/ee12-demo-jetty-websocket.properties|webapps/ee12-demo-jetty-websocket.properties
maven://org.eclipse.jetty.demos/jetty-ee12-demo-jetty-websocket/webapp/${jetty.version}/war|webapps/ee12-demo-jetty-websocket.war
