# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the Jetty EECommon JNDI reference factories

[environment]
ee

[depend]
jndi

[lib]
lib/jetty-ee-jndi-${jetty.version}.jar

[ini]
jetty.webapp.addHiddenClasses+=,-org.eclipse.jetty.ee.jndi.factories.