# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee10

[depend]
ee10-servlet
ee10-annotations

[lib]
lib/ee10-apache-jsp/jakarta.el.jakarta.el-api-@ee10.jakarta.el.api.version@.jar
lib/ee10-apache-jsp/jakarta.servlet.jsp.jakarta.servlet.jsp-api-@ee10.jakarta.servlet.jsp.api.version@.jar
lib/ee10-apache-jsp/org.eclipse.jdt.ecj-@eclipse.jdt.ecj.version@.jar
lib/ee10-apache-jsp/org.mortbay.jasper.apache-el-@ee10.jsp.impl.version@.jar
lib/ee10-apache-jsp/org.mortbay.jasper.apache-jsp-@ee10.jsp.impl.version@.jar
lib/jetty-ee10-apache-jsp-${jetty.version}.jar

