# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds servlet standard security handling to the classpath.

[environment]
ee8

[depend]
server
security
ee8-servlet

[lib]
lib/jetty-ee8-security-${jetty.version}.jar
