# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds servlet standard security handling to the classpath.

[environment]
ee8

[depends]
server
security
ee8-servlet

[files]
maven://org.eclipse.jetty.ee8/jetty-ee8-security/${jetty.version}/jar|lib/ee8/jetty-ee8-security-${jetty.version}.jar

[lib]
lib/ee8/jetty-ee8-security-${jetty.version}.jar
