# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables support for EE10 FastCGI proxying.

[environment]
ee10

[tags]
fcgi
proxy

[depends]
fcgi

[files]
maven://org.eclipse.jetty.ee10/jetty-ee10-fcgi-proxy/${project.version}/jar|lib/ee10/jetty-ee10-fcgi-proxy-${project.version}.jar
maven://org.eclipse.jetty.ee10/jetty-ee10-proxy/${project.version}/jar|lib/ee10/jetty-ee10-proxy-${project.version}.jar

[lib]
lib/ee10/jetty-ee10-fcgi-proxy-${project.version}.jar
lib/ee10/jetty-ee10-proxy-${project.version}.jar
