# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enable the Jetty WebSocket API support for deployed web applications.

[environment]
ee9

[tags]
websocket

[depends]
websocket-core-server
ee9-annotations

[files]
maven://org.eclipse.jetty.ee9.websocket/jetty-ee9-websocket-jetty-api/${jetty.version}/jar|lib/ee9/jetty-ee9-websocket-jetty-api-${jetty.version}.jar
maven://org.eclipse.jetty.ee9.websocket/jetty-ee9-websocket-jetty-common/${jetty.version}/jar|lib/ee9/jetty-ee9-websocket-jetty-common-${jetty.version}.jar
maven://org.eclipse.jetty.ee9.websocket/jetty-ee9-websocket-jetty-server/${jetty.version}/jar|lib/ee9/jetty-ee9-websocket-jetty-server-${jetty.version}.jar
maven://org.eclipse.jetty.ee9.websocket/jetty-ee9-websocket-servlet/${jetty.version}/jar|lib/ee9/jetty-ee9-websocket-servlet-${jetty.version}.jar

[lib]
lib/ee9/jetty-ee9-websocket-jetty-api-${jetty.version}.jar
lib/ee9/jetty-ee9-websocket-jetty-common-${jetty.version}.jar
lib/ee9/jetty-ee9-websocket-jetty-server-${jetty.version}.jar
lib/ee9/jetty-ee9-websocket-servlet-${jetty.version}.jar
