//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

package org.eclipse.jetty.quic.client.internal;

import java.net.InetSocketAddress;
import java.net.SocketAddress;
import java.util.List;
import java.util.Map;

import org.eclipse.jetty.io.ClientConnector;
import org.eclipse.jetty.io.EndPoint;
import org.eclipse.jetty.io.RetainableByteBuffer;
import org.eclipse.jetty.quic.api.Session;
import org.eclipse.jetty.quic.api.frames.CryptoFrame;
import org.eclipse.jetty.quic.api.frames.TransportParameters;
import org.eclipse.jetty.quic.api.tls.ext.QuicTransportParametersExtension;
import org.eclipse.jetty.quic.client.QuicClient;
import org.eclipse.jetty.quic.client.QuicClientQuicConfiguration;
import org.eclipse.jetty.quic.common.QuicSession;
import org.eclipse.jetty.quic.common.frames.FrameStream;
import org.eclipse.jetty.quic.common.packets.PacketNumbers;
import org.eclipse.jetty.quic.common.tls.ClientQuicTLS;
import org.eclipse.jetty.tls.Message;
import org.eclipse.jetty.tls.common.generator.MessagesGenerator;
import org.eclipse.jetty.tls.ext.ALPNExtension;
import org.eclipse.jetty.tls.ext.ServerNameExtension;
import org.eclipse.jetty.util.Callback;
import org.eclipse.jetty.util.Promise;

public class ClientQuicSession extends QuicSession
{
    private final MessagesGenerator tlsGenerator;
    private final ClientQuicTLS quicTLS;
    private final Map<String, Object> context;
    private final FrameStream cryptoStream = new FrameStream();

    public ClientQuicSession(ClientConnector connector, QuicClientQuicConfiguration quicConfiguration, PacketNumbers packetNumbers, ClientQuicTLS clientQuicTLS, EndPoint endPoint, Map<String, Object> context)
    {
        super(connector.getExecutor(), connector.getByteBufferPool(), quicConfiguration, packetNumbers, clientQuicTLS, sessionListener(context), endPoint);
        this.quicTLS = clientQuicTLS;
        this.context = context;
        this.tlsGenerator = new MessagesGenerator(getByteBufferPool());
    }

    private static Session.Listener sessionListener(Map<String, Object> context)
    {
        return (Session.Listener)context.get(QuicClient.SESSION_LISTENER_CONTEXT_KEY);
    }

    @SuppressWarnings("unchecked")
    private static List<String> alpnProtocols(Map<String, Object> context)
    {
        return (List<String>)context.get(ClientConnector.APPLICATION_PROTOCOLS_CONTEXT_KEY);
    }

    public void connect(Promise.Invocable<Session> promise)
    {
        try
        {
            ClientQuicTLS.Configuration configuration = new ClientQuicTLS.Configuration()
                .quicVersion(getQuicConfiguration().getQuicVersion());

            SocketAddress remoteSocketAddress = getEndPoint().getRemoteSocketAddress();
            if (remoteSocketAddress instanceof InetSocketAddress inet)
            {
                String serverName = inet.getHostString();
                configuration.extension(new ServerNameExtension(serverName));
            }

            List<String> protocols = alpnProtocols(context);
            if (protocols == null || protocols.isEmpty())
                throw new IllegalStateException("missing ALPN protocols");
            configuration.extension(new ALPNExtension(protocols));

            TransportParameters transportParameters = getListener().onPrepare(this);
            // TODO: default the parameters.
            configuration.extension(new QuicTransportParametersExtension(transportParameters));

            byte[] dstConnectionId = quicTLS.newRandomBytes(12);
            configuration.inputKeyMaterial(dstConnectionId);
            setDestinationConnectionId(dstConnectionId);

            // Link the ClientQuicTLS back to this session to
            // send the TLS messages generated by ClientQuicTLS.
            // TODO: this is obviously wrong, as we cannot continue to notify the same promise.
            quicTLS.addMessageListener(this::sendTLSMessages);

            // Link the TLS message generator back to ClientQuicTLS, so that
            // it can update the TranscriptHash as TLS messages are generated.
            tlsGenerator.addListener(quicTLS);

            // TODO: link the ClientQuicTLS to receive the TLS messages.

            quicTLS.startHandshake(configuration, Promise.Invocable.toCallback(promise, this));

            promise.succeeded(this);
        }
        catch (Throwable x)
        {
            promise.failed(x);
        }
    }

    private void sendTLSMessages(List<Message> messages, Callback callback)
    {
        RetainableByteBuffer.Mutable accumulator = new RetainableByteBuffer.DynamicCapacity(getByteBufferPool(), getQuicConfiguration().isUseOutputDirectByteBuffers(), -1, 0, 0);
        try
        {
            for (Message message : messages)
            {
                tlsGenerator.generate(accumulator, message);
            }
            CryptoFrame cryptoFrame = new CryptoFrame(0, accumulator);
            crypto(cryptoFrame, callback);
        }
        catch (Throwable x)
        {
            accumulator.release();
            callback.failed(x);
        }
    }
}
