# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables JAAS for deployed web applications.

[depend]
security

[before]
deployment-scanner

[xml]
etc/jetty-jaas.xml

[ini-template]
## The file location (absolute path, or relative to $JETTY_BASE)
## for the JAAS "java.security.auth.login.config" system property.
# jetty.jaas.login.conf=etc/login.conf
