# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
# tag::description[]
This module provides common configuration of Java Servlet web applications over all environments.
# end::description[]

[environment]
<inherit>

[depend]
ee/common-servlet

[xml]
etc/jetty-ee-webapp.xml

[lib]
lib/jetty-ee-webapp-${jetty.version}.jar
