# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Template configuration file to apply to all web applications deployed in the EECommon environment.

[tags]
deployment

[depend]
ee/common-deploy

[files]
basehome:modules/deployment.d/ee-environment.properties|environments/ee-environment.properties
basehome:modules/deployment.d/ee-environment.xml|environments/ee-environment.xml

