//
// ========================================================================
// Copyright (c) 1995 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

= Jakarta Faces TagLibs

If you want to use Jakarta Faces with your Jakarta EE web application, you should enable the xref:modules/standard.adoc#eeN-ext[`{ee-all}-ext`] Jetty module, and copy the relevant Jakarta Faces API jar files, and the Jakarta Faces implementation jar files of your choice into the `$JETTY_BASE/lib/{ee-all}/ext` directory created by the `{ee-all}-ext` module you enabled.

Then you will need to tell Jetty which of those jar files contains the `+*.tld+` files.
To accomplish that, you need to specify either the name of the file or a pattern that matches the name of the file(s) as the `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern` context attribute.
You will need to preserve the existing value of the attribute, and add in your extra pattern.

Below you can find an example of using a Jetty context XML file to add a pattern to match files starting with `jsf-`, which contain the `+*.tld+` files:

[,xml,subs=+attributes]
----
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.{ee-current}.webapp.WebAppContext"> <!--1-->
  <Call name="setAttribute"> <!--2-->
    <Arg>org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern</Arg> <!--3-->
    <Arg>.*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$|.*/jsf-[^/]*\.jar$</Arg> <!--4-->
  </Call>
</Configure>
----
<1> Configures a link:{javadoc-url}/org/eclipse/jetty/{ee-current}/webapp/WebAppContext.html[`WebAppContext`], which is the Jetty component that represents a Jakarta EE web application.
<2> Sets a context attribute.
<3> Specifies the name of the context attribute.
<4> Specifies the value of the context attribute, adding the additional pattern `+.*/jsf-[^/]*\.jar$+` to those already existing.
