# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Demo Jetty WebSocket Webapp

[environment]
<inherit>

[tags]
demo
webapp

[depends]
ee/common-deploy
ext
ee/common-websocket-jetty

[files]
basehome:modules/demo.d/ee-demo-jetty-websocket.xml|webapps/ee-demo-jetty-websocket.xml
basehome:modules/demo.d/ee-demo-jetty-websocket.properties|webapps/ee-demo-jetty-websocket.properties
maven://org.eclipse.jetty.demos/jetty-ee-demo-jetty-websocket/webapp/${jetty.version}/war|webapps/ee-demo-jetty-websocket.war
