# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Enables GCloud Datastore API and implementation.

[tags]
3rdparty
gcloud

[depends]
gcloud
logging-jcl-capture
logging-jul-capture

