# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee8

[depend]
ee8-servlet
ee8-annotations

[ini]
eclipse.jdt.ecj.version?=@eclipse.jdt.ecj.version@
ee8.jsp.impl.version?=@jsp.impl.version@

[lib]
lib/ee8-apache-jsp/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
lib/ee8-apache-jsp/org.mortbay.jasper.apache-el-${ee8.jsp.impl.version}.jar
lib/ee8-apache-jsp/org.mortbay.jasper.apache-jsp-${ee8.jsp.impl.version}.jar
lib/jetty-ee8-apache-jsp-${jetty.version}.jar
