# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee8

[depends]
ee8-servlet
ee8-annotations

[ini]
eclipse.jdt.ecj.version?=@eclipse.jdt.ecj.version@
ee8.jsp.impl.version?=@ee8.jsp.impl.version@

[files]
maven://org.eclipse.jdt/ecj/${eclipse.jdt.ecj.version}/jar|lib/ee8/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
maven://org.eclipse.jetty.ee8/jetty-ee8-apache-jsp/${jetty.version}/jar|lib/ee8/jetty-ee8-apache-jsp-${jetty.version}.jar
maven://org.mortbay.jasper/mortbay-apache-el/${ee8.jsp.impl.version}/jar|lib/ee8/support/org.mortbay.jasper.mortbay-apache-el-${ee8.jsp.impl.version}.jar
maven://org.mortbay.jasper/mortbay-apache-jsp/${ee8.jsp.impl.version}/jar|lib/ee8/support/org.mortbay.jasper.mortbay-apache-jsp-${ee8.jsp.impl.version}.jar

[lib]
lib/ee8/jetty-ee8-apache-jsp-${jetty.version}.jar
lib/ee8/support/org.eclipse.jdt.ecj-${eclipse.jdt.ecj.version}.jar
lib/ee8/support/org.mortbay.jasper.mortbay-apache-el-${ee8.jsp.impl.version}.jar
lib/ee8/support/org.mortbay.jasper.mortbay-apache-jsp-${ee8.jsp.impl.version}.jar
