# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee8

[depend]
ee8-servlet
ee8-annotations

[lib]
lib/ee8-apache-jsp/@org.eclipse.jdt:ecj@
lib/ee8-apache-jsp/@org.mortbay.jasper:mortbay-apache-el@
lib/ee8-apache-jsp/@org.mortbay.jasper:mortbay-apache-jsp@
lib/jetty-ee8-apache-jsp-${jetty.version}.jar
