# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds the Jetty EE10 JNDI reference factories

[environment]
ee10

[depend]
jndi

[lib]
lib/jetty-ee10-jndi-${jetty.version}.jar
