# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds the Jetty EE10 JNDI reference factories

[environment]
ee10

[depend]
ee/common-jndi
jndi

[lib]
lib/jetty-ee10-jndi-${jetty.version}.jar

[ini]
jetty.webapp.addHiddenClasses+=,-org.eclipse.jetty.ee.jndi.factories.