# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables a server-wide connection limit.

[tags]
connector

[depend]
server

[xml]
etc/jetty-connectionlimit.xml

[ini-template]

## The limit of connections to apply
#jetty.connectionlimit.maxConnections=1000

## The idle timeout to apply (in milliseconds) when connections are limited
#jetty.connectionlimit.idleTimeout=1000
