# DO NOT EDIT THIS FILE - Use start modules correctly - See: https://eclipse.dev/jetty/documentation/

[description]
Deprecated name for requestlog using custom request logger.

[tags]
requestlog
internal

[depends]
requestlog

