# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Deprecated name for requestlog using custom request logger.

[tags]
requestlog
internal

[depends]
requestlog

