# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Generates a warning that server has been run from $JETTY_HOME rather than from a $JETTY_BASE.

[xml]
etc/home-base-warning.xml

