# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Generates a warning that server has been run from $JETTY_HOME rather than from a $JETTY_BASE.

[xml]
etc/home-base-warning.xml

