# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Enables the java.sql JPMS module.

[tags]
jpms

[jpms]
add-modules: java.sql
