# DO NOT EDIT THIS FILE
# See https://eclipse.dev/jetty/documentation/ > Operations Guide > Jetty Start Mechanism

[description]
Adds the $JETTY_BASE/resources directory to the server classpath.
Useful for configuration property files (eg jetty-logging.properties)

[tags]
classpath

[lib]
resources/

[files]
resources/

