# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Creates and updates state file used by jetty.sh

[tags]
start

[depend]
server

[xml]
etc/jetty-state.xml

[ini-template]
## State Config
jetty.state=${jetty.base}/jetty.state


