# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation parsing.

[depend]
server

[ini]
asm.version?=@asm.version@

[lib]
lib/jetty-annotations-${jetty.version}.jar
lib/annotations/asm-${asm.version}.jar
lib/annotations/asm-analysis-${asm.version}.jar
lib/annotations/asm-commons-${asm.version}.jar
lib/annotations/asm-tree-${asm.version}.jar
