# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Adds ASM libs.

[depend]
server

[ini]
asm.version?=@asm.version@

[files]
maven://org.ow2.asm/asm/${asm.version}/jar|lib/support/asm-${asm.version}.jar
maven://org.ow2.asm/asm-analysis/${asm.version}/jar|lib/support/asm-analysis-${asm.version}.jar
maven://org.ow2.asm/asm-commons/${asm.version}/jar|lib/support/asm-commons-${asm.version}.jar
maven://org.ow2.asm/asm-tree/${asm.version}/jar|lib/support/asm-tree-${asm.version}.jar

[lib]
lib/support/asm-${asm.version}.jar
lib/support/asm-analysis-${asm.version}.jar
lib/support/asm-commons-${asm.version}.jar
lib/support/asm-tree-${asm.version}.jar
