//
//  ========================================================================
//  Copyright (c) 1995-2018 Mort Bay Consulting Pty. Ltd.
//  ========================================================================
//  All rights reserved. This program and the accompanying materials
//  are made available under the terms of the Eclipse Public License v1.0
//  and Apache License v2.0 which accompanies this distribution.
//
//      The Eclipse Public License is available at
//      http://www.eclipse.org/legal/epl-v10.html
//
//      The Apache License v2.0 is available at
//      http://www.opensource.org/licenses/apache2.0.php
//
//  You may elect to redistribute this code under either of these licenses.
//  ========================================================================
//

[[what-is-jetty]]
=== What is Jetty?

At the most basic level, Jetty is an Open-Source HTTP web server and Java servlet container.
Development of Jetty began in 1995 with the original foundations laid by Greg Wilkins, who still actively contributes to the project.
Today, Jetty is one of the most widely distributed web servers around.
It has been use to power projects from small websites to massive applications with tens of millions of users.
Companies like Yahoo, Google, Salesforce.com and many more count Jetty as an integral part of their own product offerings.

From the start, Jetty was built to be as flexible as possible while at the same time providing support for the most popular and robust technologies available.
Since it's inception Jetty has been on the forefront of technological innovation and was among the first to offer support for HTTP/1.1, asynchronous servlets, Comet, WebSocket and HTTP/2.
