//
// ========================================================================
// Copyright (c) 1995-2021 Mort Bay Consulting Pty Ltd and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
// ========================================================================
//

[[og-server-compliance]]
=== Server Compliance Modes

The Jetty server strives to keep up with the latest https://en.wikipedia.org/wiki/Request_for_Comments[IETF RFC]s for compliance with internet specifications, which
are periodically updated.  When possible Jetty will support backwards compatibility by providing compliance modes that can be configured to allow some legacy violations of the specifications. There are compliance modes provided for:

* xref:og-server-compliance-http[HTTP Compliance]
* xref:og-server-compliance-uri[URI Compliance]
* xref:og-server-compliance-cookie[Cookie Compliance]

Compliance modes sets of allowed Violations from the RFC requirements, or in some cases on additional requirements Jetty has implemented in excess of the RFC (e.g. to avoid Ambiguous URIs).
For example, the HTTP RFCs requires that request methods are https://datatracker.ietf.org/doc/html/rfc7230#section-3.1.1[case sensitive], however Jetty can allow case-insensitive methods by including the https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/http/HttpCompliance.Violation.html#CASE_INSENSITIVE_METHOD[CASE_INSENSITIVE_METHOD] in the https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/http/HttpCompliance.html[HttpCompliance] set of allowed violations.

Common compliance modes are defined as static constant fields (e.g. https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/http/HttpCompliance.html#RFC2616[HttpCompliance.RFC2616]) and can be configured in the server.ini file by name (e.g. "RFC2616").  Alternately compliance modes can be defined by a string that adds and/or removes individual violations by name (e.g. ""RFC2616,-MULTILINE_FIELD_VALUE,CASE_INSENSITIVE_METHOD" is the RFC 2616 compliance set without allowing multiline field values, but allowing case-insensitive methods).

include::server-compliance-http.adoc[]
include::server-compliance-uri.adoc[]
include::server-compliance-cookie.adoc[]


