<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.ee11</groupId>
    <artifactId>jetty-ee11</artifactId>
    <version>12.1.13-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>jetty-ee11-home</artifactId>
  <packaging>pom</packaging>
  <name>EE11 :: Home Assembly</name>

  <properties>
    <assembly-directory>${basedir}/target/jetty-ee11-home</assembly-directory>
    <source-assembly-directory>${basedir}/target/jetty-ee11-home-sources</source-assembly-directory>
    <spotbugs.skip>true</spotbugs.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-security</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-async-rest-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jaas-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jetty-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
      <exclusions>
        <exclusion>
          <groupId>javax.el</groupId>
          <artifactId>el-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jndi-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jsp-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jspc-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-mock-resources</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-simple-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-spec-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet6-demo-jspc-6-1-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet6-demo-jspc-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet6-demo-simple-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet6-demo-spec-6-1-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-apache-jsp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-cdi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-fcgi-proxy</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-glassfish-jstl</artifactId>
      <exclusions>
        <exclusion>
          <groupId>jakarta.el</groupId>
          <artifactId>jakarta.el-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.el</groupId>
          <artifactId>el-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-jaspi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-jndi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-plus</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-proxy</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-quickstart</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-servlets</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.demos</groupId>
      <artifactId>jetty-ee11-demo-jetty-websocket-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.demos</groupId>
      <artifactId>jetty-ee11-demo-proxy-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.websocket</groupId>
      <artifactId>jetty-ee11-websocket-jakarta-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.websocket</groupId>
      <artifactId>jetty-ee11-websocket-jetty-client-webapp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.websocket</groupId>
      <artifactId>jetty-ee11-websocket-jetty-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.websocket</groupId>
      <artifactId>jetty-ee11-websocket-servlet</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <tarLongFileMode>posix</tarLongFileMode>
          <appendAssemblyId>false</appendAssemblyId>
        </configuration>
        <executions>
          <execution>
            <id>binary</id>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <descriptors>
                <descriptor>src/main/assembly/jetty-assembly.xml</descriptor>
              </descriptors>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-ee11-jetty-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.toolchain,
                org.eclipse.jetty.ee11,
                org.eclipse.jetty.ee11.websocket</includeGroupIds>
              <excludeGroupIds>org.eclipsejetty.ee11.demos</excludeGroupIds>
              <excludeClassifiers>config</excludeClassifiers>
              <includeTypes>jar</includeTypes>
              <includeScope>runtime</includeScope>
              <outputDirectory>${assembly-directory}/lib/ee11</outputDirectory>
              <useRepositoryLayout>false</useRepositoryLayout>
              <copySignatures>true</copySignatures>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee11-support-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.annotation,
                jakarta.authentication,
                jakarta.el,
                jakarta.enterprise,
                jakarta.inject,
                jakarta.interceptor,
                jakarta.servlet,
                jakarta.servlet.jsp,
                jakarta.servlet.jsp.jstl,
                jakarta.transaction,
                jakarta.websocket,
                jakarta.websocket.client,
                org.eclipse.jdt,
                org.glassfish.wasp,
                org.glassfish.web,
                org.mortbay.jasper</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <includeScope>runtime</includeScope>
              <outputDirectory>${assembly-directory}/lib/ee11/support</outputDirectory>
              <!-- this is true to make sure that non-jpms artifacts use a full identifiable name -->
              <prependGroupId>true</prependGroupId>
              <copySignatures>true</copySignatures>
            </configuration>
          </execution>
          <execution>
            <id>unpack-config-deps</id>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.ee11,
                org.eclipse.jetty.ee11.demos</includeGroupIds>
              <classifier>config</classifier>
              <includeTypes>jar</includeTypes>
              <includeScope>runtime</includeScope>
              <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
              <excludes>META-INF/**,
                webapps/**,
                start.d/**,
                start.ini</excludes>
              <outputDirectory>${assembly-directory}</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>unpack-demo-deps</id>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.demos</includeGroupIds>
              <classifier>config</classifier>
              <includeTypes>jar</includeTypes>
              <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
              <includes>**/ee11-demo-*,**/demo.d/override-web.xml</includes>
              <outputDirectory>${assembly-directory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
