# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Template configuration file to apply to all web applications deployed in the EE12 environment.

[tags]
deployment

[depend]
ee12-deploy

[files]
basehome:modules/deployment.d/ee12-environment.properties|environments/ee12-environment.properties
basehome:modules/deployment.d/ee12-environment.xml|environments/ee12-environment.xml

