# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
This module enables support for Jakarta EE 11 web applications.

[environment]
ee12

[depend]
ee/common-webapp
ee12-servlet
ee12-security

[xml]
etc/jetty-ee12-webapp.xml

[lib]
lib/jetty-ee12-webapp-${jetty.version}.jar

[ini-template]
# tag::ini-template[]
## Customize protected and hidden classes for this web application context.
#jetty.webapp.addProtectedClasses+=,org.example.
#jetty.webapp.addHiddenClasses+=,org.example.

## Default ContextHandler class for ee12 environment deployments
# jetty.deploy.defaultContextHandlerClass=org.eclipse.jetty.ee.webapp.WebAppContext
# end::ini-template[]
