<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.ee9</groupId>
    <artifactId>jetty-ee9</artifactId>
    <version>12.1.13-SNAPSHOT</version>
  </parent>
  <artifactId>jetty-ee9-home</artifactId>
  <packaging>pom</packaging>
  <name>EE9 :: Home Assembly</name>

  <properties>
    <assembly-directory>${basedir}/target/jetty-ee9-home</assembly-directory>
    <source-assembly-directory>${basedir}/target/jetty-ee9-home-sources</source-assembly-directory>
    <spotbugs.skip>true</spotbugs.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-async-rest-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jaas-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jetty-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
      <exclusions>
        <exclusion>
          <groupId>javax.el</groupId>
          <artifactId>el-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jndi-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jsp-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-jspc-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-mock-resources</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-simple-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.demos</groupId>
      <artifactId>jetty-servlet5-demo-spec-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-apache-jsp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-cdi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-fcgi-proxy</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-glassfish-jstl</artifactId>
      <exclusions>
        <exclusion>
          <groupId>jakarta.el</groupId>
          <artifactId>jakarta.el-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.el</groupId>
          <artifactId>el-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-jaspi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-jndi</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-openid</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-plus</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-proxy</artifactId>
    </dependency>

    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-quickstart</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9</groupId>
      <artifactId>jetty-ee9-servlets</artifactId>
    </dependency>
    <!-- Demo ee9 Apps -->
    <dependency>
      <groupId>org.eclipse.jetty.ee9.demos</groupId>
      <artifactId>jetty-ee9-demo-jetty-websocket-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9.demos</groupId>
      <artifactId>jetty-ee9-demo-proxy-webapp</artifactId>
      <version>${project.version}</version>
      <classifier>config</classifier>
      <type>jar</type>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9.websocket</groupId>
      <artifactId>jetty-ee9-websocket-jakarta-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9.websocket</groupId>
      <artifactId>jetty-ee9-websocket-jetty-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9.websocket</groupId>
      <artifactId>jetty-ee9-websocket-jetty-client-webapp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9.websocket</groupId>
      <artifactId>jetty-ee9-websocket-jetty-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee9.websocket</groupId>
      <artifactId>jetty-ee9-websocket-servlet</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <tarLongFileMode>posix</tarLongFileMode>
          <appendAssemblyId>false</appendAssemblyId>
        </configuration>
        <executions>
          <execution>
            <id>binary</id>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <descriptors>
                <descriptor>src/main/assembly/jetty-assembly.xml</descriptor>
              </descriptors>
            </configuration>
          </execution>
          <execution>
            <id>sources</id>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <descriptors>
                <descriptor>src/main/assembly/jetty-source-assembly.xml</descriptor>
              </descriptors>
              <appendAssemblyId>true</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-ee9-jetty-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.toolchain,
                org.eclipse.jetty.ee9,
                org.eclipse.jetty.ee9.websocket</includeGroupIds>
              <excludeGroupIds>org.eclipsejetty.ee9.demos</excludeGroupIds>
              <excludeClassifiers>config</excludeClassifiers>
              <includeTypes>jar</includeTypes>
              <includeScope>runtime</includeScope>
              <outputDirectory>${assembly-directory}/lib/ee9</outputDirectory>
              <useRepositoryLayout>false</useRepositoryLayout>
              <copySignatures>true</copySignatures>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee9-jetty-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.toolchain,
                org.eclipse.jetty.ee9,
                org.eclipse.jetty.ee9.websocket</includeGroupIds>
              <excludeGroupIds>org.eclipsejetty.ee9.demos</excludeGroupIds>
              <includeTypes>jar</includeTypes>
              <includeScope>runtime</includeScope>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee9</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee9-support-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.annotation,
                jakarta.authentication,
                jakarta.enterprise,
                jakarta.inject,
                jakarta.interceptor,
                jakarta.transaction,
                org.eclipse.jdt,
                org.glassfish.web,
                org.mortbay.jasper</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <includeScope>runtime</includeScope>
              <outputDirectory>${assembly-directory}/lib/ee9/support</outputDirectory>
              <!-- this is true to make sure that non-jpms artifacts use a full identifiable name -->
              <prependGroupId>true</prependGroupId>
              <copySignatures>true</copySignatures>
            </configuration>
          </execution>
          <execution>
            <id>copy-ee9-support-src-deps</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>jakarta.annotation,
                jakarta.authentication,
                jakarta.enterprise,
                jakarta.inject,
                jakarta.interceptor,
                jakarta.transaction,
                org.eclipse.jdt,
                org.glassfish.web,
                org.mortbay.jasper</includeGroupIds>
              <includeTypes>jar</includeTypes>
              <includeScope>runtime</includeScope>
              <classifier>sources</classifier>
              <outputDirectory>${source-assembly-directory}/lib/ee9/support</outputDirectory>
              <!-- this is true to make sure that non-jpms artifacts use a full identifiable name -->
              <prependGroupId>true</prependGroupId>
            </configuration>
          </execution>
          <execution>
            <id>unpack-config-deps</id>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.ee9,
                org.eclipse.jetty.ee9.demos</includeGroupIds>
              <classifier>config</classifier>
              <includeScope>runtime</includeScope>
              <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
              <excludes>META-INF/**,webapps/**,start.d/**,start.ini</excludes>
              <outputDirectory>${assembly-directory}</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>unpack-demo-deps</id>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeGroupIds>org.eclipse.jetty.demos</includeGroupIds>
              <classifier>config</classifier>
              <includeTypes>jar</includeTypes>
              <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
              <includes>**/ee9-demo-*</includes>
              <outputDirectory>${assembly-directory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
