# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Expose the Jetty WebSocket Client classes to deployed web applications.

[environment]
ee8

[tags]
websocket

[depends]
websocket-core-client
ee8-annotations

[files]
maven://org.eclipse.jetty.ee8.websocket/jetty-ee8-websocket-jetty-api/${jetty.version}/jar|lib/ee8/jetty-ee8-websocket-jetty-api-${jetty.version}.jar
maven://org.eclipse.jetty.ee8.websocket/jetty-ee8-websocket-jetty-client/${jetty.version}/jar|lib/ee8/jetty-ee8-websocket-jetty-client-${jetty.version}.jar
maven://org.eclipse.jetty.ee8.websocket/jetty-ee8-websocket-jetty-common/${jetty.version}/jar|lib/ee8/jetty-ee8-websocket-jetty-common-${jetty.version}.jar

[lib]
lib/ee8/jetty-ee8-websocket-jetty-api-${jetty.version}.jar
lib/ee8/jetty-ee8-websocket-jetty-client-${jetty.version}.jar
lib/ee8/jetty-ee8-websocket-jetty-common-${jetty.version}.jar
