# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Demo Jakarta WebSocket Webapp

[environment]
ee9

[tags]
demo
webapp

[depends]
ee9-deploy
ext
ee9-servlets
ee9-websocket-jakarta

[files]
basehome:modules/demo.d/ee9-demo-jakarta-websocket.xml|webapps/ee9-demo-jakarta-websocket.xml
basehome:modules/demo.d/ee9-demo-jakarta-websocket.properties|webapps/ee9-demo-jakarta-websocket.properties
maven://org.eclipse.jetty.ee9.demos/jetty-ee9-demo-jakarta-websocket-webapp/${jetty.version}/war|webapps/ee9-demo-jakarta-websocket.war
