# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Provides a DefaultAuthConfigFactory for jaspi

[environment]
ee11

[tags]
security

[depend]
ee11-security

[provide]
auth-config-factory

[xml]
etc/jaspi/jetty-ee11-jaspi-default.xml
